### PR TITLE
Added support for high DPI versions of icons and cursors

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/9838

### CODE REVIEW

**Comment by icculus** [comment]
This looks reasonable to me. The only bikesheddy thing I could add here is that the naming scheme ("SurfaceHasImages", etc) is probably confusing if you don't realize that surfaces (which _are_ images) can have alternate representations now.

Is this strictly meant to be for multiple dimensions, or are we going to find out people want to use this to push through images with different colorspaces/formats, too? (and should we _stop that from happening_ because it's a pandora's box of unforeseen complexity?)

**Comment by slouken** [comment]
@Kontrabant, is there anything the Wayland backend should be doing to support high DPI cursors and icons?

**Comment by Kontrabant** [comment]
Yes, the scale factor for custom cursors will need to be set, and the pull for the xdg-toplevel-icon will need to be updated. 

I’ll get to it in a couple of days (currently bedridden with the flu).

**Comment by slouken** [comment]
> Yes, the scale factor for custom cursors will need to be set, and the pull for the xdg-toplevel-icon will need to be updated.
> 
> I’ll get to it in a couple of days (currently bedridden with the flu).

Oh man, I hope you feel better soon!

**Comment by Kontrabant** [comment]
Wayland scaled cursor support is in. Still waiting on the new wayland-protocols to be tagged before merging the icon support, at which point I'll address high-DPI icons, as until then, there is no way to test anything as no desktops have merged support for the protocol yet either.

> Oh man, I hope you feel better soon!

Thanks, turned out to the the Covid variant going around. That was the worst sore throat I've ever experienced. Definitely not recommended :).

**Comment by slouken** [comment]
> Wayland scaled cursor support is in. Still waiting on the new wayland-protocols to be tagged before merging the icon support, at which point I'll address high-DPI icons, as until then, there is no way to test anything as no desktops have merged support for the protocol yet either.
> 
> > Oh man, I hope you feel better soon!
> 
> Thanks, turned out to the the Covid variant going around. That was the worst sore throat I've ever experienced. Definitely not recommended :).

Ouch, I'm glad you're feeling better!

**Pull request merged**
