### PR TITLE
audio: Resampler optimizations

### PR DESCRIPTION
**Pull request by icculus**
This removes the mentioned bottleneck from #5493, and a spinlock, and a risk of allocation failures at runtime, at a cost of about 20k of static data being added to the binary.

I think this is probably a reasonable tradeoff, but it's also very close to the 2.0.22 release so I don't want to push a change like this without some review.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
I do something similar in another project for the same reason - it's definitely worth it if it's accurate! A possible precision improvement would be to printf with the maximum number of decimal places, which AFAIK is %9f. It wouldn't be the first time if the text representation possibly cut some values off a bit early...

Other than that it seems like the same thing but with less allocation so as long as the text represents the real values it's probably fine.

**Comment by icculus** [comment]
> A possible precision improvement would be to printf with the maximum number of decimal places

Oh, good call, I forgot to do that! Added a patch to the PR for that.

**Comment by eloj** [comment]
Would it make sense to output the table as hexadecimal constants instead? That gives you an exact bit rep.

**Comment by icculus** [comment]
Whoops, didn't realize renaming the branch would close the pull request. I'll open a new one. Sorry about that!

**Pull request closed without merging**
