### PR TITLE
Fix joystick (/dev/input/xxx) support on FreeBSD

### PR DESCRIPTION
**Pull request by martymac**
When switching to CMake, src/joystick/linux/SDL_sysjoystick.c file got excluded from FreeBSD builds, losing support for /dev/input/xxx devices.

See also: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279907

### CODE REVIEW

**Comment by slouken** [comment]
Merged, thanks!

**Comment by martymac** [comment]
Thanks!

**Comment by martymac** [comment]
Hmmm, can you cherry-pick that commit to SDL2 branch too ? Or do you want me to send another MR ?

**Comment by martymac** [comment]
I have opened a dedicated MR for SDL2 branch. Thanks!

**Pull request merged**
