### PR TITLE
test code cleanups to silence warnings

### PR DESCRIPTION
**Pull request by christianrauch**
This cleans up the test code to silence compiler warnings.

### CODE REVIEW

**Comment by sezero** [comment]
From a _very_ brief look, 

- `%llx` -> `%lx` changes in testqsort are clearly wrong: long is 64
  bits only on LP64 platforms, not on WIN64 or 32 bit systems.

- I don't think it's a good idea to remove the compile-time asserts
  from testplatform.c

There may be more gotchas, I didn't look that carefully.

What are, and how serious are the warnings you are getting?

**Comment by christianrauch** [comment]
> long is 64 bits only on LP64

Thanks for the hint. I change the format specifier to make it portable.

> I don't think it's a good idea to remove the compile-time asserts

Ok, I added them again.

> What are, and how serious are the warnings you are getting?

Well, they are just warnings so they are not serious by definition. You should see all the warnings about shadowed and unused variables by using a recent gcc version (e.g. 9.3.0 on Ubuntu 20.04).

**Comment by sezero** [comment]
> > long is 64 bits only on LP64
> 
> Thanks for the hint. I change the format specifier to make it portable.

You can use SDL_PRIu64 and SDL_PRIx64 there: see SDL_stdinc.h

**Comment by christianrauch** [comment]
I replaced `llx` and `llu` with their SDL types.

@sezero Can you check again?

**Comment by sezero** [comment]
> I replaced `llx` and `llu` with their SDL types.
> 
> @sezero Can you check again?

That part looks ok to me. The rest is up to maintainers.

**Pull request merged**
