### PR TITLE
Improved support for <8bpp surfaces

### PR DESCRIPTION
**Pull request by ccawley2011**

### CODE REVIEW

**Comment by slouken** [comment]
Thanks!

The only one I wasn't sure about was changing the surfaces returned by SDL_LoadBMP, but since SDL3 is an ABI break, I think this is fine.

**Comment by sezero** [comment]
Any changes needed in sdl2-compat ?

**Comment by sezero** [comment]
> Any changes needed in sdl2-compat ?

.. considering the fact that `SDL_PIXELTYPE_INDEX2` is inserted instead of being appended, changes will be needed, yes?

**Comment by slouken** [comment]
@ccawley2011, yeah, to simplify compatibility, we might need to do the same trick with adding the new type at the end here.

**Comment by sezero** [comment]
> @ccawley2011, yeah, to simplify compatibility, we might need to do the same trick with adding the new type at the end here.

So: @ccawley2011, @slouken: Should we do something like this in SDL3?
```diff
diff --git a/include/SDL3/SDL_pixels.h b/include/SDL3/SDL_pixels.h
index 02bae04..3d39e2e 100644
--- a/include/SDL3/SDL_pixels.h
+++ b/include/SDL3/SDL_pixels.h
@@ -88,7 +88,6 @@ typedef enum
 {
     SDL_PIXELTYPE_UNKNOWN,
     SDL_PIXELTYPE_INDEX1,
-    SDL_PIXELTYPE_INDEX2,
     SDL_PIXELTYPE_INDEX4,
     SDL_PIXELTYPE_INDEX8,
     SDL_PIXELTYPE_PACKED8,
@@ -98,7 +97,9 @@ typedef enum
     SDL_PIXELTYPE_ARRAYU16,
     SDL_PIXELTYPE_ARRAYU32,
     SDL_PIXELTYPE_ARRAYF16,
-    SDL_PIXELTYPE_ARRAYF32
+    SDL_PIXELTYPE_ARRAYF32,
+    /* appended at the end for compatibility with sdl2-compat:  */
+    SDL_PIXELTYPE_INDEX2
 } SDL_PixelType;
 
 /** Bitmap pixel order, high bit -> low bit. */
```

**Comment by slouken** [comment]
We've run into this a couple of times. I think maybe it's time to bite the bullet and add a function to convert between SDL2 and 3 pixel formats.

**Comment by sezero** [comment]
As you wish. Leaving that into your hands.

**Comment by slouken** [comment]
I remember now why we didn't do that. We'd have to change format everywhere it's used... notably in SDL_Surface.

**Pull request merged**
