### PR TITLE
Remove specific QueueDrawLines

### PR DESCRIPTION
**Pull request by 1bsyl**
Remove specific QueueDrawLines and use RenderGeometry

### CODE REVIEW

**Comment by 1bsyl** [comment]
@icculus the branch was already created ...
What about PSP / PSPVITAX and DirectFB implementation  ?

**Comment by slouken** [comment]
Let's leave DirectFB alone, I haven't heard any issues with that so far. @icculus, you want to take a quick look at PSP?

**Comment by icculus** [comment]
> you want to take a quick look at PSP?

Doing so now.

**Comment by icculus** [comment]
PSP change is in with 6d3b5d66cd4f593dd70d26babe42b62203c8bada. Tested on an emulator, it works.

**Comment by icculus** [comment]
(I don't have Vita build tools or a way to run it, so I'm leaving that alone.)

**Comment by isage** [comment]
I'll deal with vita

**Pull request merged**
