### PR TITLE
android: create android prefab archive with build-release.py

### PR DESCRIPTION
**Pull request by madebr**
~With these changes, I can get maven to sign and upload the Android Archive.
Authentication fails because I don't have an account at [Sonatype OSSRH](https://central.sonatype.org/publish/publish-guide/).~

I'm marking this pr as draft because more changes might be required.

### CODE REVIEW

**Comment by madebr** [comment]
First build the archive:
```
docker run --rm -ti -v $PWD:/src:z android-for-sdl /src/build-scripts/android-prefab.sh
```

For uploading, the ["manual deployment"](https://central.sonatype.org/publish/publish-manual/#deployment) should be used.
So you need to add the jira login to `~/.m2/settings.xml`, and re-use the id in the deplay command.

Then `cd` to the prefab folder and execute:
```
mvn gpg:sign-and-deploy-file -Durl=https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/ -DrepositoryId=$SDL_OSSRH -DpomFile=SDL2-2.25.0.pom -Dfile=SDL2-2.25.0.aar
```

The gpg signing can be configured though arguments of the [maven gpg plugin](https://maven.apache.org/plugins/maven-gpg-plugin/sign-mojo.html).

**Comment by madebr** [comment]
I added a `Dockerfile` for building an Android build container.
It has android-ndk 21.4.7075529 (21e), which is the same as the one used on Github Actions.
It carries the latest android api, such that our java sources can "see" all Android classes.

**Comment by slouken** [comment]
Why did you close this?

**Comment by madebr** [comment]
I was pruning branches, and didn't realize a pr was open for this.
This pr is outdated anyhow by the android support I added yesterday.

**Comment by madebr** [comment]
This should become part of the `build-release.py` script, and be created on GitHub actions.

**Comment by madebr** [comment]
The `build-release.py` script now also creates an Android prefab archive.
https://github.com/madebr/SDL/actions/runs/8462274313

How to test:
- Clone https://github.com/madebr/sdlcross
- Checkout the SDL3 branch
- Download the `android.zip` from the [artifacts section](https://github.com/madebr/SDL/actions/runs/8462274313)
- Extract `SDL3-3.1.0.aar` into `app/libs`
- Open the sdlcross project in Android Studio and build the Android app

**Comment by madebr** [comment]
The latest adds the proguard file to the android archive.
I also made it somewhat easier to debug the SDL libraries.
By running `settings set target.source-map /src/SDL3 /path/to/extracted/SDL3` in the Android lldb debugger, it is possible to step inside the SDL library with source text (instead of assembly code).

The Android toolchain does [currently not provide an easier way](https://github.com/google/prefab/issues/182) to match sources with prebuilt binaries.

**Comment by slouken** [comment]
> I also made it somewhat easier to debug the SDL libraries. By running `settings set target.source-map /src/SDL3 /path/to/extracted/SDL3` in the Android lldb debugger, it is possible to step inside the SDL library with source text (instead of assembly code).

Is this documented in README-android.md?

**Comment by madebr** [comment]
Prefab  is currently completely undocumented.
My goal was to document usage once it is published on a public (maven?) server.

This change is simply to add `-ffile-prefix-map=` to the cflag. (I'm also going to apply it to the mingw binaries)
It's only useful for release artifacts.
We currently don't document creation of the release artifacts either.

**Comment by slouken** [comment]
> With gdb/lldb, you can configure the SDL source path using `settings set target.source-map /src/SDL3 /path/to/extracted/SDL3` and building with `-ffile-prefix-map=...`. Is there something similar for MSVC?

Not that I know of, but Visual Studio will prompt you for the source location if you don't have it at the same place on your system.

**Comment by madebr** [comment]
> > With gdb/lldb, you can configure the SDL source path using `settings set target.source-map /src/SDL3 /path/to/extracted/SDL3` and building with `-ffile-prefix-map=...`. Is there something similar for MSVC?
> 
> Not that I know of, but Visual Studio will prompt you for the source location if you don't have it at the same place on your system.

Thanks. Perhaps we should build the MSVC binaries in `C:\SDL-3.1.2` on ci? Then we can instruct people to extract the source archive to C:, and debugging should magically work.

**Comment by slouken** [comment]
Sure, that sounds good. I don't know that we should use `src` as a subdirectory. If anything I'd use C:\temp

**Comment by madebr** [comment]
I'd like to merge these changes in main before adding a arm64 release artifact.
The executive decision to also upload a Android aar archive to the GitHub release tab remains with you.

**Pull request merged**
