### PR TITLE
audiocvt: Speed up channel count conversion by replacing divisions

### PR DESCRIPTION
**Pull request by JoelLinn**
Division is expensive and the compiler can not replace it themselves.
Though we now we will be ok in terms of floating point edge behaviour.

## Description

Replaces divisions by constants with reciprocal multiplication.
For 5.1 to stereo conversion this results in a 30% speedup.

**Edit** (revised statements about SSE/AVX, had a bug in test code):

I also vectorized the 51toStereo code which increased speed further.
~~I will test that code and remove draft status once I verified it.~~

**Edit**

conversion of `512 * 6` samples:
```
2021-06-12T02:00:19+02:00
Running cmake-build-relwithdebinfo/BenchVector51toStereo
Run on (8 X 4500 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 256 KiB (x4)
  L3 Unified 8192 KiB (x1)
Load Average: 0.62, 0.72, 0.35
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
-----------------------------------------------------------------------
Benchmark                             Time             CPU   Iterations
-----------------------------------------------------------------------
SDL_Convert51ToStereo               171 ns          171 ns      4095683
SDL_Convert51ToStereo_divfix        119 ns          119 ns      5949738
SDL_Convert51ToStereo_sse          50.3 ns         50.3 ns     13870364
SDL_Convert51ToStereo_avx          43.0 ns         43.0 ns     16289025
MEMCPY                             96.2 ns         96.2 ns      7287207
```

`SDL_Convert51ToStereo` is whats in `main`
`SDL_Convert51ToStereo_divfix` the first commit in this PR
`SDL_Convert51ToStereo_sse`  128bit 
`SDL_Convert51ToStereo_avx`  256bit

### CODE REVIEW

**Comment by flibitijibibo** [comment]
This is great! It's also pretty important for GetAudioDeviceSpec users since, [depending on how it's used](https://github.com/FNA-XNA/FAudio/blob/4881db35a409bc8cafa774440f6e672425853bcc/src/FAudio_platform_sdl2.c#L288-L331), downmixing will be really common. I'd be okay with having this patch in now, with the SSE/AVX work to come in later when it's ready.

**Comment by JoelLinn** [comment]
Sure, if desired this can be merged as is.
When will the merge window for the 2.0.16 release close?

**Comment by flibitijibibo** [comment]
I'm not 100% sure when 2.0.16 will freeze but looking at the milestone there should still be a good amount of time.

CC @icculus, this patch by itself should be pretty safe to merge.

**Comment by icculus** [comment]
Adding to the milestone so I remember to look at this, but not committing until I do.

**Comment by JoelLinn** [comment]
SSE saves 50% execution time compared to the C code (with the divisions replaced) while AVX only saves about 15% time compared to SSE.
This is because extracting the interleaved samples requires a lot of shuffles. AVX 256 bit registers are split in two lanes and only a select few instructions can move data between lo and hi.
AVX512F would help significantly since it can shuffle/permute values across all lanes at latency=1.

I noticed an Issue about the SSE3 version of Stereo to Mono. `__SSE3__` is not defined on Windows by default. If it were, it would mean the compiler is emitting SSE3 instructions anyways -  HaveSSE3() would be redundant. SDL would crash anyways in some random place were the compiler used an SSE3 instruction (On a system without SSE3). Imho, the correct approach is to not test for `__SSE3__` but for the availability of the intrinsics (like with `immintrin.h`)

Also, It would probably make sense to wrap the pragmas needed with GCC and Clang into a define in the `SDL_cpuinfo.h` header (?) and deploy them to other places were intrinsics are used (e.g. `SDL_ConvertStereoToMono`). I refrained from doing so myself because I am certain I would at least break one of the build system/platform combinations :P

**Comment by icculus** [comment]
> Division is expensive and the compiler can not replace it themselves.

I was going to say this is ridiculous, obviously a compiler can convert a division against a constant to a multiplication of its reciprocal, but oh my gosh, you're right:

https://gcc.godbolt.org/z/af19Kv43M

(Clang and GCC both won't do it, even at -O3)

...do they refuse to do this because of floating point precision concerns?

**Comment by icculus** [comment]
This all looks good, thanks!

I'm going to generate a couple separate issues for other comments, so we remember to explore them later.

**Comment by sezero** [comment]
The AVX patch is wrong and results in build failure, at least for x86:
```
src/audio/SDL_audiocvt.c: In function 'SDL_Convert51ToStereo_AVX':
src/audio/SDL_audiocvt.c:123: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'two_fifths_v'
src/audio/SDL_audiocvt.c:123: error: 'two_fifths_v' undeclared (first use in this function)
src/audio/SDL_audiocvt.c:123: error: (Each undeclared identifier is reported only once
src/audio/SDL_audiocvt.c:123: error: for each function it appears in.)
src/audio/SDL_audiocvt.c:123: warning: implicit declaration of function '_mm256_set1_ps'
src/audio/SDL_audiocvt.c:124: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'half'
src/audio/SDL_audiocvt.c:124: error: ISO C90 forbids mixed declarations and code
src/audio/SDL_audiocvt.c:124: error: 'half' undeclared (first use in this function)
src/audio/SDL_audiocvt.c:146: error: '__m256' undeclared (first use in this function)
src/audio/SDL_audiocvt.c:146: error: expected ';' before 'fc_distributed'
src/audio/SDL_audiocvt.c:149: error: ISO C90 forbids mixed declarations and code
src/audio/SDL_audiocvt.c:153: error: expected ';' before 'permuted0'
src/audio/SDL_audiocvt.c:155: error: expected ';' before 'permuted1'
src/audio/SDL_audiocvt.c:160: error: expected ';' before 'out'
src/audio/SDL_audiocvt.c:161: error: 'out' undeclared (first use in this function)
src/audio/SDL_audiocvt.c:161: warning: implicit declaration of function '_mm256_add_ps'
src/audio/SDL_audiocvt.c:161: error: 'fc_distributed' undeclared (first use in this function)
src/audio/SDL_audiocvt.c:162: warning: implicit declaration of function '_mm256_mul_ps'
src/audio/SDL_audiocvt.c:164: warning: implicit declaration of function '_mm256_storeu_ps'
src/audio/SDL_audiocvt.c:151: warning: unused variable 'permuted0_hi'
src/audio/SDL_audiocvt.c:149: warning: unused variable 'permuted0_lo'
src/audio/SDL_audiocvt.c:144: warning: unused variable 'fc_distributed_hi'
src/audio/SDL_audiocvt.c:142: warning: unused variable 'fc_distributed_lo'
src/audio/SDL_audiocvt.c:138: warning: unused variable 'in4'
src/audio/SDL_audiocvt.c:135: warning: unused variable 'in1'
make: *** [build/SDL_audiocvt.lo] Error 1
```

**Comment by JoelLinn** [comment]
AVX should be available to 32 bit mode but it seems like either the header isn't included or they are undefined for another reason

**Comment by sezero** [comment]
Hm, old compilers have issues:

- gcc-4.4.7 (linux): fails as above

- gcc-4.5.4 (mingw): ICEs with
 `src/audio/SDL_audiocvt.c:113:9: internal compiler error: in c_builtin_function_ext_scope, at c-decl.c:3558`
  Line 113 is `#pragma GCC target("avx")`

- gcc-4.9.4 (linux): no failures.

**Comment by Triang3l** [comment]
> ...do they refuse to do this because of floating point precision concerns?
Optimization that may affect rounding (including replacement of division with multiplication, reordering according to associativity properties, usage of fused multiply-add on PowerPC, among other things) can only be performed with the `-ffast-math` (aka `/fp:fast` on Visual C++) compiler option. Also, while 2.5 is exactly 0b1.01 * 2^1, 0.4 cannot even be represented as a binary fraction — in binary that's 0b1.100110011… * 2^-2, so if you replace the division by a multiplication in this case, you will be multiplying by an already rounded factor. The only case when replacement of division with multiplication is exact, and is allowed with the precise or the strict math option, is division by powers of 2, in which case both are simple exponent biasing.

**Comment by sezero** [comment]
>     * gcc-4.5.4 (mingw): ICEs with
>       `src/audio/SDL_audiocvt.c:113:9: internal compiler error: in c_builtin_function_ext_scope, at c-decl.c:3558`
>       Line 113 is `#pragma GCC target("avx")`

BTW, that ICE happens when targeting x86_64 too, so a gcc problem, to be ignored.

**Comment by JoelLinn** [comment]
"Function Specific Option Pragmas" have been introduced in GCC 4.4, so every earlier compiler should thus crash.
https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gcc/Function-Specific-Option-Pragmas.html

If 4.5.4 crashes (ignoring it's mingw) I wouldn't expect 4.4.x to work either.
Maybe we should just disable all the affected code for such old compilers, before the pragma is parsed (also concerns #4531)

**Comment by icculus** [comment]
> Maybe we should just disable all the affected code for such old compilers, before the pragma is parsed

Yes, this needs to be disabled on older compilers if they will ICE on it. We can just make a blanket "if it's less than GCC 5.0.0" or whatever. Those compilers will just not get the SSE version of the converter.

**Comment by icculus** [comment]
Can't reopen pull requests, but I opened a new issue for the compiler ICE'ing problem.

**Pull request merged**
