### PR TITLE
DirectX 12 Renderer

### PR DESCRIPTION
**Pull request by chalonverse**
## Description
This pull request adds an implementation of a DirectX 12 Renderer backend to SDL. You might wonder "Why do we need another renderer?" My primary motivation of implementing this is that I would like to add Xbox GDK support to SDL. Unfortunately, Xbox GDK does not support DirectX 11 -- DirectX 12 is required. Adding an implementation of a DirectX 12 renderer is a stepping stone to eventually supporting Xbox GDK.

This renderer supports the normal Windows target only -- it is disabled on WinRT. Although support for WinRT _could_ be added, I did not want to spend time adding support for a platform which Microsoft considers deprecated.

Additionally, because earlier versions of the Windows 10 SDK have a bug in the C bindings for DirectX 12 (where certain functions will crash), Direct X 12 support also requires Windows SDK version 10.0.19401.0 or higher. This is checked in `SDL_config_windows.h` but I don't know how to also add that check to the configure and/or CMake build flows.

Other than not supporting WinRT, this renderer has feature parity with the DirectX 11 renderer. I used the DirectX 11 renderer's code as a starting point and rewrote everything to work with DirectX 12. Performance-wise, on some of the test programs it is on par with or slightly faster than the DirectX 11 renderer. However, in most cases it is noticeably slower than the DirectX 11 renderer. For example, on testsprite2 I get around 5,000 FPS with the DirectX 11 renderer but I get only 2,500 FPS with the DirectX 12 renderer. I think part of this is just that the way `SDL_render` issues some of the commands isn't particularly great for maximizing performance in the DirectX 12 rendering model, but it's also likely there is some room for improvement. However, I wanted to get a functional pull request in first.

To enable the renderer, set `SDL_HINT_RENDER_DRIVER` to `"direct3d12"`.

Additionally, you can enable the DirectX 12 and DXGI debug layer by setting `SDL_HINT_RENDER_DIRECT3D11_DEBUG` to `"1"`

I am open to any feedback or changes required to merge this, please let me know!

## What I've Tested
I've tried to test as many of the test programs as possible, in some cases locally modifying the test case code to force on the direct3d12 renderer when the `"--renderer direct3d12"` command line argument was not respected:
* testautomation_render passes all the automated render tests
* testdraw2 yields correct results
* testoverlay2 yields correct results
* testrendertarget yields correct results
* testsprite2 yields correct results
* testyuv yields correct results when in hardware mode

Additionally, because there seems to be no test cases for `SDL_LockTexture` and `SDL_UnlockTexture`, I locally tested it out by adding some additional code to testsprite2, and it seems to behave correctly.

I've also tested out enabling the DirectX 12 renderer in one of my existing 2D game projects, and the visual output seems to be identical to the default renderer.

## Caveats
* Currently, there is a limit on the maximum number of textures (16384). This number seems reasonably high enough that I doubt anyone will encounter the limit. This number could be easily increased in the code if needed. However, having a limit on the number of textures makes it much more efficient and easy to reuse SRV descriptors, which would be more difficult to do if an arbitrary number of textures were required. However, I can change this if needed.
* Currently, there is a limit on the maximum number of primitives in the vertex buffer sent by the internal SDL command queue to 2048 primitives. The reason this is limited is because it makes it possible to allocate all the temporary vertex buffers on a single ~8MB resource heap, which is more efficient than allocating a separate heap specifically for each vertex buffers. It is conceivable that if `SDL_HINT_RENDER_LINE_METHOD` is set to the default Bresenham's line algorithm and a very long line is drawn, as that will generate a large set of points in the vertex buffer. It would be easy to increase this number to something higher, and it's also possible to remove the limit of necessary (though it will be less efficient).
* I've only tested compiling through Visual Studio. I made updates where relevant to both the `CMakeLists.txt` and configure scripts, so I _think_ it should work, but I was uncertain what the normal build process is, and this may need testing. As I mentioned above, I'm also not certain about how to handle the Windows SDK check issue.

### CODE REVIEW

**Comment by sezero** [comment]
New entries to dynapi should not be inserted but appended:
running gendynapi.pl and then hand-editing to add `__WIN32__`
ifdefs would do it. Here is a patch on top of your work 
which does just that:
```diff
diff --git a/src/dynapi/SDL2.exports b/src/dynapi/SDL2.exports
index 8cd2a4b..1bf7d5f 100644
--- a/src/dynapi/SDL2.exports
+++ b/src/dynapi/SDL2.exports
@@ -847 +847,2 @@
 ++'_SDL_GUIDFromString'.'SDL2.dll'.'SDL_GUIDFromString'
+++'_SDL_RenderGetD3D12Device'.'SDL2.dll'.'SDL_RenderGetD3D12Device'
diff --git a/src/dynapi/SDL_dynapi_overrides.h b/src/dynapi/SDL_dynapi_overrides.h
index b49def8..5537f1b 100644
--- a/src/dynapi/SDL_dynapi_overrides.h
+++ b/src/dynapi/SDL_dynapi_overrides.h
@@ -792,3 +792,2 @@
 #define SDL_RenderGetD3D11Device SDL_RenderGetD3D11Device_REAL
-#define SDL_RenderGetD3D12Device SDL_RenderGetD3D12Device_REAL
 #define SDL_UpdateNVTexture SDL_UpdateNVTexture_REAL
@@ -874 +873,2 @@
 #define SDL_GUIDFromString SDL_GUIDFromString_REAL
+#define SDL_RenderGetD3D12Device SDL_RenderGetD3D12Device_REAL
diff --git a/src/dynapi/SDL_dynapi_procs.h b/src/dynapi/SDL_dynapi_procs.h
index 0ec2669..8706dc3 100644
--- a/src/dynapi/SDL_dynapi_procs.h
+++ b/src/dynapi/SDL_dynapi_procs.h
@@ -858,3 +858,2 @@ SDL_DYNAPI_PROC(int,SDL_SoftStretchLinear,(SDL_Surface *a, const SDL_Rect *b, SD
 SDL_DYNAPI_PROC(ID3D11Device*,SDL_RenderGetD3D11Device,(SDL_Renderer *a),(a),return)
-SDL_DYNAPI_PROC(ID3D12Device*,SDL_RenderGetD3D12Device,(SDL_Renderer *a),(a),return)
 #endif
@@ -949 +948,4 @@ SDL_DYNAPI_PROC(void,SDL_GUIDToString,(SDL_GUID a, char *b, int c),(a,b,c),)
 SDL_DYNAPI_PROC(SDL_GUID,SDL_GUIDFromString,(const char *a),(a),return)
+#ifdef __WIN32__
+SDL_DYNAPI_PROC(ID3D12Device*,SDL_RenderGetD3D12Device,(SDL_Renderer *a),(a),return)
+#endif

**Comment by chalonverse** [comment]
Ok, I've applied that dynapi patch

**Comment by Cacodemon345** [comment]
Is there any reason to PR the DirectX 12 renderer to SDL? Especially given you are targetting Xbox GDK, which I believe is under NDA?

**Comment by chalonverse** [comment]
Furthermore, since last year most if not all of the GDK APIs that would be required for an Xbox GDK port of SDL are no longer under NDA, as they are shared with Windows GDK. In fact, Microsoft released a repository of Xbox samples under the MIT license: https://github.com/microsoft/Xbox-GDK-Samples/

That being said, it is possible that while the DirectX 12 renderer and Windows GDK support absolutely can be in the public SDL repo, the Xbox GDK support might have to be in a private repo as is currently done for Nintendo Switch.

Even if my end goal of Xbox GDK has to be private, I think the stepping stones of the DirectX 12 and Windows GDK would be useful to the broader community.

**Comment by Cacodemon345** [comment]
WinRT support would also be nice for Xbox Live Creators Program titles, since they can use DirectX 12 according to the official docs despite being UWP.

I don't think programs on Xbox Dev Mode will be able to access DirectX 12 though, or so it seems, given the documentation on that seems to be extremely vague and nothing states on how to get stuff there recognized as a game instead of an app.

**Comment by icculus** [comment]
This fills a welcome gap, but to be clear, when the GPU API merges, this would be one of the backends that gets deleted. But we are still some time away from there.

**Comment by flibitijibibo** [comment]
Throwing in a note as a WinRT comaintainer: If GDK is an express goal for this patchset, WinRT can and should be ignored - while the Creator's Program is still using UWP I do not expect it to be this way for much longer. VisualC-GDK should be actively looked into as a replacement for VisualC-WinRT, and we can host VisualC-GDKX in a private repo (though the code should be able to stay entirely the same, unless we start pushing features that use XBL APIs... controller ownership maybe?).

**Comment by icculus** [comment]
> This fills a welcome gap

(this phrase made sense in my head when I wrote it, I swear.)

This is a **welcome patch** to **fill a gap**.   🤣

Is someone fixing the conflicts, or should I take care of it?

**Comment by Cacodemon345** [comment]
AFAIK Windows GDK is just Win32 + GDK extensions so a VisualC-GDK project sounds redundant.

**Comment by chalonverse** [comment]
icculus - Thanks for resolving the conflict! I understand that when the GPU API is integrated it will mean removing this renderer, but I figure that is still going to be a while. I'm happy to help with adding DirectX 12 to that as well (if needed) when the time comes.

RE: Whether Windows GDK needs another project file or not, primarily it's just that each vcxproj would need to have a different target for Windows GDK that links against the additional GDK libraries and sets GDK-specific project settings and preprocessor defines. One way to do this is to add an additional Solution Configuration for Windows GDK, and then each of the vcxproj for each test program could be setup for that additional configuration. The other option is to make a separate VisualC-GDK solution/project files. Either way would work, I think -- it's just a preference thing.

Regarding differences between Windows and Xbox GDK, a primary difference is just that the subset of Win32/other Windows APIs supported by Xbox GDK is much smaller than Windows GDK, which largely lets you use any old Win32 APIs you want to. As an example, you can continue to use XInput/RawInput/other input APIs in Windows GDK _or_ the new GameInput API, but Xbox GDK requires that you use GameInput. The goal, I think, should be to try to make the differences between Windows GDK and Xbox GDK as minimal as possible, but there will be some exceptions. For example, you really _do_ want to support arbitrary non-Xbox controllers on Windows, so I don't think that switching Windows GDK to use GameInput is the correct choice.

Furthermore, there are going to be some required changes that cannot be avoided: off the top of my head, Xbox GDK uses PresentX instead of DXGI to manage the swapchain, and the shader blobs will be different as they are precompiled for Xbox One and/or Xbox Series, respectively.

Perhaps the GDK topic can be a larger discussion elsewhere -- I'm not sure the best place for that? I could make a draft PR? Or make an issue for it? I've not started any work on that part, yet.

**Comment by flibitijibibo** [comment]
We can use #4519 for GDK discussion!

**Comment by neheb** [comment]
Since this was added, is there a point to having DX11 support?

**Comment by chalonverse** [comment]
One reason to keep DirectX 11 support is as of right now, WinRT and Windows Phone targets only support the DirectX 11 renderer.

**Comment by icculus** [comment]
D3D11 is _also_ slated to go away with the GPU work, as there will be a D3D11 backend there that will give us support on everything back to Windows Vista (if SDL3 drops WinXP support we could drop D3D9 too, hint hint).

But for now, it stays.

**Comment by ahmed605** [comment]
> it is disabled on WinRT. Although support for WinRT could be added, I did not want to spend time adding support for a platform which Microsoft considers deprecated.

UWP isn't deprecated, it still getting new features, there's no official document from Microsoft that says so (they even mentioned it at Build 2022 as one of ways recommend to create new Windows apps)

Having a UWP support would be very nice considering that it's still the only way to *properly* create universal Windows apps

(If you meant the WinRT ABI, that isn't deprecated either and I don't think it will ever be, considering that this is the path Microsoft chooses for almost every new API, including WASDK APIs)

**Comment by ahmed605** [comment]
> And on top of that, it remains the only way to create cross-platform Xbox Live Creators Program games. If support for Direct3D 12 were extended to work with UWP it would be very helpful.
> 
> Microsoft Store in Windows 11 also remains an UWP app.

Yeah, it's the only way to create apps for Hololens too

**Comment by chalonverse** [comment]
> 
> UWP isn't deprecated, it still getting new features, there's no official document from Microsoft that says so (they even mentioned it at Build 2022 as one of ways recommend to create new Windows apps)
> 
> Having a UWP support would be very nice considering that it's still the only way to _properly_ create universal Windows apps
> 
> I assume adding UWP support would be as simple as rendering to a Swapchain created using CreateSwapChainForCoreWindow

Maybe depreciated is a strong term — but to clarify, is there any platform for UWP/WinRT which supports DirectX 12 but _does not_ support DirectX 11?

At least according to https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/system-resource-allocation, apps on Xbox Live Creators program don’t allow for DirectX 12 at all. Games can use DirectX 11 or 12, even on Xbox Series consoles.

It’s possible that the WinRT code for the swap chain that the DirectX 11 renderer uses may work for DirectX 12, but at least for DirectX 11 there are other special cases for WinRT in the renderer. I’m not familiar really with the WinRT development workflow so I think one of the WinRT maintainers would have to comment on how much work it would be.

**Comment by ahmed605** [comment]
> but to clarify, is there any platform for UWP/WinRT which supports DirectX 12 but does not support DirectX 11?

nope, but I mean it would be nice to use DX 12 renderer instead of 11

I mean there's no platform for legacy Win32 apps that supports DirectX 12 but not 11 either

**Comment by Cacodemon345** [comment]
> At least according to https://docs.microsoft.com/en-us/windows/uwp/xbox-apps/system-resource-allocation, apps on Xbox Live Creators program don’t allow for DirectX 12 at all. Games can use DirectX 11 or 12, even on Xbox Series consoles.

You are reading too hard into the last paragraph, which is for non-UWP Xbox games. The first portion of page states that the requirements depend on whether you are developing a UWP app or a Xbox Live Creators Program game. For the latter the ability to use DX12 exists.

**Comment by ahmed605** [comment]
> I still have no idea how to mark an app as a game to be honest.

The Partner Center allows you to do so iirc

**Comment by chalonverse** [comment]
I could look at the WinRT/UWP support once I finish my GDK project. Conceivably, it wouldn't be that different from how it works with DirectX 11, but I have no experience developing for UWP so it would be a bit of a learning curve to even figure out how to test it properly.

**Comment by ahmed605** [comment]
Hey @chalonverse, any news on the UWP support?

BTW regarding this
> apps on Xbox Live Creators program don’t allow for DirectX 12 at all.

non-games UWP apps on Xbox Series S and X can now use DirectX 12!

**Comment by chalonverse** [comment]
Sorry for the late reply @ahmed605, I got pretty busy with work after pushing the Xbox GDK stuff in July. Currently I don't really have the bandwidth to get the WinRT DirectX 12 support working. And with the SDL_GPU project work coming along for SDL 3, I'm not sure how long this backend will continue to be supported.

**Pull request merged**
