### PR TITLE
Use VBO for SDL_Renderer/OpenGL back-end

### PR DESCRIPTION
**Pull request by 1bsyl**
Use VBO for the SDL_Renderer / OpenGL Backen
Mostly copy-paste from GLES2 back-end ...

Tested with texture / points / lines / triangles on linux

### CODE REVIEW

**Comment by slouken** [comment]
It looks like you don't actually check to see if VBO's are supported. Can you check with the Microsoft software OpenGL driver? That's a good proxy for old/less-capable hardware.

**Comment by slime73** [comment]
As per https://github.com/libsdl-org/SDL/issues/5061#issuecomment-990917485 I wonder if it'll be faster to use VBO-less `glDrawArrays` and friends. That's been my experience with my own code on desktop platforms, at least.

I believe the GLES2 backend uses VBOs rather than client-side arrays because the latter is a lot slower in some ANGLE-based web implementations, which won't be an issue in the desktop GL backend.

**Comment by 1bsyl** [comment]
@slouken I've no idea how to try that and I haven't updated/boot my window for a while so if someone has this set up, it be quite convenient !

@slime73 
I've tried the patch (see below).
(also with some tweak modification to enable the client state only once + to batch all similar commands).
It runs at 72 ms so it's a little bit faster (with more stable timings) than the VBO (wich was ! 75 ms) 
(anyway faster, that the current glBegin/for loop/glEnd




```
diff --git a/src/render/opengl/SDL_render_gl.c b/src/render/opengl/SDL_render_gl.c
index dbfcc414c..ff4f79b51 100644
--- a/src/render/opengl/SDL_render_gl.c
+++ b/src/render/opengl/SDL_render_gl.c
@@ -989,7 +989,7 @@ GL_QueueGeometry(SDL_Renderer *renderer, SDL_RenderCommand *cmd, SDL_Texture *te
     int i;
     int count = indices ? num_indices : num_vertices;
     GLfloat *verts;
-    int sz = 2 + 4 + (texture ? 2 : 0);
+    int sz = 2 + 1 + (texture ? 2 : 0);
 
     verts = (GLfloat *) SDL_AllocateRenderVertices(renderer, count * sz * sizeof (GLfloat), 0, &cmd->data.draw.first);
     if (!verts) {
@@ -1006,7 +1006,7 @@ GL_QueueGeometry(SDL_Renderer *renderer, SDL_RenderCommand *cmd, SDL_Texture *te
     for (i = 0; i < count; i++) {
         int j;
         float *xy_;
-        SDL_Color col_;
+        int col_;
         if (size_indices == 4) {
             j = ((const Uint32 *)indices)[i];
         } else if (size_indices == 2) {
@@ -1018,15 +1018,12 @@ GL_QueueGeometry(SDL_Renderer *renderer, SDL_RenderCommand *cmd, SDL_Texture *te
         }
 
         xy_ = (float *)((char*)xy + j * xy_stride);
-        col_ = *(SDL_Color *)((char*)color + j * color_stride);
+        col_ = *(int *)((char*)color + j * color_stride);
 
         *(verts++) = xy_[0] * scale_x;
         *(verts++) = xy_[1] * scale_y;
 
-        *(verts++) = col_.r * inv255f;
-        *(verts++) = col_.g * inv255f;
-        *(verts++) = col_.b * inv255f;
-        *(verts++) = col_.a * inv255f;
+        *((int *)verts++) = col_;
 
         if (texture) {
             float *uv_ = (float *)((char*)uv + j * uv_stride);
@@ -1279,6 +1276,7 @@ GL_RunCommandQueue(SDL_Renderer * renderer, SDL_RenderCommand *cmd, void *vertic
                 const GLfloat *verts = (GLfloat *) (((Uint8 *) vertices) + cmd->data.draw.first);
                 SDL_Texture *texture = cmd->data.draw.texture;
                 const size_t count = cmd->data.draw.count;
+                int stride = sizeof (GLfloat) * 2 /* position */ + sizeof (int) /* color */;
 
                 if (texture) {
                     SetCopyState(data, cmd);
@@ -1286,6 +1284,24 @@ GL_RunCommandQueue(SDL_Renderer * renderer, SDL_RenderCommand *cmd, void *vertic
                     SetDrawState(data, cmd, SHADER_SOLID);
                 }
 
+                data->glEnableClientState(GL_VERTEX_ARRAY);
+                data->glEnableClientState(GL_COLOR_ARRAY);
+                if (texture) {
+                    data->glEnableClientState(GL_TEXTURE_COORD_ARRAY);
+                    stride += sizeof (GLfloat) * 2; /* tex coord */
+                }
+                data->glColorPointer(4, GL_UNSIGNED_BYTE, stride, verts + 2);
+                data->glVertexPointer(2, GL_FLOAT, stride, verts);
+                if (texture) {
+                    data->glTexCoordPointer(2, GL_FLOAT, stride, verts + 2 + 1);
+                }
+                data->glDrawArrays(GL_TRIANGLES, 0, (GLsizei) count);
+                data->glDisableClientState(GL_VERTEX_ARRAY);
+                data->glDisableClientState(GL_COLOR_ARRAY);
+                if (texture) {
+                    data->glDisableClientState(GL_TEXTURE_COORD_ARRAY);
+                }
+#if 0
                 {
                     size_t j;
                     float currentColor[4];
@@ -1313,6 +1329,7 @@ GL_RunCommandQueue(SDL_Renderer * renderer, SDL_RenderCommand *cmd, void *vertic
                     data->glEnd();
                     data->glColor4f(currentColor[0], currentColor[1], currentColor[2], currentColor[3]);
                 }
+#endif
                 break;
            }
 

```

**Comment by 1bsyl** [comment]
@slime73 you're probably right about the indices.
But it seems difficult to do for all cases
- we need two separate buffers (if we want to aggregates the commands).
- we cannot eliminate always the copies (there a potential multiplication by render->scale for vertices, multiplication for textcoord for non-power of two texture (only opengl), eventually no indice, or char/shot/indice indice).
+ the fact that the SDL_Render cannot "steal/keep internally" the user pointer (which may change).
+ most of the time RenderGeometry is used for small drawing (RenderCopy, FillRect), so that there are maybe less advantages ti use indices there.
..
But, I think there is a nice example we could try at some point : DearImGui can have huge plot, with 64k points, 
 they use "short int" indices. so we could try to set some assumptions, so that it exist at least a fastest path.
eg: lot of indice, indice short, no scaling needed,
And we can use SDL_FlushRendere before/after so that we can render immediately during the call.

**Comment by 1bsyl** [comment]
@slime73 @slime73 @rtrussell 
Sorry, I totally messed up with the timing of rtrussell bench, because of my build partially compiled with -O2 ...

with opengl backend:
- With current head, the circles draws: 25 ms.
- With the line/triangle function: it draws at 115 ms.
- With the line/triangle function + Opengl/VBO path (this PR): it draws at 40 ms.
- With the line/triangle function + Opengl/-Without-VBO path (the function / slime73): it draws at 35 ms.

**Comment by rtrussell** [comment]
> t looks like you don't actually check to see if VBO's are supported. Can you check with the Microsoft software OpenGL driver? That's a good proxy for old/less-capable hardware.

VBOs were apparently [introduced](https://stackoverflow.com/questions/14207055/opengl-vertex-arrays-required-version) in core OpenGL 1.5, and glDrawElements in OpenGL 1.1.  I don't know what minimum version of OpenGL SDL2 requires, but glDrawElements would be safer.

**Comment by 1bsyl** [comment]
so we would probably go for @slime73 idea.
we could add some weak dlopen loading to keep backward compatibility
```
if (glVertexPointer != NULL) {
 ... use it
} else {
  old code:
   glBegin()      etc.
  
} 
```

**Comment by slime73** [comment]
> could add some weak dlopen loading to keep backward compatibility

For plain vertex arrays I don't think this is needed - VBOs require OpenGL 1.5 (or an extension), but vertex arrays + glDrawArrays (via `glVertexPointer`, `glColorPointer`, etc) only require GL 1.1 which SDL_Render's GL backend already requires.

**Comment by rtrussell** [comment]
> For plain vertex arrays I don't think this is needed - buffer objects (VBOs) require OpenGL 1.5 (or an extension), but rendering vertex arrays in general (via `glDrawArrays`, `glVertexPointer`, `glColorPointer`, etc) only requires GL 1.1 which SDL_Render's GL backend already requires.

I presume the intention is to use the new code for OpenGL ES as well as OpenGL?  Over at [Issue #5061](https://github.com/libsdl-org/SDL/issues/5061) it was reported that there is the "_Same problem on Raspberry Pi with kmsdrm backend and OpenGL ES: Lines are always one pixel too short_".

**Comment by slouken** [comment]
I think this is superceded by https://github.com/libsdl-org/SDL/pull/5097, please reopen this if I'm mistaken.

**Comment by icculus** [comment]
So this is likely not ever going to be a problem for desktop OpenGL, but the primary reason to use VBOs for our usage pattern is that later Core Profile OpenGL does not offer client-side arrays and _must_ use VBOs. The Compatibility Profile still has them afaik.

#5097 just moves us to array drawing at all, but it's still client-side arrays.

It's theoretically possible that some GL implementations can perform better with VBOs, or are just managing an internal VBO for you when you use a client-side array. For an array that isn't static data, like we use, the wins are more questionable. If we could reuse the VBO unchanged for multiple draws, it would likely be much faster though, but I don't think we can have that with the existing public API.

**Comment by slime73** [comment]
Yeah. For streaming vertex data like SDL_Render does, I did some fairly extensive profiling across different setups over the years for LÖVE and ended up with [this](https://github.com/love2d/love/blob/main/src/modules/graphics/opengl/StreamBuffer.cpp#L494) which is probably much more complicated than SDL_Render would ever need (especially because the effort could go into something like a Vulkan backend instead) – the tl;dr is that GL3+ requires VBOs as you say, but until GL4.5 it only offers data transfer APIs for them that are at best roughly as fast as client-side arrays, and at worst much slower (depending on graphics driver internals).

My tests never involved GLES2+ANGLE/web though, which is the platform that resulted in SDL_Render's GLES2 VBO code being created because client-side arrays were slower in ANGLE if I'm remembering right.

**Pull request closed without merging**
