### PR TITLE
Add build target to Xcode project to create an xcframework for iOS

### PR DESCRIPTION
**Pull request by tjpadula**
Add a build target to the Mac Xcode project to build an SDL2.xcframework for all combinations of iOS platforms (devices and simulator) for all applicable CPUs.

Full info for building the xcframework and using it in a client app is included in the appropriate iOS readme.

## Description
Build target affects only iOS. The combinations provided by this target are:

Simulator: i386, x86_64, and arm64
Devices: arm64 and armv7

(Note that you must build on an Apple Silicon Mac if you need the arm64 simulator platform build.)

An xcframework is a new (as of Xcode 11) uber-framework which can handle any combination of processor type and target OS platform. 

In the past, iOS devices were always an ARM variant processor, and the simulator was always i386 or x86_64, and thus libraries could be combined into a single framework for both simulator and device. With the introduction of the Apple Silicon ARM-based machines, regular frameworks would collide as CPU type was no longer sufficient to differentiate the platform. So Apple created the new xcframework library package.

## Issue
https://github.com/libsdl-org/SDL/issues/6156

### CODE REVIEW

**Comment by slouken** [comment]
Does Apple support multi-platform xcframeworks? e.g. a single target for all platforms and architectures? Or a single target where the platform is specified in the UI, like the current framework target?

**Comment by tjpadula** [comment]
If by multi-platform, you mean iOS vs Mac vs iPadOS vs Apple TV, Apple Silicon vs. Intel, and iOS Simulator vs. iOS devices, that is exactly what an xcframework is for. Xcode automatically pulls the relevant platform parts when it builds depending on the target type.

**Comment by tjpadula** [comment]
And I see that two of the Ubuntu checks failed, both of them tripping over a version string. But, the log shows identical version strings. As far as I can tell, I didn't touch this part, certainly not intentionally, can someone tell me what to do at this point?

**Comment by sezero** [comment]
@slouken: Why is `./test/versioning.sh` failing?

```
$ ./test/versioning.sh
ok - configure.ac 2.25.0
ok - configure 2.25.0
ok - CMakeLists.txt 2.25.0
ok - Makefile.os2 2.25.0
ok - Makefile.w32 2.25.0
ok - version.rc FILEVERSION 2,25,0,0
ok - version.rc PRODUCTVERSION 2,25,0,0
ok - version.rc FileVersion 2, 25, 0, 0
ok - version.rc ProductVersion 2, 25, 0, 0
ok - Info-Framework.plist CFBundleShortVersionString 2.25.0
ok - Info-Framework.plist CFBundleVersion 2.25.0
not ok - project.pbxproj DYLIB_COMPATIBILITY_VERSION is inconsistent, expected 2501.0.0
2501.0.0, got 2501.0.0
2501.0.0
1
1
not ok - project.pbxproj DYLIB_CURRENT_VERSION is inconsistent, expected 2501.0.0
2501.0.0, got 2501.0.0
2501.0.0
1
1
1..13
```

**Comment by sezero** [comment]
BTW, the newly added entries have `DYLIB_CURRENT_VERSION` and `DYLIB_COMPATIBILITY_VERSION` as 1 and 1, which seem inconsistent.

**Comment by sezero** [comment]
OK, a fix is pushed as 911524da45ee2ae44c7c200fdc15c6da7566c3eb

**Comment by ericoporto** [comment]
Hey, is this build provided by the current CI on releases? I understood this is the best way for using SDL2 iOS builds.

**Comment by slouken** [comment]
Right now the xcframework is for iOS, which isn't pre-built as part of the release process. In the long run we probably want a single xcframework that covers all platforms and architectures and release that as a single download for Xcode. I'm not sure what needs to be done to make that happen though.

**Pull request merged**
