### PR TITLE
cmake: find DirectFB through a cmake module + use it in installed sdl2 prefix

### PR DESCRIPTION
**Pull request by madebr**
project:
- let `test/versioning.sh` also check the version variables embedded in the generated `configure` script
- Switched order of regenerating `configure` and running `test/versioning.sh` in `docs/release_checklist.md`

directfb:
- Find directfb headers using a `FindDirectFB.cmake` module.
- Re-use this module for looking for directfb for an installed sdl2 prefix

Addresses cmake directfb part of https://github.com/libsdl-org/SDL/issues/3930
X11 is still todo

### CODE REVIEW

**Comment by slouken** [comment]
@madebr, what's the status of this patch? Is this something you want to get in for 2.26?

**Comment by madebr** [comment]
No, I need to rebase and think about possible alternatives.

**Comment by bl4ckb0ne** [comment]
The patchset doesnt apply to 2.24.2 anymore.

**Comment by sezero** [comment]
I guess this can be closed because SDL3 dropped directfb support.

**Comment by madebr** [comment]
Yes, and the various CMake find modules can be integrated in `cmake/sdlfind.cmake`.

**Pull request closed without merging**
