### PR TITLE
Refactor gendynapi.py to make it more re-usable

### PR DESCRIPTION
**Pull request by madebr**
In a later stage, we should probably turn it into a python module that can be imported.
This would be useful for generating [tbd](https://github.com/libsdl-org/SDL_image/issues/438)s and [ymls for llvm-ifs](https://github.com/libsdl-org/setup-sdl/issues/25).

### CODE REVIEW

**Comment by sezero** [comment]
What is the minimum python3 version required after this?
My python3.7 fails with the following:
```
Traceback (most recent call last):
  File "./gendynapi.py", line 62, in <module>
    @dataclasses.dataclass(frozen=True)
  File "./gendynapi.py", line 66, in SdlProcedure
    parameter: list[str]
TypeError: 'type' object is not subscriptable
```

**Comment by madebr** [comment]
> What is the minimum python3 version required after this? My python3.7 fails with the following:

3.9:  array subscript

(3.9 is the oldest version not in EOL)

**Comment by madebr** [comment]
If you really need 3.7 support,
you can add the following at the the top
```python
from typing import List
```
and replace all instances of `list[...]` with `List[...]`.
And similarly for tuple and dict.

**Comment by sezero** [comment]
OK, I'll build a 3.9 version. Thanks.

**Pull request merged**
