### PR TITLE
gamecontrollerdb: Linux, add mappings for hid-nintendo driver and more

### PR DESCRIPTION
**Pull request by SuperSamus**
## Description
Adds mappings for the new Nintendo Switch controller driver, `hid-nintendo`, mainlined in the Linux kernel since 5.16.
Plus, some more Switch related controllers (taken from https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt).

Tested only on a Switch Pro Controller `050000007e0500000920000001800000`, using the `SDL_GAMECONTROLLERCONFIG` environment variable. (Without it, according to the Xbox layout, the West and North buttons are "physically" swapped, while the South and East buttons aren't).

## Existing Issue(s)
Closes https://github.com/DanielOgorchock/linux/issues/28, and https://patchwork.kernel.org/project/linux-input/patch/20220512001500.16739-1-fletcher0max@gmail.com/.

### CODE REVIEW

**Comment by SuperSamus** [comment]
Is there any holdup for this?
Like, did I do something wrong (definitely possible since I'm inexperenced)? Should I do something different?

**Comment by slouken** [comment]
No, you haven't done anything wrong here, I just haven't had a chance to set up a system with hid-nintendo to verify the mappings.

FYI, Nintendo switch mappings should check hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1 so the hint selects the correct position vs label mapping.

**Comment by SuperSamus** [comment]
> FYI, Nintendo switch mappings should check hint:SDL_GAMECONTROLLER_USE_BUTTON_LABELS:=1 so the hint selects the correct position vs label mapping.

I did put the check on everything but single joycons (where it doesn't make much sense, since you are either pressing a d-pad on the left joycon, or the labels are rotated 90° on the right joycon, unless you simply want A/B and X/Y swapped on these too).

**Comment by SuperSamus** [comment]
Sorry for bumping again, but could it be possible for this to be tested before SDL 2.24.0 releases?
(I stress the fact that right now, the default experience with the Switch Pro Controller on Linux has the wrong mappings, so this should be fixed as soon as possible.)

**Comment by slouken** [comment]
Sure, I'll take a look.

**Comment by slouken** [comment]
Looks good, thanks!

**Pull request merged**
