### PR TITLE
Render GPU: Don't call GetWindowSizeInPixels during RenderPreset

### LINKED ISSUE #10977: SDL3, macOS: Main thread warnings with latest revision of SDL3
Since recently I am getting these warnings when calling `SDL_RenderPresent()` on macOS Sonoma:

[NSView bounds] must be used from main thread only
[NSView convertRectToBacking:] must be used from main thread only

This did not happen before.

### PR DESCRIPTION
**Pull request by thatcosmonaut**
Resolves #10977

### CODE REVIEW

**Comment by Akaricchi** [comment]
Someone needs to check this with logical presentation. It looks like https://github.com/libsdl-org/SDL/blob/d2094bd0a248d03384b9fe01b09456cb6f063272/src/render/SDL_render.c#L2651 overwrites these values with the fake ones, which is definitely not what we want here.

**Comment by thatcosmonaut** [comment]
Is the actual pixel size cached somewhere already?

**Comment by slouken** [comment]
> Is the actual pixel size cached somewhere already?

No, but we can save it here:
```
static void UpdateLogicalPresentation(SDL_Renderer *renderer)
{
    if (renderer->logical_presentation_mode == SDL_LOGICAL_PRESENTATION_DISABLED) {
        renderer->main_view.logical_offset.x = renderer->main_view.logical_offset.y = 0.0f;
        renderer->main_view.logical_scale.x = renderer->main_view.logical_scale.y = 1.0f;
        renderer->main_view.current_scale.x = renderer->main_view.scale.x;  // skip the multiplications against 1.0f.
        renderer->main_view.current_scale.y = renderer->main_view.scale.y;
        UpdateMainViewDimensions(renderer);
        UpdatePixelClipRect(renderer, &renderer->main_view);
        return;  // All done!
    }

    int iwidth, iheight;
    SDL_GetRenderOutputSize(renderer, &iwidth, &iheight);
```

**Comment by thatcosmonaut** [comment]
Should be fixed now.

**Review by slouken — APPROVED** [review]

**Review by flibitijibibo — APPROVED** [review]

**Comment by andreasgrabher** [comment]
It seems this causes a crash on my system (Mac mini M1, macOS Sonoma). I get this error message:

```
-[MTLTextureDescriptorInternal validateWithDevice:], line 1357: error 'Texture Descriptor Validation
MTLTextureDescriptor has width of zero.
MTLTextureDescriptor has height of zero.
'
```

**Comment by slouken** [comment]
@thatcosmonaut, the 0 width/height error was caused by the window size never getting set when logical presentation is disabled. I'm fixing it now, but please be more diligent about testing your changes before submitting them.

**Comment by thatcosmonaut** [comment]
My apologies, I'm not very familiar with SDL_Render so I probably shouldn't have touched this.

**Comment by slouken** [comment]
> My apologies, I'm not very familiar with SDL_Render so I probably shouldn't have touched this.

It's fine for you to make changes anywhere in the SDL codebase, and conceptually what you did is fine. It's just that you didn't, say, run testsprite or anything to verify that your changes worked. If you have any questions about how to test things elsewhere, please feel free to ask!

**Comment by thatcosmonaut** [comment]
I actually did run testsprite and it was fine on my machine (famous last words...) But I think there's a render mode I wasn't aware of that caused the crash, so I probably need to check more of the tests next time.

**Pull request merged**
