### PR TITLE
Switch to SDL_Bool like other SDL types

### PR DESCRIPTION
**Pull request by markand**

### CODE REVIEW

**Comment by slouken** [comment]
Let's hold off on merging this, we may be switching to the stdbool type.

**Comment by sezero** [comment]
I don't think this one is a good idea.

**Comment by slouken** [comment]
Maybe I'm just conditioned by years of looking at the code, but I prefer `SDL_bool` as well. @icculus?

**Comment by icculus** [comment]
> Maybe I'm just conditioned by years of looking at the code, but I prefer SDL_bool as well.

Same.

**Comment by sezero** [comment]
Close?

**Comment by slouken** [comment]
Yep, in general we've decided to minimize sweeping code changes that won't translate to SDL2. This will minimize the work involved in merging fixes between them.

**Pull request closed without merging**
