### PR TITLE
SDL_HAVE_YUV adjustments

### PR DESCRIPTION
**Pull request by pionere**
1. hide renderer->UpdateTextureYUV assignment in case SDL_HAVE_YUV is false to prevent compilation error
2. hide more code in case SDL_HAVE_YUV is false to reduce footprint
3. _EXTERNAL_OES only for ANDROID (?)
4. free renderer in D3D11_CreateRenderer if D3D11_RenderData can not be allocated to prevent memory leak
5. hide impossible (?) branch in D3D_UnlockTexture

Note: be aware, I do not know what I'm doing!

### CODE REVIEW

**Comment by 1bsyl** [comment]
merged : 
[fix compile error with disabled SDL_HAVE_YUV (vita)](https://github.com/libsdl-org/SDL/pull/5313/commits/c708ea4aa4397321c9a0df92ed0fb0c69425dca0)
[c708ea4](https://github.com/libsdl-org/SDL/pull/5313/commits/c708ea4aa4397321c9a0df92ed0fb0c69425dca0)

merged : 
@pionere
[extend the code hidden by SDL_HAVE_YUV](https://github.com/libsdl-org/SDL/pull/5313/commits/ea4fee34fbabc2c8dc285b87a1aeefd34507718d)
[ea4fee3](https://github.com/libsdl-org/SDL/pull/5313/commits/ea4fee34fbabc2c8dc285b87a1aeefd34507718d)

merged : 
@pionere
[fix memory leak in D3D11_CreateRenderer](https://github.com/libsdl-org/SDL/pull/5313/commits/ba62bedb9e116635d97cdfb7991a9d41e8ac8789) [ba62bed](https://github.com/libsdl-org/SDL/pull/5313/commits/ba62bedb9e116635d97cdfb7991a9d41e8ac8789)



Not sure about:
 [*_EXTERNAL_OES only for ANDROID](https://github.com/libsdl-org/SDL/pull/5313/commits/93c1de9e51025e732aae592f77437c03ee083868) [93c1de9](https://github.com/libsdl-org/SDL/pull/5313/commits/93c1de9e51025e732aae592f77437c03ee083868)

Not sure about:
[hide impossible branch in D3D_UnlockTexture](https://github.com/libsdl-org/SDL/pull/5313/commits/9cc3cda9769423b58da68535bd6a66fea2057e8c) [9cc3cda](https://github.com/libsdl-org/SDL/pull/5313/commits/9cc3cda9769423b58da68535bd6a66fea2057e8c)

**Comment by slouken** [comment]
External OES is not Android only, and even if it were, the additional preprocessor complexity would save almost no code size.

**Comment by slouken** [comment]
This seems reasonable:
[hide impossible branch in D3D_UnlockTexture](https://github.com/libsdl-org/SDL/pull/5313/commits/9cc3cda9769423b58da68535bd6a66fea2057e8c) [9cc3cda](https://github.com/libsdl-org/SDL/pull/5313/commits/9cc3cda9769423b58da68535bd6a66fea2057e8c)

**Comment by 1bsyl** [comment]
[hide impossible branch in D3D_UnlockTexture](https://github.com/libsdl-org/SDL/pull/5313/commits/9cc3cda9769423b58da68535bd6a66fea2057e8c) [9cc3cda](https://github.com/libsdl-org/SDL/pull/5313/commits/9cc3cda9769423b58da68535bd6a66fea2057e8c) 
is merged,
so this close the PR

**Pull request closed without merging**
