### PR TITLE
Add SDL notifications

### PR DESCRIPTION
**Pull request by 1bsyl**
Refactor the patch for notification  ( initially from https://github.com/libsdl-org/SDL/issues/1932 )

currently only linux/DBUS

### CODE REVIEW

**Comment by orowith2os** [comment]
As @smcv suggested in the original issue:

> For the Linux implementation, it would be best if this was container-friendly by trying both [org.freedesktop.portal.Notification](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-org.freedesktop.portal.Notification) and [org.freedesktop.Notifications](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html), in some order (try one, and if it fails with a D-Bus error, try the other).

**Comment by 1bsyl** [comment]
closing this PR, and re-open new one https://github.com/libsdl-org/SDL/pull/7857

**Comment by 1bsyl** [comment]
@madebr @sezero : hey! I don't know how to squash + force push the commit when I'have a "merge branch" in the middle ? 
(it re-ask me to re-do the merge n times, so it's faster to close the branch, and re-create a new one) 
Any idea ?

**Comment by madebr** [comment]
You could have tried a squash merge. (`git merge --sqash`)

**Comment by 1bsyl** [comment]
@madebr 
I tried with updating the video capture PR ( 5477). Only the gendyapi files were divergent...

git checkout br_video_capture
git merge main --squash
... merge the gendynapi files ...
git commit 
git push

// 1 new commit on github! (so 2, in total).

git rebase origin -i 
I want to squash the merge with initial commit.. (changed, the second pick -> s)
but I am asked to re-do! the merge once-again . :/

**Comment by madebr** [comment]
You need to start from the `main` branch:
```
git fetch origin
git checkout origin/main
git merge br_notifications --squash
```
Fix the conflicts, and create the squash commit.
```
git add -u
git commit -m "Add SDL notifications"
git checkout -B br_notification
```

**Comment by 1bsyl** [comment]
@madebr 
but the commit will be done in the main branch ?

**Comment by madebr** [comment]
By doing `git checkout origin/main`, you are in detached state.
You're in no man lands.
In the last step, you're forcing the current branch to `br_notifications`.

**Comment by 1bsyl** [comment]
ok :) thanks ! will try later !

**Comment by 1bsyl** [comment]
@madebr thanks that works :)

(for my record, as a very last step, I need to do
`git push origin br_notifications -f` )

**Pull request closed without merging**
