### PR TITLE
Stop 100ms hang in linux SDL_UDEV_Poll on new device.

### PR DESCRIPTION
**Pull request by TomHillT**
Whenever a new device was detected, SDL_UDEV_Poll will wait for 100ms for the device to finish initializing. This call is likely made on the application's main thread, so during this time the application is stalled.
Instead if this scenario is detected, make note of the new device, but only process the add event in a future SDL_UDEV_Poll once 100ms has passed. This frees up the application to do other work in the meantime.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
I think this would still end up delaying device connections significantly, though it at least fixes the hitch described in #4257. Before going with something like this I'd _really_ like to know why that delay is there in the first place. Ideally this was just some temporary goof that's since been fixed, meaning this can be removed entirely.

**Comment by TomHillT** [comment]
I agree, would be great to know if the delay is actually needed / why it was there to begin with. I couldn't find any reasons why, but admit my search skills might not be up to the task. I did try without the delay on my setup and found no issue, but decided to take caution against a full removal as I lack the ability to do full compatibility testing across many different setups & devices to have full confidence.

What I can say is that this fix at least keeps behavior as much as possible the same as today, but without the forced stall blocking our UI updates. In our worst cases, multiple devices would be added in the same frame; each generating multiple events, adding up to terrible performance. My reasoning here was that in my opinion, it's 'ok' for a device to take some time to show up, but it is not ok for it to get in the way of multiple game frames being rendered.

**Comment by flibitijibibo** [comment]
Yeah, as far as preserving behavior goes this should be okay - I think the only perceptible difference is that the initial frame won't have controllers like it would have before, but that shouldn't be a major problem. Assuming we really need this delay this patch lgtm.

@slouken, what was the story behind that commit? Is there a specific device we can reproduce the original issue with?

**Comment by flibitijibibo** [comment]
Looks like Sam removed the delay:

https://github.com/libsdl-org/SDL/commit/40e5ce7fe518c0e5a98735d1165a306642ac0e62

So I guess it was just for Steam Link!

**Comment by slouken** [comment]
Yep, thanks for bringing this up!

**Pull request closed without merging**
