### PR TITLE
Removed reference to ant project.

### PR DESCRIPTION
**Pull request by gbgames**
The android-project-ant directory does not exist anymore.

### CODE REVIEW

**Comment by Croydon** [comment]
@gbgames @slouken Maybe I'm missing context, but the android-project-ant directory does still exist...?

https://github.com/libsdl-org/SDL/tree/main/android-project-ant

**Comment by gbgames** [comment]
@Croydon Huh. Weird. It exists in source, strangely, but it was not in SDL 2.0.14's release. I just double-checked, and it is missing in the official release tarball.

And I could have sworn I found an old commit in which someone removed that directory, but I'm not finding it now.

**Comment by slouken** [comment]
Thanks for catching that, I've reverted the commit: https://github.com/libsdl-org/SDL/commit/599001d4c7559b4ed04b3d5590e5536ed87c165e

Maybe we need a comment that it's on GitHub instead?

**Comment by gbgames** [comment]
I'm still thrown off. I remember when I was trying to upgrade from 2.0.12 to 2.0.14 that the directory was missing, and I checked the source, and I thought I saw that there was a commit that removed that directory. Could something have changed in the last month that collapsed a bunch of changesets and potentially lost a few of them?

What I'm wondering now is if that directory should have been in the 2.0.14 release as well as wondering if it will show up in the next official release.

**Comment by slouken** [comment]
No, it's not supported, so it won't show up in official releases.

**Pull request merged**
