### PR TITLE
Add GLES2 shader prologue infrastructure.

### LINKED ISSUE #6166: Blank screen on older Android devices since 5858c7dfce80b0854b04475dde97996692ce9200 (Actually, OpenGLES2 is broken on Windows as well)
Used to work before this commit. Example of older Android versions are 5.1.1 Nexus Tablet and 4.2.2 Chinese TV Stick.

Just now tested on Windows and when I use the OpenGLES2 renderer it doesn't draw anything on that platform either.

### PR DESCRIPTION
**Pull request by eloj**
## Background

There is supposedly an OpenGL ES2 target that does not support precision specifiers. However, the existing logic to detect this is currently broken in two ways:

1) There's a typo of the `#ifdef` as `#if`.
2) Checking for `GL_FRAGMENT_PRECISION_HIGH` can not be the correct way to detect this platform. Other targets, including some desktops, will also not have this defined (for various reasons).

Because some of the shader code is missing precision specifiers, and because a default is ONLY provided if `GL_FRAGMENT_PRECISION_HIGH` is set, these other targets break.

## Approach

Instead of 'hard-coding' the prologue string into shaders in the C source, use our ability to provide a list of strings to `glShaderSource` instead, leaving the determination to run-time.

See discussion below for more information.

## Existing Issue(s)

Would fix #6166, Relates to #6174

### CODE REVIEW

**Comment by 1bsyl** [comment]
It sounds a good idea.
Maybe, we should revert the shaders to to the initial behavior (eg no highp + precision definition) as we had before for a while.
and add a SDL HINT so it's possible to select a highp prologue/shaders (#5884) when required.

If there is an issue with shader compilation (because of highp or for systems that don't understand precision keywords ), 
we could add a fallback to compile a shader with a different prologue without precision keywords https://github.com/libsdl-org/SDL/commit/5858c7dfce80b0854b04475dde97996692ce9200).

**Comment by eloj** [comment]
I've gone ahead and made it a hint to use the 'precision specifier stripping' prologue.

I've also rolled the default texcoord precision into the prologue as a define, to reduce code duplication in the shaders.

I added the missing _explicit_ precision specifiers to the shader code (to the best of my ability), and verified that it works on my machine without the `precision mediump float` default. I did however keep the default specifier in for reasons already explained above.

**Comment by slime73** [comment]
At this point I don't think a hint is a good idea - for all we know (aside from the issues with 5858c7), the reason for that commit in the first place could have been due to a bug in SDL's code. A hint would just obscure the bug instead of fixing it if that's the case.

I think we'd need @slouken to give more details on specifics for why/when 5858c7 was needed, before adding public APIs for it is on the table.

> I added the missing explicit precision specifiers to the shader code

Explicit `mediump` specifies for individual float/vector variables aren't needed when `precision mediump float;` is in the shader code.

**Comment by slouken** [comment]
Can we have a value for the hint that sets it to undefined?

**Comment by slime73** [comment]
> Checking for `GL_FRAGMENT_PRECISION_HIGH` can not be the correct way to detect this platform. Other targets, including some desktops, will also not have this defined (for various reasons).

Can you elaborate on this? It works fine in other apps and is the way that's recommended by the GLES2 specifications. As a user, I'd like to know where this doesn't work otherwise the hint is just too confusing to me.

Are there specific GLES2 drivers that are not compliant with the GLES2 spec? If so, which ones are they? What would user code that uses the hint look like?

**Comment by slime73** [comment]
>  In what 'apps' is it okay to assume that precision specifiers can be omitted if GL_FRAGMENT_PRECISION_HIGH is undefined?

That's not what I was talking about, sorry for the confusion, Prior to commit 5858c7 the precision specifiers existed in all codepaths (*unless* there was a bug in SDL's code).

I'm saying it would be a spec violation if `GL_FRAGMENT_PRECISION_HIGH` doesn't do what the spec says it does on a given driver, so it would be good to know which driver if that's the case.

> I'm perfectly fine with removing the whole "no precision specifiers" thing, but in order to make any sort of progress I'm working on the assumption that there's a mystery reason that the original change to start undefining precision specifiers was made to begin with.

Right, no one has explained the mystery reason so far, so it remains a mystery as to what the best approach to fix it would be, IMO. I suspect if there was a good reason, it was to address an upstream driver bug - in which case the driver bug should be reported and a workaround can exist entirely within SDL_Render's backend code without exposing an external API (a new hint).

**Comment by eloj** [comment]
Whether the "mystery workaround" is enabled via a hint or by checking GL_RENDERER/GL_VERSION for a specific driver/platform seems a mere detail. The whole purpose of this was to provide the infrastructure required to enable any such run-time check.

If it turns out it's not wanted, then c'est la vie.

> @slouken:  Can we have a value for the hint that sets it to undefined?

Sorry, I'm not sure I understand what you're asking for.

**Comment by slouken** [comment]
> Do you having `SDL_RENDER_OPENGL_FORCE_TEXCOORD_PRECISION={0,1,2}` with '0' for undefined/default/best?

Yes, sorry, I meant collapsing the 3 hints into a single hint that specifies the precision. We should support "high", "medium" and "undefined" to match the actual value used.

It also looks like the original code always specified precision mediump float, so we should always do that if it wasn't causing other issues, and then specify the texture coordinate precision seperately, according to the hint, defaulting to "best"

**Comment by eloj** [comment]
I guess I can do that.

I will try to have this change in later tonight.

**Comment by eloj** [comment]
Changes force pushed:

1. Unconditionally set `precision mediump float` in fragment shaders. Previously wasn't set in undef case.
2. Collapse hints into `SDL_RENDER_OPENGLES2_TEXCOORD_PRECISION`, which can be 'best' (implied/default), 'high', 'medium' or 'undefined'.
3. Because of (1), setting the hint to 'undefined' no longer results in an error due to missing precision specifiers.

**Comment by slouken** [comment]
Great. @AntTheAlchemist, can you confirm this fixes your issue on old Android devices and Windows?

**Comment by 1bsyl** [comment]
Shouldn't the default value for the hint be "medium" as before ?

Don't we need a fallback if the shader doesn't compile at run-time on some platform ? 

I mean the hint can be used to select a preferred precision for 99% device. but if the app runs on a device that doesn't handle the precision, we may want that the renderer back-end try a second compilation with a different shader (well, same shader, but different prologue).

**Comment by slime73** [comment]
> Shouldn't the default value for the hint be "medium" as before ?

Matching the behaviour as of https://github.com/libsdl-org/SDL/commit/65647b341777e469efc9a3e05755eb89daed4ecc would make the default "best" instead of "medium". Changing it to default to medium would effectively reopen #5884 IMO - needing to manually set it to a non-default value to get things to render properly on the majority of mobile devices seems like a bad default, and unintuitive for users (especially because mediump texture coordinates may appear fine on one device and appear totally broken on another, depending on what texture is being used etc.)

> if the app runs on a device that doesn't handle the precision

The existing `#ifdef GL_FRAGMENT_PRECISION_HIGH` used for `SDL_TEXCOORD_PRECISION` should handle that situation already, when the "best" hint is used.

(In fact IMO the "high" hint is kind of redundant, and arguably so is the "medium" hint although not as obviously as the "high" hint).

**Comment by eloj** [comment]
> Shouldn't the default value for the hint be "medium" as before ?

Before when? AFAICT the default for `v_texCoord` has not changed. 1d19524522c092e54335405c18f8cb3c6e33441e made it the 'best' of `highp` or else `mediump`.

> Don't we need a fallback if the shader doesn't compile at run-time on some platform ?

That to me is #6174 territory.

> but if the app runs on a device that doesn't handle the precision, we may want that the renderer back-end try a second ...

If there is such a device, it would be good to get a report with specifics. Until then, we're just going in circles. I'm getting dizzy.

Broad context; the opengles2 renderer is broken on every platform _right now_.

**Comment by eloj** [comment]
> In fact IMO the "high" hint is kind of redundant because it will cause shader compile errors instead of gracefully falling back

I can tell you that this is not the case on my platform. `GL_FRAGMENT_PRECISION_HIGH` is undefined in the SDL ES2 contex, but the compiler happily accepts `highp` precision anyway.

There's probably some underlying issue that could be rooted out from that, but I'm not motivated enough to dig for it.

Being able to 'force' the texcoord precision could conceivably be useful for debugging, as it was at the core of #5884

**Comment by slime73** [comment]
> I can tell you that this is not the case on my platform.

Which platform is that? If it's desktop, those drivers tend to ignore precision qualifiers regardless, because the underlying hardware can't really use them effectively. So I wouldn't be too surprised if a desktop driver accepts `highp` in *more* situations than it should. It'd only be an issue if it actually affects shader output in that situation (or in situations where drivers accept `highp` in less situations than they should).

**Comment by AntTheAlchemist** [comment]
No, this still doesn't work - no change. My old Nexus 7 is still not drawing anything and no errors reported, only SDL_RenderClear seems to work. Also OpenGLES2 renderer on Windows 10 with a GeForce GTX 1650 (it's not an old card) is the same, nothing drawn, no errors.

**Comment by AntTheAlchemist** [comment]
I just posted that I didn't see any change, and deleted my post because I realised the latest source I'm downloading from the "<> Code" tab isn't including this new hint. Are the proposed changes hiding in a pull request? How do I grab the code I need to test? I don't have a clue how Github works or what a pull request is, sorry. 1:30am here in the UK and need to call it a day.

**Comment by eloj** [comment]
@AntTheAlchemist Something like this. Assuming you're standing in a git clone of SDL:main 

```bash
$ git remote add eddy git@github.com:eloj/SDL.git
$ git fetch eddy
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 29 (delta 18), reused 21 (delta 15), pack-reused 0
Unpacking objects: 100% (29/29), 25.30 KiB | 539.00 KiB/s, done.
From github.com:eloj/SDL
 * [new branch]          gles2-shaders-fix -> eddy/gles2-shaders-fix
 * [new branch]          main              -> eddy/main

$ git merge eddy/gles2-shaders-fix

Merge made by the 'ort' strategy.
 WhatsNew.txt                             |   2 +-
 src/render/opengles2/SDL_render_gles2.c  |  21 ++++++++++---
 src/render/opengles2/SDL_shaders_gles2.c | 136 ++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------
 src/render/opengles2/SDL_shaders_gles2.h |  12 ++++++++
 4 files changed, 110 insertions(+), 61 deletions(-)
```

You should now be able to build. As alternative you can clone my whole repo, but that'll take longer.

**Comment by AntTheAlchemist** [comment]
> @AntTheAlchemist Something like this. Assuming you're standing in a git clone of SDL:main

I'm sorry, I have no idea what any of that is, I'm guessing they're Linux commands or something? I'm building the Windows DLL from the VisualC directory using Visual Studio 2022, and running Android version from my Android Studio project.

**Comment by AntTheAlchemist** [comment]
I download the source code as a .zip file.

**Comment by AntTheAlchemist** [comment]
'$' is not recognized as an internal or external command, operable program or batch file.

**Comment by eloj** [comment]
Those represent the linux command line, not applicable if you use Windows (normally).

If you downloaded the [source as a zip](https://github.com/eloj/SDL/archive/refs/heads/gles2-shaders-fix.zip) I guess you'd build it however you'd normally build SDL. Unpacking it and opening the project file, or however that works.

**Comment by AntTheAlchemist** [comment]
@eloj I don't have any GIT software installed, I'm just using the website. The link to the source is what I needed, thanks. Will try it now.

Not sure if it's worth considering that the texture limit on old OpenGLES2 drivers is ridiculously low, like 2048 bytes. Maybe there is a link between texture limit and the existence of precision specifiers?

**Comment by AntTheAlchemist** [comment]
It all seems to work now, on all my devices. I even played around with "SDL_RENDER_OPENGLES2_TEXCOORD_PRECISION" and all platforms now work with "medium", "high", and "undefined", is that right?

**Comment by eloj** [comment]
Good. Yes, that's pretty much the expected outcome, if everything supports 'high'.

(If a device doesn't support 'high' then I'd expect it to behave as before; i.e the shader compiler fails (silently, because the error doesn't propagate to the client) and nothing renders)

**Comment by slouken** [comment]
@AntTheAlchemist, thanks for confirming!

@slime73, @1bsyl, I think this patch has the behavior that we want, where by default it will use the shader preprocessor to pick either high or medium depending on what is supported by the driver, and we have the ability to force it in case that doesn't work.

I'm waiting for some internal confirmation on the Valve side and then I'll merge this.

**Comment by slime73** [comment]
I think the default is good - I'm still of the opinion that a user-facing hint isn't truly needed, but that's just my onion and I'm not gonna object to it being merged just because of that. :)

Since it does have a hint and the hint is in the changelog, should it also have a `#define` and header documentation in SDL_hints.h?

**Comment by slouken** [comment]
I'll probably remove the hint from the changelog and we can decide between now and release whether it needs to be officially documented.

**Comment by eloj** [comment]
I still don't understand the 'undefined' case. Mystery platform that supports setting a default precision, but not explicit ones.

(The original PR didn't inject the default precision if 'undefined' was hinted, because leaving out ALL of them at least seemed... consistent in the spec breaking)

**Comment by 1bsyl** [comment]
thanks for the answers 

I meant the default I wanted was mediump as before evocating highp, but I agree that maybe "best" is the best idea as a default.
Just to remind that requiring "highp" is almost a corner case (using big large texture as atlas, with very small addressing inside) and my experience on android, is that there are device that don't even allow create such big texture.
If we choose best, it would be nice to make sure that "highp" vs "mediump" shouldn't result in a drop of performance neither.
(personally I wont select highp to avoid the 0.01 device where this will an issue !)


About the fallback for undefined precision : 
there is an "undef" hint ok. but it doesn't  seems clearly be a fallback when using "best".
And since, this is somehow a bugfix (to be confirmed), it should be available for all modes. (of course, with "undef" hint, this would be redundant but it doesn't hurt neither).

also could GL_FRAGMENT_PRECISION_HIGH be defined to 0 ?
```
    #ifdef GL_FRAGMENT_PRECISION_HIGH
        #if GL_FRAGMENT_PRECISION_HIGH
             use highp
        #else
             use mediump
         #end
    #else
           use mediump or undef ?
    #end 
```

if we assume it's always defined to 1
```
    #ifdef GL_FRAGMENT_PRECISION_HIGH
             use highp
    #else
           use mediump or undef ?
    #end 
```

My use-case: 
building a app that work fine with "mediump" shader on 99.99 device. if you drop the same .apk on a device that doesn't handle precision, the SDL_renderer should automatically switch to use the undef prologue.

(this would be a second compilation instruction because  the first compilation would fail)

**Comment by slime73** [comment]
> Just to remind that requiring "highp" is almost a corner case (using big large texture as atlas, with very small addressing inside)

It's actually much less of a corner case than people might assume - for example, many phones have pretty high resolution screens, and using a full-screen render target is common. When that render target is drawn, `mediump` texture coordinates won't have enough precision to represent all pixels in it (depending on the screen resolution).

> If we choose best, it would be nice to make sure that "highp" vs "mediump" shouldn't result in a drop of performance neither.

I don't think it'll have a real impact on performance: it doesn't change any of the shader code's math to use highp values, it just changes a single vec2 variable that's passed through to the texture sampling function. It couldn't hurt to double-check performance though, of course.

> also could GL_FRAGMENT_PRECISION_HIGH be defined to 0 ?

Not without violating the GLES2 specification (see my quote from the spec in a post above).

**Comment by 1bsyl** [comment]
@slim73 thanks for the answers !

**Comment by slouken** [comment]
I went ahead and merged a tweaked version of this commit, thanks!

I removed the hint from the documentation, because I'm not sure it's necessary. The original problem here was that the shaders didn't have a #version statement, so some shader compilers assumed desktop GLSL even though it was running in a GLES context.

Let's go ahead and try this on a variety of systems and if we don't need the hint, we can remove that logic to simplify this a bit.

**Pull request closed without merging**
