### PR TITLE
emscripten: Remove use of EM_ASM from SDL_timer code.

### PR DESCRIPTION
**Pull request by sbc100**
Instead use the native emscripten timer API.

See https://github.com/emscripten-core/emscripten/issues/17941

### CODE REVIEW

**Comment by sbc100** [comment]
@Daft-Freak

**Comment by icculus** [comment]
```
/home/runner/work/SDL/SDL/src/timer/SDL_timer.c:378:10: fatal error: 'emscripten/eventloop.h' file not found
```

The builder is using Emscripten 2.0.27. I don't mind requiring a newer Emscripten, if this is in a stable emsdk release.

**Comment by sbc100** [comment]
> ```
> /home/runner/work/SDL/SDL/src/timer/SDL_timer.c:378:10: fatal error: 'emscripten/eventloop.h' file not found
> ```
> 
> The builder is using Emscripten 2.0.27. I don't mind requiring a newer Emscripten, if this is in a stable emsdk release.

Looks like that header was added in 2.0.31.   Yes, we generally consider all emscripten releases to be equally stable so it should be not probably to update from one release to a more recent one.

**Comment by Daft-Freak** [comment]
Ah, can't complain about removing an `EM_ASM`.

https://github.com/libsdl-org/SDL/blob/main/.github/workflows/emscripten.yml#L12 to bump the version BTW.

**Comment by sbc100** [comment]
> 2.0.31 was obviously a miss; I'm wondering if the build action should just have this install "latest" instead of a specific version and never think about it again?

I think pinning to a specific version probably makes some sense.  Otherwise CI could start breaking for external reasons.   How do you handle this for other targets/platforms?

**Comment by sbc100** [comment]
Looks like it was actually 2.0.32 that added that header.  I will upload a change to bump to latest though I think

**Comment by sezero** [comment]
You guys need to update emscripten readmes for the requirement, I guess?

**Comment by icculus** [comment]
> You guys need to update emscripten readmes for the requirement, I guess?

Done.

**Comment by Daft-Freak** [comment]
TBH I'm not sure the readme is very up-to-date in general... It could also do with some more details, at least a mention of `-sUSE_SDL=2`. (Looks like it's still the stuff I threw together when starting the port). 

Okay, getting off-topic :)

**Comment by slouken** [comment]
Feel free to update the README, it probably hasn't been updated much since you threw it together. :)

**Pull request merged**
