### PR TITLE
Use `SDL_PixelFormatEnum` as type in public headers

### PR DESCRIPTION
**Pull request by Susko3**
## Description

- updates public API structs and functions to use `SDL_PixelFormatEnum` instead of generic `Uint32`
  - this requires updates to `SDL_DYNAPI_PROC` definitions as the two types are not compatible
- changes format specifiers involving `SDL_PixelFormatEnum` to `%d`

Changes in this PR have been picked from https://github.com/libsdl-org/SDL/pull/9191.

## Existing Issue(s)

- https://github.com/libsdl-org/SDL/issues/9186

### CODE REVIEW

**Comment by slouken** [comment]
This change should probably be pushed through the internal functions in src/video/*

**Comment by Susko3** [comment]
> src/video/*

I don't like the look of that * 

I'm mostly interested in public headers for now. I've already spent more time than I would have like on this PR series. So I'll not be updating that, sorry.

**Comment by icculus** [comment]
This looks good to me.

We probably need an assert in sdl2-compat to make sure these still fit in 32 bits, but that's outside this PR.

**Comment by icculus** [comment]
And yes, we're going to need to fix up a _lot_ of internal code. I don't suppose a compiler warning will catch all those places?

**Comment by Susko3** [comment]
https://github.com/libsdl-org/SDL/blob/1e8b006d43166a77d8311d89938e2082b9febe22/include/SDL3/SDL_stdinc.h#L365-L380

**Comment by slouken** [comment]
> Should you perhaps update `SDL_QueryTexture` too?

Yes!

**Pull request merged**
