### PR TITLE
Improve sdl2-config.cmake.in and SDL2Config.cmake

### PR DESCRIPTION
**Pull request by DanielGibson**
~~**Still work in progress and not completely tested** - Feedback welcome though! :)~~
Should now work, but I have only tested Windows and Linux.
Especially Mac is not tested at all (because I don't have a Mac).

* Make both sdl2-config.cmake (generated when SDL2 is built with autotools) and SDL2Config.cmake (generated if SDL2 is built with CMake) export both `${SDL2_LIBRARIES}`, `${SDL2_INCLUDE_DIRS}` etc *and* `SDL2::SDL2`, `SDL2::SDL2main` etc (#4004)
* Make `SDL2::SDL2` as exported by SDL2Config.cmake work with MinGW (#3665)

### CODE REVIEW

**Comment by DanielGibson** [comment]
Just for reference, I *did* toy around with `CMAKE_GNUtoMS` which is supposed to generate valid .lib files when building with MinGW on Windows (and presumably only if you have VS installed, it seems to use lib.exe from the VS developer console).
It *did* generate a `libSDL2.lib` which might even be usable, but it doesn't do anything about libSDL2main.a.
Apparently MSVC can even link .a archives (I think in the end .lib and .a are both **ar** archives), but it complains about SAFESEH (`libSDL2main.a(SDL_windows_main.c.obj) : error LNK2026: module unsafe for SAFESEH image`).

I hope to get this PR in a mergeable state soonish, but it's not easy to motivate myself to fight this unholy trinity of crap that CMake, MinGW and Windows is. However, I do *not* think I'll get SDL2Config.cmake/SDL2Target*.cmake generated by CMake+MinGW in a state that actually works (however, if it and the binaries are generated by CMake+MSVC it *does* work, the SDL-using app can then be built with both MSVC and MinGW).
As described in https://github.com/libsdl-org/SDL/issues/4004#issuecomment-826192852 and following, for that to work at all I'd have to change the link order (get `-lmingw32` before SDL2main) and I have no idea how to do that, except for in SDL2Config.cmake to throw away the SDL2::SDL2main target (as defined by SDL2Target.cmake) and redefine it in a way that hardcodes the correct libs in the correct order (and only uses the paths of the original targets). That feels very dirty and I really hope that there is a better, cleaner way (**maybe someone with better CMake knowledge can fix that?**). And `-lmingw32` must only be prepended if both SDL2(main) and your app are built with MinGW - I don't think there currently is a way to tell which compiler generated SDL2Target.cmake..

**Comment by DanielGibson** [comment]
I think this is ready for review now.
A simple testcase can be found at https://gist.github.com/DanielGibson/ca02b1692499ce4911f7884dc0a67bbf

Now both SDL2Config.cmake and sdl2-config.cmake export `SDL2_LIBRARIES` etc and `SDL2::SDL2` etc.
I tested on Windows (with MinGW and VS2017) and Linux.
**What still doesn't work** is building an application with MinGW if SDL2 has been built with MinGW+CMake (=> `SDL2Config.cmake` is used), because (*as far as I know*) CMake doesn't seem to have a way to tell a library target that its users should first link against another lib (`libmingw32` in our case) before linking against the lib (`SDL2main` in our case) itself.
The only "fixes", or rather workarounds, I can imagine are pretty ugly so I'll save that for another PR and hope someone more familar with CMake comes up with something better.
All other cases I tested do work (though other platforms like macOS should be tested by people using them!).

I also fixed #4310 (building SDL2 from git with CMake on Linux produced `libSDL2-2.0.so.1` instead of `libSDL2-2.0.so.0`).

**Comment by Ghabry** [comment]
Oh this is great!

For macOS you only need lots of frameworks, otherwise you get tons of linker errors.

I'm maintaining my own CMake SDL2 file for a different project. The framework list is in there in case you want to copy it over.
https://github.com/EasyRPG/Player/blob/master/builds/cmake/Modules/FindSDL2.cmake#L244-L259

Can also test for you if it works on macOS :)

**Comment by DanielGibson** [comment]
Do all those libs have to be linked only when linking SDL statically or also when linking SDL dynamically?

**Comment by Ghabry** [comment]
good point, forgot about dynamic linking. They are only needed when linking static.

**Pull request merged**
