### PR TITLE
vita: test vita piglet/pvr gles support on ci + fixes

### PR DESCRIPTION
**Pull request by madebr**
#7120 showed that not all vita code is built on ci
This pr enables gles(2) supports on ci and uncovers some issues.

The build currently fails due to missing symbols.

@raphasamp 
What libraries are missing?

### CODE REVIEW

**Comment by raphasamp** [comment]
Maybe the PIB should be removed from SDL 3, since it was [discontinued by its developer](https://github.com/SonicMastr/Pigs-In-A-Blanket). It was a sub-optimal method to achiev OpenGL ES it seems. I personally never used it, so I've no grounds to state what its lacking to compile.

On the PVR side, it's not configuring completely:
`--   VIDEO_VITA_PVR              (Wanted: ON): OFF`

For building it, [PVR_PSP2](https://github.com/GrapheneCt/PVR_PSP2) would need to be fetched and a way of finding its include folder added to the CMake file, or copied to the vitasdk folder or added to C_INCLUDE_PATH/CPLUS_INCLUDE_PATH. Then the latest version of the libraries compatible with the VitaSDK would need to be fetched from vitasdk_stubs.zip from [here](https://github.com/GrapheneCt/PVR_PSP2/releases/tag/v3.8), and added to the link directories in some way (CMake, Copied to vitasdk or pointed by LD_LIBRARY_PATH). Then it will be able to configure properly for using it and the build will currently fail on src/video/SDL_video.c because something since the change to SDL3 started broke its compilation under VITA, making APIENTRY be undefined when compiling it (the SDL2 branch currently compile just fine).

Oh, and to test the GL4ES functionality that also exists on the VIDEO_VITA_PVR toggle, fetching [gl4es4vita](https://github.com/SonicMastr/gl4es4vita) would be needed too, since its compilation is dependant on these headers being present if I'm not mistaken (Never used this specific feature, but it should be straightfoward as the main PVR to implement in CI).

**Comment by madebr** [comment]
I can reproduce your `APIENTRY` error when using PVR-PSP2.
By removing `APIENTRY` from these typedefs, I can build SDL3 for the Vita:
https://github.com/libsdl-org/SDL/blob/34bb0735d830e99b3f7bff68a3277986ebce7df1/src/video/SDL_video.c#L3355-L3359

**Comment by madebr** [comment]
I "fixed" it on ci by manually adding the following to `EGL/egl.h`
```c
#ifndef IMG_CALLCONV
#define IMG_CALLCONV
#endif
```

I have opened a ticket in the upstream egl library: https://github.com/GrapheneCt/PVR_PSP2/issues/19

**Comment by madebr** [comment]
gl4es4vita is causing issues as well. It looks like the vita opengl headers clash with the SDL Khronos headers:
```
ninja: job failed: /home/user/vitasdk/bin/arm-vita-eabi-gcc -DSDL_BUILD_MAJOR_VERSION=3 -DSDL_BUILD_MICRO_VERSION=0 -DSDL_BUILD_MINOR_VERSION=0 -DSDL_STATIC_LIB -DUSING_GENERATED_CONFIG_H -D__VITA__ -D__psp2__ -I/build/include-config-release -I/src/src -I/build/include -I/src/include -I/src/include/SDL3 -Wl,-q -O3 -DNDEBUG -idirafter /src/src/video/khronos -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wshadow -fdiagnostics-color=always -Winvalid-pch -include /build/CMakeFiles/SDL3-static.dir/cmake_pch.h -MD -MT CMakeFiles/SDL3-static.dir/src/video/SDL_video.c.obj -MF CMakeFiles/SDL3-static.dir/src/video/SDL_video.c.obj.d -o CMakeFiles/SDL3-static.dir/src/video/SDL_video.c.obj -c /src/src/video/SDL_video.c
In file included from /src/include/SDL3/SDL_opengl.h:2098,
                 from /src/src/video/SDL_video.c:37:
/src/include/SDL3/SDL_opengl_glext.h:343:5: error: redeclaration of enumerator 'KHRONOS_FALSE'
  343 |     KHRONOS_FALSE = 0,
      |     ^~~~~~~~~~~~~
In file included from /home/user/vitasdk/arm-vita-eabi/include/EGL/eglplatform.h:29,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl1_4.h:25,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl.h:33,
                 from /src/include/SDL3/SDL_egl.h:33,
                 from /src/src/video/SDL_egl_c.h:28,
                 from /src/src/video/SDL_video.c:26:
/home/user/vitasdk/arm-vita-eabi/include/KHR/khrplatform.h:254:5: note: previous definition of 'KHRONOS_FALSE' was here
  254 |     KHRONOS_FALSE = 0,
      |     ^~~~~~~~~~~~~
In file included from /src/include/SDL3/SDL_opengl.h:2098,
                 from /src/src/video/SDL_video.c:37:
/src/include/SDL3/SDL_opengl_glext.h:344:5: error: redeclaration of enumerator 'KHRONOS_TRUE'
  344 |     KHRONOS_TRUE  = 1,
      |     ^~~~~~~~~~~~
In file included from /home/user/vitasdk/arm-vita-eabi/include/EGL/eglplatform.h:29,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl1_4.h:25,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl.h:33,
                 from /src/include/SDL3/SDL_egl.h:33,
                 from /src/src/video/SDL_egl_c.h:28,
                 from /src/src/video/SDL_video.c:26:
/home/user/vitasdk/arm-vita-eabi/include/KHR/khrplatform.h:255:5: note: previous definition of 'KHRONOS_TRUE' was here
  255 |     KHRONOS_TRUE  = 1,
      |     ^~~~~~~~~~~~
In file included from /src/include/SDL3/SDL_opengl.h:2098,
                 from /src/src/video/SDL_video.c:37:
/src/include/SDL3/SDL_opengl_glext.h:345:5: error: redeclaration of enumerator 'KHRONOS_BOOLEAN_ENUM_FORCE_SIZE'
  345 |     KHRONOS_BOOLEAN_ENUM_FORCE_SIZE = KHRONOS_MAX_ENUM
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user/vitasdk/arm-vita-eabi/include/EGL/eglplatform.h:29,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl1_4.h:25,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl.h:33,
                 from /src/include/SDL3/SDL_egl.h:33,
                 from /src/src/video/SDL_egl_c.h:28,
                 from /src/src/video/SDL_video.c:26:
/home/user/vitasdk/arm-vita-eabi/include/KHR/khrplatform.h:256:5: note: previous definition of 'KHRONOS_BOOLEAN_ENUM_FORCE_SIZE' was here
  256 |     KHRONOS_BOOLEAN_ENUM_FORCE_SIZE = KHRONOS_MAX_ENUM
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /src/include/SDL3/SDL_opengl.h:2098,
                 from /src/src/video/SDL_video.c:37:
/src/include/SDL3/SDL_opengl_glext.h:346:3: error: conflicting types for 'khronos_boolean_enum_t'
  346 | } khronos_boolean_enum_t;
      |   ^~~~~~~~~~~~~~~~~~~~~~
In file included from /home/user/vitasdk/arm-vita-eabi/include/EGL/eglplatform.h:29,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl1_4.h:25,
                 from /home/user/vitasdk/arm-vita-eabi/include/EGL/egl.h:33,
                 from /src/include/SDL3/SDL_egl.h:33,
                 from /src/src/video/SDL_egl_c.h:28,
                 from /src/src/video/SDL_video.c:26:
/home/user/vitasdk/arm-vita-eabi/include/KHR/khrplatform.h:257:3: note: previous declaration of 'khronos_boolean_enum_t' was here
  257 | } khronos_boolean_enum_t;
      |   ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by madebr** [comment]
@raphasamp, I almost forgot to thank you for the explanation :)

**Comment by madebr** [comment]
Applying the following patch does not work, because the headers are apparently not equivalent:
```patdch
--- a/include/SDL3/SDL_opengl_glext.h
+++ b/include/SDL3/SDL_opengl_glext.h
@@ -35,8 +35,9 @@ extern "C" {
 #define GL_GLEXT_VERSION 20220530
 
 /*#include <KHR/khrplatform.h>*/
-#ifndef __khrplatform_h_
+#if !defined(__khrplatform_h_) && !defined(__drvkhrplatform_h_)
 #define __khrplatform_h_
+#define __drvkhrplatform_h_
 
 /*
 ** Copyright (c) 2008-2018 The Khronos Group Inc.
```

```
ninja: job failed: /home/user/vitasdk/bin/arm-vita-eabi-gcc -DSDL_BUILD_MAJOR_VERSION=3 -DSDL_BUILD_MICRO_VERSION=0 -DSDL_BUILD_MINOR_VERSION=0 -DSDL_STATIC_LIB -DUSING_GENERATED_CONFIG_H -D__VITA__ -D__psp2__ -I/build/include-config-release -I/src/src -I/build/include -I/src/include -I/src/include/SDL3 -Wl,-q -O3 -DNDEBUG -idirafter /src/src/video/khronos -Wall -fno-strict-aliasing -Wdeclaration-after-statement -Wshadow -fdiagnostics-color=always -Winvalid-pch -include /build/CMakeFiles/SDL3-static.dir/cmake_pch.h -MD -MT CMakeFiles/SDL3-static.dir/src/video/SDL_egl.c.obj -MF CMakeFiles/SDL3-static.dir/src/video/SDL_egl.c.obj.d -o CMakeFiles/SDL3-static.dir/src/video/SDL_egl.c.obj -c /src/src/video/SDL_egl.c
/src/src/video/SDL_egl.c:119:48: error: unknown type name 'GLenum'; did you mean 'EGLenum'?
  119 | typedef void (APIENTRY* PFNGLGETINTEGERVPROC) (GLenum pname, GLint * params);
      |                                                ^~~~~~
      |                                                EGLenum
/src/src/video/SDL_egl.c:119:62: error: unknown type name 'GLint'; did you mean 'EGLint'?
  119 | typedef void (APIENTRY* PFNGLGETINTEGERVPROC) (GLenum pname, GLint * params);
      |                                                              ^~~~~
      |     
```

**Comment by madebr** [comment]
@slouken 
Currently, gl4es4vita support is broken with the build error of https://github.com/libsdl-org/SDL/pull/7123#issuecomment-1399816170

Vita developers removing their account after requesting support is not helping either...

**Comment by madebr** [comment]
I got gl4es4vita working with some change to the SDL sources + a patch for PVR_PSP2.
See https://github.com/GrapheneCt/PVR_PSP2/issues/21

**Comment by slouken** [comment]
Great! Feel free to merge when ready.

**Comment by isage** [comment]
Ooof. Somehow i missed that.
First of all, installing deps is easier via https://github.com/isage/vita-packages-extra **but**:
1. PIB can (and should be) removed. cc @SonicMastr 
2. Not testing on CI (or providing prebuilt version in vitasdk)  PVR build was intentional, since pvr_psp2 is legally gray. 

So you might want to revert.

**Comment by madebr** [comment]
Testing grey code seems fine to me. Usage of it in commercial software. (I am not a lawyer).
If we cannot test the code, why ship it?

I defer the rework of vita ci to the person removing pib support.

**Comment by isage** [comment]
Well, my task is to warn. But since pvr_psp2 isn't linked statically, that should be okay (i'm not a lawyer either)
(and your approach to installing deps is better for the time being, since there's no new release with khr fix yet)

**Comment by madebr** [comment]
Your legal concerns should probably be documented in docs/README-vita.md, possibly with links to external resources.
You probably mean the lack of license of  [pvr_psp2](https://github.com/GrapheneCt/PVR_PSP2)?

**Comment by isage** [comment]
No, pvr_psp2 lacks license for a reason:
It's proprietary powervr code, "leaked" by LG in one of their android source releases. pvr license states, that it's licensed under license you received it under, and LG released it under GPL, but then again, LG didn't had right to do so.

**Comment by isage** [comment]
on a separate legal note: there's zero code in sdl from pvr (PVRSRVCreateVirtualAppHint along with hint itself is a custom func/struct written by GrapheneCt)

**Pull request merged**
