### PR TITLE
Python conventional changes

### PR DESCRIPTION
**Pull request by TurnipGuy30**
## Description

Changed some lines of code according to Python conventions. No functionality is changed.

### CODE REVIEW

**Comment by slouken** [comment]
The Sourcery report in your [pull request](https://github.com/TurnipGuy30/SDL/pull/1) reports a quality reduction by applying this change:
```
Changed files | Quality Before | Quality After | Quality Change
src/joystick/sort_controllers.py | 68.46% 🙂 | 68.24% 🙂 | -0.22% 👎
```
Are you sure this is something we want?

**Comment by TurnipGuy30** [comment]
The recommendation on Sourcery's pull is to `Try splitting into smaller methods`, which is unrelated to the reason for my pull request. Because of this, I don't see why these small changes would decrease the code quality.

I could make more changes in an effort to improve Sourcery's rating, but I wouldn't be able to see if the rating has changed as Sourcery has not scanned this pull request, implying that Sourcery is not installed on this repository.

I'll see what I can do regarding Sourcery's biggest suggestion, `Try splitting into smaller methods`.

**Comment by slouken** [comment]
There's no reason to spend a lot of time refactoring this script. What's the motivation for this current PR?

**Comment by TurnipGuy30** [comment]
I made a [pull request](https://github.com/ppy/SDL/pull/1) on [`ppy`'s fork](https://github.com/ppy/SDL), but I was told to contribute to the main project instead.

To answer your question: I already have the Sourcery changes, so I want to do something with them.

**Pull request merged**
