### PR TITLE
remove visualtest:

### PR DESCRIPTION
**Pull request by sezero**
it is outdated (hasn't been maintained for years), and doesn't compile
for non-windows.

Closes: https://github.com/libsdl-org/SDL/issues/1557
Also see: https://github.com/libsdl-org/SDL/issues/4108#issuecomment-781459285

### CODE REVIEW

**Comment by icculus** [comment]
I agree. @slouken, should we pull the trigger on this one?

**Comment by sezero** [comment]
> Let's actually fire it up and see if it's valuable?

I know I won't. Aren't the cmdline tests enough?

**Comment by ccawley2011** [comment]
> Let's actually fire it up and see if it's valuable?

I had a go at this, and while it builds with Visual Studio using the changes in [this branch](https://github.com/ccawley2011/SDL/tree/visualtest), all of the tests currently fail.

**Comment by sezero** [comment]
PING?

**Comment by slouken** [comment]
We shouldn't delete it until @icculus has a chance to look at why the tests are failing. In theory this would catch all of the render visual bugs that he's working on this milestone.

**Comment by icculus** [comment]
I'll give this the benefit of the doubt and examine the existing code more seriously for 2.0.20, and we'll either remove or maintain it at that point.

**Comment by sezero** [comment]
I pushed multiple build fixes to visual test, including parts of @ccawley2011's
MSVC project file fixes, and deleted my kill-visualtest branch and closed this PR.

@icculus, @slouken, @ccawley2011: further discussion about visual test issues
should go into a new ticket.

**Pull request closed without merging**
