### PR TITLE
cmake: do all compile tests with -D_GNU_SOURCE=1

### LINKED ISSUE #7026: cmake: strcasestr detection fails
Happens with both SDL2 and SDL3: see CI ubuntu configuration logs. In github CI
with android and macos, it seems to detect, though.

Doesn't work for me locally, either.

From my CMakeError.log:
```
Determining if the strcasestr exist failed with the following output:
Change Dir: /home/sezero/SDL/b/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_97dce/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_97dce.dir/build.make CMakeFiles/cmTC_97dce.dir/build
gmake[1]: Entering directory `/home/sezero/SDL/b/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_97dce.dir/CheckSymbolExists.c.o
/usr/bin/cc   -idirafter "/home/sezero/SDL/src/video/khronos"    -o CMakeFiles/cmTC_97dce.dir/CheckSymbolExists.c.o   -c /home/sezero/SDL/b/CMakeFiles/CMakeTmp/CheckSymbolExists.c
/home/sezero/SDL/b/CMakeFiles/CMakeTmp/CheckSymbolExists.c: In function ‘main’:
/home/sezero/SDL/b/CMakeFiles/CMakeTmp/CheckSymbolExists.c:14: error: ‘strcasestr’ undeclared (first use in this function)
/home/sezero/SDL/b/CMakeFiles/CMakeTmp/CheckSymbolExists.c:14: error: (Each undeclared identifier is reported only once
/home/sezero/SDL/b/CMakeFiles/CMakeTmp/CheckSymbolExists.c:14: error: for each function it appears in.)
gmake[1]: *** [CMakeFiles/cmTC_97dce.dir/CheckSymbolExists.c.o] Error 1
gmake[1]: Leaving directory `/home/sezero/SDL/b/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_97dce/fast] Error 2

File /home/sezero/SDL/b/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <stddef.h>
#include <stdarg.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <wchar.h>
#include <float.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef strcasestr
  return ((int*)(&strcasestr))[argc];
#else
  (void)argc;
  return 0;
#endif
}
```

Building that test source as it is does fail indeed, but with `-D_GNU_SOURCE=1`
it succeeds: We need that define when detecting `strcasestr` -- or with all of
libc function calls' detection.

I don't have a patch.

### PR DESCRIPTION
**Pull request by madebr**
Fixes #7026

### CODE REVIEW

**Review by sezero — APPROVED** [review]

**Comment by sezero** [comment]
SDL2 (and release-2.26.x) branches need a similar fix, although I'm not sure whether it's worth it.

**Comment by madebr** [comment]
Pushed as 460b7b247f0046bda8b49242435924d03ea9f608 and e312fbb37d6f47027482239c5c0d27f0673ea4f7

**Comment by sezero** [comment]
Assuming `CMAKE_REQUIRED_FLAGS` affects `check_c_source_compiles`,
is the following OK as a follow-up cleanup?
```diff
diff --git a/cmake/sdlchecks.cmake b/cmake/sdlchecks.cmake
index ee24d57..8700441 100644
--- a/cmake/sdlchecks.cmake
+++ b/cmake/sdlchecks.cmake
@@ -820,7 +820,6 @@ macro(CheckPTHREAD)
       list(APPEND SDL_PC_CFLAGS ${PTHREAD_CFLAGS})
 
       check_c_source_compiles("
-        #define _GNU_SOURCE 1
         #include <pthread.h>
         int main(int argc, char **argv) {
           pthread_mutexattr_t attr;
@@ -831,7 +830,6 @@ macro(CheckPTHREAD)
         set(SDL_THREAD_PTHREAD_RECURSIVE_MUTEX 1)
       else()
         check_c_source_compiles("
-            #define _GNU_SOURCE 1
             #include <pthread.h>
             int main(int argc, char **argv) {
               pthread_mutexattr_t attr;
@@ -862,7 +860,6 @@ macro(CheckPTHREAD)
       check_include_file(pthread_np.h HAVE_PTHREAD_NP_H)
       if (HAVE_PTHREAD_H)
         check_c_source_compiles("
-            #define _GNU_SOURCE 1
             #include <pthread.h>
             int main(int argc, char **argv) {
               pthread_setname_np(pthread_self(), \"\");
```

**Comment by madebr** [comment]
Yes, that should be fine!

**Pull request merged**
