### PR TITLE
Add parenthesis after sizeof()

### PR DESCRIPTION
**Pull request by 1bsyl**
normalize to "sizeof (expression)"
not really tested ..

### CODE REVIEW

**Comment by sezero** [comment]
Here is the patch I had just generated: [patch.txt](https://github.com/libsdl-org/SDL/files/10935900/patch.txt)

I normalized all to `sizeof(xxx)` without a space in between.
I also seem to have touched a few other places and changed `(sizeof x)`
to `sizeof(x)`, and also the tidied multi line statements into single
ones while I was there.

**Comment by sezero** [comment]
.. and I specifically avoided audiocvt.c because there is an open PR for it.

**Comment by slouken** [comment]
There shouldn't be a space between sizeof and the operand. I'll go ahead and accept @sezero's patch. @1bsyl, do you have any cleanup beyond that?

**Comment by 1bsyl** [comment]
that's ok!

**Pull request closed without merging**
