### PR TITLE
hidpai: implement HD rumble for Nintendo switch controllers 

### PR DESCRIPTION
**Pull request by Candygoblen123**
hidpai: implement HD rumble for Nintendo switch controllers 

## Description
This PR adds support for the "HD Rumble" on Nintendo switch controllers, and adds the methods `SDL_HDRumbleJoystick` and `SDL_HDRumbleGamepad` to applications. This PR is based off the work of @german77 in #4538 that has been updated for SDL3 and had some issues fixed.

### CODE REVIEW

**Comment by slouken** [comment]
Given that this is specific to the Nintendo Switch hardware, I'm inclined to plumb this through the SendEfffect() API.

**Comment by Candygoblen123** [comment]
Although I am not familiar with them, there are other controllers (like the PS5 dualsense)that have HD rumble like features, and could potentially use the same API.

**Comment by slouken** [comment]
> Although I am not familiar with them, there are other controllers (like the PS5 dualsense) that have HD rumble like features, and could potentially use the same API. So I decided to go on and add the methods.

The PS5 HD rumble is entirely different and uses audio data to describe the rumble waveform.

**Comment by Candygoblen123** [comment]
If you would like, I can remove the exposed methods and fix up the SendEffect() to make it more user-friendly

**Comment by slouken** [comment]
> If you would like, I can remove the exposed methods and fix up the SendEffect() to make it more user-friendly

Yes please. Can you describe what you mean by "fix up the SendEffect"?

> would to not be possible to try to emulate the API on the PS5 so that they behave similarly?

Not as far as I know.

**Comment by Candygoblen123** [comment]
> Yes please. Can you describe what you mean by "fix up the SendEffect"?
Integrate the implementation in SendEffect in this PR better with the pre existing SendEffect code

**Comment by slouken** [comment]
No, that sounds good, thanks!

**Pull request closed without merging**
