### PR TITLE
SDL file times are 64-bit integers representing nanoseconds since the Unix epoch

### PR DESCRIPTION
**Pull request by slouken**
Related to https://github.com/libsdl-org/SDL/pull/9257

### CODE REVIEW

**Comment by Kontrabant** [comment]
Let's do it.  Someone can always bump it to an __int128 if it's an issue in 200 years :)

**Comment by sezero** [comment]
sdl2-compat needs readjusting after this?

**Comment by slouken** [comment]
> sdl2-compat needs readjusting after this?

I don't think so, do we use these anywhere in SDL2?

**Comment by sezero** [comment]
Hm, I confused myself about event timestamps. Don't mind me, sorry about the noise.

**Pull request merged**
