### PR TITLE
Add missing \returns, change "return" to "returns" to have same naming

### PR DESCRIPTION
**Pull request by 1bsyl**
* Add missing \returns, change "return" to "returns" to have same naming

### CODE REVIEW

**Comment by 1bsyl** [comment]
This add an SDL_ResultCode for all those functions :
```
int SDL_GetAudioDeviceSpec() : returns 0 on success, nonzero on error 
int SDL_GetDefaultAudioInfo() : returns 0 on success, nonzero on error 
int SDL_PlayAudioDevice() : returns 0 on success or a negative error code on failure; call 
int SDL_PauseAudioDevice() : returns 0 on success or a negative error code on failure; call 
int SDL_PutAudioStreamData() : returns 0 on success, or -1 on error. 
int SDL_FlushAudioStream() : returns 0 on success or a negative error code on failure; call 
int SDL_ClearAudioStream() : returns 0 on success or a negative error code on failure; call 
int SDL_MixAudioFormat() : returns 0 on success or a negative error code on failure; call 
int SDL_QueueAudio() : returns 0 on success or a negative error code on failure; call 
int SDL_ClearQueuedAudio() : returns 0 on success or a negative error code on failure; call 
int SDL_LockAudioDevice() : returns 0 on success or a negative error code on failure; call 
int SDL_ConvertAudioSamples() : returns 0 on success or a negative error code on failure. On error, 
int SDL_SetWindowShape() : returns 0 on success, SDL_INVALID_SHAPE_ARGUMENT on an invalid shape 
int SDL_LockMutex() : returns 0, or -1 on error. 
int SDL_UnlockMutex() : returns 0, or -1 on error. 
int SDL_SemWait() : returns 0 on success or a negative error code on failure; call 
int SDL_SemPost() : returns 0 on success or a negative error code on failure; call 
int SDL_CondSignal() : returns 0 on success or a negative error code on failure; call 
int SDL_CondBroadcast() : returns 0 on success or a negative error code on failure; call 
int SDL_DetachVirtualJoystick() : returns 0 on success, or -1 if an error occurred. 
int SDL_SetJoystickVirtualAxis() : returns 0 on success, -1 on error. 
int SDL_SetJoystickVirtualButton() : returns 0 on success, -1 on error. 
int SDL_SetJoystickVirtualHat() : returns 0 on success, -1 on error. 
int SDL_SetJoystickPlayerIndex() : returns 0 on success or a negative error code on failure; call 
int SDL_GetJoystickGUIDString() : returns 0 on success or a negative error code on failure; call 
int SDL_RumbleJoystick() : returns 0, or -1 if rumble isn't supported on this joystick 
int SDL_RumbleJoystickTriggers() : returns 0, or -1 if trigger rumble isn't supported on this joystick 
int SDL_SetJoystickLED() : returns 0 on success, -1 if this joystick does not have a modifiable LED 
int SDL_SendJoystickEffect() : returns 0, or -1 if this joystick or driver doesn't support effect packets 
int SDL_GetVersion() : returns 0 on success or a negative error code on failure; call 
int SDL_SetPixelFormatPalette() : returns 0 on success or a negative error code on failure; call 
int SDL_SetPaletteColors() : returns 0 on success or a negative error code if not all of the colors 
int SDL_SetSurfacePalette() : returns 0 on success or a negative error code on failure; call 
int SDL_LockSurface() : returns 0 on success or a negative error code on failure; call 
int SDL_SaveBMP_RW() : returns 0 on success or a negative error code on failure; call 
int SDL_SetSurfaceRLE() : returns 0 on success or a negative error code on failure; call 
int SDL_SetSurfaceColorKey() : returns 0 on success or a negative error code on failure; call 
int SDL_GetSurfaceColorKey() : returns 0 on success or a negative error code on failure; call 
int SDL_SetSurfaceColorMod() : returns 0 on success or a negative error code on failure; call 
int SDL_GetSurfaceColorMod() : returns 0 on success or a negative error code on failure; call 
int SDL_SetSurfaceAlphaMod() : returns 0 on success or a negative error code on failure; call 
int SDL_GetSurfaceAlphaMod() : returns 0 on success or a negative error code on failure; call 
int SDL_SetSurfaceBlendMode() : returns 0 on success or a negative error code on failure; call 
int SDL_GetSurfaceBlendMode() : returns 0 on success or a negative error code on failure; call 
int SDL_GetSurfaceClipRect() : returns 0 on success or a negative error code on failure; call 
int SDL_ConvertPixels() : returns 0 on success or a negative error code on failure; call 
int SDL_PremultiplyAlpha() : returns 0 on success or a negative error code on failure; call 
int SDL_FillSurfaceRect() : returns 0 on success or a negative error code on failure; call 
int SDL_FillSurfaceRects() : returns 0 on success or a negative error code on failure; call 
int SDL_BlitSurface() : returns 0 on success or a negative error code on failure; call 
int SDL_BlitSurfaceUnchecked() : returns 0 on success or a negative error code on failure; call 
int SDL_SoftStretch() : returns 0 on success or a negative error code on failure; call 
int SDL_SoftStretchLinear() : returns 0 on success or a negative error code on failure; call 
int SDL_BlitSurfaceScaled() : returns 0 on success or a negative error code on failure; call 
int SDL_BlitSurfaceUncheckedScaled() : returns 0 on success or a negative error code on failure; call 
int SDL_Vulkan_LoadLibrary() : returns 0 on success or -1 if the library couldn't be loaded; call 
int SDL_SetThreadPriority() : returns 0 on success or a negative error code on failure; call 
int SDL_TLSSet() : returns 0 on success or a negative error code on failure; call 
int SDL_SetGamepadPlayerIndex() : returns 0 on success or a negative error code on failure; call 
int SDL_GetGamepadTouchpadFinger() : returns 0 on success or a negative error code on failure; call 
int SDL_SetGamepadSensorEnabled() : returns 0 or -1 if an error occurred. 
int SDL_GetGamepadSensorData() : returns 0 or -1 if an error occurred. 
int SDL_RumbleGamepad() : returns 0, or -1 if rumble isn't supported on this gamepad 
int SDL_RumbleGamepadTriggers() : returns 0, or -1 if trigger rumble isn't supported on this gamepad 
int SDL_SetGamepadLED() : returns 0, or -1 if this gamepad does not have a modifiable LED 
int SDL_SendGamepadEffect() : returns 0, or -1 if this gamepad or driver doesn't support effect packets 
int SDL_AddHintCallback() : returns 0 on success or a negative error code on failure; call 
int SDL_SetClipboardText() : returns 0 on success or a negative error code on failure; call 
int SDL_SetPrimarySelectionText() : returns 0 on success or a negative error code on failure; call 
int SDL_OpenURL() : returns 0 on success, or -1 on error; call SDL_GetError() for more 
int SDL_ShowMessageBox() : returns 0 on success or a negative error code on failure; call 
int SDL_ShowSimpleMessageBox() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRectUnion() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRectUnionFloat() : returns 0 on success or a negative error code on failure; call 
int SDL_WarpMouseGlobal() : returns 0 on success or a negative error code on failure; call 
int SDL_SetRelativeMouseMode() : returns 0 on success or a negative error code on failure; call 
int SDL_CaptureMouse() : returns 0 on success or -1 if not supported; call SDL_GetError() for more 
int SDL_SetCursor() : returns 0 on success or a negative error code on failure; call 
int SDL_ShowCursor() : returns 0 on success or a negative error code on failure; call 
int SDL_HideCursor() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowWMInfo() : returns 0 on success or a negative error code on failure; call 
int SDL_GetDisplayBounds() : returns 0 on success or a negative error code on failure; call 
int SDL_GetDisplayUsableBounds() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowFullscreenMode() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowTitle() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowIcon() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowPosition() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowPosition() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowSize() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowSize() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowBordersSize() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowSizeInPixels() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowMinimumSize() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowMinimumSize() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowMaximumSize() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowMaximumSize() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowBordered() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowResizable() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowAlwaysOnTop() : returns 0 on success or a negative error code on failure; call 
int SDL_ShowWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_HideWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_RaiseWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_MaximizeWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_MinimizeWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_RestoreWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowFullscreen() : returns 0 on success or a negative error code on failure; call 
int SDL_UpdateWindowSurface() : returns 0 on success or a negative error code on failure; call 
int SDL_UpdateWindowSurfaceRects() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowGrab() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowKeyboardGrab() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowMouseGrab() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowMouseRect() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowOpacity() : returns 0 on success or a negative error code on failure; call 
int SDL_GetWindowOpacity() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowModalFor() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowInputFocus() : returns 0 on success or a negative error code on failure; call 
int SDL_SetWindowHitTest() : returns 0 on success or -1 on error (including unsupported); call 
int SDL_FlashWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_EnableScreenSaver() : returns 0 on success or a negative error code on failure; call 
int SDL_DisableScreenSaver() : returns 0 on success or a negative error code on failure; call 
int SDL_GL_LoadLibrary() : returns 0 on success or a negative error code on failure; call 
int SDL_GL_SetAttribute() : returns 0 on success or a negative error code on failure; call 
int SDL_GL_GetAttribute() : returns 0 on success or a negative error code on failure; call 
int SDL_GL_MakeCurrent() : returns 0 on success or a negative error code on failure; call 
int SDL_GL_SetSwapInterval() : returns 0 on success or -1 if setting the swap interval is not supported; 
int SDL_GL_GetSwapInterval() : returns 0 on success or -1 error. call SDL_GetError() for more 
int SDL_GL_SwapWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_GL_DeleteContext() : returns 0 on success or a negative error code on failure; call 
int SDL_SetTextInputRect() : returns 0 on success or a negative error code on failure; call 
int SDL_GetSensorData() : returns 0 or -1 if an error occurred. 
int SDL_hid_init() : returns 0 on success and -1 on error. 
int SDL_hid_exit() : returns 0 on success and -1 on error. 
int SDL_hid_set_nonblocking() : returns 0 on success and -1 on error. 
int SDL_hid_close() : returns 0 on success or a negative error code on failure; call 
int SDL_hid_get_manufacturer_string() : returns 0 on success and -1 on error. 
int SDL_hid_get_product_string() : returns 0 on success and -1 on error. 
int SDL_hid_get_serial_number_string() : returns 0 on success and -1 on error. 
int SDL_hid_get_indexed_string() : returns 0 on success and -1 on error. 
int SDL_HapticUpdateEffect() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticRunEffect() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticStopEffect() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticSetGain() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticSetAutocenter() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticPause() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticUnpause() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticStopAll() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticRumbleInit() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticRumblePlay() : returns 0 on success or a negative error code on failure; call 
int SDL_HapticRumbleStop() : returns 0 on success or a negative error code on failure; call 
int SDL_GUIDToString() : returns 0 on success or a negative error code on failure; call 
int SDL_Init() : returns 0 on success or a negative error code on failure; call 
int SDL_InitSubSystem() : returns 0 on success or a negative error code on failure; call 
int SDL_RWclose() : returns 0 on success or a negative error code on failure; call 
int SDL_CreateWindowAndRenderer() : returns 0 on success, or -1 on error; call SDL_GetError() for more 
int SDL_GetRendererInfo() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderWindowSize() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderOutputSize() : returns 0 on success or a negative error code on failure; call 
int SDL_GetCurrentRenderOutputSize() : returns 0 on success or a negative error code on failure; call 
int SDL_QueryTexture() : returns 0 on success or a negative error code on failure; call 
int SDL_SetTextureColorMod() : returns 0 on success or a negative error code on failure; call 
int SDL_GetTextureColorMod() : returns 0 on success or a negative error code on failure; call 
int SDL_SetTextureAlphaMod() : returns 0 on success or a negative error code on failure; call 
int SDL_GetTextureAlphaMod() : returns 0 on success or a negative error code on failure; call 
int SDL_SetTextureBlendMode() : returns 0 on success or a negative error code on failure; call 
int SDL_GetTextureBlendMode() : returns 0 on success or a negative error code on failure; call 
int SDL_SetTextureScaleMode() : returns 0 on success, or -1 if the texture is not valid. 
int SDL_GetTextureScaleMode() : returns 0 on success, or -1 if the texture is not valid. 
int SDL_SetTextureUserData() : returns 0 on success, or -1 if the texture is not valid. 
int SDL_UpdateTexture() : returns 0 on success or a negative error code on failure; call 
int SDL_UpdateYUVTexture() : returns 0 on success or -1 if the texture is not valid; call 
int SDL_UpdateNVTexture() : returns 0 on success, or -1 if the texture is not valid. 
int SDL_LockTexture() : returns 0 on success or a negative error code if the texture is not valid 
int SDL_LockTextureToSurface() : returns 0 on success, or -1 if the texture is not valid or was not created 
int SDL_SetRenderTarget() : returns 0 on success or a negative error code on failure; call 
int SDL_SetRenderLogicalPresentation() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderLogicalPresentation() : returns 0 on success or a negative error code on failure; call 
int SDL_RenderCoordinatesFromWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_RenderCoordinatesToWindow() : returns 0 on success or a negative error code on failure; call 
int SDL_ConvertEventToRenderCoordinates() : returns 0 on success or a negative error code on failure; call 
int SDL_SetRenderViewport() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderViewport() : returns 0 on success or a negative error code on failure; call 
int SDL_SetRenderClipRect() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderClipRect() : returns 0 on success or a negative error code on failure; call 
int SDL_SetRenderScale() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderScale() : returns 0 on success or a negative error code on failure; call 
int SDL_SetRenderDrawColor() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderDrawColor() : returns 0 on success or a negative error code on failure; call 
int SDL_SetRenderDrawBlendMode() : returns 0 on success or a negative error code on failure; call 
int SDL_GetRenderDrawBlendMode() : returns 0 on success or a negative error code on failure; call 
int SDL_RenderClear() : returns 0 on success or a negative error code on failure; call 
int SDL_RenderPoint() : returns 0 on success, or -1 on error 
int SDL_RenderPoints() : returns 0 on success, or -1 on error 
int SDL_RenderLine() : returns 0 on success, or -1 on error 
int SDL_RenderLines() : returns 0 on success, or -1 on error 
int SDL_RenderRect() : returns 0 on success, or -1 on error 
int SDL_RenderRects() : returns 0 on success, or -1 on error 
int SDL_RenderFillRect() : returns 0 on success, or -1 on error 
int SDL_RenderFillRects() : returns 0 on success, or -1 on error 
int SDL_RenderTexture() : returns 0 on success, or -1 on error 
int SDL_RenderTextureRotated() : returns 0 on success, or -1 on error 
int SDL_RenderGeometry() : returns 0 on success, or -1 if the operation is not supported 
int SDL_RenderGeometryRaw() : returns 0 on success, or -1 if the operation is not supported 
int SDL_RenderReadPixels() : returns 0 on success or a negative error code on failure; call 
int SDL_RenderPresent() : returns 0 on success or a negative error code on failure; call 
int SDL_RenderFlush() : returns 0 on success or a negative error code on failure; call 
int SDL_GL_BindTexture() : returns 0 on success, or -1 if the operation is not supported; call 
int SDL_GL_UnbindTexture() : returns 0 on success, or -1 if the operation is not supported 
int SDL_SetRenderVSync() : returns a 0 int on success, or non-zero on failure 
int SDL_GetRenderVSync() : returns a 0 int on success, or non-zero on failure 
int SDL_SetMemoryFunctions() : returns 0 on success or a negative error code on failure; call 
int SDL_RegisterApp() : returns 0 on success, -1 on error. SDL_GetError() may have details. 
int SDL_LinuxSetThreadPriority() : returns 0 on success, or -1 on error. 
int SDL_LinuxSetThreadPriorityAndPolicy() : returns 0 on success, or -1 on error. 
int SDL_iPhoneSetAnimationCallback() : returns 0 on success or a negative error code on failure; call 
int SDL_AndroidGetExternalStorageState() : returns 0 on success or a negative error code on failure; call 
int SDL_AndroidShowToast() : returns 0 if success, -1 if any error occurs. 
int SDL_AndroidSendMessage() : returns 0 on success or a negative error code on failure; call 
int SDL_GDKGetTaskQueue() : returns 0 if success, -1 if any error occurs. 

```

**Comment by 1bsyl** [comment]
but not for: 

```
int SDL_GetNumAudioDrivers() : returns the number of built-in audio drivers. 
int SDL_GetNumAudioDevices() : returns the number of available devices exposed by the current driver or 
int SDL_GetAudioStreamData() : returns the number of bytes read from the stream, or -1 on error 
int SDL_GetAudioStreamAvailable() : returns the number of converted/resampled bytes available. 
int SDL_GetShapedWindowMode() : returns 0 if the window has a shape and, provided shape_mode was not NULL, 
int SDL_TryLockMutex() : returns 0, `SDL_MUTEX_TIMEDOUT`, or -1 on error; call SDL_GetError() for 
int SDL_SemTryWait() : returns 0 if the wait succeeds, `SDL_MUTEX_TIMEDOUT` if the wait would 
int SDL_SemWaitTimeout() : returns 0 if the wait succeeds, `SDL_MUTEX_TIMEDOUT` if the wait does not 
int SDL_CondWait() : returns 0 when it is signaled or a negative error code on failure; call 
int SDL_CondWaitTimeout() : returns 0 if the condition variable is signaled, `SDL_MUTEX_TIMEDOUT` if 
int SDL_GetJoystickInstancePlayerIndex() : returns the player index of a joystick, or -1 if it's not available 
int SDL_GetJoystickPlayerIndex() : returns the player index, or -1 if it's not available. 
int SDL_GetNumJoystickAxes() : returns the number of axis controls/number of axes on success or a 
int SDL_GetNumJoystickHats() : returns the number of POV hats on success or a negative error code on 
int SDL_GetNumJoystickButtons() : returns the number of buttons on success or a negative error code on 
int SDL_GetCPUCount() : returns the total number of logical CPU cores. On CPUs that include 
int SDL_GetCPUCacheLineSize() : returns the L1 cache line size of the CPU, in bytes. 
int SDL_GetSystemRAM() : returns the amount of RAM configured in the system in MiB. 
int SDL_AddGamepadMapping() : returns 1 if a new mapping is added, 0 if an existing mapping is updated, 
int SDL_AddGamepadMappingsFromRW() : returns the number of mappings added or -1 on error; call SDL_GetError() 
int SDL_GetNumGamepadMappings() : returns the number of mappings. 
int SDL_GetGamepadInstancePlayerIndex() : returns the player index of a gamepad, or -1 if it's not available 
int SDL_GetGamepadPlayerIndex() : returns the player index for gamepad, or -1 if it's not available. 
int SDL_GetNumGamepadTouchpads() : returns number of touchpads 
int SDL_GetNumGamepadTouchpadFingers() : returns number of supported simultaneous fingers 
int SDL_SetError() : returns always -1. 
int SDL_PeepEvents() : returns the number of events actually stored or a negative error code on 
int SDL_PollEvent() : returns 1 if there is a pending event or 0 if there are none available. 
int SDL_WaitEvent() : returns 1 on success or 0 if there was an error while waiting for events; 
int SDL_WaitEventTimeout() : returns 1 on success or 0 if there was an error while waiting for events; 
int SDL_PushEvent() : returns 1 on success, 0 if the event was filtered, or a negative error 
int SDL_GetNumVideoDrivers() : returns a number >= 1 on success or a negative error code on failure; call 
int SDL_GetSensorInstanceNonPortableType() : returns the sensor platform dependent type, or -1 if `instance_id` is not 
int SDL_GetSensorNonPortableType() : returns the sensor platform dependent type, or -1 if `sensor` is NULL. 
int SDL_hid_write() : returns the actual number of bytes written and -1 on error. 
int SDL_hid_read_timeout() : returns the actual number of bytes read and -1 on error. If no packet was 
int SDL_hid_read() : returns the actual number of bytes read and -1 on error. If no packet was 
int SDL_hid_send_feature_report() : returns the actual number of bytes written and -1 on error. 
int SDL_hid_get_feature_report() : returns the number of bytes read plus one for the report ID (which is 
int SDL_GetNumTouchDevices() : returns the number of registered touch devices. 
int SDL_GetNumTouchFingers() : returns the number of active fingers for a given touch device on success 
int SDL_NumHaptics() : returns the number of haptic devices detected on the system or a negative 
int SDL_HapticOpened() : returns 1 if it has been opened, 0 if it hasn't or on failure; call 
int SDL_HapticIndex() : returns the index of the specified haptic device or a negative error code 
int SDL_MouseIsHaptic() : returns SDL_TRUE if the mouse is haptic or SDL_FALSE if it isn't. 
int SDL_JoystickIsHaptic() : returns SDL_TRUE if the joystick is haptic, SDL_FALSE if it isn't, or a 
int SDL_HapticNumEffects() : returns the number of effects the haptic device can store or a negative 
int SDL_HapticNumEffectsPlaying() : returns the number of effects the haptic device can play at the same time 
int SDL_HapticNumAxes() : returns the number of axes on success or a negative error code on failure; 
int SDL_HapticEffectSupported() : returns SDL_TRUE if effect is supported, SDL_FALSE if it isn't, or a 
int SDL_HapticNewEffect() : returns the ID of the effect on success or a negative error code on 
int SDL_HapticGetEffectStatus() : returns 0 if it isn't playing, 1 if it is playing, or a negative error 
int SDL_HapticRumbleSupported() : returns SDL_TRUE if effect is supported, SDL_FALSE if it isn't, or a 
int SDL_AtomicSet() : returns the previous value of the atomic variable. 
int SDL_AtomicGet() : returns the current value of an atomic variable. 
int SDL_AtomicAdd() : returns the previous value of the atomic variable. 
int SDL_GetNumRenderDrivers() : returns a number >= 0 on success or a negative error code on failure; call 
int SDL_GetNumAllocations() : returns the number of allocations 
int SDL_RunApp() : returns the return value from mainFunction: 0 on success, -1 on failure; 
int SDL_Direct3D9GetAdapterIndex() : returns the D3D9 adapter index on success or a negative error code on 
int SDL_GetAndroidSDKVersion() : returns the Android API level. 
```

**Comment by 1bsyl** [comment]
it should be quite easy, to replace explicit "return 0;" by a "return SDL_OK;" in the function typed SDL_ResultCode.

**Comment by slouken** [comment]
@icculus, what is your thought on SDL_ResultCode?
@1bsyl, even if we don't end up committing that, it's useful to make sure the function documentation is correct, so thanks!

**Comment by icculus** [comment]
Hard pass on SDL_ResultCode, sorry.

**Comment by 1bsyl** [comment]
I don't feel confident with SDL_ResultCode neither. so I removed the commit.
it remains the commit, that add `\returns` where it's missing. and add `s` to `\return`

**Comment by 1bsyl** [comment]
then, telling 
"returns number or negative error code ..."
or 
"returns 0 on success or negative error code ..."

is covering more of actual functions.

**Comment by 1bsyl** [comment]
merging, this is one since it's improve the documentation.
(so that I don't need to rebase/revert multiple times)

**Pull request merged**
