### PR TITLE
Fixed most small problems reported by cppcheck for src/core PR #7307

### PR DESCRIPTION
**Pull request by 1bsyl**
Fixed most small problems reported by cppcheck for src/core PR #7307 (from @kevin2kevin2)

https://github.com/libsdl-org/SDL/pull/7307

### CODE REVIEW

**Comment by 1bsyl** [comment]
that eases the code reading ...
and when you run the tool next time, that's as many warning less...
I am going to change the commits so that we can cherry pick the pointer issue for SDL2

**Comment by slouken** [comment]
I'm not opposed to these changes, but can you change:
```
int value;
value = blah;
```
to:
`int value = blah;`

**Comment by 1bsyl** [comment]
updated

**Comment by 1bsyl** [comment]
cherry picked the for SDL2: 
"Fix potential de-referencing null pointer in SDL_EVDEV_kbd_keycode()": https://github.com/libsdl-org/SDL/commit/d948e6c3c592db7bfdcf14d4e869ff8db238e50a

**Pull request merged**
