### PR TITLE
SDL_DisplayMode now represents physical pixels and has added a displa…

### PR DESCRIPTION
**Pull request by slouken**
…y scaling factor

Work in progress on https://github.com/libsdl-org/SDL/issues/7134

### CODE REVIEW

**Comment by slouken** [comment]
@Kontrabant, what is the right change for Wayland here? If it's complex, should I commit and let you make the right changes?

**Comment by slime73** [comment]
I wonder how much code is out there which uses display mode width and height to set (non-fullscreen) width and height.

I don't think it's a super huge deal to make the two have different coordinate systems, but at the very least there should probably be explicit documentation around CreateWindow and/or DisplayModes saying you can't just use one's values for the other without converting.

**Comment by slouken** [comment]
> I wonder how much code is out there which uses display mode width and height to set (non-fullscreen) width and height. I know some games have a fixed list of sizes based on available display modes that can be used for non-fullscreen window sizes, instead of having a fully resizable window, for example.
> 
> I don't think it's a super huge deal to make the two have different coordinate systems, but at the very least there should probably be explicit documentation around CreateWindow and/or DisplayModes saying you can't just use one's values for the other without converting.

Yeah, it turns out that most games use the fullscreen desktop flag and then query for the window size, or use an explicit video mode, and the fullscreen video modes have a 1.0 scale, so it's not generally an issue. The gotcha on Windows is that now the window size is in scaled space, so you need to call SDL_GetWindowSizeInPixels() to get your backbuffer size.

I kind of want to wait and see how this impacts real projects. @flibitijibibo, thoughts?

**Comment by slime73** [comment]
> I wonder how much code is out there which uses display mode width and height to set (non-fullscreen) width and height.

This is one reason I kind of liked the idea of having both point_w/point_h and pixel_w/pixel_h in the display mode struct, because it's more intuitive to choose the right one for a given situation compared to manually converting by using the scale value.

But maybe the scale value is more intuitive in other situations... but having the scale and both sizes would feel kind of redundant. API design is hard 😅

**Comment by sezero** [comment]
What changes are needed in sdl2-compat after this?

**Comment by Kontrabant** [comment]
> @Kontrabant, what is the right change for Wayland here? If it's complex, should I commit and let you make the right changes?

Basically just setting the desktop scale as all exclusive modes are 1.0.  I'll take care of it.

**Comment by slouken** [comment]
> What changes are needed in sdl2-compat after this?

The SDL2 display mode should have w and h equal to SDL3 w and h divided by the display_scale.

**Comment by sezero** [comment]
> The SDL2 display mode should have w and h equal to SDL3 w and h divided by the display_scale.

The following then?
```diff
diff --git a/src/sdl2_compat.c b/src/sdl2_compat.c
index 892be6a..cd3b573 100644
--- a/src/sdl2_compat.c
+++ b/src/sdl2_compat.c
@@ -3208,22 +3208,23 @@ static void
 DisplayMode_2to3(const SDL2_DisplayMode *in, SDL_DisplayMode *out) {
     if (in && out) {
         out->format = in->format;
         out->w = in->w;
         out->h = in->h;
         out->refresh_rate = (float) in->refresh_rate;
+        out->display_scale = 1.0f;
         out->driverdata = in->driverdata;
     }
 }
 
 static void
 DisplayMode_3to2(const SDL_DisplayMode *in, SDL2_DisplayMode *out) {
     if (in && out) {
         out->format = in->format;
-        out->w = in->w;
-        out->h = in->h;
+        out->w = (int) SDL_floor((in->w / in->display_scale) + 0.5f);
+        out->h = (int) SDL_floor((in->h / in->display_scale) + 0.5f);
         out->refresh_rate = (int) SDL_ceil(in->refresh_rate);
         out->driverdata = in->driverdata;
     }
 }
 
 DECLSPEC int SDLCALL
```

**Comment by slouken** [comment]
Yes, that looks reasonable. Although, any reason not to use SDL_ceil() instead of the SDL_floor() expression?

**Comment by sezero** [comment]
Didn't have any other sane solution other than assigning 1.0f to display_scale
in 2-to-3 conversion.

> Yes, that looks reasonable.

OK,

> Although, any reason not to use SDL_ceil() instead of the SDL_floor() expression?

Just being over-cautious -- ceil would return 2 for 1.01

Any changes before I apply?

**Comment by Kontrabant** [comment]
#7152 for Wayland

> Yes, that looks reasonable. Although, any reason not to use SDL_ceil() instead of the SDL_floor() expression?

Or `SDL_lroundf()`?  Rounds halfway cases away from 0 and ignores any system rounding mode changes.

**Comment by Kontrabant** [comment]
> ```diff
> +        out->w = (int) SDL_floor((in->w / in->display_scale) + 0.5f);
> +        out->h = (int) SDL_floor((in->h / in->display_scale) + 0.5f);
> ```

Isn't this just `SDL_lroundf()`? Rounds halfway cases away from 0 and the rounding isn't affected by system rounding mode changes.

**Comment by sezero** [comment]
> > ```diff
> > +        out->w = (int) SDL_floor((in->w / in->display_scale) + 0.5f);
> > +        out->h = (int) SDL_floor((in->h / in->display_scale) + 0.5f);
> > ```
> 
> Isn't this just `SDL_lroundf()` behavior? Rounds halfway cases away from 0 and the rounding isn't affected by system rounding mode changes.

Well, yes, thanks! Is the following good? (As a bonus, changes SDL_ceil to direct SDL3_ceil..)
```diff
diff --git a/src/sdl2_compat.c b/src/sdl2_compat.c
index 892be6a..6a2735b 100644
--- a/src/sdl2_compat.c
+++ b/src/sdl2_compat.c
@@ -3208,23 +3208,24 @@ static void
 DisplayMode_2to3(const SDL2_DisplayMode *in, SDL_DisplayMode *out) {
     if (in && out) {
         out->format = in->format;
         out->w = in->w;
         out->h = in->h;
         out->refresh_rate = (float) in->refresh_rate;
+        out->display_scale = 1.0f;
         out->driverdata = in->driverdata;
     }
 }
 
 static void
 DisplayMode_3to2(const SDL_DisplayMode *in, SDL2_DisplayMode *out) {
     if (in && out) {
         out->format = in->format;
-        out->w = in->w;
-        out->h = in->h;
+        out->w = SDL3_lroundf(in->w / in->display_scale);
+        out->h = SDL3_lroundf(in->h / in->display_scale);
-        out->refresh_rate = (int) SDL_ceil(in->refresh_rate);
+        out->refresh_rate = (int) SDL3_ceil(in->refresh_rate);
         out->driverdata = in->driverdata;
     }
 }
 
 DECLSPEC int SDLCALL
 SDL_GetDisplayMode(int displayIndex, int modeIndex, SDL2_DisplayMode *mode)
```

**Comment by sezero** [comment]
Applied changes to sdl2-compat.

**Pull request merged**
