### PR TITLE
gdk: Backport SDL3 MR #8844

### PR DESCRIPTION
**Pull request by flibitijibibo**
Not much to see here, this just applies the open Xbox GDK portions to SDL2!

CC @chalonverse @TheSpydog

### CODE REVIEW

**Review by TheSpydog — APPROVED** [review]
LGTM!

**Comment by slouken** [comment]
This is fine to merge, but just as a reminder, @libsdl-org/a-team, once a release candidate is made, please check with me or @icculus before merging any changes to that branch. We may be in final RC mode and don't want to introduce any regressions between the last RC that people saw and the final release.

**Comment by madebr** [comment]
Shouldn't a `release-2.30.x` branch be created to separate the release branch from the development one?

**Comment by flibitijibibo** [comment]
> Shouldn't a `release-2.30.x` branch be created to separate the release branch from the development one?

I assumed this as well, my mistake - fortunately this only affects Xbox and WinGDK builds so it should be safe from affecting other targets.

**Comment by slouken** [comment]
> Shouldn't a `release-2.30.x` branch be created to separate the release branch from the development one?

That's usually branched after release, but it's not a bad idea to do that once an RC is made to allow parallel development. I won't do it for this release, but I'll try to remember in the future, thanks!

**Comment by slouken** [comment]
FYI, we're making another SDL 2.30 release candidate with audio distortion fixes, so feel free to commit anything you want to go out for this release.

**Pull request merged**
