### PR TITLE
Add the raw platform specific key code to SDL_Keysym

### PR DESCRIPTION
**Pull request by slouken**
This allows applications to handle keys that SDL doesn't recognize, in a platform dependent way.

Fixes https://github.com/libsdl-org/SDL/issues/6390

### CODE REVIEW

**Comment by slouken** [comment]
@Kontrabant, is there anything meaningful to do for the Wayland platform here?

**Comment by slouken** [comment]
Like that?

**Comment by slouken** [comment]
Thanks!

**Comment by slouken** [comment]
@Kontrabant, can you add the Wayland code for querying the full keymap? You can look at the Cocoa and Windows implementations for examples.

**Comment by Kontrabant** [comment]
> @Kontrabant, can you add the Wayland code for querying the full keymap? You can look at the Cocoa and Windows implementations for examples.

Sure, I'll take care of it.

**Comment by slouken** [comment]
> > @Kontrabant, can you add the Wayland code for querying the full keymap? You can look at the Cocoa and Windows implementations for examples.
> 
> Sure, I'll take care of it.

Thanks! I'll leave it as-is for now and you can add a PR once this is merged, or you can push a separate commit to this PR, whichever you prefer.

**Comment by slouken** [comment]
@Kontrabant, can you also do the X11 code? I have the place where it needs to be done, I just don't know how to map from modifiers to level, and I suspect it'll be the same as the Wayland code.

**Pull request merged**
