### PR TITLE
Prevent ASAN warning in SDL_triangle.c

### PR DESCRIPTION
**Pull request by 1bsyl**
like SDL_triangle.c:305:30: runtime error: left shift of negative value -672 (even if the value was correctly computed)

### CODE REVIEW

**Comment by 1bsyl** [comment]
I think the fix is fine, i tested.
instead of:
`y = x << FP_BITS.`
where x can be positive or negative, 
if does:
```

if (x>0) 
y = x << FP_BITS
else 
x *= -1;
y = x << FP_BITS
y *= -1;

 


```

**Comment by 1bsyl** [comment]
wait, there is one more !

**Comment by 1bsyl** [comment]
updated! 
in 2 commits, so that only the first one need to be cherry picked !

**Review by sezero — COMMENTED** [review]
Not sure what to do with this. Is there any performance impact by pointing the ear by the toe?

**Comment by 1bsyl** [comment]
no performance impact, since that's the upper code, before the rendering loops! 
It's more about making asan happy. (I first thought this was again an undefined behavior).

**Comment by 1bsyl** [comment]
cherry-picked for SDL2: 4033a0a83b3a675c6b7803e36fb13114579d0b5b

**Pull request merged**
