### PR TITLE
Remove SDL_SetWindowBrightness, SDL_SetWindowGammaRamp, and SDL_CalculateGammaRamp.

### PR DESCRIPTION
**Pull request by slime73**
## Description
This removes `SDL_SetWindowBrightness`, `SDL_GetWindowBrightness`, `SDL_SetWindowGammaRamp`, and `SDL_GetWindowGammaRamp`.

I wasn't sure what to do with `SDL_CalculateGammaRamp` -  as-is it feels very vestigial, but if the proposed `SDL_SetRendererGammaRamp` ever gets implemented (#4710) then I suppose it'd still be useful. For now I left it alone.

## Existing Issue(s)
https://github.com/libsdl-org/SDL/issues/3519#issuecomment-1223465043
#1119
#1495
#1779
#4710

### CODE REVIEW

**Comment by slouken** [comment]
Go ahead and remove SDL_CalculateGammaRamp() as well, we can always pull it back out of source control if we end up needing it.

**Comment by slouken** [comment]
We shouldn't merge this until we figure out what our fallback for sdl2-compat is going to be. @icculus, maybe we should implement https://github.com/libsdl-org/SDL/issues/4710 first, so we have a working implementation for code using the 2D renderer?

**Comment by icculus** [comment]
My _assumption_ is that this doesn't work on most platforms now, and if it does it changes the whole desktop's gamma, so for sdl2-compat I was just going to have it return -1 and not even attempt to implement it.

If we do implement this at the render API layer, it's probably doable with a shader and always faking the main display with a render target, but that's a pretty serious change to make this happen.

(If you reply "but Steam Link needs this," I'm going to weep openly. It's going to be awkward for everyone. Just warning you in advance.)

**Comment by slouken** [comment]
Nope, it does change the whole desktop gamma, and it's very awkward when the application doesn't respond to focus changes by restoring it, or crashes. I'm totally fine with returning -1.

@slime73, can you add an entry to docs/README-migration.txt for this change?

**Pull request merged**
