### PR TITLE
Tests: Use the main callback code macros

### PR DESCRIPTION
**Pull request by Lzard**
Use the new main callback code macros in the tests that use those callbacks, as discussed in #9883.

### CODE REVIEW

**Review by slouken — APPROVED** [review]

**Comment by slouken** [comment]
@icculus, nice bonus of this is that we get to remove all the comments explaining what returning a particular value means. :)

**Comment by icculus** [comment]
The macros are _so wordy_ though...!   :)

**Comment by icculus** [comment]
Docs updated in 0fe99004291f3706b3d82475b5fc1b57c267ed5c.

**Comment by slouken** [comment]
Should we remove `MAIN_CALLBACK`?

**Comment by Lzard** [comment]
Maybe use names similar to the callback functions, e.g `SDL_APP_SUCCESS`, `SDL_APP_FAILURE`, `SDL_APP_CONTINUE`?

**Comment by icculus** [comment]
> Maybe use names similar to the callback functions, e.g SDL_APP_SUCCESS, SDL_APP_FAILURE, SDL_APP_CONTINUE?

Yeah, I like that more. I'll update that.

**Comment by icculus** [comment]
Okay, shorter names are live in 3364aff75760982f202088f70f985376eae9f8fe, thanks for the suggestion!

**Comment by slouken** [comment]
I like that too. Thanks!

**Pull request merged**
