### PR TITLE
wayland: Prefer our SSD implementation if available

### PR DESCRIPTION
**Pull request by flibitijibibo**
While libdecor supports zxdg-decoration, we already have our own implementation and we know it works (and we can debug it if something goes wrong). With this in mind, I flipped the priorities for SSD/CSD: We'll try to get both xdg-shell and zxdg-decoration, but if the latter is unavailable we'll fall back to libdecor.

Tested with both GNOME and Plasma.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Quick force-push to explicitly set the xdg-shell pointer to NULL - this managed to get through because libdecor ensures nobody sees the pointer, right up until we exit...

**Comment by sezero** [comment]
What is `SDL_WAYLAND_HAVE_WAYLAND_LIBDECOR`? Only cmake added it,
but it isn't even defined in any of the SDL_config headers.  And
why do you need it along with `HAVE_LIBDECOR_H`?

**Comment by sezero** [comment]
And I take it back: `SDL_WAYLAND_HAVE_WAYLAND_LIBDECOR` isn't defined anywhere at all.
Should we remove that check?

**Comment by flibitijibibo** [comment]
That's supposed to be a check for dynamically loaded libdecor - it should be 1 when present and 0 when not, similar to this:

https://github.com/libsdl-org/SDL/blob/main/src/video/wayland/SDL_waylanddyn.c#L152

Local testing has this working for me if I arbitrarily change the dynamic file name string in the so file from libdecor-0 to libdecor-1.

**Pull request merged**
