### PR TITLE
linux: add joystick fallback for /dev/input/js[0-9]

### PR DESCRIPTION
**Pull request by rofl0r**
## Description

on systems where udev doesn't manage input devices, one can still
access the joystick via /dev/input/js0 using the old-fashioned simple
API exposed by linux/joystick.h, as demonstrated by e.g. gnuboy's
sys/linux/joy.c [0].

[0]: https://github.com/rofl0r/gnuboy/blob/master/sys/linux/joy.c

## Existing Issue(s)

#4713

### CODE REVIEW

**Comment by slouken** [comment]
What systems are you running into where js* are available, but event* are not?

**Comment by rofl0r** [comment]
i'm using my own distro sabotage linux, one of many small distros using mdev instead of udev (this move was necessary many years ago when udev was absorbed into systemd, which many users don't want to use).

**Comment by slouken** [comment]
Do you have a way to install that distro? I'd like to test the changes before accepting them.

FYI, the joystick is opened read-write in order to support rumble. What we can do is try to open read-write and then fall back to open read-only, which should handle both cases.

**Comment by rofl0r** [comment]
> Do you have a way to install that distro? I'd like to test the changes before accepting them.

it should be easy to test: just remove the permission to read from /dev/input/event*:
```
sudo chown root:root /dev/input/event*
sudo chmod 640 /dev/input/event*
sudo chmod o+r /dev/input/js0
```
, and then the code using the udev API and ioctls should fail (unless your systemd infrastructure immediately overrides the permissions...) and fall back to using the new js0 code (assuming that device exists to begin and can be read by you).

sabotage is a build-it-from-source distro, but if the above fails for you i can look into making a qemu image available to you.

> FYI, the joystick is opened read-write in order to support rumble. What we can do is try to open read-write and then fall back to open read-only, which should handle both cases.

yes, my patch here does that.

**Comment by smcv** [comment]
> using mdev instead of udev

Is mdev unable to create `/dev/input/event*` (evdev) device nodes?

evdev has been the recommended kernel API for input devices for quite a long time, with the device-type-specific interfaces (`js*`, `mouse*`, etc.) considered deprecated, so it seems wise to arrange some way for your OS distribution to use evdev.

> this move was necessary many years ago when udev was absorbed into systemd

systemd's udev can be used without using systemd as init system, and standalone udev-compatible projects like eudev also exist, so mdev is far from the only option, even if you don't want anything to do with systemd.

**Comment by rofl0r** [comment]
> device-type-specific interfaces (js*, mouse*, etc.) considered deprecated

by whom ? fact is that the old API still exists, is much simpler, and doesn't need a background daemon watching events and setting up stuff in the background, therefore a 20 year old emulator just works, while SDL2 doesn't (currently).

> systemd's udev can be used without using systemd as init system

yeah, but last time i checked you still needed libsystemd, which refuses to use portable POSIX interfaces and deliberately uses unportable GLIBC-only api, so it doesn't work with musl libc.

**Comment by rofl0r** [comment]
rebased on main.

**Comment by rofl0r** [comment]
again, rebased on main.

**Comment by slouken** [comment]
This has been implemented with a hint to control it in https://github.com/libsdl-org/SDL/commit/1c78b0800759174abe1bac01ce5b9cd788a6a372

**Comment by rofl0r** [comment]
thanks a lot for implementing this. i'm personally not quite happy with the choice to make support for the classical joystick depending on whether the user set a special environment variable, and i suspect others might feel the same, so i've made a patch here we can use to support classic joystick unconditionally so it "just werks" (TM) : https://0x0.st/-R2I.patch

**Comment by slouken** [comment]
You're welcome. The reason I added the hint was because controllers that are supported by both interfaces show up as two joysticks.

**Comment by rofl0r** [comment]
> The reason I added the hint was because controllers that are supported by both interfaces show up as two joysticks.

ah, that makes sense. i was hoping they both use same device inode so it could be detected using this, but it seems the event device has JS_INODE+1 (and identical timestamps), however the timestamp thing doesn't seem to be a reliable method, as other event nodes have identical timestamps too.

```
$ stat /dev/input/js0 
  File: /dev/input/js0
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 6h/6d   Inode: 8947454     Links: 1     Device type: d,0
Access: (0644/crw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-10-24 03:25:18.000000000
Modify: 2021-10-24 03:25:18.000000000
Change: 2021-10-24 03:25:18.000000000

$ stat /dev/input/event14
  File: /dev/input/event14
  Size: 0               Blocks: 0          IO Block: 4096   character special file
Device: 6h/6d   Inode: 8947455     Links: 1     Device type: d,4e
Access: (0640/crw-r-----)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-10-24 03:25:18.000000000
Modify: 2021-10-24 03:25:18.000000000
Change: 2021-10-24 03:25:18.000000000
```

anyway it's fine as is.

**Pull request closed without merging**
