### PR TITLE
wayland: Rewrite update_scale_factor to always use the current display scale

### PR DESCRIPTION
**Pull request by flibitijibibo**
This fixes some crashes on startup I had when in high-DPI mode - for some reason this affected one setup and not the others, which is why this wasn't caught until now.

### CODE REVIEW

**Comment by dos1** [comment]
That doesn't seem right? It should use the highest scale factor from all the outputs the window is shown on, otherwise you may get the surface scaled up (and therefore blurry) on multi-monitor setups.

**Comment by flibitijibibo** [comment]
Looked into it and I see what was wrong - the problem roots from when the driver was trying to use the placeholder VideoDisplay, which was causing memory corruption issues:

https://github.com/libsdl-org/SDL/commit/ed24c3452a99e6515faf99f155c77872f35eacd6

When this got fixed it meant there was no longer userdata, because there's nothing for the wl_output to cling onto - the result is that we never get a valid scale_factor, and the result is that new_factor always remained 0 (or 1, if you change the declaration as I did in this patch).

There's probably a way to store the scale factor from each wl_output, but until then this at least makes it so it gets at least _one_ scale rather than none. For FNA this works out because we do a window sanity check when moving across displays, so it adjusts the window correctly while SDL then readjusts the EGL surface, resulting in stable transitions (even though the second display's window will look a little weird until it's considered the active display).

**Comment by flibitijibibo** [comment]
Found something extra interesting - it seems there's a default wl_output that's used on startup and doesn't match any of the outputs we've bound! I'm working to fix this now, when ignoring the "ghost" output everything works again.

**Comment by flibitijibibo** [comment]
Patch has been updated - it mostly reverts to the original pattern, but ensures that scale_factor is always initialized to something sane. Most importantly, it does some new work to make sure that the wl_outputs thrown at us are always ones we recognize; I still don't know what the mysterious ghost output is but in testing one more time this does enough to avoid it, and from what I can tell it exclusively happens on initialization.

@dos1, this look better?

**Comment by dos1** [comment]
Better :) Although that `Wayland_check_wl_output` smells pretty bad. Could you maybe post a `WAYLAND_DEBUG=client` log from a run where you see such "ghost" output?

**Comment by flibitijibibo** [comment]
Gist because it's long... I see two wl_output ids which is a little odd, the rest makes sense to me.

https://gist.github.com/flibitijibibo/b95b0b44ed38cbb45cc8a444071fa5c2

**Comment by dos1** [comment]
This looks like the very same output represented with two different wl_output objects bound from two different wl_registries (`wl_registry@2` and `wl_registry@5`). 

My guess would be that the other one comes from libdecoration - does it happen without it? If no, then checking whether the output is known to SDL may actually make sense.

**Comment by flibitijibibo** [comment]
You're absolutely right, it was libdecor causing the fuss! This is an easy fix as a result, instead of the weird wl_output check we just have to make sure the surface is an SDL surface. Force-pushed with the proper fix!

**Comment by slouken** [comment]
Can you rebase this after the previous commit?

Thanks!

**Comment by flibitijibibo** [comment]
Rebased!

**Pull request merged**
