### PR TITLE
[SDL2][PSP] Allow to use `ShowMessageBox` without window

### PR DESCRIPTION
**Pull request by fjtrujy**
## Description
This PR allows to show message box even if there are no windows created.
In order to make this work we are now creating a temporal GU context if there is no window created.

Some other changes have been done:
- Unify constants on `src/render/psp/SDL_render_psp.h`
- Move `SDL_pspmessagebox` implementation to `SDL_pspvideo.c`
- Reduced the size of the GU list.
- Some other minor changes

The `test/testmessage.c` example works as expected now.

Screenshot 2024-08-22 at 18 10 23
Screenshot 2024-08-22 at 18 10 29
Screenshot 2024-08-22 at 18 10 35
Screenshot 2024-08-22 at 18 10 41
Screenshot 2024-08-22 at 18 10 46
Screenshot 2024-08-22 at 18 10 50
Screenshot 2024-08-22 at 18 10 55
Screenshot 2024-08-22 at 18 11 00
Screenshot 2024-08-22 at 18 11 05
Screenshot 2024-08-22 at 18 11 10

### CODE REVIEW

**Comment by fjtrujy** [comment]
Pinging @erysdren as he was original MessageBox implementation

**Comment by fjtrujy** [comment]
I have also tested it in real PSP hardware and there everything worked fine, even the wrong unicode text we can see in the previous screenshots from PPSSPP.

Cheers

**Comment by fjtrujy** [comment]
@slouken feel free to merge this PR!

**Comment by ledow** [comment]
Can this work on other platforms?  SDL2 MessageBoxes on Steam Deck (when running as a Windows executable) don't appear for me and I haven't got to the bottom of why (running with just SDL_WINDOW_SHOWN) flag on the window.

**Comment by slouken** [comment]
Have you already done similar work for SDL3?

**Pull request merged**
