### PR TITLE
SDL_Rect: SDL_FRectEquals /w epsilon

### PR DESCRIPTION
**Pull request by eloj**
This changes `SDL_FRectEquals` to compare the rects using the absolute difference vs a default epsilon, implemented in terms of `SDL_FRectEqualsEpsilon`, which takes the epsilon as an argument.

The default epsilon was pulled out of thin air as of writing, and is certainly up for discussion. I don't think it need to be as small as `FLT_EPSILON`, but let me know what you think.

I did not see any tests for FRects, but I'm open to adding some.

## Existing Issue(s)

Rationale: See #5558

### CODE REVIEW

**Comment by slouken** [comment]
This looks good to me.

**Comment by slouken** [comment]
Actually, we should probably use `FLT_EPSILON` for `SDL_FRectEquals`, and we'll probably need to define SDL_FLT_EPSILON for this purpose.

**Comment by eloj** [comment]
I changed the default epsilon to `SDL_FLT_EPSILON`, which I added as a define. If `FLT_EPSILON` is not available for this purpose, [the decimal value](https://git.musl-libc.org/cgit/musl/tree/include/float.h) for `0x0.000002p0` is directly.

**Comment by slouken** [comment]
Looks good, thanks!

**Pull request merged**
