### PR TITLE
Fixing WM_CHAR event handling for Unicode characters outside the Basic Multilingual Plane

### PR DESCRIPTION
**Pull request by hgs3**
This PR addresses an issue where SDL2 is mishandling `WM_CHAR` events for Unicode characters from Supplementary Planes. The issue is when a code point from a Supplementary Plane is entered, Windows sends two separate `WM_CHAR` messages back to back: The first message includes the UTF-16 High Surrogate and the second the UTF-16 Low Surrogate. The problem is SDL is converting both high and low surrogates individually to UTF-8 as they are received. The user is then sent two separate `SDL_TEXTINPUT` events both containing invalid UTF-8. The problem can be corrected by collecting both surrogates, performing conversion, and sending one `SDL_TEXTINPUT` with valid UTF-8.

This bug has likely gone unnoticed because most modern languages are defined in the Basic Multilingual Plane (BMP). Additionally, UTF-16 characters within the BMP are valid UTF-32 which explains why the existing implementation is working for those characters. However, there are _some_ modern non-Latin Asian, Middle-Eastern, and African scripts that fall outside the BMP, as do most emoji characters. I myself caught this bug when attempting to input emoji.

You can verify this PR addresses the issue by running the `checkkeys` test application and entering an emoji, like [Grinning Face (U+1F600)](https://www.compart.com/en/unicode/U+1F600). The current implementation, without the fix, will produce the following output (notice it's printing the high and low surrogates individually as invalid UTF-8):

```
INFO: INPUT Text (\xed\xa0\xbd): "�"
INFO: INPUT Text (\xed\xb8\x80): "�"
```

The correct output (with the fix) looks like this:

```
INFO: INPUT Text (\xf0\x9f\x98\x80): "😀"
```

### CODE REVIEW

**Review by slouken — CHANGES_REQUESTED** [review]
WIN_ConvertUTF32toUTF8() is more efficient than SDL_iconv_string() and should be used for BMP handling in WM_CHAR. Otherwise this looks good, thanks!

**Comment by hgs3** [comment]
@slouken Good idea! I've also optimized the conversion from the Supplementary Plane. I used [this algorithm from Unicode.org](https://unicode.org/faq/utf_bom.html#utf16-4). Note: They use the terminology "lead" to refer to the High Surrogate and "trail" to refer to the Low Surrogate.

**Comment by slouken** [comment]
Looks good, this can go in for 2.0.18.

Thanks!

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/SDL/commit/ccb06296b94828c86dfa2d3f0f319e97bcfbc0f1 to fix build against older SDKs.

**Pull request merged**
