### PR TITLE
Move intrinsic includes into a private header

### LINKED ISSUE #4729: inclusion of intrinsics headers in SDL_cpuinfo.h makes it impossible to use SDL2 with alternative compilers
i'd like to compile my SDL2-using projects with alternative C compilers, such as tcc or [cproc](https://github.com/michaelforney/cproc) for faster compilation speed (or to check for GNUisms) while developing, however all of them bail out failing to parse GCC's intrinsics headers which are unconditionally included.

after some discussion with fellow compiler authors and linux distribution packagers we all agreed that SDL shouldn't include the intrinsics headers from a public, but only from a private header for internal use (i.e. during compile of SDL2 itself).

alternatively, the inclusion of all of the intrinsics headers could be shielded by some preprocessor macro such as SDL_INTERNAL which is defined during the build using the build system but not in SDL's headers themselves.

### PR DESCRIPTION
**Pull request by ccawley2011**
The relevant code was relying on defines in `SDL_build_config\.h`, and having the includes in a public header causes issues when using pre-built SDL with alternative compilers.

Fixes #4729.

### CODE REVIEW

**Comment by slouken** [comment]
I think we still want to have a header in the public API that people can optionally include that does the magic they need to use intrinsics. Maybe move that to SDL_cpuintrin.h?

We've had a bunch of bugs around this, I think part of the problem is that the header allowed you to use intrinsics that weren't supported because of compiler options.

Here are some related bug: https://github.com/libsdl-org/SDL/issues/6214, https://github.com/libsdl-org/SDL/issues/4531

**Comment by slouken** [comment]
Also, either way, this PR needs an entry in WhatsNew.txt and docs/README-migration.txt

**Comment by icculus** [comment]
> I think part of the problem is that the header allowed you to use intrinsics that weren't supported because of compiler options

Specifically, we gate all sorts of intrinsic using code behind `#ifdef __SSE3__` and whatever, but Clang (and others?) don't define this until you add `-msse3` to the command line, which makes the compiler use SSE3 opcodes itself for C code it compiles, regardless of what intrinsics we might use.

I don't think there's a lot of value in SDL solving the "what *intrin.h" header do I include?" problem for the app,  and probably causes problems when _we_ are globally defining things like `__ARM_NEON` for everyone.

What we need to do, for the bugs that were mentioned, is move just our intrinsic code into separate .c files that are built with `-msse3`, etc, so that we can have SSE3-optimized code using those intrinsics available, in the event that the runtime system has SSE3 support, and not use SSE3 at all otherwise.

**Comment by madebr** [comment]
I find it hard to hard to force enabling/disabling the intrinsics through cmake.
You can configure with `-DSDL_SSE2=OFF`, but still have sse2 intrinsics if e.g. you have `-arch=x86-64-v4` in your compiler flags.

**Comment by icculus** [comment]
> but still have sse2 intrinsics if e.g. you have -march=x86-64-v4 in your compiler flags (this arch defines __SSE2__)

I mean, to be fair, if you _ask for it_, you should probably get it.  :)

**Comment by madebr** [comment]
> I mean, to be fair, if you _ask for it_, you should probably get it. :)

True. My understanding of these options was that it enables/disables hand crafted assembly routines.
Perhaps I was wrong.

**Comment by slouken** [comment]
I don't think so, they tell the compiler what architecture you're targeting and affects what SIMD instructions can be used for optimization by the compiler as well.

**Comment by slouken** [comment]
@ccawley2011, can you resolve the conflicts and add documentation in WhatsNew.txt and docs/README-migration.txt? I'd like to merge this.

**Comment by ccawley2011** [comment]
> @ccawley2011, can you resolve the conflicts and add documentation in WhatsNew.txt and docs/README-migration.txt? I'd like to merge this.

OK, done.

**Pull request merged**
