### PR TITLE
Fix and improve github CI

### PR DESCRIPTION
**Pull request by substring**
## Description
The current CI doesn't work and can be fixed. To simplify steps, use a matrix to build on various OS + allow platform specific flags.
The linux build should now cover a wider case of video backends.

## Existing Issue(s)
no issue, just all github builds are broken so far

### CODE REVIEW

**Comment by mgerhardy** [comment]
The ci is still broken - somehow the project settings must be adopted:
```
actions/checkout@v2 is not allowed to be used in libsdl-org/SDL. Actions in this workflow must be: within a repository owned by libsdl-org.
```

This is the same error as before.

**Comment by icculus** [comment]
Dumb question: we have a Buildbot which I have neglected to switch over to GitHub, but will be doing so shortly. Do we need CI set up here at all (or set up to use something other than our full-time builders?)

I'm not against dumping buildbot, but we have it and it builds for like 20 targets, some of them quite weird, already.

**Comment by icculus** [comment]
> Make github CI great again

Also: I understand that comedy is subjective...but don't do that.

**Comment by substring** [comment]
The actions here have a better visibility now you have moved to github : you get the result straight a merge request, and it runs rather fast. I'm sorry rto read it's still broken, so probably something to do with the project settings I guess, I'll investigate.

**Comment by mgerhardy** [comment]
I totally agree - it greatly helps people that are forking the project to provide pull requests to get their code compiled on all major platforms without having access to them (Of course the buildbot most likely still has even more platforms - but even IOS and Android could get added to this CI, too)

**Comment by substring** [comment]
@icculus No politics really, I'm sorry if the commit name offended someone, just an enthusiastic person who is glad to contribute the way he can, nothing more. Next commits will be more "neutral".

Now for the CI still not triggering : https://github.community/t/checkout-v2-error-actions-in-this-workflow-must-within-a-repository-owned-by-organization/136315/2

**Pull request merged**
