### PR TITLE
audio: pipewire: Load the default null sink

### PR DESCRIPTION
**Pull request by Kontrabant**
Pipewire 0.3.46 includes a module that provides a null output sink that dynamically appears if no other audio devices are present on the system, so an application will always have something available to it.  Load it if it is available.

@flibitijibibo

### CODE REVIEW

**Review by flibitijibibo — APPROVED** [review]
Makes sense to me, but will check with Ryan just in case we're supposed to do something special in this scenario...

**Comment by icculus** [comment]
I'm wondering if failing when there isn't an audio device isn't the more appropriate course of action here, verses users complaining that the game isn't making sound.

(We already have a similar "null" target in SDL, but to be clear, it has to be specifically requested, it won't fall back to it by default.)

**Comment by eloj** [comment]
I just happend to look at this code earlier today, and for what little it's worth, I agree with Ryan.

It would be weird to have pipewire behave differently from other backends, and if this behaviour was to be changed, it'd have to be via flipping the 'demand_only' boolean in the 'dummy' driver bootstrap entry.

**Comment by slouken** [comment]
Agreed. The dummy driver is for when the user or application wants to run audio but not actually get any output. Audio drivers should play sound by default.

**Pull request closed without merging**
