### PR TITLE
cmake: add SDL_INSTALL_CMAKEDIR cache variable to override location of cmake config files

### PR DESCRIPTION
**Pull request by madebr**
This option will help external projects that ship SDL2 for multiple configurations, such as the Vulkan SDK.
See https://github.com/libsdl-org/SDL/issues/6406

By installing the cmake config files for 32-bit to e.g. `Lib32/cmake` and those for 64-bit to e.g. `Lib/cmake`,
then wrapper `cmake/SDL2Config.cmake` and `cmake/SDL2ConfigVersion.cmake` scripts can be created.

**cmake/SDL2ConfigVersion.cmake**
```cmake# SDL2 CMake version configuration file:
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(sdl2_config_path "${CMAKE_CURRENT_LIST_DIR}/../Lib32/cmake/sdl2ConfigVersion.cmake")
elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(sdl2_config_path "${CMAKE_CURRENT_LIST_DIR}/../Lib/cmake/SDL2ConfigVersion.cmake")
else("${CMAKE_SIZEOF_VOID_P}" STREQUAL "")
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
    return()
endif()

if(NOT EXISTS "${sdl2_config_path}")
    message(WARNING "${sdl2_config_path} does not exist: SDL2 package is corrupted")
    set(PACKAGE_VERSION_UNSUITABLE TRUE)
    return()
endif()

include("${sdl2_config_path}")

```

**cmake/SDL2Config.cmake**
```cmake
if(CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(sdl2_config_path "${CMAKE_CURRENT_LIST_DIR}/../Lib32/cmake/Sdl2Config.cmake")
elseif(CMAKE_SIZEOF_VOID_P EQUAL 8)
    set(sdl2_config_path "${CMAKE_CURRENT_LIST_DIR}/../Lib/cmake/Sdl2Config.cmake")
else("${CMAKE_SIZEOF_VOID_P}" STREQUAL "")
    set(SDL2_FOUND FALSE)
    return()
endif()

if(NOT EXISTS "${sdl2_config_path}")
    message(WARNING "${sdl2_config_path} does not exist: SDL2 package is corrupted")
    set(SDL2_FOUND FALSE)
    return()
endif()

include("${sdl2_config_path}")
```

This is the same thing we are doing with our MinGW prebuilt packages.

### CODE REVIEW

**Comment by slouken** [comment]
Do we need to do this for the SDL satellite libraries?

**Comment by madebr** [comment]
As a gesture, we can 😄

**Comment by lunarpapillo** [comment]
So, to use this when building the **Vulkan SDK**, we'd do a 64-bit build with `-DSDL_INSTALL_CMAKEDIR=Lib/cmake` and a 32-bit build with `-DSDL_INSTALL_CMAKEDIR=Lib32/cmake`?  Or am I reading this incorrectly?

**Comment by madebr** [comment]
That's correct.

Also, if you're sharing the `include` directory between 32-bit and 64-bit SDL2, be careful with `SDL_config.h`.
Because it is generated by CMake, it might be different.
This is probably not an issue because you are generating them both in succession.

[This is how Fedora addresses this](https://src.fedoraproject.org/rpms/SDL2/blob/rawhide/f/SDL2.spec#_137).

**Pull request merged**
