### PR TITLE
Minor improvements for CPU detection on ARM

### LINKED ISSUE #4095: CPU_haveARMSIMD() for Linux
SDL_cpuinfo.c:CPU_haveARMSIMD() for Linux case has:
https://github.com/libsdl-org/SDL/blob/main/src/cpuinfo/SDL_cpuinfo.c#L378
```
        Elf32_auxv_t aux;
        while (read(fd, &aux, sizeof aux) == sizeof aux)
        {
            if (aux.a_type == AT_PLATFORM)
            {
                const char *plat = (const char *) aux.a_un.a_val;
```

Do we not need `Elf64_auxv_t aux;` for 64 bit platforms? Because
a_type and a_un.a_val are uint32_t in Elf32_auxv_t, but uint64_t in
Elf64_auxv_t.  E.g.:
```
diff --git a/src/cpuinfo/SDL_cpuinfo.c b/src/cpuinfo/SDL_cpuinfo.c
index 896b4dd..b792ae2 100644
--- a/src/cpuinfo/SDL_cpuinfo.c
+++ b/src/cpuinfo/SDL_cpuinfo.c
@@ -375,7 +375,11 @@ CPU_haveARMSIMD(void)
     fd = open("/proc/self/auxv", O_RDONLY);
     if (fd >= 0)
     {
+#ifdef _LP64
+        Elf64_auxv_t aux;
+#else
         Elf32_auxv_t aux;
+#endif
         while (read(fd, &aux, sizeof aux) == sizeof aux)
         {
             if (aux.a_type == AT_PLATFORM)
```

I don't have anything-arm to test (or compile), however did I notice
this when building SDL-1.2 for x86_64, where CPU_haveARMSIMD() is not
guarded against `__arm__` define (which may be an oversight), and got
a -Wint-to-pointer-cast warning.

### PR DESCRIPTION
**Pull request by ccawley2011**
## Description
This PR makes the following changes:
- `readProcAuxvForNeon` has been changed to use `Elf32_auxv_t`, the SIMD and SDL1 detection code. It is also only built on 32--bit ARM, since it was unused with AArch64.
- The non-ARM check is prioritized over the OpenBSD and `elf_aux_info` checks.
- SDL_HasARMSIMD is now tested in `testplatform`.

## Existing Issue(s)
Fixes #4095.

### CODE REVIEW

**Comment by sezero** [comment]
I take it that `__arm__` and `__aarch64__` are mutually exclusive?

**Comment by sezero** [comment]
> I take it that `__arm__` and `__aarch64__` are mutually exclusive?

OK, I see that they're mutually exclusive like `__i386__` and `__x86_64__`

Out of curiosity: Should we not add a case for `__aarch64__` to return true for
SIMD and NEON? (Would that add complications?)

**Comment by ccawley2011** [comment]
> Out of curiosity: Should we not add a case for `__aarch64__` to return true for
> SIMD and NEON? (Would that add complications?)

OK, done.

**Comment by sezero** [comment]
Thanks.

**Pull request merged**
