### PR TITLE
ci: bump the BSDS 

### LINKED ISSUE #10224: FreeBSD builder is busted
```
/usr/bin/ssh -t runner@cross_platform_actions_host sh -c 'cd "/home/runner/work/SDL/SDL" && exec "$SHELL" -e'
Pseudo-terminal will not be allocated because stdin is not a terminal.
Updating FreeBSD repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries: 
Newer FreeBSD version for package zziplib:
To ignore this error set IGNORE_OSVERSION=yes
- package: 1303001
- running kernel: 1302001
Ignore the mismatch and continue? [y/N]: Processing entries... done
pkg: repository FreeBSD contains packages for wrong OS version: FreeBSD:13:amd64
Unable to update repository FreeBSD
Error updating repositories!
```

### PR DESCRIPTION
**Pull request by madebr**
Kudos to @jacob-carlborg for the feedback in https://github.com/cross-platform-actions/action/discussions/90

## Existing Issue(s)
Fixes #10224

### CODE REVIEW

**Comment by slouken** [comment]
Merged, thanks!

**Comment by sezero** [comment]
SDL2 CI needs similar attention (if you haven't done so already)

**Comment by sezero** [comment]
> SDL2 CI needs similar attention (if you haven't done so already)

OK, did that myself.

**Comment by slouken** [comment]
> > SDL2 CI needs similar attention (if you haven't done so already)
> 
> OK, did that myself.

Thanks!

**Pull request merged**
