### PR TITLE
Attempt at fixing flaky FreeBSD and ps2 workflows + tests + more tests for CTest  + install SDL man pages

### PR DESCRIPTION
**Pull request by madebr**
- Attempt at fixing flaky vmactions FreeBSD workflow. https://github.com/vmactions/freebsd-vm/issues/28 suggested to increase the mem size
- Attempt at fixing flaky ps2 workflow. https://github.com/ps2dev/ps2dev/issues/67 suggests to disable parallel building
- Fix argument parsing of testsem
- Fix running torturethread on MinGW on msys2
- Add a few noninterative tests to CTest, that are now run each time on ci
- Generate and install man pages, created by `build-scripts/wikiheaders.pl`.

@slouken 
I suppose it is okay to install the man pages?
Then, developers can do `man SDL_Init` in their console.

### CODE REVIEW

**Comment by slouken** [comment]
Yes, that seems like a great idea.

**Comment by sezero** [comment]
I get the following error from main branch. This is probably because my perl
is rather old? ( perl-5.10.1 )
```console
Scanning dependencies of target SDL3_docs
[  3%] Generating SDL3 wiki markdown files
syntax error at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 819, near "$sectionsref{"
Global symbol "$sectionsref" requires explicit package name at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 820.
syntax error at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 820, near "$sectionsref{"
Global symbol "$sectionsref" requires explicit package name at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 821.
syntax error at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 821, near "$sectionsref{"
Global symbol "$sectionsref" requires explicit package name at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 822.
syntax error at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 822, near "$sectionsref{"
Global symbol "$sectionsref" requires explicit package name at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 823.
syntax error at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 823, near "$sectionsref{"
Global symbol "$sectionsref" requires explicit package name at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 824.
syntax error at /home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl line 824, near "$sectionsref{"
/home/ozzie/SDL-sezero/build-scripts/wikiheaders.pl has too many errors.
make[2]: *** [docs/wiki/SDL_Init.md] Error 255
```

**Comment by madebr** [comment]
I'm a Perl noob, so @icculus should comment on this.
A perl version from 2009 surely won't help.

I didn't limit the version range, so I'm guessing blind.
What about [requiring perl 5.22 (2015)](https://dev.perl.org/perl5/news/).

**Comment by sezero** [comment]
Hm, perl-interpreter 5.26.2 on another box works...  Some of the generated man pages look funny, though, like:
```
       This function also acts as a full memory barrier.  Note:Ifyoudon'tknowwhatthisfunctionisfor,youshouldn'tuse it!
```

**Comment by madebr** [comment]
I'm going to create an issue to track man issue(s).
I am missing some features from the `wikiheaders.pl` script.

**Pull request merged**
