### PR TITLE
Renamed SDL events for clarity

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/6877

### CODE REVIEW

**Comment by slouken** [comment]
@libsdl-org/a-team, how does this look?

**Comment by 1bsyl** [comment]
yes, great !

**Comment by icculus** [comment]
Let's do it.

**Comment by Iniquitatis** [comment]
Just to make sure: are names like `SDL_EVENT_MOUSE_BUTTONUP`, `SDL_EVENT_MOUSE_BUTTONDOWN`, `SDL_EVENT_LOCALECHANGED`, and `SDL_EVENT_TEXTEDITING_EXT` intentionally left without additional underscores? The first two are inconsistent with other `SDL_EVENT_*_BUTTON_*` names, and the latter one is inconsistent with `SDL_EVENT_TEXT_EDITING` now.

**Comment by madebr** [comment]
I will rename them to `SDL_EVENT_LOCALE_CHANGED` and `SDL_EVENT_TEXT_EDITING_EXT`.
Thank you for telling us about the oversights.

**Comment by madebr** [comment]
See https://github.com/libsdl-org/SDL/commit/69aede6c9e285718ec23a51a448143a7472d0122

**Pull request merged**
