### PR TITLE
GPU D3D12: Fix teardown and leaks on device creation failure

### LINKED ISSUE #10629: GPU: renderer memory leaks
Running `testyuv --trackmem`:
Memory allocations:
```
Allocation 0: 64 bytes
	0x7ffab37991f8: SDL_realloc_REAL+0x38 C:\projects\SDL-experimental\src\stdlib\SDL_malloc.c:5335
	0x7ffab39a21e9: D3D12_ReleaseGraphicsPipeline+0x89 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:3517
	0x7ffab399b087: D3D12_INTERNAL_ReleaseBlitPipelines+0xf7 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:3542
	0x7ffab399be72: D3D12_INTERNAL_DestroyRenderer+0x22 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:1261
	0x7ffab399c535: D3D12_DestroyDevice+0x25 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:1396
	0x7ffab369812d: SDL_DestroyGPUDevice_REAL+0x2d C:\projects\SDL-experimental\src\gpu\SDL_gpu.c:491
	0x7ffab3711568: GPU_DestroyRenderer+0x168 C:\projects\SDL-experimental\src\render\sdlgpu\SDL_render_gpu.c:1057
	0x7ffab36ceeb8: SDL_DestroyRendererWithoutFreeing+0xe8 C:\projects\SDL-experimental\src\render\SDL_render.c:5149
	0x7ffab36ce2f3: SDL_DestroyRenderer_REAL+0x53 C:\projects\SDL-experimental\src\render\SDL_render.c:5178
	0x7ffab365f945: SDL_DestroyRenderer+0x15 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:178
	0x7ff7a6df88dd: SDL_main+0x12fd C:\projects\SDL-experimental\test\testyuv.c:555
	0x7ffab38fba91: SDL_RunApp_REAL+0x241 C:\projects\SDL-experimental\src\main\windows\SDL_sysmain_runapp.c:88
	0x7ffab366a746: SDL_RunApp_DEFAULT+0x36 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ffab36603f1: SDL_RunApp+0x31 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ff7a6df8961: main+0x21 C:\projects\SDL-experimental\include\SDL3\SDL_main_impl.h:99
	0x7ff7a6e0e218: __scrt_common_main_seh+0x10c D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	0x7ffbc343dbe7: BaseThreadInitThunk+0x17 :0
	0x7ffbc4ce5a6c: RtlUserThreadStart+0x2c :0
Allocation 1: 32 bytes
	0x7ffab3799181: SDL_calloc_REAL+0x41 C:\projects\SDL-experimental\src\stdlib\SDL_malloc.c:5317
	0x7ffab39a9807: D3D12_INTERNAL_AllocateCommandBuffer+0x357 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:6582
	0x7ffab39a99c2: D3D12_INTERNAL_AcquireCommandBufferFromPool+0x22 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:66	0x7ffab39a9a67: D3D12_AcquireCommandBuffer+0x57 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:6640
	0x7ffab369987c: SDL_AcquireGPUCommandBuffer_REAL+0x3c C:\projects\SDL-experimental\src\gpu\SDL_gpu.c:1051
	0x7ffab3712026: GPU_CreateRenderer+0x5b6 C:\projects\SDL-experimental\src\render\sdlgpu\SDL_render_gpu.c:1283
	0x7ffab36c4577: SDL_CreateRendererWithProperties_REAL+0x2a7 C:\projects\SDL-experimental\src\render\SDL_render.c:1032
	0x7ffab36c42ab: SDL_CreateRenderer_REAL+0x4b C:\projects\SDL-experimental\src\render\SDL_render.c:1168
	0x7ffab365e6bf: SDL_CreateRenderer+0x1f C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:146
	0x7ff7a6df8436: SDL_main+0xe56 C:\projects\SDL-experimental\test\testyuv.c:475
	0x7ffab38fba91: SDL_RunApp_REAL+0x241 C:\projects\SDL-experimental\src\main\windows\SDL_sysmain_runapp.c:88
	0x7ffab366a746: SDL_RunApp_DEFAULT+0x36 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ffab36603f1: SDL_RunApp+0x31 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ff7a6df8961: main+0x21 C:\projects\SDL-experimental\include\SDL3\SDL_main_impl.h:99
	0x7ff7a6e0e218: __scrt_common_main_seh+0x10c D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	0x7ffbc343dbe7: BaseThreadInitThunk+0x17 :0
	0x7ffbc4ce5a6c: RtlUserThreadStart+0x2c :0
Allocation 2: 256 bytes
	0x7ffab37991f8: SDL_realloc_REAL+0x38 C:\projects\SDL-experimental\src\stdlib\SDL_malloc.c:5335
	0x7ffab399b815: D3D12_INTERNAL_ReleaseTexture+0x75 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:1073
	0x7ffab399b8de: D3D12_INTERNAL_ReleaseTextureContainer+0x5e C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:1093
	0x7ffab39a1e92: D3D12_ReleaseTexture+0x32 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:3421
	0x7ffab36995e9: SDL_ReleaseGPUTexture_REAL+0x49 C:\projects\SDL-experimental\src\gpu\SDL_gpu.c:952
	0x7ffab37113c3: GPU_DestroyTexture+0x73 C:\projects\SDL-experimental\src\render\sdlgpu\SDL_render_gpu.c:1017
	0x7ffab36d6fb6: SDL_DestroyTextureInternal+0x1d6 C:\projects\SDL-experimental\src\render\SDL_render.c:5088
	0x7ffab36ce286: SDL_DestroyTexture_REAL+0x16 C:\projects\SDL-experimental\src\render\SDL_render.c:5097
	0x7ffab365f915: SDL_DestroyTexture+0x15 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:181
	0x7ff7a6e0a9d2: SDLTest_CleanupTextDrawing+0x62 C:\projects\SDL-experimental\src\test\SDL_test_font.c:3498
	0x7ff7a6df88d0: SDL_main+0x12f0 C:\projects\SDL-experimental\test\testyuv.c:554
	0x7ffab38fba91: SDL_RunApp_REAL+0x241 C:\projects\SDL-experimental\src\main\windows\SDL_sysmain_runapp.c:88
	0x7ffab366a746: SDL_RunApp_DEFAULT+0x36 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ffab36603f1: SDL_RunApp+0x31 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ff7a6df8961: main+0x21 C:\projects\SDL-experimental\include\SDL3\SDL_main_impl.h:99
	0x7ff7a6e0e218: __scrt_common_main_seh+0x10c D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	0x7ffbc343dbe7: BaseThreadInitThunk+0x17 :0
	0x7ffbc4ce5a6c: RtlUserThreadStart+0x2c :0
Allocation 3: 32 bytes
	0x7ffab3799181: SDL_calloc_REAL+0x41 C:\projects\SDL-experimental\src\stdlib\SDL_malloc.c:5317
	0x7ffab39a9807: D3D12_INTERNAL_AllocateCommandBuffer+0x357 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:6582
	0x7ffab39a99c2: D3D12_INTERNAL_AcquireCommandBufferFromPool+0x22 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:66	0x7ffab39a9a67: D3D12_AcquireCommandBuffer+0x57 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:6640
	0x7ffab369987c: SDL_AcquireGPUCommandBuffer_REAL+0x3c C:\projects\SDL-experimental\src\gpu\SDL_gpu.c:1051
	0x7ffab371131b: GPU_RenderPresent+0x2cb C:\projects\SDL-experimental\src\render\sdlgpu\SDL_render_gpu.c:998
	0x7ffab36ce1ed: SDL_RenderPresent_REAL+0xbd C:\projects\SDL-experimental\src\render\SDL_render.c:5021
	0x7ffab365f8e5: SDL_RenderPresent+0x15 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:757
	0x7ff7a6df8887: SDL_main+0x12a7 C:\projects\SDL-experimental\test\testyuv.c:546
	0x7ffab38fba91: SDL_RunApp_REAL+0x241 C:\projects\SDL-experimental\src\main\windows\SDL_sysmain_runapp.c:88
	0x7ffab366a746: SDL_RunApp_DEFAULT+0x36 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ffab36603f1: SDL_RunApp+0x31 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ff7a6df8961: main+0x21 C:\projects\SDL-experimental\include\SDL3\SDL_main_impl.h:99
	0x7ff7a6e0e218: __scrt_common_main_seh+0x10c D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	0x7ffbc343dbe7: BaseThreadInitThunk+0x17 :0
	0x7ffbc4ce5a6c: RtlUserThreadStart+0x2c :0
Allocation 4: 256 bytes
	0x7ffab37991f8: SDL_realloc_REAL+0x38 C:\projects\SDL-experimental\src\stdlib\SDL_malloc.c:5335
	0x7ffab399b525: D3D12_INTERNAL_ReleaseBuffer+0x75 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:993
	0x7ffab399b5ee: D3D12_INTERNAL_ReleaseBufferContainer+0x5e C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:1013
	0x7ffab39a2002: D3D12_ReleaseTransferBuffer+0x32 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:3467
	0x7ffab369970c: SDL_ReleaseGPUTransferBuffer_REAL+0x4c C:\projects\SDL-experimental\src\gpu\SDL_gpu.c:994
	0x7ffab370f018: GPU_UpdateTexture+0x398 C:\projects\SDL-experimental\src\render\sdlgpu\SDL_render_gpu.c:305
	0x7ffab36c70a0: SDL_UpdateTexture_REAL+0x200 C:\projects\SDL-experimental\src\render\SDL_render.c:2096
	0x7ffab36d1ce5: SDL_UpdateTextureFromSurface+0x395 C:\projects\SDL-experimental\src\render\SDL_render.c:1576
	0x7ffab36c595d: SDL_CreateTextureFromSurface_REAL+0xa8d C:\projects\SDL-experimental\src\render\SDL_render.c:1731
	0x7ffab365e8cf: SDL_CreateTextureFromSurface+0x1f C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:156
	0x7ff7a6e09f2f: SDLTest_DrawCharacter+0x32f C:\projects\SDL-experimental\src\test\SDL_test_font.c:3233
	0x7ff7a6e0a26d: SDLTest_DrawString+0xcd C:\projects\SDL-experimental\src\test\SDL_test_font.c:3362
	0x7ff7a6df880e: SDL_main+0x122e C:\projects\SDL-experimental\test\testyuv.c:540
	0x7ffab38fba91: SDL_RunApp_REAL+0x241 C:\projects\SDL-experimental\src\main\windows\SDL_sysmain_runapp.c:88
	0x7ffab366a746: SDL_RunApp_DEFAULT+0x36 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ffab36603f1: SDL_RunApp+0x31 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ff7a6df8961: main+0x21 C:\projects\SDL-experimental\include\SDL3\SDL_main_impl.h:99
	0x7ff7a6e0e218: __scrt_common_main_seh+0x10c D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	0x7ffbc343dbe7: BaseThreadInitThunk+0x17 :0
	0x7ffbc4ce5a6c: RtlUserThreadStart+0x2c :0
Allocation 5: 64 bytes
	0x7ffab37991f8: SDL_realloc_REAL+0x38 C:\projects\SDL-experimental\src\stdlib\SDL_malloc.c:5335
	0x7ffab39a1f29: D3D12_ReleaseSampler+0x89 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:3435
	0x7ffab3699649: SDL_ReleaseGPUSampler_REAL+0x49 C:\projects\SDL-experimental\src\gpu\SDL_gpu.c:966
	0x7ffab37114d8: GPU_DestroyRenderer+0xd8 C:\projects\SDL-experimental\src\render\sdlgpu\SDL_render_gpu.c:1041
	0x7ffab36ceeb8: SDL_DestroyRendererWithoutFreeing+0xe8 C:\projects\SDL-experimental\src\render\SDL_render.c:5149
	0x7ffab36ce2f3: SDL_DestroyRenderer_REAL+0x53 C:\projects\SDL-experimental\src\render\SDL_render.c:5178
	0x7ffab365f945: SDL_DestroyRenderer+0x15 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:178
	0x7ff7a6df88dd: SDL_main+0x12fd C:\projects\SDL-experimental\test\testyuv.c:555
	0x7ffab38fba91: SDL_RunApp_REAL+0x241 C:\projects\SDL-experimental\src\main\windows\SDL_sysmain_runapp.c:88
	0x7ffab366a746: SDL_RunApp_DEFAULT+0x36 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ffab36603f1: SDL_RunApp+0x31 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ff7a6df8961: main+0x21 C:\projects\SDL-experimental\include\SDL3\SDL_main_impl.h:99
	0x7ff7a6e0e218: __scrt_common_main_seh+0x10c D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	0x7ffbc343dbe7: BaseThreadInitThunk+0x17 :0
	0x7ffbc4ce5a6c: RtlUserThreadStart+0x2c :0
Allocation 6: 32 bytes
	0x7ffab3799181: SDL_calloc_REAL+0x41 C:\projects\SDL-experimental\src\stdlib\SDL_malloc.c:5317
	0x7ffab39ad0a5: D3D12_CreateDevice+0xea5 C:\projects\SDL-experimental\src\gpu\d3d12\SDL_gpu_d3d12.c:8146
	0x7ffab3698085: SDL_CreateGPUDeviceWithProperties_REAL+0x205 C:\projects\SDL-experimental\src\gpu\SDL_gpu.c:474
	0x7ffab3711bbf: GPU_CreateRenderer+0x14f C:\projects\SDL-experimental\src\render\sdlgpu\SDL_render_gpu.c:1207
	0x7ffab36c4577: SDL_CreateRendererWithProperties_REAL+0x2a7 C:\projects\SDL-experimental\src\render\SDL_render.c:1032
	0x7ffab36c42ab: SDL_CreateRenderer_REAL+0x4b C:\projects\SDL-experimental\src\render\SDL_render.c:1168
	0x7ffab365e6bf: SDL_CreateRenderer+0x1f C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:146
	0x7ff7a6df8436: SDL_main+0xe56 C:\projects\SDL-experimental\test\testyuv.c:475
	0x7ffab38fba91: SDL_RunApp_REAL+0x241 C:\projects\SDL-experimental\src\main\windows\SDL_sysmain_runapp.c:88
	0x7ffab366a746: SDL_RunApp_DEFAULT+0x36 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ffab36603f1: SDL_RunApp+0x31 C:\projects\SDL-experimental\src\dynapi\SDL_dynapi_procs.h:781
	0x7ff7a6df8961: main+0x21 C:\projects\SDL-experimental\include\SDL3\SDL_main_impl.h:99
	0x7ff7a6e0e218: __scrt_common_main_seh+0x10c D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
	0x7ffbc343dbe7: BaseThreadInitThunk+0x17 :0
	0x7ffbc4ce5a6c: RtlUserThreadStart+0x2c :0
Total: 0.72 Kb in 7 allocations
```

### PR DESCRIPTION
**Pull request by thatcosmonaut**
Resolves #10629 

Let's see if this fixes CI...

### CODE REVIEW

**Comment by icculus** [comment]
Please hold while we give you write access.

**Comment by thatcosmonaut** [comment]
Will push to main from now on 👍

**Comment by slouken** [comment]
> Please hold while we give you write access.

Already done. :)

**Comment by slouken** [comment]
Please don't add branches to the public repo. Instead fork SDL and make pull requests from there. Thanks!

**Comment by icculus** [comment]
I just went over the unofficial PR policy with the crew, which is "just push things if they aren't controversial or you're the expert on the topic, otherwise PRs are for discussion and feedback."

**Comment by slouken** [comment]
I'm going to squash and merge, and then delete this branch, and you can continue any other iteration from your fork.

**Pull request merged**
