### PR TITLE
Clean up any renderer in SDL_DestroyWindowSurface()

### PR DESCRIPTION
**Pull request by slouken**
Also added an automated test to verify window surface functionality.

Fixes https://github.com/libsdl-org/SDL/issues/10133

### CODE REVIEW

**Comment by slouken** [comment]
@madebr, the GitHub action says CI tests are failing, but I'm not seeing the failures in the logs. Do you know what's happening here?

**Comment by madebr** [comment]
> @madebr, the GitHub action says CI tests are failing, but I'm not seeing the failures in the logs. Do you know what's happening here?

https://github.com/libsdl-org/SDL/actions/runs/9723303509/job/26838263556?pr=10145#step:6:46023

GitHub logging is out of sync when printing from 2 or more processes are involved.

**Comment by madebr** [comment]
I opened the minidump, and it has the following backtrace [at this location](https://github.com/slouken/SDL/blob/9eecc2e6362d204c64ae4fbc098361eb0a354e2e/src/render/direct3d12/SDL_render_d3d12.c#L967).

Wondering, the tests are run with `SDL_RENDER_DRIVER=dummy`. Should it be at this location at all?

```
[External Code]
SDL3.dll!D3D12_CreateDeviceResources(SDL_Renderer * renderer) Line 967
	at D:\a\SDL\SDL\src\render\direct3d12\SDL_render_d3d12.c(967)
SDL3.dll!D3D12_CreateRenderer(SDL_Renderer * renderer, SDL_Window * window, unsigned int create_props) Line 3298
	at D:\a\SDL\SDL\src\render\direct3d12\SDL_render_d3d12.c(3298)
SDL3.dll!SDL_CreateRendererWithProperties_REAL(unsigned int props) Line 1014
	at D:\a\SDL\SDL\src\render\SDL_render.c(1014)
SDL3.dll!SDL_CreateRenderer_REAL(SDL_Window * window, const char * name) Line 1151
	at D:\a\SDL\SDL\src\render\SDL_render.c(1151)
testautomation.exe!video_getWindowSurface(void * arg) Line 2280
	at D:\a\SDL\SDL\test\testautomation_video.c(2280)
testautomation.exe!SDLTest_RunTest(SDLTest_TestSuiteReference * testSuite, const SDLTest_TestCaseReference * testCase, unsigned __int64 execKey, int forceTestRun) Line 270
	at D:\a\SDL\SDL\src\test\SDL_test_harness.c(270)
testautomation.exe!SDLTest_RunSuites(SDLTest_TestSuiteReference * * testSuites, const char * userRunSeed, unsigned __int64 userExecKey, const char * filter, int testIterations) Line 590
	at D:\a\SDL\SDL\src\test\SDL_test_harness.c(590)
testautomation.exe!SDL_main(int argc, char * * argv) Line 159
	at D:\a\SDL\SDL\test\testautomation.c(159)
SDL3.dll!SDL_RunApp_REAL(int _argc, char * * _argv, int(*)(int, char * *) mainFunction, void * reserved) Line 456
	at D:\a\SDL\SDL\src\core\windows\SDL_windows.c(456)
[External Code]
```


with following local variables:

<details>

<summary>Local variables</summary>

  | Name | Value | Type
-- | -- | -- | --
  | createDebug | 0 | int
  | CreateDXGIFactoryFunc | Variable is optimized away and not available. |  
  | CreateEventExFunc | 0x00007ff9794e3a70 {kernel32.dll!CreateEventExW} | void *(*)(_SECURITY_ATTRIBUTES *, const wchar_t *, unsigned long, unsigned long)
  | creationFlags | Variable is optimized away and not available. |  
  | D3D12CreateDeviceFunc | 0x00007ff943365cf0 {D3D12.dll!D3D12CreateDevice(void)} | HRESULT(*)(IUnknown *, D3D_FEATURE_LEVEL, const _GUID * const, void * *)
  | D3D12GetDebugInterfaceFunc | Variable is optimized away and not available. |  
◢ | d3dDevice | 0x0000000000000000 <NULL> | ID3D12Device *
  | lpVtbl | <Unable to read memory> |  
◢ | data | 0x000001efb23769f0 {hDXGIMod=dxgi.dll!0x00007ff976740000 hD3D12Mod=D3D12.dll!0x00007ff943360000 dxgiFactory=...} | D3D12_RenderData *
  | hDXGIMod | dxgi.dll!0x00007ff976740000 (Type information missing from symbol file) | void *
  | hD3D12Mod | D3D12.dll!0x00007ff943360000 | void *
  | ▶ dxgiFactory | 0x000001efb22feed0 <No type information available in symbol file for dxgi.dll> | IDXGIFactory6 *
  | ▶ dxgiAdapter | 0x000001efb22ffeb0 <No type information available in symbol file for dxgi.dll> | IDXGIAdapter4 *
  | ▶ dxgiDebug | 0x0000000000000000 <NULL> | IDXGIDebug *
  | ▶ swapChain | 0x0000000000000000 <NULL> | IDXGISwapChain4 *
  | ▶ d3dDevice | 0x0000000000000000 <NULL> | ID3D12Device1 *
  | ▶ debugInterface | 0x0000000000000000 <NULL> | ID3D12Debug *
  | ▶ commandQueue | 0x0000000000000000 <NULL> | ID3D12CommandQueue *
  | ▶ commandList | 0x0000000000000000 <NULL> | ID3D12GraphicsCommandList2 *
  | swapEffect | DXGI_SWAP_EFFECT_DISCARD (0) | DXGI_SWAP_EFFECT
  | swapFlags | 0 | unsigned int
  | syncInterval | 0 | unsigned int
  | presentFlags | 512 | unsigned int
  | renderTargetFormat | DXGI_FORMAT_UNKNOWN (0) | DXGI_FORMAT
  | pixelSizeChanged | 0 | int
  | ▶ rtvDescriptorHeap | 0x0000000000000000 <NULL> | ID3D12DescriptorHeap *
  | rtvDescriptorSize | 0 | unsigned int
  | ▶ textureRTVDescriptorHeap | 0x0000000000000000 <NULL> | ID3D12DescriptorHeap *
  | ▶ srvDescriptorHeap | 0x0000000000000000 <NULL> | ID3D12DescriptorHeap *
  | srvDescriptorSize | 0 | unsigned int
  | ▶ samplerDescriptorHeap | 0x0000000000000000 <NULL> | ID3D12DescriptorHeap *
  | samplerDescriptorSize | 0 | unsigned int
  | ▶ commandAllocators | 0x000001efb2376a90 {0x0000000000000000 <NULL>, 0x0000000000000000 <NULL>} | ID3D12CommandAllocator *[2]
  | ▶ renderTargets | 0x000001efb2376aa0 {0x0000000000000000 <NULL>, 0x0000000000000000 <NULL>} | ID3D12Resource *[2]
  | fenceValue | 0 | unsigned __int64
  | currentBackBufferIndex | 0 | int
  | ▶ fence | 0x0000000000000000 <NULL> | ID3D12Fence *
  | fenceEvent | 0x0000000000000000 | void *
  | ▶ rootSignatures | 0x000001efb2376ad0 {0x0000000000000000 <NULL>, 0x0000000000000000 <NULL>, 0x0000000000000000 <NULL>} | ID3D12RootSignature *[3]
  | pipelineStateCount | 0 | int
  | ▶ pipelineStates | 0x0000000000000000 <NULL> | D3D12_PipelineState *
  | ▶ currentPipelineState | 0x0000000000000000 <NULL> | D3D12_PipelineState *
  | ▶ vertexBuffers | 0x000001efb2376b00 {{resource=0x0000000000000000 <NULL> view={BufferLocation=0 SizeInBytes=0 StrideInBytes=...} ...}, ...} | D3D12_VertexBuffer[256]
  | ▶ nearestPixelSampler | {ptr=0 } | D3D12_CPU_DESCRIPTOR_HANDLE
  | ▶ linearSampler | {ptr=0 } | D3D12_CPU_DESCRIPTOR_HANDLE
  | ▶ uploadBuffers | 0x000001efb2378b10 {0x0000000000000000 <NULL>, 0x0000000000000000 <NULL>, 0x0000000000000000 <NULL>, ...} | ID3D12Resource *[32]
  | currentUploadBuffer | 0 | int
  | ▶ srvPoolHead | 0x0000000000000000 <NULL> | D3D12_SRVPoolNode *
  | ▶ srvPoolNodes | 0x000001efb2378c20 {{index=0 next=0x0000000000000000 }, {index=0 next=0x0000000000000000 }, {index=0 ...}, ...} | D3D12_SRVPoolNode[16384]
  | ▶ vertexShaderConstantsData | {model={v={_11=0.00000000 _12=0.00000000 _13=0.00000000 ...} m=0x000001efb23b8c20 {0x000001efb23b8c20 {...}, ...} } ...} | VertexShaderConstants
  | rotation | DXGI_MODE_ROTATION_UNSPECIFIED (0) | DXGI_MODE_ROTATION
  | ▶ textureRenderTarget | 0x0000000000000000 <NULL> | D3D12_TextureData *
  | ▶ currentRenderTargetView | {ptr=0 } | D3D12_CPU_DESCRIPTOR_HANDLE
  | ▶ currentShaderResource | {ptr=0 } | D3D12_CPU_DESCRIPTOR_HANDLE
  | ▶ currentSampler | {ptr=0 } | D3D12_CPU_DESCRIPTOR_HANDLE
  | cliprectDirty | 1 | int
  | currentCliprectEnabled | 0 | int
  | ▶ currentCliprect | {x=0 y=0 w=0 ...} | SDL_Rect
  | ▶ currentViewport | {x=0 y=0 w=0 ...} | SDL_Rect
  | currentViewportRotation | 0 | int
  | viewportDirty | 1 | int
  | ▶ identity | {v={_11=1.00000000 _12=0.00000000 _13=0.00000000 ...} m=0x000001efb23b8cf8 {0x000001efb23b8cf8 {1.00000000, ...}, ...} } | Float4X4
  | currentVertexBuffer | 0 | int
  | issueBatch | 0 | int
◢ | defaultBlendModes | 0x00000026b0b4f600 {0} | const unsigned int[1]
  | [0] | 0 | const unsigned int
◢ | defaultRTVFormats | 0x00000026b0b4f604 {DXGI_FORMAT_UNKNOWN (0)} | const DXGI_FORMAT[1]
  | [0] | DXGI_FORMAT_UNKNOWN (0) | const DXGI_FORMAT
◢ | descriptorHeapDesc | {Type=D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV (0) NumDescriptors=0 Flags=40 ...} | D3D12_DESCRIPTOR_HEAP_DESC
  | Type | D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV (0) | D3D12_DESCRIPTOR_HEAP_TYPE
  | NumDescriptors | 0 | unsigned int
  | Flags | 40 | D3D12_DESCRIPTOR_HEAP_FLAGS
  | NodeMask | 0 | unsigned int
  | DXGIGetDebugInterfaceFunc | Variable is optimized away and not available. |  
◢ | dxgiInfoQueue | 0x000001efb2304df0 {lpVtbl=0x000001efb2304bd0 {QueryInterface=0x646e65722e4c4453 AddRef=0x7865742e72657265 ...} } | IDXGIInfoQueue *
  | ▶ lpVtbl | 0x000001efb2304bd0 {QueryInterface=0x646e65722e4c4453 AddRef=0x7865742e72657265 Release=0x726f665f65727574 ...} | IDXGIInfoQueueVtbl *
◢ | filter | {AllowList={NumCategories=2989470256 pCategoryList=0x000001efb2304e40 {776750163} NumSeverities=156 ...} ...} | D3D12_INFO_QUEUE_FILTER
  | ▶ AllowList | {NumCategories=2989470256 pCategoryList=0x000001efb2304e40 {776750163} NumSeverities=156 ...} | D3D12_INFO_QUEUE_FILTER_DESC
  | ▶ DenyList | {NumCategories=0 pCategoryList=0x0000000000000000 {???} NumSeverities=0 ...} | D3D12_INFO_QUEUE_FILTER_DESC
  | i | Variable is optimized away and not available. |  
  | infoQueue | Variable is optimized away and not available. |  
  | j | Variable is optimized away and not available. |  
  | k | Variable is optimized away and not available. |  
  | kernel32 | Variable is optimized away and not available. |  
  | l | Variable is optimized away and not available. |  
  | props | Variable is optimized away and not available. |  
◢ | queueDesc | {Type=154 Priority=0 Flags=-1305475744 ...} | D3D12_COMMAND_QUEUE_DESC
  | Type | 154 | D3D12_COMMAND_LIST_TYPE
  | Priority | 0 | int
  | Flags | -1305475744 | D3D12_COMMAND_QUEUE_FLAGS
  | NodeMask | 495 | unsigned int
▶ | renderer | 0x000001efb22fa4d0 {WindowEvent=0x00007ff9433fda30 {SDL3.dll!D3D12_WindowEvent(SDL_Renderer *, const SDL_WindowEvent *)} ...} | SDL_Renderer *
  | result | S_OK | HRESULT
◢ | rootDescriptorHeaps | 0x00000026b0b4f630 {0x0000000000000000 <NULL>, 0x0000000000000002 {lpVtbl=??? }} | ID3D12DescriptorHeap *[2]
  | ▶ [0] | 0x0000000000000000 <NULL> | ID3D12DescriptorHeap *
  | ▶ [1] | 0x0000000000000002 {lpVtbl=??? } | ID3D12DescriptorHeap *
  | rootSigData | Variable is optimized away and not available. |  
◢ | samplerDesc | {Filter=-1305497040 AddressU=495 AddressV=1127819350 ...} | D3D12_SAMPLER_DESC
  | Filter | -1305497040 | D3D12_FILTER
  | AddressU | 495 | D3D12_TEXTURE_ADDRESS_MODE
  | AddressV | 1127819350 | D3D12_TEXTURE_ADDRESS_MODE
  | AddressW | 32761 | D3D12_TEXTURE_ADDRESS_MODE
  | MipLODBias | -1.02458557e-08 | float
  | MaxAnisotropy | 495 | unsigned int
  | ComparisonFunc | 1129017327 | D3D12_COMPARISON_FUNC
  | ◢ BorderColor | 0x00000026b0b4f6cc {4.591e-41#DEN, 0.00000000, 0.00000000, 0.00000000} | float[4]
  | [0] | 4.591e-41#DEN | float
  | [1] | 0.00000000 | float
  | [2] | 0.00000000 | float
  | [3] | 0.00000000 | float
  | MinLOD | 0.00000000 | float
  | MaxLOD | 2.803e-45#DEN | float
  | severities | Variable is optimized away and not available. |  


</details>

**Comment by slouken** [comment]
> I opened the minidump, and it has the following backtrace [at this location](https://github.com/slouken/SDL/blob/9eecc2e6362d204c64ae4fbc098361eb0a354e2e/src/render/direct3d12/SDL_render_d3d12.c#L967).
> 
> Wondering, the tests are run with `SDL_RENDER_DRIVER=dummy`. Should it be at this location at all?

This came up as another bug in https://github.com/libsdl-org/SDL/issues/10061. My answer was the render driver doesn't affect window surface, but now I'm thinking it should. I'll go ahead and make that change.

**Comment by slouken** [comment]
Also, thank you for setting up crash uploads for CI!

**Pull request merged**
