### PR TITLE
2.0.22 backports

### PR DESCRIPTION
**Pull request by sezero**
A handful of backports to 2.0.22 branch

### CODE REVIEW

**Comment by slouken** [comment]
I would prefer if only critical and well tested regression fixes go in, so distribution maintainers and developers can use it as a source for interim updates if necessary. We won't do it this time, but the idea is when we're comfortable we can peel off a .1 interim release that people can update to if they want.

People who want new functionality or non-regression bug fixes can pull off of main with all the usual caveats.

**Comment by slouken** [comment]
Please always use a PR like this for merging into a stable release branch. Thanks!

**Comment by sezero** [comment]
Sure, that's why I made a PR.

Waiting for it to be reviewed.

**Comment by slouken** [comment]
The only change I would pull right now is:
[fd75065](https://github.com/libsdl-org/SDL/pull/5690/commits/fd750656ff257697dbe996a6a627ffe1dd90ad57)

The mouse warp and capture fixes should get more testing, but if they look good, they can be pulled in as well.

Everything else can wait until the next release, IMHO.

**Comment by icculus** [comment]
Not to nitpick, but very few of these need to go in a 2.22.1 release, when 2.24.0 is coming in ~67 days.

The autocapture fixes might be nice, and the upcoming fix for #5593 that I'm working on would make sense...things where it regressed from the previous release and we want to fix it quickly instead of waiting three or so months.

But I'm not _opposed_ to any of these on a first attempt, as we're still figuring out how to do .1 releases.

**Comment by icculus** [comment]
> Everything else can wait until the next release, IMHO.

I'm actually just a small perl script that just waits to submit comments until seconds after Sam said the same thing, lol.

**Comment by slouken** [comment]
> But I'm not _opposed_ to any of these on a first attempt, as we're still figuring out how to do .1 releases.

For stable release branches I'd much rather start conservative and relax it if that makes sense once we get comfortable with the new release cadence.

**Comment by slouken** [comment]
@smcv can weigh in here with what he'd like to see included in Debian point releases as well.

**Comment by smcv** [comment]
> For stable release branches I'd much rather start conservative and relax it if that makes sense once we get comfortable with the new release cadence.

Yes, this. The main things I'd want to see in `.1` releases are:

* security fixes
* targeted fixes for user-visible regressions, like the regressions in recent releases that led to me asking for the versioning scheme to change :-)

... the sort of thing that downstream distributions would be inclined to patch in themselves, if they didn't get the fixes via a point release.

**Comment by sezero** [comment]
OK, pulled that MFI crash fix into mainstream 2.0.22,

Closing this and keeping the rest for myself for now.

**Comment by smcv** [comment]
> @smcv can weigh in here with what he'd like to see included in Debian point releases as well.

I'm unlikely to be able to use SDL micro releases in a Debian stable point release in any case, because the lifetime of a Debian stable release is 3 years, and the lifetime of a SDL "feature release" is more like 3 months; so by the end of a release cycle, I'm deep into retrocomputing territory regardless of what upstream does.

My interest in this from a Debian point of view is that I've often had to pull post-release regression fixes into Debian's *development* branch (which is basically a rolling release, at least when we're not in freeze), and ideally I'd like *those* fixes to be the sort of thing that gets into 2.24.1 (or even 2.0.22.1 if you're doing that) rather than something that downstream distributors are expected to know that they should backport. Things like:

* #5187
* 67c4b99 (maybe)
* #5056
* #5064
* cec5a12
* #4638

(and that's about 1 year of backported fixes). Faster-release-cycle distributions, like Arch and Fedora, are likely to want the same sort of thing. The key thing for backported fixes like these is that they're narrowly-scoped, fix a real-world problem, and are unlikely to cause further regressions.

The changes that are in `2.0.22` already all look like the sort of size I had in mind.

#5692 is an example of something that I probably *wouldn't* backport, because it's just not important enough (deliberately picking on one of my own commits as not-for-backport here).

**Comment by smcv** [comment]
> The mouse warp and capture fixes should get more testing, but if they look good, they can be pulled in as well.

Given the issues we've had recently with well-intentioned mouse-warping changes making other games regress, this seems like the sort of thing that should maybe go out in a 2.23.x development/preview release (now that we have a version scheme that makes those possible!) before it gets backported into a stable release (now that we have a version scheme that makes *those* possible).

**Comment by slouken** [comment]
Also, the preview releases should be tagged in git, but should _not_ get signed packages and binary releases, instead they should be built by people who want to try out newer code without going all the way to the main repo.

Actually, come to think of it, who is the audience that would use those preview releases?

**Comment by sezero** [comment]
> Also, the preview releases should be tagged in git, but should _not_ get signed packages and binary releases, instead they should be built by people who want to try out newer code without going all the way to the main repo.
> 
> Actually, come to think of it, who is the audience that would use those preview releases?

Preview releases (such as 2.24.0-rc1 or something, am I reading you correctly?) may
not find much users.

However, backport branches after a stable release (e.g. 2.0.22 branch, 
or 2.24.0 branch when it happens) do may find users: not necessarily
distros but some games bundling their copy of SDL.

**Comment by smcv** [comment]
It depends how you want to use the 2.odd.z preview releases, really.

If you're using them as alphas: hello, it's me, I am the audience :-) Or, to be more precise, downstream packagers like me who have access to a distribution area that is not used by unsuspecting end-users, like Debian `experimental` and maybe Arch's `testing` (as opposed to Debian `unstable` and the main Arch release, which are rolling releases which *are* used by end users). I'm not going to package every commit (and when I'm not concentrating on SDL, I *can't* package every commit), so tagging alpha/beta releases is a good marker for "if you're ready to test something, this is a good version to try".

If you're using them as release candidates, in the same spirit as https://discourse.libsdl.org/t/sdl-2-0-22-prerelease/35306, then I think it's worth doing a source tarball and maybe a subset of binary builds, partly to get wider testing and partly to prove that it can be done (so that when it gets to release time, you don't suddenly discover that it can no longer be compiled for iPhone or whatever). The more of this gets exercised regularly by CI, the less necessary the "prove that it can be done" aspect is.

Of course, there's nothing to stop you from having some alpha releases that don't have any artifacts beyond the git tag, and then starting to publish more artifacts as the development branch gets closer to release.

**Pull request closed without merging**
