### PR TITLE
Use a tagged version of OpenWatcom in CI builds

### PR DESCRIPTION
**Pull request by ccawley2011**
This should fix the current CI failures for now.

### CODE REVIEW

**Comment by madebr** [comment]
I hope to have fixed the setup-watcom action asap.

**Comment by sezero** [comment]
https://github.com/open-watcom/setup-watcom is getting commits.

@jmalak said that we keep using open-watcom/setup-watcom@v0 and
he will replace in all releases .tar.gz files by .tar.xz - don't
know what that means but not what I was expecting.
https://github.com/open-watcom/open-watcom-v2/commit/f73936da03d811ad162853fd4eeb8b07e0426732

**Comment by madebr** [comment]
The v0 api won't change (=no new inputs/outputs).
I guess he means that it will now only download .tar.xz archives, and not try .tar.gz.
Which means the fix introduced in this pr might now work anymore as "2022-05-01-Build" is a .tar.gz, not a .tar.xz.

The setup-watcom action could of course try downloading both .tar.gz and .tar.xz to facilitate the transition.
But I'm not a true javascript dev, and I *think neither is jmalak.

**Comment by jmalak** [comment]
The main issue is with tar on windows and xz compression format.
I can modify it to use both gz and xz compression formats, but first tar and xz issue must be fixed.

**Comment by jmalak** [comment]
It is fixed now, you can use both tar.gz and tar.xz formats.

**Comment by sezero** [comment]
Thank you.

**Pull request merged**
