### PR TITLE
Added SDL_StartTextInputWithProperties()

### PR DESCRIPTION
**Pull request by slouken**
This allows you to customize the text input so you can have numeric text entry, hidden passwords, etc.
    
Fixes https://github.com/libsdl-org/SDL/issues/7101
Fixes https://github.com/libsdl-org/SDL/issues/7965
Fixes https://github.com/libsdl-org/SDL/issues/9439

### CODE REVIEW

**Comment by icculus** [comment]
What happens if the app specifies multiple types (number and email, etc)?

**Comment by slouken** [comment]
> What happens if the app specifies multiple types (number and email, etc)?

Funny you should ask that... the behavior is technically undefined, but I just pushed a change so it's consistent across platforms. Basically there's a priority from most secure to least secure.

**Comment by slouken** [comment]
The other thing we could do is make that enumeration public. I was thinking that boolean properties would be more flexible (e.g. it's a number and it's a password), but maybe a fixed enumeration that we add to over time is better?

**Comment by icculus** [comment]
The docs say you have to hide password text yourself, which would certainly be true if rendering your own text, but assuming the OS is always handling this for the actual virtual keyboard text field, this note is confusing and should be removed.

Otherwise, API looks solid. I'm excited to try this out!

**Comment by slouken** [comment]
> The docs say you have to hide password text yourself, which would certainly be true if rendering your own text, but assuming the OS is always handling this for the actual virtual keyboard text field, this note is confusing and should be removed.

Fixed!

> Otherwise, API looks solid. I'm excited to try this out!

Thanks! :)

**Pull request merged**
