### PR TITLE
autotools, cmake, macOS: Do not use the system iconv() by default

### PR DESCRIPTION
**Pull request by sezero**
backport from PR #9676 by @flibitijibibo

Maybe cherry pick to 2.30.x too (or maybe not)

### CODE REVIEW

**Comment by sezero** [comment]
Autotools is fine. But cmake seems to insist on finding and linking to system iconv, according to CI logs. What did I miss? @flibitijibibo, @madebr ?

**Comment by flibitijibibo** [comment]
Does it have to be `MACOS` instead of `MACOSX`? Wasn't sure if that was something we defined, and I notice that the only other place that uses that in CMakeLists checks it at the same time as `DARWIN` so I wonder if it even gets looked at...

**Comment by sezero** [comment]
As I recall, it used to be MACOSX in SDL2, renamed to MACOS in SDL3..

**Comment by flibitijibibo** [comment]
I guess it could be ending up in the `DARWIN` path? Seems unlikely but who knows:

https://github.com/libsdl-org/SDL/blob/SDL2/cmake/sdlplatform.cmake#L35-L38

**Comment by sezero** [comment]
> I guess it could be ending up in the `DARWIN` path? Seems unlikely but who knows:
> 
> https://github.com/libsdl-org/SDL/blob/SDL2/cmake/sdlplatform.cmake#L35-L38

Ugh, that's an SDL2-SDL3 difference I missed, so yes I think so. Force-pushed, let's see how it goes.

**Comment by sezero** [comment]
.. and yes, it seems to work now according to cmake's end report. This is ready now.

**Review by slouken — APPROVED** [review]

**Review by flibitijibibo — APPROVED** [review]

**Comment by sezero** [comment]
Patch is pulled into SDL2. 

If you want to cherry-pick into 2.30.x, I leave that to you guys.

**Comment by slouken** [comment]
Cherry-picked, thanks!

**Pull request merged**
