### PR TITLE
Fixed bug #7614: Segmentation Fault in SDL_BlitSurface

### PR DESCRIPTION
**Pull request by 1bsyl**
Fixed bug #7614: Segmentation Fault in SDL_BlitSurface
Update SDL_BlitSurface to use Intersect functions

### CODE REVIEW

**Comment by 1bsyl** [comment]
@slouken @icculus 
head, is still crashing with the following case:


```
#include <SDL3/SDL.h>
#include <stdio.h>

int main(void)
{
    SDL_Init(SDL_INIT_VIDEO);
    SDL_Window *window = SDL_CreateWindow("Test", 385, 166, 0);
    SDL_Surface *surface = SDL_CreateSurface(100, 100, SDL_PIXELFORMAT_RGBA32);
    SDL_Surface *window_surface = SDL_GetWindowSurface(window);
    SDL_Rect dst_rect;
    dst_rect.x = 384;
    dst_rect.y = -2147483583;
    dst_rect.w = 100;
    dst_rect.h = 100;
    SDL_BlitSurface(surface, NULL, window_surface, &dst_rect);
    return 0;
}

```

**Comment by icculus** [comment]
> head, is still crashing with the following case

I assume this is the thing I was saying about SDL_IntersectRect being buggy for negative coordinates, here:

https://github.com/libsdl-org/SDL/issues/8301#issuecomment-1834072649

**Comment by slouken** [comment]
I merged the simpler fix in https://github.com/libsdl-org/SDL/pull/8682, but I'll leave this open for consideration for SDL 3.x

**Comment by slouken** [comment]
There were additional 64-bit conversion warnings in the code, and as I started to fix them, I realized I was reimplementing rect intersection. :)

**Comment by 1bsyl** [comment]
I also seeing other overflows, 
and asan is seems to be a good tool to detect them.

here's a fuzzing testcase [main_bug_7614_clip_overflow_RANDOM.c.txt](https://github.com/libsdl-org/SDL/files/13993217/main_bug_7614_clip_overflow_RANDOM.c.txt)

```
/src/video/SDL_rect_impl.h:90:10: runtime error: signed integer overflow: 2147483647 + 300 cannot be represented in type 'int'
/src/video/SDL_rect_impl.h:100:22: runtime error: signed integer overflow: -2147483349 - 2147483647 cannot be represented in type 'int'
/src/video/SDL_rect_impl.h:104:10: runtime error: signed integer overflow: 2147483647 + 2147483647 cannot be represented in type 'int'
/src/video/SDL_rect_impl.h:114:22: runtime error: signed integer overflow: -2 - 2147483647 cannot be represented in type 'int'
/src/video/SDL_blit.c:74:43: runtime error: signed integer overflow: 2147483647 * 4 cannot be represented in type 'int'
/src/video/SDL_blit.c:82:43: runtime error: signed integer overflow: 2147483647 * 4 cannot be represented in type 'int'
/src/video/SDL_blit_A.c:603:9: runtime error: signed integer overflow: 2147483647 + 3 cannot be represented in type 'int'
```

I haven't fixed that currently, maybe next week

**Comment by slouken** [comment]
Can you create a new issue for those?

**Comment by 1bsyl** [comment]
I haven't fixed that currently, maybe next week

**Pull request merged**
