### PR TITLE
cmake: use pkg-config + test compile instead of Find module for detecting rpi

### LINKED ISSUE #8050: Raspberry Pi build broken?
I'm trying to build on Raspberry Pi, and it's not finding headers I would expect.

For example, I'm trying to build with libusb:
```
/usr/bin/cc   -D_GNU_SOURCE=1 -o CMakeFiles/cmTC_3cf20.dir/CheckIncludeFile.c.o -c /home/saml/projects/SDL/build-rpi/CMakeFiles/CMakeScratch/TryCompile-Y2whUE/CheckIncludeFile.c
/home/saml/projects/SDL/build-rpi/CMakeFiles/CMakeScratch/TryCompile-Y2whUE/CheckIncludeFile.c:1:20: fatal error: libusb.h: No such file or directory
 #include <libusb.h>

./CMakeCache.txt:PC_LIBUSB_CFLAGS:INTERNAL=-I/usr/include/libusb-1.0
./CMakeCache.txt:PC_LIBUSB_INCLUDE_DIRS:INTERNAL=/usr/include/libusb-1.0
./CMakeCache.txt:PC_LIBUSB_MODULE_NAME:INTERNAL=libusb-1.0
./CMakeCache.txt:PC_LIBUSB_STATIC_CFLAGS:INTERNAL=-I/usr/include/libusb-1.0
./CMakeCache.txt:PC_LIBUSB_STATIC_INCLUDE_DIRS:INTERNAL=/usr/include/libusb-1.0

$ ls /usr/include/libusb-1.0
libusb.h
```

Also:
```
-- Found RPi_BcmHost: /opt/vc/lib/libbcm_host.so  
-- Could NOT find RPi_BrcmEGL (missing: RPi_BrcmEGL_EGL_eglext_brcm_h_PATH) 
```
and I notice that FindRPi_BrcmEGL.cmake sets RPi_BrcmEGL_EGL_eglplatform_h_PATH, not RPi_BrcmEGL_EGL_eglext_brcm_h_PATH.
Where did we get this file and why are we using it instead of what we had before?

### PR DESCRIPTION
**Pull request by madebr**
- Blind rpi fix
- Fixes SDL_HIDAPI_LIBUSB

Fixes #8050

@slouken 
Can you please test this?
I don't have a rpi configured right now, so I can't test it.

### CODE REVIEW

**Comment by slouken** [comment]
```
-- Performing Test HAVE_RPI - Success
CMake Error at cmake/sdltargets.cmake:59 (get_property):
  get_property not given name for TARGET scope.
Call Stack (most recent call first):
  cmake/sdlchecks.cmake:1111 (sdl_generic_link_dependency)
  CMakeLists.txt:1439 (CheckRPI)
```

**Comment by slouken** [comment]
Much closer:
```
/usr/bin/ld: cannot find -lbcm_host
```

**Comment by slouken** [comment]
Where this is found varies by distribution, but here it's in /opt/vc/lib/libbcm_host.so

**Comment by slouken** [comment]
Adding -l/opt/vc/lib to the link line works here.

**Comment by madebr** [comment]
Does `pkg-config bcm_host` or `pkg-config brcmegl` work?
I'm wondering whether `/opt/vc/lib/pkgconfig` is in the default `PKG_CONFIG_PATH`.

**Comment by slouken** [comment]
It appears not to be:
```
$ ls /opt/vc/lib/pkgconfig
bcm_host.pc  brcmegl.pc  brcmglesv2.pc  brcmvg.pc  mmal.pc  vcsm.pc
$ pkg-config bcm_host --libs
Package bcm_host was not found in the pkg-config search path.
Perhaps you should add the directory containing `bcm_host.pc'
to the PKG_CONFIG_PATH environment variable
No package 'bcm_host' found
```

**Comment by slouken** [comment]
```
$ PKG_CONFIG_PATH=/opt/vc/lib/pkgconfig pkg-config bcm_host --libs
-L/opt/vc/lib -lbcm_host -lvcos -lvchiq_arm -pthread
```

**Comment by slouken** [comment]
Looks good, thanks! Should I merge, or are you still iterating?

**Comment by madebr** [comment]
> Looks good, thanks! Should I merge, or are you still iterating?

I think the `check_c_source_compiles` can be removed.

I also think SDL does not need to link to `brcmegl` if it turned out `bcm_host.pc` and `brcmegl.pc` were never actually used before.

Can you re-build SDL in a clean build folder?

**Comment by slouken** [comment]
It works great!

**Comment by madebr** [comment]
Merging.
For completeness, this pr also renames `SDL_TEST` -> `SDL_TEST_LIBRARY`.
See https://github.com/libsdl-org/SDL/commit/41a96c813336a933c21bdf7352d7f26115bfe3f8#commitcomment-122911331

**Pull request merged**
