### PR TITLE
Cleanup WIN_CreateCursor() code a bit

### LINKED ISSUE #6476: Cleanup WIN_CreateCursor() code a bit
https://github.com/libsdl-org/SDL/blob/92b3c53c92971e685254fd89f89ce6bde8cea60e/src/video/windows/SDL_windowsmouse.c#L94-L96

https://github.com/libsdl-org/SDL/blob/92b3c53c92971e685254fd89f89ce6bde8cea60e/src/video/windows/SDL_windowsmouse.c#L120

Not an issue but could be written like this:
```cpp
// hbmMask is a monochrome DIB (1 bit per pixel).
// Proper size calculation is tricky since its every
// scanline should be DWORD-aligned.
// Gery, Ron. “DIBs and Their Use.” MSDN Technology Group, 20 Mar. 1992, https://learn.microsoft.com/previous-versions/ms969901(v=msdn.10). 
UINT maskbitslen = (((surface->w + 31) & ~31) >> 3) * surface->h;
```

### PR DESCRIPTION
**Pull request by DJm00n**
Closes #6476

Now generating proper mask for a cursor.
Ref code: https://github.com/dotnet/wpf/blob/main/src/Microsoft.DotNet.Wpf/src/PresentationFramework/MS/Internal/AppModel/IconHelper.cs#L199-L332
https://learn.microsoft.com/en-us/windows/win32/menurc/using-cursors#creating-a-cursor

### CODE REVIEW

**Comment by slouken** [comment]
The shaped window code is likely to go away in SDL 3.0, you probably don't want to rely on it.

**Comment by DJm00n** [comment]
@slouken I don’t mind if it goes to 3.0. I can make changes in my local repo.

**Comment by slouken** [comment]
@DJm00n, could you update this PR so we can merge it?

Thanks!

**Comment by DJm00n** [comment]
@slouken done.

**Comment by slouken** [comment]
Is BITMAPV5HEADER required? If so, does that break functionality on older versions of Windows?

**Comment by DJm00n** [comment]
>older versions of Windows
AFAIK `BITMAPV5HEADER` is available since Windows XP when alpha blending was introduced in Windows...Do we need to support more older versions?

**Comment by slouken** [comment]
No, Windows XP is fine, thanks!

**Pull request merged**
