### PR TITLE
Add a `DECOR_LIB` variable to use with `find_lib`.

### PR DESCRIPTION
**Pull request by Trigan2025**
## Description
This variable filled by `$PKG_CONFIG --libs` help if the libdecor resides under a directory like /usr/local/lib/x86_64-linux-gnu.
Note that the others changes are made by the run of `autogen.sh`.

### CODE REVIEW

**Comment by sezero** [comment]
Isn't the following better? (Can't test myself: don't have a setup with libdecor installable.
Also, diff to the generated files are intentionally left out.)
```diff
diff --git a/configure.ac b/configure.ac
index 25b6e9e..a611bb7 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1630,12 +1630,10 @@ dnl See if libdecor is available
                           , enable_libdecor=yes)
             if test x$enable_libdecor = xyes; then
                 AC_MSG_CHECKING(for libdecor support)
-                AS_IF([$PKG_CONFIG --exists libdecor-0],
-                      [video_libdecor=yes],
-                      [video_libdecor=no])
+                PKG_CHECK_MODULES([LIBDECOR], [libdecor-0], video_libdecor=yes, video_libdecor=no)
                 AC_MSG_RESULT($video_libdecor)
                 if test x$video_libdecor = xyes; then
-                    EXTRA_CFLAGS="$EXTRA_CFLAGS `$PKG_CONFIG --cflags libdecor-0`"
+                    EXTRA_CFLAGS="$EXTRA_CFLAGS $LIBDECOR_CFLAGS"
                     AC_DEFINE(HAVE_LIBDECOR_H, 1, [ ])
 
                     AC_ARG_ENABLE(libdecor-shared,
@@ -1646,7 +1644,7 @@ dnl See if libdecor is available
                        enable_libdecor_shared=no
                     fi
 
-                    decor_lib=[`find_lib "libdecor-0.so.*" "" | sed 's/.*\/\(.*\)/\1/; q'`]
+                    decor_lib=[`find_lib "libdecor-0.so.*" "$LIBDECOR_LIBS" | sed 's/.*\/\(.*\)/\1/; q'`]
 
                     if test x$have_loadso != xyes && \
                        test x$enable_libdecor_shared = xyes; then
@@ -1658,7 +1656,7 @@ dnl See if libdecor is available
                         echo "-- dynamic libdecor -> $decor_lib"
                         AC_DEFINE_UNQUOTED(SDL_VIDEO_DRIVER_WAYLAND_DYNAMIC_LIBDECOR, "$decor_lib", [ ])
                     else
-                        EXTRA_LDFLAGS="$EXTRA_LDFLAGS `$PKG_CONFIG --libs libdecor-0`"
+                        EXTRA_LDFLAGS="$EXTRA_LDFLAGS $LIBDECOR_LIBS"
                     fi
                 fi
             fi
```

**Comment by flibitijibibo** [comment]
This looks okay to me - it's been a while but I think I just ripped off libsamplerate when I wrote this, so if these variables are part of libdecor's pkgconfig this seems like a good improvement.

**Comment by sezero** [comment]
OK then, @Trigan2025: I'd like to apply [patch-5460a.txt](https://github.com/libsdl-org/SDL/files/8356737/patch-5460a.txt) I attached above -- OK?

**Comment by Trigan2025** [comment]
Sorry for the waiting, yes that's works too so it's OK @sezero

**Comment by sezero** [comment]
Patch applied as https://github.com/libsdl-org/SDL/commit/a630b0293838a161aa499fd0ff3cf0632bce5ff2

**Pull request closed without merging**
