### PR TITLE
Added function to check the state of a thread

### PR DESCRIPTION
**Pull request by Mori-TM**
## Description
SDL_GetThreadState returns the current state of a thread as enum SDL_ThreadState, which is now also accessible for the user.

- Added SDL_GetThreadState
- Moved SDL_ThreadState from SDL_thread_c.h -> SDL_thread.h
- The "available since" version might not be correct on the new function and the old enum

## Existing Issue(s)
https://github.com/libsdl-org/SDL/issues/11702

### CODE REVIEW

**Comment by slouken** [comment]
This seems good to me, though I might remove _STATE from the enum values. @icculus, thoughts?

**Comment by icculus** [comment]
Agreed, let's drop _STATE. But otherwise, I'm on board.

**Comment by icculus** [comment]
The `\since` should be updated, as the enum wasn't in the public api before this.

But I'm not sure what the right version is, since we might do a release candidate before 3.2.0. Let's fix that after merging the PR.

**Comment by slouken** [comment]
The version should be 3.1.8

**Comment by slouken** [comment]
I'll go ahead and merge, and we can fix it up afterwards. Thanks!

**Pull request merged**
