### PR TITLE
PSP: fix regression, GetTicks64 should return millisecs

### PR DESCRIPTION
**Pull request by rofl0r**
introduced in 82b449611afc4129c562512a5463da0cd9937406

### CODE REVIEW

**Comment by ccawley2011** [comment]
One additional detail is that `SDL_GetTicks64` is specified as returning the number of milliseconds "since the SDL library initialized". This seems like something that should be preserved as well.

Otherwise, this change looks OK.

**Comment by rofl0r** [comment]
@ccawley2011 good catch. updated.

**Comment by slouken** [comment]
Is sceRtcGetTickResolution() guaranteed to be microsecond resolution? Why would they have that function if it's constant in all cases?

**Comment by rofl0r** [comment]
yeah, it's constant: https://github.com/uofw/uofw/blob/master/src/kd/rtc/rtc.c#L777

**Comment by slouken** [comment]
Great. It might be worth throwing an SDL_assert in SDL_TicksInit(), just in case. I'll go ahead and merge as-is though.

Thanks!

**Pull request merged**
