### PR TITLE
SDL_Renderer do Opengl batching

### PR DESCRIPTION
**Pull request by 1bsyl**
Do OpenGL batching.
So that we can drop the glBegin/glEnd and be more consistent.
Code is similar to the GLES2 backend.

(add @slime73 )

### CODE REVIEW

**Comment by 1bsyl** [comment]
Just tested with fps with testdraw2. (and opengl)

| line method | FPS before | FPS after |
|--------------------|-----------------|--------------|
|1| 900 | 730 |
|2| 1300 | 930 |
|3| 1300 | 930 |

It makes just thing worse ...

**Comment by slouken** [comment]
I wonder if this made things worse for GLES2 also? (See https://github.com/libsdl-org/SDL/issues/5206 for details)

**Comment by 1bsyl** [comment]
It was misleading because batching isn't automatically enabled.

when I enable batching, I got the same fps for OpenGL with and without this #PR

| line method | FPS before | FPS after |
|--------------------|-----------------|--------------|
|1| 930 | 930 |
|2| 1330 | 1330 |
|3| 1300 | 1300 |

`SDL_RENDER_BATCHING=1 SDL_RENDER_LINE_METHOD=3 ./testdraw2 --info render --renderer opengl`


In fact, we this PR, we must enable batching to have the same performance. 
(which anyway should also always be set)

**Comment by icculus** [comment]
Do we want this patch, or is it not worth it? I'm skeptical that we're ever going to see something serious that runs SDL2 but needs glBegin(), so even at the same performance I'm fine with the change unless there's a reason not to.

Also, with this change: I'm wondering if we are close to collapsing all three GL renderers down into a single codebase with some `#ifdef`s (or just `if`s).

**Comment by 1bsyl** [comment]
Not yet at merging the 3 GL renderers, but one step closer...

With similar code, it seems to me it gets:
- easier to reveal bugs
- have less source of bugs since we have less different code

**Pull request merged**
