### PR TITLE
Android: Filter out drivers based on SDL_***_DISABLED defines, to help reduce build size

### PR DESCRIPTION
**Pull request by AntTheAlchemist**
Defines such as SDL_SENSOR_DISABLED don't make much difference (about 2k) to the final build. This patch will exclude respective drivers from the build-config to further reduce build size. A total of 177k can be saved, with SDL_LEAN_AND_MEAN that's 542k, which is a considerable saving and results in a much more compact APK for anyone looking to strip out unwanted systems.

### CODE REVIEW

**Review by AntTheAlchemist — COMMENTED** [review]
I've made a right mess of this... still no good at this PR stuff.

**Comment by madebr** [comment]
No need to close a "messed-up PR".
This one is salvageable:
we can review your changes at https://github.com/libsdl-org/SDL/pull/9985/files and merge them into main together in one commit by squashing them.

**Comment by AntTheAlchemist** [comment]
> No need to close a "messed-up PR". This one is salvageable: we can review your changes at https://github.com/libsdl-org/SDL/pull/9985/files and merge them into main together in one commit by squashing them.

Thanks @madebr. Only 1 file was showing as changed in that link, there should be 3 files changes in total, so it's a bit beyond messed-up. I'll start again and re-submit.

**Comment by madebr** [comment]
You can "fix" it by pushing additional commits to the "main" branch of your SDL fork.

In "git speak", you need to stage the 2 other files (git add), so git knows they should be part of the next commit.
Then create a commit and push it.

**Comment by AntTheAlchemist** [comment]
That went right over my head and I'm just making it worse. There is also a change to progard that shouldn't be in there, which is a PR already merged to SDL yesterday.

I'm adding you as a contributor 🤕

**Comment by AntTheAlchemist** [comment]
There should be changes to Android.mk, SDL_build_config_android.h & SDL_android.c

**Comment by madebr** [comment]
I can't push to your SDL or scrap fork, so I pushed it to a `ant-allin1` branch in my repo.
See https://github.com/madebr/SDL/commits/ant-allin1/

You can check it in a new branch out locally by running:
```
git fetch https://github.com/madebr/SDL ant-allin1:android-filter-disabled-devices
```

If you want, I can also create a pr myself, on which you can suggest changes.
As you see from the link above, you remain the creator of commit.

**Pull request closed without merging**
