### PR TITLE
Inhibit classification of CH Pro Pedals rudder pedals as accelerometer when udev is not used

### LINKED ISSUE #7500: Rudder pedals "CH Pro Pedals" incorrectly detected as accelerometer on Linux without udev
When using SDL2 on Linux without udev enabled (e. g. in the Steam container runtime), the CH Pro Pedals are incorrectly detected as accelerometer, and not listed as a joystick. The CH Pro Pedals are a rudder pedals product.

Because it has three axes and no buttons, it is classified as an accelerometer in `SDL_EVDEV_GuessDeviceClass()` (see [src/core/linux/SDL_evdev_capabilities.c](https://github.com/libsdl-org/SDL/blob/0479df5/src/core/linux/SDL_evdev_capabilities.c)).

Proposals for solution:
* Make an exception for this particular device (detected by USB VID 0x068e / PID 0x00f2) not to classify as a joystick.
* Rely on the property `INPUT_PROP_ACCELEROMETER` being set by the Linux kernel (since 4.0) instead of checking the number of axes / existence of buttons to detect accelerometers.

The algorithm systemd-udev uses to detect accelerometers is very similar to what SDL does. It also does not rely on the property `INPUT_PROP_ACCELEROMETER`, but also classifies devices with three axes and no buttons as accelerometers (see https://github.com/systemd/systemd/blob/v253/src/udev/udev-builtin-input_id.c#L185). However, for this particular product, there is a hwdb rule (see https://github.com/systemd/systemd/commit/230ed4c4bad8b3c1d9d746a80e6f78dc71d1c87f).

### PR DESCRIPTION
**Pull request by felixhaedicke**
The CH Pro Pedals are incorrectly classified as accelerometer in SDL_EVDEV_GuessDeviceClass(), because it has three axes and no buttons.

## Description
This introduces the new function IsExplicitlyKnwownAsJoystick() to check if a device is known to be a joystick by checking the vendor / product ID. For now, this functions checks for the CH Pro Pedals, and returns SDL_FALSE for all other devices, to proceed with the check via GuessIsJoystick() as before.

Furthermore, the call to GuessIsJoystick() is now done after product id determination in IsJoystick(), to be able to perform the IsExplicitlyKnwownAsJoystick() before calling GuessIsJoystick().

## Existing Issue(s)
Fixes #7500.

### CODE REVIEW

**Comment by smcv** [comment]
Having a table of known devices would probably scale better. Is this in-scope for the game controller database, or is that only for gamepads? If that's only for gamepads, then a similar mechanism for other gaming input devices (flight sticks, pedals, steering wheels, etc.) might make sense.

**Comment by smcv** [comment]
It would be good to add details of this device (or any other devices whose detection is changed) to `test/testevdev.c`, so that it can't regress without being noticed.

**Comment by smcv** [comment]
> Having a table of known devices would probably scale better. Is this in-scope for the game controller database, or is that only for gamepads? If that's only for gamepads, then a similar mechanism for other gaming input devices (flight sticks, pedals, steering wheels, etc.) might make sense.

I tried implementing this approach in #7598.

> It would be good to add details of this device (or any other devices whose detection is changed) to `test/testevdev.c`, so that it can't regress without being noticed.

I've done this for some other gaming input devices in #7597, but I don't have access to CH Pro Pedals or their `steam-runtime-input-monitor` or `evemu-describe` output, so I can't add them to the table of test data myself.

**Comment by slouken** [comment]
We'll go with the table based approach. @felixhaedicke, feel free to add your information to @smcv's draft PR.

**Pull request closed without merging**
