### PR TITLE
SDL3 WinXP support

### LINKED ISSUE #8666: Windows XP support?
re: Fixed building with older Windows SDK https://github.com/libsdl-org/SDL/commit/f00ecf5f190feb6db0727b0c93f7a609f70be76d

These flags require Vista. I'm mentioning it in case SDL 3 is intended to work on XP.

https://github.com/libsdl-org/SDL/blob/f00ecf5f190feb6db0727b0c93f7a609f70be76d/src/video/windows/SDL_windowsevents.c#L176

[MapVirtualKeyA documentation](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeya)

https://github.com/libsdl-org/SDL/blob/f00ecf5f190feb6db0727b0c93f7a609f70be76d/src/video/windows/SDL_windowsevents.c#L878

[WideCharToMultiByte documentation](https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-widechartomultibyte). If I remember correctly XP always returns an error with the flag set.

### PR DESCRIPTION
**Pull request by icculus**
This only needed minor changes, afaik, so here you go.

It will _not_ be our policy to support WinXP if we have to make heroic efforts to maintain compatibility, but these changes are small, so this might be worth merging.

Fixes #8666.

### CODE REVIEW

**Comment by madebr** [comment]
In a qemu windows xp virtual machine, I see unknown pixel formats (see https://github.com/libsdl-org/SDL/issues/8328)
https://github.com/libsdl-org/SDL/issues/8328#issuecomment-1806686851 fixes it for me (the patch is not applied to main)

**Comment by icculus** [comment]
I've added both those patches to the PR. We want both of them, right?

**Comment by madebr** [comment]
The second one was not really needed, but it correct (for me) on the windows xp vm and wine.

**Comment by icculus** [comment]
Okay, force-pushed with just the first patch in there, now.

**Comment by icculus** [comment]
Last call before I merge this!

**Pull request merged**
