### PR TITLE
Namespace the object creation properties

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/10543

### CODE REVIEW

**Review by icculus — APPROVED** [review]

**Comment by icculus** [comment]
Hah, beat me to it

**Comment by madebr** [comment]
The properties currently live under `SDL.*`.
Do we want to version them for SDL4? :)

**Comment by slouken** [comment]
> The properties currently live under `SDL.*`. Do we want to version them for SDL4? :)

No, we want to pass them through. Speaking of which, can we remove the version prefix from cmake variables in the satellite libraries? People shouldn't have to change their build scripts to rename SDL2 to SDL2 for everything (or SDL3 to SDL4) in the future.

**Comment by madebr** [comment]
> > The properties currently live under `SDL.*`. Do we want to version them for SDL4? :)
> 
> No, we want to pass them through. Speaking of which, can we remove the version prefix from cmake variables in the satellite libraries? People shouldn't have to change their build scripts to rename SDL2 to SDL2 for everything (or SDL3 to SDL4) in the future.

Done :)

**Comment by sezero** [comment]
> > > The properties currently live under `SDL.*`. Do we want to version them for SDL4? :)
> > 
> > 
> > No, we want to pass them through. Speaking of which, can we remove the version prefix from cmake variables in the satellite libraries? People shouldn't have to change their build scripts to rename SDL2 to SDL2 for everything (or SDL3 to SDL4) in the future.
> 
> Done :)

Going from SDL2 to SDL3, people will now have to change their cmake build scripts from SDL2XXX_ to SDLXXX_ for all the satellite libraries: Is this what you really intended?

**Comment by madebr** [comment]
> > > > The properties currently live under `SDL.*`. Do we want to version them for SDL4? :)
> > > 
> > > 
> > > No, we want to pass them through. Speaking of which, can we remove the version prefix from cmake variables in the satellite libraries? People shouldn't have to change their build scripts to rename SDL2 to SDL2 for everything (or SDL3 to SDL4) in the future.
> > 
> > 
> > Done :)
> 
> Going from SDL2 to SDL3, people will now have to change their cmake build scripts from SDL2XXX_ to SDLXXX_ for all the satellite libraries: Is this what you really intended?

Yes. We also don't have `SDL3_*` options for SDL3.

**Pull request merged**
