### PR TITLE
Mayflash Adapter PS4 Mode Support

### PR DESCRIPTION
**Pull request by mariotaku**
## Description

[Mayflash MAGIC-S PRO 2 adapter](https://www.mayflash.com/product/magic_s_pro_2.html) Has PS4/Xbox mode, which emulates a PS4 controller, and has VID/PID of `33df:000d`.

This PR allows SDL to recognize the adapter as a PS4 controller.

### CODE REVIEW

**Comment by mariotaku** [comment]
Hi! I have updated the commits and base.

**Comment by slouken** [comment]
Merged, thanks!

**Comment by sezero** [comment]
This is cherry picked to release-2.30.x, but not to SDL2 branch

**Comment by slouken** [comment]
Thanks, pushed!

**Pull request merged**
