### PR TITLE
Windows event hook fix: All events are now sent to the hook during dispatch along with a reference to the SDL_Window.

### PR DESCRIPTION
**Pull request by dtromb**
## Description

- Signature of `SDL_WindowsMessageHook()` changed to support return value and pass the `SDL_Window` in.

 old decl:  ` typedef SDL_bool (SDLCALL *SDL_WindowsMessageHook)(void *userdata, MSG *msg);`
 new decl: `typedef SDL_bool (SDLCALL *SDL_WindowsMessageHook)(void *userdata, MSG *msg, SDL_Window *window, Sint64 *return_val);`

- Modified the event loop and handler so that any message in the event queue can be delivered to the hook function, not just the ones that SDL dispatches.

- Added a pre-init hint to select between the old behavior and the new behavior.  

   The new behavior takes effect iff the pre-init hint SDL_HOOK_EVENTS_FROM_WINDOW_PROC is set.   It is currently set to SDL_FALSE per default (ie. default SDL2 behavior).  At some point during our conversations @playmer felt that this was a pure bugfix and so there was no need to enable or disable the behavior.  If this is still true, I can easily remove the hint, or set it to default SDL_TRUE.   However I realized there are two use cases which might be problems if it were mandatory:
   
   First, this change necessarily means that code that used to hook and listen to untranslated key codes will now receive the translated messages (since they are dispatched), as well as the original untranslated messages (since they are also dispatched), instead of just the untranslated ones.  This could potentially cause confusing double-key-strokes.   However, it is probably mitigated by the fact that there is a completely separate mechanism now for hooking key event, which most new code likely uses.
   
   Second, and more importantly, there are some fields in the `MSG` structure send to the event loop whose values are not available during event dispatch.  In particular there is no way for the WndProc function to know the original values of the `time` field, which gives a timestamp of event generation, or the `pt` field, which records the cursor position at event generation.  So, any code that relies on these fields will want to use the old behavior.   (One can imagine logging these fields for session playback or anti-cheat purposes in games, as well as other use cases...)  
   
   It might be possible to overcome this limitation by maintaining a queue  of this extra information as it comes into the event loop, and adding it back into the `MSG  ` sent to the hook function during WndProc.   But this may be too complex for too little compatibility, when it could simple be configurable.

## Existing Issue(s)

This PR intends to resolve https://github.com/libsdl-org/SDL/issues/10497

### CODE REVIEW

**Comment by slouken** [comment]
Hmm, most people who need this functionality set the window proc directly on the window and then chain to SDL's window proc. That way they see everything that flows through before SDL does and have complete control over the dispatch flow.

**Comment by dtromb** [comment]
> Hmm, most people who need this functionality set the window proc directly on the window and then chain to SDL's window proc. 

That's one way to do it.  It's infintessimally less performant (another function call, compare, and branch per message as opposed to just compare and branch), but that's probably not important.   The main issue is that there would still be no easy / good way to get the `SDL_Window` given just the `MSG `structure.  In my use case (redraw borders during NCPAINT) this means we'd probably have to use windows DC drawing instead of SDL drawing in the hook.   (There might be a way to get a window / surface from just the window handle and exported SDL features?  But I couldn't find one.)

**Comment by slouken** [comment]
> > Hmm, most people who need this functionality set the window proc directly on the window and then chain to SDL's window proc.
> 
> That's one way to do it. It's infintessimally less performant (another function call, compare, and branch per message as opposed to just compare and branch), but that's probably not important. The main issue is that there would still be no easy / good way to get the `SDL_Window` given just the `MSG `structure. In my use case (redraw borders during NCPAINT) this means we'd probably have to use windows DC drawing instead of SDL drawing in the hook. (There might be a way to get a window / surface from just the window handle and exported SDL features? But I couldn't find one.)

Usually there's a hashtable of HWND to SDL_Window maintained on the application side if that's important, but we could add it as a window property, the way we do with the window data.

**Comment by dtromb** [comment]
The only other caveats I can think of to that approach are that you'd possibly miss the first little cluster of events (could maybe workaround by using the existing hook and blocking in it, manually dispatching the first message and then unregistering the hook), and that there's a restriction on setting the WndProc where you have to be doing that from the same process that created the window (seems exotic to the point of/and/or irrelevant).   

I'll try to do the test case I've been using this way, if it works I'm personally indifferent to the choice between enhancing and ignoring the existing mechanism.... it's there if you want it.   (worth the exercise for knowledge gained)

**Comment by slouken** [comment]
What was the resolution on this? Did you end up needing this functionality or was the existing support enough?

**Comment by slouken** [comment]
You've been quiet, so I assume that you solved things to your satisfaction, and I'll go ahead and close this. If that's not the case, please let me know ASAP, so I can reopen before the ABI lock.

**Pull request closed without merging**
