### PR TITLE
 fixed build rwops

### PR DESCRIPTION
**Pull request by 1bsyl**
fixing build

### CODE REVIEW

**Comment by sezero** [comment]
These fixes don't seem correct to me -- but I do like to be corrected:
Casting Sint64 to size_t will defeat detection of possible error-returns
and will also cripple the values on 32 bit targets. I suggest changing
the relevant vars' types to Sint64 and adding some more negative return
checks, instead.

**Comment by 1bsyl** [comment]
yes, maybe you're right.
anyway, the testautomation --filter rwops is passing anymore (with or without cast, with size_t or Sint64)

**Comment by 1bsyl** [comment]
@sezero , It seems the nested switch in test/testime.c is badly nested, and broken ? (line 708 and +)

**Comment by 1bsyl** [comment]
remove some extra {} in testime.c:
https://github.com/libsdl-org/SDL/commit/ffaf451558039dd1f357f34b4ec81b8b1e888e83

**Comment by 1bsyl** [comment]
wsa there forever: 
https://github.com/spurious/SDL-mirror/commit/f39fe0593767c30088bca2e2a3493fded748a7ff#diff-66b59e243058c24c6d08f5e9da7c6eeaae40f904af5b1755aabd554bdd9ef7ac

**Comment by 1bsyl** [comment]
cherry picked in SDL2: https://github.com/libsdl-org/SDL/commit/8e72be31171dc4891169fa99ee78aaf4c0f20367

**Comment by slouken** [comment]
> These fixes don't seem correct to me -- but I do like to be corrected: Casting Sint64 to size_t will defeat detection of possible error-returns and will also cripple the values on 32 bit targets. I suggest changing the relevant vars' types to Sint64 and adding some more negative return checks, instead.

@icculus, this is the kind of application level churn I was thinking about.

**Comment by 1bsyl** [comment]
Just updated the testautomation_rwops because of error code -1 when writing is impossible

**Pull request merged**
