### PR TITLE
d3d12: Import DirectX-Headers, use local d3d12.h in SDL_render

### PR DESCRIPTION
**Pull request by flibitijibibo**
This avoids lots of build issues with the various D3D12 headers out there (MinGW, old Windows SDKs, etc) and also opens the door for WSL2 libd3d12.so support.

Note that the build system has not been changed; technically _all_ platforms now have d3d12.h but we should only enable the backend when it's actually expected to work.

Part of #9312

### CODE REVIEW

**Comment by sezero** [comment]
So the MS headers work with mingw: nice. 

Run dos2unix on the headers?

**Comment by flibitijibibo** [comment]
> So the MS headers work with mingw: nice.
> 
> Run dos2unix on the headers?

Done!

**Comment by slouken** [comment]
If we include these, do we need to do the D3D_CALL hacks in there for Xbox vs Desktop?

**Comment by flibitijibibo** [comment]
> If we include these, do we need to do the D3D_CALL hacks in there for Xbox vs Desktop?

I'll have to check but AFAIK d3d12_x/d3d12_xs still don't have C macros, which means we'll eventually have to reuse it for GPU. When we get to that part I'll try to make `src/video/directx/SDL_d3d12.h` to share that stuff between Render and GPU.

**Comment by slouken** [comment]
> > If we include these, do we need to do the D3D_CALL hacks in there for Xbox vs Desktop?
> 
> I'll have to check but AFAIK d3d12_x/d3d12_xs still don't have C macros, which means we'll eventually have to reuse it for GPU. When we get to that part I'll try to make `src/video/directx/SDL_d3d12.h` to share that stuff between Render and GPU.

Great, thanks.

**Pull request merged**
