### PR TITLE
Don't automatically free temporary memory, let the application call SDL_FreeTemporaryMemory() when it's ready.

### PR DESCRIPTION
**Pull request by slouken**
Also mark up all functions that return temporary memory with SDL_DECLSPEC_TEMP, to help people implementing language bindings.

Fixes https://github.com/libsdl-org/SDL/issues/10378

### CODE REVIEW

**Review by icculus — APPROVED** [review]

**Comment by sezero** [comment]
I guess sdl2-compat needs another update after this.

**Comment by slouken** [comment]
Maybe. The ABI hasn't changed. We should think about what, if anything, makes sense for SDL2 applications, but where this memory was no longer available was never defined in SDL2.

**Comment by slouken** [comment]
Yeah, I double checked and there isn't a "one place" that is the right place to free temporary memory. The safest thing to do is to wait and clean them up in SDL_Quit(), which is what happens now. @icculus, thoughts?

**Comment by icculus** [comment]
I think it's still probably reasonable to do it in the event loop for only the main thread's memory list, but yeah, SDL_Quit and thread termination for sure, and manually for any thread when they call SDL_FreeTemporaryMemory, as a fence to say "I'm good up to this point."

**Comment by icculus** [comment]
Then again, maybe a note in the PollEvent docs that says "it's not a bad idea to free temporary memory before you start calling this in a loop" is all you need.

**Pull request merged**
