### PR TITLE
cmake: add -Wimplicit-fallthrough warning

### PR DESCRIPTION
**Pull request by madebr**

### CODE REVIEW

**Comment by slouken** [comment]
Yes please, thank you! :)

**Comment by sezero** [comment]
Some are the missing breaks are hard to believe that they haven't been
caught so far, e.g. the ones in vitavideo and testcolorspace.

**Comment by madebr** [comment]
> Some are the missing breaks are hard to believe that they haven't been caught so far, e.g. the ones in vitavideo and testcolorspace.

Looks like not a lot of people are inputting text on vita.
The colorspace bug is benign: the app exits anyway.

**Comment by meyraud705** [comment]
There are also missing fall through in `SDL_memset` and `SDL_memcpy`, why didn't the CI found them?

**Comment by madebr** [comment]
We only test `-DSDL_LIBC=OFF` with MSVC, and that does not have `-Wimplicit-fallthrough`.
`clang-cl` supports it, but did not catch this.

**Pull request merged**
