### PR TITLE
Switched the SDL sensor API to return a list of sensors instead of working with device indices

### PR DESCRIPTION
**Pull request by slouken**
Reference: https://github.com/libsdl-org/SDL/issues/6889

### CODE REVIEW

**Comment by slouken** [comment]
If this looks good, I'll make a similar change to the joystick and gamepad APIs

**Review by icculus — APPROVED** [review]
Looks good to me!

**Comment by themightyoarfish** [comment]
(unfortunately github wont let me comment inline)

In `src/joystick/SDL_gamepad.c`
```
static SDL_bool SDL_GetDriverAndJoystickIndex(SDL_JoystickID instance_id, SDL_JoystickDriver **driver, int *driver_index)
{
    int i, num_joysticks, device_index;

    SDL_AssertJoysticksLocked();

    if (instance_id > 0) {
```

I am currently changing some code over from sdl2, and I stumbled upon this change. Previously, joystick id could be 0, but here it assumes > 0. 
Is this a typo or an intentional change? The `SDL_OpenJoystick()` documentation does not state that the value should be > 0, but maybe I don't have the full picture.

**Comment by themightyoarfish** [comment]
But I conclude from the discussion at https://github.com/libsdl-org/SDL/issues/6889 that one should not pass in numbers manually, but use the values obtained via `  SDL_JoystickID *sticks = SDL_GetJoysticks(&num_sticks_);`, got it.

**Comment by icculus** [comment]
Yeah, they are arbitrary numbers and not indices into an array now, and zero is considered a "null" value.

**Pull request merged**
