### PR TITLE
SDL_TriggerBreakPoint update using builtin instead of assembly versio…

### PR DESCRIPTION
**Pull request by devnexen**
…ns if available

## Description
Mainly with clang toolchain, using `__builtin_debugtrap` if possible.

### CODE REVIEW

**Comment by sezero** [comment]
This fails build with some older compilers:
```
  CC     build/SDL_assert.lo
In file included from src/./SDL_internal.h:123,
                 from src/SDL_assert.c:21:
include/SDL_assert.h:54:46: error: missing binary operator before token "("
In file included from src/./SDL_internal.h:123,
                 from src/SDL.c:21:
include/SDL_assert.h:54:46: error: missing binary operator before token "("
make: *** [build/SDL_assert.lo] Error 1
```

Maybe something like this???
```diff
diff --git a/include/SDL_assert.h b/include/SDL_assert.h
index defadf1..436d55f 100644
--- a/include/SDL_assert.h
+++ b/include/SDL_assert.h
@@ -47,6 +47,13 @@ on the assertion line and not in some random guts of SDL, and so each
 assert can have unique static variables associated with it.
 */
 
+#if defined(__has_builtin)
+  #if __has_builtin(__builtin_debugtrap)
+    #define SDL_TriggerBreakpoint() __builtin_debugtrap()
+  #endif
+#endif
+
+#if !defined(SDL_TriggerBreakpoint)
 #if defined(_MSC_VER)
 /* Don't include intrin.h here because it contains C++ code */
     extern void __cdecl __debugbreak(void);
@@ -66,6 +73,7 @@ assert can have unique static variables associated with it.
     /* How do we trigger breakpoints on this platform? */
     #define SDL_TriggerBreakpoint()
 #endif
+#endif /**/
 
 #if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L) /* C99 supports __func__ as a standard. */
 #   define SDL_FUNCTION __func__
```

**Comment by devnexen** [comment]
Yes it had been committed fast did not have time to fix :-)

**Comment by slouken** [comment]
Fixed with 626a3c5ef75ed50a81779f4a9dec8c9864258b3b?

**Comment by sezero** [comment]
> Fixed with [626a3c5](https://github.com/libsdl-org/SDL/commit/626a3c5ef75ed50a81779f4a9dec8c9864258b3b)?

Nope:
```
/bin/sh build-scripts/updaterev.sh
  CC     build/SDL.lo
In file included from SDL/src/./SDL_internal.h:123,
                 from /SDL/src/SDL.c:21:
include/SDL_assert.h:54:23: error: missing binary operator before token "("
make: *** [build/SDL.lo] Error 1
```

**Comment by slouken** [comment]
Okay, give me a few minutes. I'll sort this out.

**Comment by slouken** [comment]
This should work better: e97b50624

**Comment by sezero** [comment]
> This should work better: [e97b506](https://github.com/libsdl-org/SDL/commit/e97b5062422cff6e8d34c2f3ecb821081f15c307)

Yes :+1:

**Pull request merged**
