### PR TITLE
SDL_getenv() should return const

### PR DESCRIPTION
**Pull request by slouken**
This also allows us to use SDL_FreeLater() and make SDL_getenv() thread-safe on Windows.

### CODE REVIEW

**Comment by sezero** [comment]
What to do in sdl2-compat: lie and pretend that SDL_getenv returns const, or what?

**Comment by slouken** [comment]
> What to do in sdl2-compat: lie and pretend that SDL_getenv returns const, or what?

Exactly 😊

**Comment by icculus** [comment]
Strictly speaking, getenv() allows you to edit the returned string, as you own the memory in the environment table, but glibc's manual very clearly says that while you _can_ do that, you absolutely 100% never should.

Which is to say, if an app edits the const string, and it just changes temporary memory and doesn't alter the actual environment, I consider that an app bug, not an sdl2-compat bug; they should have used SDL_setenv to do that!

**Comment by sezero** [comment]
OK, pushed https://github.com/libsdl-org/sdl2-compat/commit/2ba061e77c334ad649f254ca3add1432566752f5 to sdl2-compat

**Comment by sezero** [comment]
> OK, pushed [libsdl-org/sdl2-compat@2ba061e](https://github.com/libsdl-org/sdl2-compat/commit/2ba061e77c334ad649f254ca3add1432566752f5) to sdl2-compat

.. and pushed https://github.com/libsdl-org/sdl2-compat/commit/22bb3a2886e8e9336717860a2bd75a91374443ee as a follow-up.

**Pull request merged**
