### PR TITLE
Support MIN/MAX blend on OpenGL + ES

### PR DESCRIPTION
**Pull request by ds-sloth**
Hello! I noticed that OpenGL has always supported the Min/Max blend operations and OpenGL ES supports them through an extension (https://registry.khronos.org/OpenGL/extensions/EXT/EXT_blend_minmax.txt; GL ES 3.0 makes this support core). I'd like to add this support to SDL2.

I think this is a reasonable addition because it doesn't extend the render API, but rather makes its support more complete.

Thank you for your time and work on the project!

## Functionality considerations

> The GL_MIN, and GL_MAX equations do not use the source or destination factors, only the source and destination colors. (https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlendEquation.xhtml)

In OpenGL, these operations effectively use blend factors of ONE, but I think that returning that the blend mode is unsupported when non-ONE blend factors are used would be unexpected to the user in many cases, and would keep the functionality from working on some applications that currently work with Direct3D.

I also wonder whether Direct3D has the same behavior and this is the cause of the remark on the SDL wiki:

> However, some factors produce unexpected results with `SDL_BLENDOPERATION_MINIMUM` and `SDL_BLENDOPERATION_MAXIMUM`. (https://wiki.libsdl.org/SDL2/SDL_ComposeCustomBlendMode)

## Implementation

* In the OpenGL renderer I simply add the blend operations to the lookup function.

* In the OpenGL ES renderer, which I believe targets OpenGL ES 1.1, I check for support for EXT_blend_minmax, store the result in the renderer's data (increasing the renderer data's size by one SDL_bool), and use it to report whether the blend operations are supported. This is the part of the PR I am the least confident about and would appreciate review from one of the maintainers of the OpenGL ES renderer.

* I also add the blend operations to the lookup function of OpenGL ES.

## Existing Issue(s)

I don't see any open issues, but min/max blend operations can in some cases substitute for bitwise blending operations, which were requested by my collaborator in #5455

### CODE REVIEW

**Comment by sezero** [comment]
SDL3 side?

**Comment by slouken** [comment]
Done, in 38697e832

**Comment by ds-sloth** [comment]
I think you just merged the OpenGL (non-ES) case for SDL3, I'm happy to submit another PR for SDL3 including it if you like.

**Comment by slouken** [comment]
OpenGL ES 1.0 support has been removed in SDL3. We can copy your change over if we end up putting it back before release.

**Comment by ds-sloth** [comment]
Thank you @slime73, I'll implement that and then submit another PR.

**Pull request merged**
