### PR TITLE
Add Mayflash PC043 adapter

### PR DESCRIPTION
**Pull request by JunielKatarn**
Adds mapping for the Mayflash PC043 Nintendo 64 controller adaptter for Windows.

## Description

See https://www.mayflash.com/product/showproduct.php?id=19

## Existing Issue(s)

#6079

### CODE REVIEW

**Comment by offalynne** [comment]
GUID collides with https://github.com/JunielKatarn/SDL/blob/e902adb2aa96e46ee5fbdcdf6b64305500df3573/src/joystick/SDL_gamecontrollerdb.h#L177

@JunielKatarn can you share the exact name as it appears in the Windows game controller dialog ?
https://support.microsoft.com/en-us/topic/how-to-troubleshoot-game-controllers-in-microsoft-games-ee731224-b2d7-f25e-3c2a-338b27dbe1f5

**Comment by JunielKatarn** [comment]
> GUID collides with https://github.com/JunielKatarn/SDL/blob/e902adb2aa96e46ee5fbdcdf6b64305500df3573/src/joystick/SDL_gamecontrollerdb.h#L177
> 
> @JunielKatarn can you share the exact name as it appears in the Windows game controller dialog ? https://support.microsoft.com/en-us/topic/how-to-troubleshoot-game-controllers-in-microsoft-games-ee731224-b2d7-f25e-3c2a-338b27dbe1f5

I don't have the adapter handy. I can asure you, though, it does not display the HuiJia name.
See #6079 for details.

@slouken explained SDL can now handle duplicate IDs, so the collision should no longer bi an issue.

**Comment by offalynne** [comment]
> @slouken explained SDL can now handle duplicate IDs, so the collision should no longer bi an issue.

If the GUIDs are the same, that's a collision. The GUID has to be differentiated by creating a map with a newer version of SDL.

Please comment with the device name when you have access to the adapter.

**Comment by JunielKatarn** [comment]
> Please comment with the device name when you have access to the adapter.

Will do.
Is there an SDL-based tool that can read the GUID without debugging SDL code?

**Comment by JunielKatarn** [comment]
@offalynne this shows up in the Game Controllers dialog:
image

**Pull request merged**
