### PR TITLE
Remove reserved identified with underscore prefix

### PR DESCRIPTION
**Pull request by 1bsyl**
remove internal underscore prefix

https://github.com/libsdl-org/SDL/issues/6856

### CODE REVIEW

**Comment by 1bsyl** [comment]
just checking if this built / auto-merge. but it seems this one can also fit

**Comment by slouken** [comment]
I think this is all taken care of. Are there any changes still pending?

**Comment by 1bsyl** [comment]
i think we can merge, this remove the reserved-identifier warning not on a public header side, but when sdl3 joystick file is built. (with the warning enabled)

**Comment by 1bsyl** [comment]
(see the diff tab)

**Pull request merged**
