### PR TITLE
Fixed OS/2 build

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Review by sezero — APPROVED** [review]
OK!

I was about to do almost the same thing. Only missing part is this:

```diff
diff --git a/src/thread/os2/SDL_systls_c.h b/src/thread/os2/SDL_systls_c.h
index bb39443..ad4fcef 100644
--- a/src/thread/os2/SDL_systls_c.h
+++ b/src/thread/os2/SDL_systls_c.h
@@ -27,12 +27,4 @@
 
 extern SDL_TLSData **ppSDLTLSData;
 
-/* SDL_OS2TLSAlloc() called from SDL_InitSubSystem() */
-void SDL_OS2TLSAlloc(void);
-
-/* SDL_OS2TLSFree() called from SDL_QuitSubSystem() */
-void SDL_OS2TLSFree(void);
-
 #endif /* SDL_THREAD_OS2 */
-
-/* vi: set ts=4 sw=4 expandtab: */
```

**Comment by slouken** [comment]
FYI, I removed the cTLSAlloc refcounting, since the semantics are now: allocate when init is first called, ignore subsequent init calls, and deallocate when quit is first called, ignore subsequent quit calls.

**Comment by sezero** [comment]
> FYI, I removed the cTLSAlloc refcounting, since the semantics are now: allocate when init is first called, ignore subsequent init calls, and deallocate when quit is first called, ignore subsequent quit calls.

OK

**Comment by slouken** [comment]
> OK!
> 
> I was about to do almost the same thing. Only missing part is this:
> 
> ```diff
> diff --git a/src/thread/os2/SDL_systls_c.h b/src/thread/os2/SDL_systls_c.h
> index bb39443..ad4fcef 100644
> --- a/src/thread/os2/SDL_systls_c.h
> +++ b/src/thread/os2/SDL_systls_c.h
> @@ -27,12 +27,4 @@
>  
>  extern SDL_TLSData **ppSDLTLSData;
>  
> -/* SDL_OS2TLSAlloc() called from SDL_InitSubSystem() */
> -void SDL_OS2TLSAlloc(void);
> -
> -/* SDL_OS2TLSFree() called from SDL_QuitSubSystem() */
> -void SDL_OS2TLSFree(void);
> -
>  #endif /* SDL_THREAD_OS2 */
> -
> -/* vi: set ts=4 sw=4 expandtab: */
> ```

Added!

**Pull request merged**
