### PR TITLE
Check for O_CLOEXEC definition in fcntl.h at configuration time,

### PR DESCRIPTION
**Pull request by sezero**
This patch makes sure `O_CLOEXEC` is available at configuration time since
its use was added during 2.0.17 development. If not available, define it
internally as 0 in `SDL_internal.h`. Define it as available for macOS>=10.7
in `SDL_config_macosx.h`. (didn't touch `SDL_config_iphoneos.h`.)

FIXME: What to do in `SDL_config_android.h`? (does not seem to be used by
SDL Android code, but...)

@icculus, @slouken: I suggest applying this for 2.0.18.

### CODE REVIEW

**Comment by icculus** [comment]
> FIXME: What to do in SDL_config_android.h? (does not seem to be used by
SDL Android code, but...)

Seems unlikely that an Android app is going to fork/exec...? I assume there generally aren't children processes and when they are, it's more like "tell the OS to launch the web browser" and it ends up a child process of something else.

**Comment by icculus** [comment]
The CMake check has `int main(void)` but doesn't return anything, and will probably fail if the user builds with CFLAGS="-Werror"

**Comment by sezero** [comment]
> The CMake check has `int main(void)` but doesn't return anything, and will probably fail if the user builds with CFLAGS="-Werror"

There are _many_ other such tests in sdlchecks.cmake, and I followed the
existing style. Should I add the return code still?

**Comment by icculus** [comment]
> There are _many_ other such tests in sdlchecks.cmake, and I followed the existing style. Should I add the return code still?

Oh. Never mind, then!

The patch looks fine to me, then, go ahead and push!

**Comment by sezero** [comment]
> The patch looks fine to me, then, go ahead and push!

Done, thanks.

**Comment by icculus** [comment]
> Done, thanks.

Thank _you_.  :)

I'll research the -Werror thing I mentioned for 2.0.20, in #5021, but it's not worth worrying about further for 2.0.18, if it's worth worrying about at all.

**Pull request merged**
