### PR TITLE
Making Haptic compact through alignment

### PR DESCRIPTION
**Pull request by JG-Adams**
Compiler insert padding to prevent alignment issue and sometime you end up wasting space.
So here I moved the 16bits type to follow after 32bits and only did it for struct that actually benefited from this.
The most impactful are SDL_HapticCondition which is the largest used in union.
you reduce this it take SDL_HapticEffect from 72 to 64 which fit nicely in cache line.
And SDL_Haptic from 128 to 120.

### CODE REVIEW

**Comment by JG-Adams** [comment]
This is inspired by #8753

**Comment by JG-Adams** [comment]
I mean to contribute to main branch. does this work?

**Comment by sezero** [comment]
I am not sure whether this is worth the trouble -- sdl2-compat will need to through another conversion procedure to accommodate the change if this is ever accepted.

>  What is patch-1?

Huh????

**Comment by sezero** [comment]
CC: @slouken

**Comment by JG-Adams** [comment]
@sezero I'm not sure what this conversion is about. Is it the DLL?
Why would it break?
If anyone could enlighten me on this. That would be nice. I am self taught so it's hard to know some things.

Maybe, if we could have a bunch more changes that need conversion procedure then we could do this?
Like maybe when SDL3 is about to finish? It is major change after all.

I think I understand what patch-1 is now. It's a locally generated repository. All good.

**Comment by sezero** [comment]
>  I'm not sure what this conversion is about.

It is this: https://github.com/libsdl-org/sdl2-compat

> Why would it break?

Since this patch changes the haptic structures, a conversion will be
needed between SDL3 and SDL2 versions of them.

> Maybe, if we could have a bunch more changes that need conversion procedure then we could do this? Like maybe when SDL3 is about to finish? It is major change after all.

Mainstainers (@slouken and/or @icculus) will decide

**Comment by icculus** [comment]
This doesn't seem like it's a serious cacheline hotspot...?

**Comment by sezero** [comment]
> This doesn't seem like it's a serious cacheline hotspot...?

Indeed

**Comment by sezero** [comment]
Close this? (Or, are we really interested?)

**Comment by slouken** [comment]
Let's leave it open for now. I'm not super excited about adding translation code for sdl2-compat, but conceptually this is something we'd want in SDL3.

**Comment by smcv** [comment]
I agree that saving a couple of bytes in a struct that is unlikely to be performance-critical doesn't seem like a strong enough justification for requiring sdl2-compat to carry translation code.

In #8753, @twhitehead notes that SDL_HAPTIC_SQUARE had to be omitted from the list of possible effects in SDL 2, because there were not enough bits in a 16-bit word to give each effect its own unique identifier. If someone wants to expand the number of possible effects to 32 by replacing a Uint16 with a Uint32, I think *that* would be a stronger justification for breaking binary compatibility and requiring sdl2-compat to carry translation code.

**Comment by smcv** [comment]
> here I moved the 16bits type to follow after 32bits and only did it for struct that actually benefited from this

Is SDL assuming that all of these structs have the type as their first bytes (the same pattern as `struct sockaddr`)? If it is, then re-ordering the fields to move the type to a later position would be a breaking change.

Strictly speaking, the `struct sockaddr` pattern is not actually valid in Standard C (it violates "strict aliasing"), and the Standard C way to do pseudo-object-orientation is to either make the "subclass" start with the "parent" struct:

```
typedef struct {
    Uint16 type;
} SDL_HapticBase;

typedef struct {
    SDL_HapticBase base; /* = { SDL_HAPTIC_CONSTANT } */
    ... other fields ...
} SDL_HapticConstant;

typedef struct {
    SDL_HapticBase base; /* = { SDL_HAPTIC_SINE } or _LEFTRIGHT or (etc.) */
    ... other fields ...
} SDL_HapticPeriodic;

...

SDL_HapticBase *base = ...;

switch (base->type)
{
    case SDL_HAPTIC_CONSTANT:
        SDL_HapticConstant *const = (SDL_HapticConstant *) base;
        ...;
        break;
    case SDL_HAPTIC_SINE:
    case SDL_HAPTIC_LEFTRIGHT:
    ...
        SDL_HapticPeriodic *periodic = (SDL_HapticPeriodic *) base;
        ...;
        break;
}
```

or use a tagged union:

```
typedef struct {
    ... other fields, but not type ...
} SDL_HapticConstant;

typedef struct {
    ... other fields, but not type ...
} SDL_HapticPeriodic;

typedef struct {
    Uint16 type;
    union {
        SDL_HapticConstant constant;
        SDL_HapticPeriodic periodic;
    } u;
} SDL_Haptic;

...

SDL_Haptic *haptic = ...;

switch (haptic->type)
{
    case SDL_HAPTIC_CONSTANT:
        SDL_HapticConstant *constant = haptic->u.constant;
        ...;
        break;
    case SDL_HAPTIC_SINE:
    case SDL_HAPTIC_LEFTRIGHT:
    ...
        SDL_HapticPeriodic *periodic = haptic->u.periodic;
        ...;
        break;
}
```

**Comment by icculus** [comment]
> In #8753, @twhitehead notes that SDL_HAPTIC_SQUARE had to be omitted from the list of possible effects in SDL 2

Oh yes, if we're doing this (and unless we're dumping the haptic subsystem completely, we _should_), then we can reshuffle the struct no problem.

**Pull request closed without merging**
