### PR TITLE
Added infrastructure for renaming API functions

### PR DESCRIPTION
**Pull request by slouken**
You can rename APIs using rename.py and all the code and documentation will be updated, and entries will be added to WhatsNew.txt and docs/README-migration.md.
e.g. `rename.py SDL_foo.h function SDL_CreateFoo SDL_FooCreate`

SDL_oldnames.h is included in the SDL header, and if you define SDL_ENABLE_OLD_NAMES, will redefine the old API functions to call the new ones, and if not, will define them as a symbol letting you what the new API function is.

### CODE REVIEW

**Comment by slouken** [comment]
This gives us the infrastructure to rename APIs however makes sense, as discussed in https://github.com/libsdl-org/SDL/issues/6569.

How do people feel about what was proposed in https://github.com/libsdl-org/SDL/issues/6569#issuecomment-1354412862?
eg, using category: 
`"Surface", "Thread", "Render", "Window", "Audio", "Joystick", "Thread"`

```
SDL_GetNumAudioDrivers => SDL_AudioGetNumDrivers
SDL_GetAudioDriver => SDL_AudioGetDriver
SDL_GetCurrentAudioDriver => SDL_AudioGetCurrentDriver
SDL_OpenAudio => SDL_AudioOpen
SDL_GetNumAudioDevices => SDL_AudioDeviceGetNum
SDL_GetAudioDeviceName => SDL_AudioDeviceGetName
SDL_GetAudioDeviceSpec => SDL_AudioDeviceGetSpec
SDL_GetDefaultAudioInfo => SDL_AudioGetDefaultInfo
SDL_OpenAudioDevice => SDL_AudioDeviceOpen
SDL_GetAudioStatus => SDL_AudioGetStatus
SDL_GetAudioDeviceStatus => SDL_AudioDeviceGetStatus
SDL_PauseAudio => SDL_AudioPause
SDL_PauseAudioDevice => SDL_AudioDevicePause
SDL_BuildAudioCVT => SDL_AudioBuildCVT
SDL_ConvertAudio => SDL_AudioConvert
SDL_NewAudioStream => SDL_AudioNewStream
SDL_FreeAudioStream => SDL_AudioFreeStream
SDL_MixAudio => SDL_AudioMix
SDL_MixAudioFormat => SDL_AudioMixFormat
SDL_QueueAudio => SDL_AudioQueue
SDL_DequeueAudio => SDL_AudioDequeue
SDL_GetQueuedAudioSize => SDL_AudioGetQueuedSize
SDL_ClearQueuedAudio => SDL_AudioClearQueued
SDL_LockAudio => SDL_AudioLock
SDL_LockAudioDevice => SDL_AudioDeviceLock
SDL_UnlockAudio => SDL_AudioUnlock
SDL_UnlockAudioDevice => SDL_AudioDeviceUnlock
SDL_CloseAudio => SDL_AudioClose
SDL_CloseAudioDevice => SDL_AudioDeviceClose
SDL_CreateShapedWindow => SDL_WindowCreateShaped
SDL_IsShapedWindow => SDL_WindowIsShaped
SDL_SetWindowShape => SDL_WindowSetShape
SDL_GetShapedWindowMode => SDL_WindowGetShapedMode
SDL_LockJoysticks => SDL_JoystickLock
SDL_UnlockJoysticks => SDL_JoystickUnlock
SDL_NumJoysticks => SDL_JoystickNum
SDL_GetJoystickGUIDInfo => SDL_JoystickGetGUIDInfo
SDL_CreateSurface => SDL_SurfaceCreate
SDL_CreateSurfaceFrom => SDL_SurfaceCreateFrom
SDL_FreeSurface => SDL_SurfaceFree
SDL_SetSurfacePalette => SDL_SurfaceSetPalette
SDL_LockSurface => SDL_SurfaceLock
SDL_UnlockSurface => SDL_SurfaceUnlock
SDL_SetSurfaceRLE => SDL_SurfaceSetRLE
SDL_HasSurfaceRLE => SDL_SurfaceHasRLE
SDL_SetSurfaceColorMod => SDL_SurfaceSetColorMod
SDL_GetSurfaceColorMod => SDL_SurfaceGetColorMod
SDL_SetSurfaceAlphaMod => SDL_SurfaceSetAlphaMod
SDL_GetSurfaceAlphaMod => SDL_SurfaceGetAlphaMod
SDL_SetSurfaceBlendMode => SDL_SurfaceSetBlendMode
SDL_GetSurfaceBlendMode => SDL_SurfaceGetBlendMode
SDL_DuplicateSurface => SDL_SurfaceDuplicate
SDL_ConvertSurface => SDL_SurfaceConvert
SDL_ConvertSurfaceFormat => SDL_SurfaceConvertFormat
SDL_Vulkan_CreateSurface => SDL_SurfaceVulkan_Create
SDL_CreateThread => SDL_ThreadCreate
SDL_CreateThreadWithStackSize => SDL_ThreadCreateWithStackSize
SDL_CreateThread => SDL_ThreadCreate
SDL_CreateThreadWithStackSize => SDL_ThreadCreateWithStackSize
SDL_GetThreadName => SDL_ThreadGetName
SDL_GetThreadID => SDL_ThreadGetID
SDL_SetThreadPriority => SDL_ThreadSetPriority
SDL_WaitThread => SDL_ThreadWait
SDL_DetachThread => SDL_ThreadDetach
SDL_WarpMouseInWindow => SDL_WindowWarpMouseIn
SDL_GetWindowWMInfo => SDL_WindowGetWMInfo
SDL_GetWindowDisplayIndex => SDL_WindowGetDisplayIndex
SDL_SetWindowDisplayMode => SDL_WindowSetDisplayMode
SDL_GetWindowDisplayMode => SDL_WindowGetDisplayMode
SDL_GetWindowICCProfile => SDL_WindowGetICCProfile
SDL_GetWindowPixelFormat => SDL_WindowGetPixelFormat
SDL_CreateWindow => SDL_WindowCreate
SDL_CreateWindowFrom => SDL_WindowCreateFrom
SDL_GetWindowID => SDL_WindowGetID
SDL_GetWindowFromID => SDL_WindowGetFromID
SDL_GetWindowFlags => SDL_WindowGetFlags
SDL_SetWindowTitle => SDL_WindowSetTitle
SDL_GetWindowTitle => SDL_WindowGetTitle
SDL_SetWindowIcon => SDL_WindowSetIcon
SDL_SetWindowData => SDL_WindowSetData
SDL_GetWindowData => SDL_WindowGetData
SDL_SetWindowPosition => SDL_WindowSetPosition
SDL_GetWindowPosition => SDL_WindowGetPosition
SDL_SetWindowSize => SDL_WindowSetSize
SDL_GetWindowSize => SDL_WindowGetSize
SDL_GetWindowBordersSize => SDL_WindowGetBordersSize
SDL_GetWindowSizeInPixels => SDL_WindowGetSizeInPixels
SDL_SetWindowMinimumSize => SDL_WindowSetMinimumSize
SDL_GetWindowMinimumSize => SDL_WindowGetMinimumSize
SDL_SetWindowMaximumSize => SDL_WindowSetMaximumSize
SDL_GetWindowMaximumSize => SDL_WindowGetMaximumSize
SDL_SetWindowBordered => SDL_WindowSetBordered
SDL_SetWindowResizable => SDL_WindowSetResizable
SDL_SetWindowAlwaysOnTop => SDL_WindowSetAlwaysOnTop
SDL_ShowWindow => SDL_WindowShow
SDL_HideWindow => SDL_WindowHide
SDL_RaiseWindow => SDL_WindowRaise
SDL_MaximizeWindow => SDL_WindowMaximize
SDL_MinimizeWindow => SDL_WindowMinimize
SDL_RestoreWindow => SDL_WindowRestore
SDL_SetWindowFullscreen => SDL_WindowSetFullscreen
SDL_GetWindowSurface => SDL_SurfaceGetWindow
SDL_UpdateWindowSurface => SDL_SurfaceUpdateWindow
SDL_UpdateWindowSurfaceRects => SDL_SurfaceUpdateWindowRects
SDL_SetWindowGrab => SDL_WindowSetGrab
SDL_SetWindowKeyboardGrab => SDL_WindowSetKeyboardGrab
SDL_SetWindowMouseGrab => SDL_WindowSetMouseGrab
SDL_GetWindowGrab => SDL_WindowGetGrab
SDL_GetWindowKeyboardGrab => SDL_WindowGetKeyboardGrab
SDL_GetWindowMouseGrab => SDL_WindowGetMouseGrab
SDL_GetGrabbedWindow => SDL_WindowGetGrabbed
SDL_SetWindowMouseRect => SDL_WindowSetMouseRect
SDL_GetWindowMouseRect => SDL_WindowGetMouseRect
SDL_SetWindowOpacity => SDL_WindowSetOpacity
SDL_GetWindowOpacity => SDL_WindowGetOpacity
SDL_SetWindowModalFor => SDL_WindowSetModalFor
SDL_SetWindowInputFocus => SDL_WindowSetInputFocus
SDL_SetWindowHitTest => SDL_WindowSetHitTest
SDL_FlashWindow => SDL_WindowFlash
SDL_DestroyWindow => SDL_WindowDestroy
SDL_GL_GetCurrentWindow => SDL_WindowGL_GetCurrent
SDL_EGL_GetWindowEGLSurface => SDL_SurfaceEGL_GetWindowEGL
SDL_GL_SwapWindow => SDL_WindowGL_Swap
SDL_GameControllerGetJoystick => SDL_JoystickGameControllerGet
SDL_HapticOpenFromJoystick => SDL_JoystickHapticOpenFrom
SDL_GetNumRenderDrivers => SDL_RenderGetNumDrivers
SDL_GetRenderDriver => SDL_RenderGetDriver
SDL_CreateWindowAndRenderer => SDL_RendererCreateWindowAnd
SDL_CreateRenderer => SDL_RendererCreate
SDL_CreateSoftwareRenderer => SDL_RendererCreateSoftware
SDL_GetRenderer => SDL_RendererGet
SDL_GetRendererInfo => SDL_RendererGetInfo
SDL_GetRendererOutputSize => SDL_RendererGetOutputSize
SDL_CreateTextureFromSurface => SDL_SurfaceCreateTextureFrom
SDL_LockTextureToSurface => SDL_SurfaceLockTextureTo
SDL_SetRenderTarget => SDL_RenderSetTarget
SDL_GetRenderTarget => SDL_RenderGetTarget
SDL_SetRenderDrawColor => SDL_RenderSetDrawColor
SDL_GetRenderDrawColor => SDL_RenderGetDrawColor
SDL_SetRenderDrawBlendMode => SDL_RenderSetDrawBlendMode
SDL_GetRenderDrawBlendMode => SDL_RenderGetDrawBlendMode
SDL_DestroyRenderer => SDL_RendererDestroy
SDL_SetWindowsMessageHook => SDL_WindowSetMessageHook
SDL_LinuxSetThreadPriority => SDL_ThreadLinuxSetPriority
SDL_LinuxSetThreadPriorityAndPolicy => SDL_ThreadLinuxSetPriorityAndPolicy
```

**Comment by slime73** [comment]
> How do people feel about what was proposed in https://github.com/libsdl-org/SDL/issues/6569#issuecomment-1354412862?

I don't have a strong opinion about the overall idea (reading documentation plus IDE fuzzy matching for autocomplete lists means the change isn't much of an improvement for me personally I think) - but some of the specifics are a bit weird:

`SDL_LockJoysticks => SDL_JoystickLock`: the plural is lost here, making it seem like it'd operate on a specific joystick.

`SDL_QueueAudio => SDL_AudioQueue`: I feel like the new name is a bit ambiguous. Before, it's "queue audio" which is pretty self-descriptive. Now it's "queue something(?) in the audio subsystem" if I'm following along with the general API style. This is minor but still feels like a bit of a regression.

`SDL_GetNumAudioDevices => SDL_AudioDeviceGetNum`, `SDL_NumJoysticks => SDL_JoystickNum`: I've always been a fan of Count over Num and I feel like Count makes more sense grammatically here - but it's another small nitpick.

`SDL_Vulkan_CreateSurface => SDL_SurfaceVulkan_Create`, `SDL_GL_SwapWindow => SDL_WindowGL_Swap`, etc: these feel pretty awkward with their underscore placement compared to the old versions.

 `SDL_SetWindowsMessageHook => SDL_WindowSetMessageHook`: the meaning of this got lost.

**Comment by slouken** [comment]
Conversely, if people prefer the SDL_VerbNoun format, are there other functions that we want to clean up instead?

**Comment by slouken** [comment]
I don't think we would want to be militant about this. I agree with all of your examples, I would for example use 'SDL_JoystickCount()` or `SDL_JoystickGetCount()` and I would leave `SDL_SetWindowsMessageHook()` alone.

**Comment by slouken** [comment]
I think the next step once we agree on a general direction is to add a comment for each header with proposed name changes (or maybe a separate issue, for discussion and tracking?)

**Comment by slouken** [comment]
@furious-programming, would you be willing to go through a few headers and create issues for each of them with a proposed naming change? If people generally like how it's shaping up, I can add commits here implementing those changes.

**Comment by icculus** [comment]
> SDL_QueueAudio => SDL_AudioQueue

Just as an example, this is where things get tricky, because one of these sounds like a function that does something, and the other sounds like an object you act upon. If I only saw the symbol, I'd assume the first is a function and the second one is a struct.

That's just a quirk of English, not a specific flaw here, but it's definitely something to watch out for.

I think the only thing that is certain is that whoever makes the first pass at this should expect to get some percentage of negative feedback and run under the assumption they might be throwing it away. We're in that awful moment of API redesign where something seems like a good idea until you do the work and find out it isn't, but it has to be done to find out. It's happened to me _twice_ today.  :)

It's possible we change all these and say "this is better" or it's possible we change them and say "SDL_CreateWindow was clear and friendly and SDL_WindowCreate feels clinical and I don't know why that is or why this should matter but it does" and then we just fix the SDL_RenderSetX/SDL_SetRenderY mistakes instead and call it a day.

That being said: we _are_ going to rename _some_ things no matter what, so the infrastructure in this PR is good no matter what.

**Comment by slouken** [comment]
Yup, totally agreed on all of this. I suggested @furious-programming because I think of all of us he’ll do the best job of suggesting helpful changes.

**Comment by furious-programming** [comment]
> I don't have a strong opinion about the overall idea (reading documentation plus IDE fuzzy matching for autocomplete lists means the change isn't much of an improvement for me personally I think) - but some of the specifics are a bit weird:

@slime73: the general idea was to **unify the naming of library elements** by establishing one universal pattern. Making identifier searches easier, whether through IDE tools or searching for text in any text editor (like Vim, Notepad++ etc.), would be an added advantage.

> `SDL_LockJoysticks => SDL_JoystickLock`: the plural is lost here, making it seem like it'd operate on a specific joystick.

The plural must be preserved, so the function should be called `SDL_JoysticksLock`.

I have several "subsystems" in my game project that distinguish singular from plural. Some units (as Pascal source files) contain the functionality of one piece of object, others are a kind of managers of a collection of a given type of objects. For example:

- `Game_Gamepad` — unit containing an object type declaration representing any gamepad (actually any SDL joystick) and a set of functions to handle it (constructor, destructor, getters, setters and general purpose functions). All functions that operate on a gamepad object have the prefix `Game_Gamepad*` (singular form).
- `Game_Gamepads` — unit containing an internal list of gamepads and a set of functions operating on the pool of available devices. All gamepad pool manipulation functions have the prefix `Game_Gamepads*` (plural form).

The same for keyboard(s), mouse(s), stick(s) and window(s), and there will be many more in the future.

> `SDL_QueueAudio => SDL_AudioQueue`: I feel like the new name is a bit ambiguous. Before, it's "queue audio" which is pretty self-descriptive. Now it's "queue something(?) in the audio subsystem" if I'm following along with the general API style. This is minor but still feels like a bit of a regression. Maybe `SDL_AudioQueueSampleData` or something similar would work well.

And here we have a problem, because `SDL_AudioQueue` can be interpreted in two ways — as mentioned, as a function and as an object type.

In my current project (and any other) I don't have this type of problem because Pascal has a different naming convention than C. In Pascal languages, the data type is always preceded by the letter `T`, the pointer by `P`, the interface by `I`, the argument by `A`. So in this case, I would have three different identifiers, making it clear what the identifier represents:

- `TSDL_AudioQueue` — data type representing the queue of the audio subsystem,
- `PSDL_AudioQueue` — a pointer to the above data type (`PPSDL_AudioQueue` as a double pointer),
- `SDL_AudioQueue` — the queuing function from the audio subsystem.

In the C language, there is no such thing (and I would rather not suggest using it, because C programmers probably won't love it), so it remains to add something to the end of the `SDL_AudioQueue*` identifier, so that it is clear what exactly you want to queue.

> `SDL_GetNumAudioDevices => SDL_AudioDeviceGetNum`, `SDL_NumJoysticks => SDL_JoystickNum`: I've always been a fan of Count over Num and I feel like Count makes more sense grammatically here - but it's another small nitpick.

Pascal also uses `Count` everywhere, but I like the current `Num` better because it's shorter and just as clear. A matter of taste. BTW, it should be `SDL_AudioDevicesGetNum` and `SDL_JoysticksGetNum` — these are getters, so they should have the `Get` words.

> `SDL_Vulkan_CreateSurface => SDL_SurfaceVulkan_Create`, `SDL_GL_SwapWindow => SDL_WindowGL_Swap`, etc: these feel pretty awkward with their underscore placement and name order compared to the old versions.

You're misinterpreting it a bit. The `SDL_GL_` and `SDL_Vulkan_` prefixes are extraordinary, so they should remain so. These functions, by the convention I suggested, should be named `SDL_Vulkan_SurfaceCreate` and `SDL_GL_WindowSwap`.

> `SDL_SetWindowsMessageHook => SDL_WindowSetMessageHook`: the meaning of this got lost.

Not for me, because it is known what subsystem the function comes from — `SDL_Window` — and what it does — `SetMessageHook`. What if I added a `_`? If I did, you would have no problem understanding what the `SDL_Window_SetMessageHook` function does, just as you now have no problem understanding what the `SDL_GL_SwapWindow` function does.
___

What I use myself and what I originally proposed is to use the following pattern:

```
Prefix         Subsystem    Infix    Postfix

SDL_           Window       Get      Num
SDL_GL_        Mouse        Set      (any other)
SDL_Vulkan_    Keyboard     Has
...            Joystick     Is
               Audio
               Video
               Renderer
               ...
```
Explanation:

- **Prefix** — the prefix is mandatory, specifying which API the identifier comes from. It cannot be changed, it cannot be omitted, must be terminated with a `_` character.
- **Subsystem** — the name of the subsystem is mandatory, it can consist of one or more words (probably no more than two words), it cannot be omitted. It can be singular or plural, depending on whether it is for a single object operation or for an object pool manager.
- **Infix** — optional, intended only for a function, and only to mark it as a getter or setter.
- **Postfix** — mandatory, containing any object name or verb, can consist of any number of words. If the function is used to get the number of some objects, it must have the `Num` prefix (e.g. `SDL_JoystickGetNumButtons`).

Postfixes should be constructed in such a way that they **share initial words**. Earlier I gave some such examples:

```
SDL_WindowCreate
SDL_WindowCreateFrom
SDL_WindowUpdateSurface
SDL_WindowUpdateSurfaceRects
```
But if you don't want to, then you can ignore it. I use this myself because it makes it easier for me to filter IDs in the **completion box**. If you don't use completion box, or the completion box can filter in such a way that it splits the identifier into substrings and matches them ignoring the order of the substrings in the identifier, then the above will not be necessary.

Now you need to consider whether you really want to use such a pattern, and if so, you need to check all edge cases (mainly data type names) to make sure that the C naming convention does not cause conflicts and introduce ambiguity. Perhaps the best solution would be to list all the identifiers that exist in the library, group them by subsystem, and then prepare equivalents that match the pattern. In this way, you can quickly check everything and confirm or refute the reasonableness of using the pattern.

**Comment by slouken** [comment]
Okay, I'll take a first pass at this.

My approach will be to use `SDL_ObjectFunction()` for functions that take an object as the first parameter, and then rename any functions that are clearly out of line with the others.

**Comment by 1bsyl** [comment]
@slouken .. I suggest not to do it manually, but generate all potential renaming like in #6569 . only review all renaming manually to make sure they make sense ...

**Comment by 1bsyl** [comment]
Half related to #6869 #6772 . but shouldn't then event be named more like `SDL_EVENT_* `:
`SDL_EVENT_WINDOW_CLOSE` for instance, instead of `SDL_WINDOWEVENT_CLOSE`.

**Comment by slouken** [comment]
I'm going to go ahead and commit this infrastructure, and we can continue the discussion of how we actually want to change things in https://github.com/libsdl-org/SDL/issues/6569

**Pull request merged**
