### PR TITLE
cmake: don't prepend absolute CMAKE_INSTALL_{INCLUDE,LIB}DIR with ${p…refix}

### PR DESCRIPTION
**Pull request by madebr**
Fixes #10246

## Existing Issue(s)

@getchoo
@OPNA2608

### CODE REVIEW

**Comment by OPNA2608** [comment]
`libdir` and `includedir` now look fine with absolute `*DIR` values, thanks.

```
↪ cat /nix/store/bfw1yzm446rf2j5z1w8iixbrchv8w8ps-sdl3-3.1.2-unstable-2024-08-01-dev/lib/pkgconfig/sdl3.pc 
prefix=${pcfiledir}/../../../../..
exec_prefix=${prefix}
libdir=/nix/store/rw4mzycm62zi89rkx8z40b48r1qgr5pd-sdl3-3.1.2-unstable-2024-08-01-lib/lib
includedir=/nix/store/bfw1yzm446rf2j5z1w8iixbrchv8w8ps-sdl3-3.1.2-unstable-2024-08-01-dev/include
```

`prefix` actually looks abit broken still as you can see, but I don't think that would be an issue for our pkg-config usage.

<details>
  <summary>Details for the prefix issue, if you want to look into it</summary>

https://github.com/libsdl-org/SDL/blob/ee65176eec3eef062388bb63da7d57281c7c2e67/cmake/sdltargets.cmake#L345-L347
https://github.com/libsdl-org/SDL/blob/ee65176eec3eef062388bb63da7d57281c7c2e67/CMakeLists.txt#L3376-L3381

This constructs i.e. `/nix/store/fd93ss4y6jibzdrhhghw7z361zj67x1s-sdl3-3.1.2-unstable-2024-08-01//nix/store/rw4mzycm62zi89rkx8z40b48r1qgr5pd-sdl3-3.1.2-unstable-2024-08-01-lib/lib/pkgconfig`, so it arrives at `../../../../..` for `SDL_PATH_PREFIX_RELATIVE_TO_PKGCONFIG`.

</details>

**Comment by madebr** [comment]
What `CMAKE_INSTALL_PREFIX` is nix using?

**Comment by OPNA2608** [comment]
`CMAKE_INSTALL_PREFIX` uses the pattern `/nix/store/<hash>-<name>-<version>`, with `<hash>` being calculated from the build inputs (source, dependencies & their hashes, flags, build script, …). The various `CMAKE_INSTALL_*DIR` variables are either pointing to the corresponding path within another output-suffixed prefix (i.e. `CMAKE_INSTALL_INCLUDEDIR=/nix/store/bfw1yzm446rf2j5z1w8iixbrchv8w8ps-sdl3-3.1.2-unstable-2024-08-01-dev/include` for the `dev` output of the package) for buildtime/runtime dependency splitting purposes, or absolute paths within the main prefix (for consistency with the output-split behaviour).

<details>
  <summary>An example of the CMake flags passed during a specific build</summary>

`
cmake flags: -GNinja -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/9b20b07d4d90kbpqx5hhv5g7p96m8ai2-sdl3-3.1.2-unstable-2024-08-01-lib/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/9b20b07d4d90kbpqx5hhv5g7p96m8ai2-sdl3-3.1.2-unstable-2024-08-01-lib/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/9b20b07d4d90kbpqx5hhv5g7p96m8ai2-sdl3-3.1.2-unstable-2024-08-01-lib/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/q8nb71x5973psbdn3fnjkd6mwkgnn39g-sdl3-3.1.2-unstable-2024-08-01/share/doc/SDL3 -DCMAKE_INSTALL_INFODIR=/nix/store/q8nb71x5973psbdn3fnjkd6mwkgnn39g-sdl3-3.1.2-unstable-2024-08-01/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/q8nb71x5973psbdn3fnjkd6mwkgnn39g-sdl3-3.1.2-unstable-2024-08-01/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/064j09jaw7jkl81c25jaq7771n5n8hzx-sdl3-3.1.2-unstable-2024-08-01-dev/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/064j09jaw7jkl81c25jaq7771n5n8hzx-sdl3-3.1.2-unstable-2024-08-01-dev/include -DCMAKE_INSTALL_SBINDIR=/nix/store/q8nb71x5973psbdn3fnjkd6mwkgnn39g-sdl3-3.1.2-unstable-2024-08-01/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/q8nb71x5973psbdn3fnjkd6mwkgnn39g-sdl3-3.1.2-unstable-2024-08-01/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/9b20b07d4d90kbpqx5hhv5g7p96m8ai2-sdl3-3.1.2-unstable-2024-08-01-lib/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/ld63wvvwm43a6rqv24g52izq19qn937v-clang-wrapper-16.0.6/bin/strip -DCMAKE_RANLIB=/nix/store/ld63wvvwm43a6rqv24g52izq19qn937v-clang-wrapper-16.0.6/bin/ranlib -DCMAKE_AR=/nix/store/ld63wvvwm43a6rqv24g52izq19qn937v-clang-wrapper-16.0.6/bin/ar -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_INSTALL_PREFIX=/nix/store/q8nb71x5973psbdn3fnjkd6mwkgnn39g-sdl3-3.1.2-unstable-2024-08-01
`

</details>

**Comment by madebr** [comment]
Thanks for explaining nix'es requirements to me :)

**Pull request merged**
