### PR TITLE
audio: pipewire: Remove hardcoded upper sample limits

### PR DESCRIPTION
**Pull request by Kontrabant**
This removes the previously hard coded 8192 upper sample limit when dealing with Pipewire buffers and latency and instead uses the buffer size set by Pipewire to clamp the spec.samples/spec.size values in addition to calculating the intermediate input buffer packet size.  This can allow the backend to avoid double-buffering in the output path when a higher latency is requested by the application as the output is only double buffered if the Pipewire buffer is too small, and the input path can avoid having to allocate extra packets in the data queue if Pipewire's new "clock.force-quantum" setting is used to increase buffer sizes, which can dramatically increase the amount of data delivered in the input callback.

The first patch in this series is just a minor bit of prep work as the stream initialization condition variable need not be atomic since it is guarded by a mutex, and converting it to a standard int makes using it with bitflags in the following commit a bit easier.

### CODE REVIEW

**Review by flibitijibibo — APPROVED** [review]
This still works for me, but I wasn't hitting the caps this patch is meant for.

@icculus will be a better judge of the capture changes than me, the 4x buffer makes sense to me but I don't know if there's a better way to deal with that.

**Comment by Kontrabant** [comment]
Thinking about it, now that it's using the absolute largest possible value of either the requested period or the Pipewire buffer size to determine the packet length, a packet size of 2x the larger of the two should be more than enough to catch the maximum possible amount of overrun.

**Comment by Kontrabant** [comment]
No changes, just re-pushed to re-run the checks since the unrelated UWP build failure was fixed upstream.  Everything passes now.

**Comment by flibitijibibo** [comment]
Gave it another look and and it's still fine... I took a look at the capture side too and it should pretty much act the same as it did before, but with slightly more work being deferred to the thread which is nice. So, this should be fine I think!

**Pull request merged**
