### PR TITLE
Create SDL-static vcxproj

### PR DESCRIPTION
**Pull request by playmer**
For those who need a vcxproj that generates a statically linked version of SDL, this supplies one.

## Description
I pretty much just copied the exiting vcxproj that generates a DLL, and adjusted it to make a statically compiled version. I made adjustments to the sln and the associated GUID so there wasn't a clash. The only iffy thing I'm immediately aware of is that this  links against the crt statically, as it's what was needed for my task. I know the DLL vcxproj links dynamically. 

Let me know if any adjustments are needed, happy to fix things!

### CODE REVIEW

**Comment by cgutman** [comment]
It would reduce duplication by just adding DebugStatic and ReleaseStatic build configurations to the existing SDL.vcxproj instead of creating a new one

**Comment by playmer** [comment]
Hmm, I don't think that solves the particular problem I'm trying to solve for (although I could be wrong). Part of the reason I need a new vcxproj is so that it can be included in a solution from another project that will include SDL as a submodule.

Were I to simply include newly named configs, When set to for example Release, we'd be linking against the DLL version of SDL. I could probably work around this somehow, but it would be somewhat of a hack (at least in the ways that immediately come to mind).

That said I could absolutely be missing something. I'm much more of a CMake person than MSBuild, but the project I'm working on handles dependencies and their build this way, so I'm attempting to do it their way. They could also potentially maintain a small fork for this, but I figured it might be useful to others as well.

**Comment by cgutman** [comment]
You can set your solution configuration to build whatever build configuration of the projects that you want. It wouldn’t have to always build Release just because the solution’s build configuration is called Release.

You could map the Release configuration in your solution to build ReleaseStatic in SDL.vcxproj.

**Comment by playmer** [comment]
Thanks I'll take a look tomorrow at mapping it over and and report back. Assuming all is good I'll switch it over! Appreciate the tip!

**Pull request closed without merging**
