### PR TITLE
Add SDL_SCANCODE_SOFTLEFT and SDL_SCANCODE_SOFTRIGHT

### PR DESCRIPTION
**Pull request by ccawley2011**
These are used in the Android and N-Gage video drivers,

The N-Gage backend also mentions "Green softkey" and "Red softkey" which may be equivalent to `AKEYCODE_CALL` and `AKEYCODE_ENDCALL` on Android. If it is, I can add those to this PR as well.

### CODE REVIEW

**Comment by mupfdev** [comment]
`AKEYCODE_CALL` and `AKEYCODE_ENDCALL` would indeed be the most appropriate keycodes.
However, they cannot in fact be used (yet). For example, the end call button would push the application into the background.
Just for the record, since this is not the issue here.

**Comment by mupfdev** [comment]
Of course, the softkeys on the left and right below the display are usually used for menu navigation. Full-screen applications usually use the buttons for the same purpose, since it simply makes sense. The green and red softkeys are used for accepting and rejecting calls, as already mentioned. After all, the N-Gage is a cell phone.

In addition, there is a D-PAD with 4 directions that can be pressed on the Classic model. The QD model has a separate button for this.

In addition there is a `C` button for deleting text and a button with a pen icon, which is currently not handled. In games, this key is usually not assigned. The number field with the asterisk and hash is self-explanatory, with special meaning assigned to the `5` and `7` keys. These keys are slightly elevated and are often the most important keys in games.

**Comment by slouken** [comment]
@ccawley2011, can you update the PR to add documentation for the softkey scancodes?

**Comment by mupfdev** [comment]
What would be the most appropriate keycode for the confirmation button?

**Comment by slouken** [comment]
@ccawley2011, can you add documentation for the call and end call scancodes? :)

**Comment by slouken** [comment]
It might also be worth noting that these are usually handled by the OS and not available to SDL applications. In fact, maybe we should just omit them entirely?

Do we need equivalent SDLK_* keycodes for these?

**Comment by smcv** [comment]
Linux evdev has `KEY_PICKUP_PHONE` and `KEY_HANGUP_PHONE` which seem like maybe they're meant to be the same thing as the green and red start/end call keys, although I can't actually find where Android maps evdev key codes to Android key codes.

Meanwhile, the left/right softkeys look like these are meant to be the same thing:

```
/*
 * Some keyboards have a buildin LCD panel where the contents are controlled
 * by the host. Often these have a number of keys directly below the LCD
 * intended for controlling a menu shown on the LCD. These keys often don't
 * have any labeling so we just name them KEY_KBD_LCD_MENU#
 */
#define KEY_KBD_LCD_MENU1               0x2b8
#define KEY_KBD_LCD_MENU2               0x2b9
#define KEY_KBD_LCD_MENU3               0x2ba
#define KEY_KBD_LCD_MENU4               0x2bb
#define KEY_KBD_LCD_MENU5               0x2bc
```

**Comment by smcv** [comment]
... or maybe not, since that says "keyboard" which is not the case for an N-Gage.

**Comment by mupfdev** [comment]
What is the next step here?

**Comment by slouken** [comment]
I merge Cameron's change. :)

**Pull request merged**
