### PR TITLE
Made event and temporary string memory thread-local and added SDL_FreeEventMemory()

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/10283

### CODE REVIEW

**Comment by madebr** [comment]
Is all TLS, event and temporary storage, ... cleared on `SDL_Quit`?
In other words, all SDL threads must be stopped when calling it?

**Comment by slouken** [comment]
> Is all TLS, event and temporary storage, ... cleared on `SDL_Quit`? In other words, all SDL threads must be stopped when calling it?

It's all cleared in SDL_Quit() for whatever thread calls that, and for other threads after they quit.

**Comment by madebr** [comment]
> > Is all TLS, event and temporary storage, ... cleared on `SDL_Quit`? In other words, all SDL threads must be stopped when calling it?
> 
> It's all cleared in SDL_Quit() for whatever thread calls that, and for other threads after they quit, or call SDL_CleanupTLS().

Thanks. I was worried we were pulling the rug from under other threads.

**Comment by slouken** [comment]
> > > Is all TLS, event and temporary storage, ... cleared on `SDL_Quit`? In other words, all SDL threads must be stopped when calling it?
> > 
> > 
> > It's all cleared in SDL_Quit() for whatever thread calls that, and for other threads after they quit, or call SDL_CleanupTLS().
> 
> Thanks. I was worried we were pulling the rug from under other threads.

Nope, it's all good. :)

**Review by icculus — APPROVED** [review]

**Comment by icculus** [comment]
Once this merges, we need to fixup sdl2-compat to do the right thing in SDL2's SDL_TLSCreate.

**Comment by slouken** [comment]
> Once this merges, we need to fixup sdl2-compat to do the right thing in SDL2's SDL_TLSCreate.

Yup.

**Comment by icculus** [comment]
Okay, wait, I'm hacking out the sdl2-compat stuff right now: why does SDL_GetTLS want a pointer if it never creates an ID?

**Comment by icculus** [comment]
(I say this because a) it's confusing and b) I need a way to create an ID without actually setting any thread-local data on it, and SDL_GetTLS seems like a reasonable way to do that.)

**Comment by icculus** [comment]
> why does SDL_GetTLS want a pointer if it never creates an ID?

Oh, it's an SDL_AtomicInt now. Okay, uh, do we really want this? We could just throw a spinlock in the one place that needs to create a TLSID without a reasonable point to add an explicit creation operation before it, instead of every TLS operation needing atomics.

**Comment by slouken** [comment]
Just initialize it with a non-zero value, the one returned from SDL_CreateTLS(), and it'll be fine.

**Comment by slouken** [comment]
I can take care of this here, it's not a big deal.

**Comment by slouken** [comment]
Super easy implementation:
```c
typedef Uint32 SDL2_TLSID;

SDL2_TLSID SDL_CreateTLS(void)
{
    static SDL_AtomicInt SDL_tls_id;
    return (SDL2_TLSID)(SDL_AtomicIncRef(&SDL_tls_id) + 1);
}

void *SDL_GetTLS(SDL2_TLSID id)
{
    SDL_AtomicInt id3 = { (int)id };
    return SDL3_GetTLS(&id3);
}

void *SDL_SetTLS(SDL2_TLSID id, const void *value, SDL_TLSDestructorCallback destructor)
{
    SDL_AtomicInt id3 = { (int)id };
    return SDL3_GetTLS(&id3, value, destructor);
}
```

**Pull request merged**
