### PR TITLE
 name checking v2

### PR DESCRIPTION
**Pull request by 1bsyl**
2nd attempt to have name checking, using a less scary way:

SDL_common.h: is the old SDL_internal.h content
SDL_internal.h : embeds the name checking, and include common.h
SDL_internal_lite.h:  just include common.h

By default all file include SDL_internal and have the name checking.
for problematic file, we change to use SDL_internal_lite.h.

temporary: I disable the cmake precompiler header SDL_internal.h because of errors.
 but maybe SDL_internal_lite.h and SDL_internal.h 
should both be precompiled header to get this working.

issue: https://github.com/libsdl-org/SDL/issues/7825
fist pr: https://github.com/libsdl-org/SDL/pull/7864

### CODE REVIEW

**Comment by meyraud705** [comment]
I noticed the check for `free` is missing. I did not fully check for all functions so maybe others are missing. Did you use a script to find all std functions?

**Comment by slouken** [comment]
@1bsyl, I appreciate the work you put into this, but please don't check it in. Let's instead have a separate optional header that we can include that does the stdlib redefining and we can optionally include that when we want to check for stdlib issues. Issues in common code will be caught by the MSVC build, so it's only other platforms where it matters.

**Comment by madebr** [comment]
In https://github.com/libsdl-org/SDL/issues/6622#issuecomment-1489600052, I did some attempts in building SDL without libc.
Perhaps my objdump regex can be used in a post-build check, to make sure only allowed symbols are used from the c library?

**Comment by 1bsyl** [comment]
ok, not sure what should be actually done here... so here's the code, to generate some file.

eventually: add "free" to the list and/or remove "memset"


```
#!/usr/bin/env python3
words = [ 'abs', 'acos', 'acosf', 'asin', 'asinf', 'asprintf', 'atan', 'atan2', 'atan2f', 'atanf', 'atof', 'atoi', 'calloc', 'ceil',
'ceilf', 'copysign', 'copysignf', 'cos', 'cosf', 'crc32', 'exp', 'expf', 'fabs', 'fabsf', 'floor', 'floorf', 'fmod', 'fmodf',
'getenv', 'isalnum', 'isalpha', 'isblank', 'iscntrl', 'isdigit', 'isgraph', 'islower', 'isprint', 'ispunct', 'isspace', 'isupper', 'isxdigit', 'itoa', 'lltoa', 'log10', 'log10f',
'logf', 'lround', 'lroundf', 'ltoa', 'malloc', 'memcmp', 'memcpy', 'memcpy4', 'memmove', 'memset', 'pow', 'powf', 'qsort', 'realloc', 'round', 'roundf', 'scalbn',
'scalbnf', 'setenv', 'sin', 'sinf', 'snprintf', 'sqrt', 'sqrtf', 'sscanf', 'strcasecmp', 'strchr', 'strcmp', 'strdup', 'strlcat', 'strlcpy', 'strlen', 'strlwr', 'strncasecmp', 'strncm
p', 'strrchr', 'strrev', 'strstr', 'strtod', 'strtokr',
'strtol', 'strtoll', 'strtoul', 'strupr', 'tan', 'tanf', 'tolower', 'toupper', 'trunc', 'truncf', 'uitoa', 'ulltoa', 'ultoa', 'utf8strlcpy', 'utf8strlen', 'vasprintf', 'vsnprintf', 'v
sscanf', 'wcscasecmp',
'wcscmp', 'wcsdup', 'wcslcat', 'wcslcpy', 'wcslen', 'wcsncasecmp', 'wcsncmp', 'wcsstr' ]


for i in words:
   print("#ifdef %s" % i)
   print("#undef %s" % i)
   print("#endif")
   print("#define %s Please_use_SDL_%s_instead" % (i, i))

```

**Comment by slouken** [comment]
Maybe instead of trying to do this via a header, we can just write a script in build-scripts that runs through the source code and verifies usage of stdlib functions?

**Comment by 1bsyl** [comment]
@slouken 
yes, sounds less problematic: https://github.com/libsdl-org/SDL/pull/7876

**Comment by slouken** [comment]
Looks good, thanks!

**Pull request closed without merging**
