### PR TITLE
Rename functions in SDL_system.h to match SDL 3.0 naming convention

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/10277

### CODE REVIEW

**Comment by sezero** [comment]
This was the worst..

Will be patching sdl2-compat shortly for it.

**Comment by slouken** [comment]
> This was the worst..
> 
> Will be patching sdl2-compat shortly for it.

Thank you!

**Comment by slouken** [comment]
Fortunately, I think we're about done renaming functions for SDL 3.0.

**Comment by sezero** [comment]
> Fortunately, I think we're about done renaming functions for SDL 3.0.

That frenzy is hopefully done

This is the worst, because now you have SDL_SetAndroidThis along with SDL_AndroidThat etc inconsistencies. I wish these were left as they had been...

**Comment by slouken** [comment]
> > Fortunately, I think we're about done renaming functions for SDL 3.0.
> 
> That frenzy is hopefully done
> 
> This is the worst, because now you have SDL_SetAndroidThis along with SDL_AndroidThat etc inconsistencies. I wish these were left as they had been...

Oh? I’ll have to go look in the morning. The intent was to make them consistent.

**Comment by slouken** [comment]
> This is the worst, because now you have SDL_SetAndroidThis along with SDL_AndroidThat etc inconsistencies. I wish these were left as they had been...

You're right, that was the worst, I'm sorry. I finished the renaming in https://github.com/libsdl-org/SDL/pull/10289.

**Pull request merged**
