### PR TITLE
cocoa/uikit: Support VK_EXT_metal_surface

### LINKED ISSUE #3906: VK_MVK_ios_surface and VK_MVK_macos_surface deprecated by VK_EXT_metal_surface
# This bug report was migrated from our old Bugzilla tracker.

**Reported in version:** HG 2.1
**Reported for operating system, platform:** Mac OS X (All), x86_64

# Comments on the original bug report:

On 2020-12-04 20:03:59 +0000, Diego wrote:

> Not so much a bug as information.
> Similarly vkCreateMacOSSurfaceMVK and vkCreateIOSSurfaceMVK are deprecated by vkCreateMetalSurfaceEXT.

### PR DESCRIPTION
**Pull request by encounter**
Uses `VK_EXT_metal_surface` (`vkCreateMetalSurfaceEXT`) when possible, otherwise falls back to the obsoleted `VK_MVK_macos_surface` and `VK_MVK_ios_surface`.

## Description
See documentation for [VK_EXT_metal_surface](https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VK_EXT_metal_surface.html).

`SDL_cocoavulkan.m` and `SDL_uikitvulkan.m` are nearly identical now, the shared code can likely be easily extracted, but I will leave that as a future improvement.

## Existing Issue(s)
Fixes #3906

### CODE REVIEW

**Comment by slouken** [comment]
@slime73, how does this look?

**Review by slime73 — COMMENTED** [review]
Do `Cocoa_Vulkan_GetInstanceExtensions` and `UIKit_Vulkan_GetInstanceExtensions` need to be updated as well?

**Comment by encounter** [comment]
Thanks, I create my Vulkan instance externally, so I missed that.

Since there doesn't appear to be an existing way to check supported extensions when building SDL_Vulkan_GetInstanceExtensions, I simply replaced the legacy extensions with `VK_EXT_metal_surface`.

This may require a Vulkan SDK update for those using SDL_Vulkan_GetInstanceExtensions, but this extension has been supported since 2019, so it seems relatively minor.

**Review by slime73 — APPROVED** [review]
Seems reasonable to me. However I haven't used Vulkan with SDL yet myself, so maybe someone with that experience should look at it too.

**Comment by icculus** [comment]
I say yes on this, but let's merge right after 2.24 finalizes.

**Review by icculus — APPROVED** [review]

**Pull request merged**
