### PR TITLE
Fix compatibility with Windows XP

### LINKED ISSUE #6189: CreateEventEx not available in XP
Noticed in an issue report at https://discourse.libsdl.org/t/xp-and-createeventexw-in-kernel32-dll/38605
A fix is needed along with a backport of it to the release branch.

CreateEventEx seems to be used in newly added d3d12 renderer:
https://github.com/libsdl-org/SDL/blob/main/src/render/direct3d12/SDL_render_d3d12.c#L1002

### PR DESCRIPTION
**Pull request by ccawley2011**
Fixes #6189.

### CODE REVIEW

**Comment by sezero** [comment]
This looks good to me: @slouken?

**Comment by sezero** [comment]
Fix cherry-picked into release-2.24.x branch as e70db38d6039b356d2f175214214b6c67f7d3e37

**Comment by slouken** [comment]
We use CreateEventEx() in a bunch of other places as well. Do they need to be reviewed and/or fixed?

**Comment by sezero** [comment]
No: windows/SDL_systimer.c uses it only for WINRT, audio/wasapi/SDL_wasapi.c uses it only for WINRT or GDK. d3d12 was the only one that hadn't checked it.

**Pull request merged**
