### PR TITLE
Updated structure and field names for consistency

### PR DESCRIPTION
**Pull request by slouken**
Type names are camel case and field names are snake case except for fields ending in id, which are capitalized.

Fixes https://github.com/libsdl-org/SDL/issues/6955

### CODE REVIEW

**Comment by slouken** [comment]
I have a follow-up PR for sdl2-compat, once this is merged.

**Review by sezero — APPROVED** [review]
I never liked most of the renames and such, but OK by me. @icculus and/or @madebr may have more to say.

**Comment by slime73** [comment]
The SDL_PixelFormat structure still seems a little weird with `bits_per_pixel` versus `Rmask` versus `refcount` all in the same struct, but I don't really have a strong opinion about it. `SDL_AudioDeviceEvent` also has `iscapture` rather than `is_capture`.

**Comment by slouken** [comment]
@icculus, we talked about changing `iscapture`, where did we land on that?

**Comment by icculus** [comment]
I don't remember if we landed at all, honestly.

We can go with `is_capture` or just `capture`, both of which are fine with me.

We can even go so far as to _remove_ the term "capture" from the API and call things "recording" or "input" or whatever, which I'm sort of wishing we do before SDL3 is married to it, honestly.

**Comment by slouken** [comment]
> We can even go so far as to _remove_ the term "capture" from the API and call things "recording" or "input" or whatever, which I'm sort of wishing we do before SDL3 is married to it, honestly.

Go for it. Now's the time, I'm about to flip on the ABI lockdown soon after your video capture, sorry, recording, changes.

**Comment by icculus** [comment]
> video capture, sorry, recording, changes.

lol

**Pull request merged**
