### PR TITLE
ci: build SDL on macos 14 (arm64)

### PR DESCRIPTION
**Pull request by madebr**
The `stdlib_swprintf` test also fails on SDL3

## Existing Issue(s)
https://github.com/libsdl-org/SDL/issues/9606

### CODE REVIEW

**Comment by slouken** [comment]
We can drop the macos13 artifact. In general we should be tracking the latest compilers and OS that Apple provides, as they quickly require them for shipping on the App Store.

In general I'd like to split the builders so we have a small representative set that builds on each commit and a more complete set that runs once a day or so. 38 builders for each commit seems insane, and takes forever when GitHub prioritizes build resources elsewhere.

**Comment by madebr** [comment]
I removed the x86_64 job.

**Comment by sezero** [comment]
As far as I can see, the 'GNU prefix' thing relies on macos-latest to be macos-12 which may change soon

**Comment by madebr** [comment]
> As far as I can see, the 'GNU prefix' thing relies on macos-latest to be macos-12 which may change soon

Yeah, I preferred to keep the `-latest` machine and rely on GitHub bumping the actual machine.
Like soon, `ubuntu-latest` will also jump to `ubuntu-24.04`.

**Comment by sezero** [comment]
OK, what do we do now? Fix test errors before merging or the other way around?

**Comment by madebr** [comment]
> OK, what do we do now? Fix test errors before merging or the other way around?

I'd wait for an Apple guy to reproduce and fix the (SDL2) issue. Our mailboxes would get spammed with failed-build-mails.

**Comment by sezero** [comment]
>  fix the (SDL2) issue. 

What is the SDL2 issue?

**Comment by madebr** [comment]
> > fix the (SDL2) issue.
> 
> What is the SDL2 issue?

Doesn't SDL2 suffer from similar issues, as you were seeing yesterday?
If not, then all is good :)

**Comment by sezero** [comment]
libsdl-org workflows are now running on macos-14, as it seems:
https://github.com/libsdl-org/SDL/actions/runs/8836336944/job/24262651643

**Comment by madebr** [comment]
> libsdl-org workflows are now running on macos-14, as it seems: https://github.com/libsdl-org/SDL/actions/runs/8836336944/job/24262651643

Indeed. Do I need to change this pr so we keep testing (older) x86_64 macos?

**Comment by sezero** [comment]
> Do I need to change this pr so we keep testing (older) x86_64 macos?

@slouken ?

**Comment by slouken** [comment]
Yes, that's probably a good idea for now.

**Comment by madebr** [comment]
I've added a job on x86_64, but I don't understand why CMake is failing to detect any x86 extensions.

**Comment by madebr** [comment]
> I think you need to make a build that is purely x86_64 in order for that to work. The tests don't return two results, one for x86 and one for arm64.

You're right. Thanks :)

**Pull request merged**
