### PR TITLE
Add SDL_Vulkan_DestroySurface functionality

### PR DESCRIPTION
**Pull request by Lephar**
## Description
Added SDL_Vulkan_DestroySurface, its documentation and corresponding platform specific implementations. Fixed some header inclusion orders to improve consistency between platforms. Added TODOs regarding MetalView creation and destruction which will benefit from the new functionality.

## Existing Issue(s)
Adds missing functionality mentioned in #7322.

### CODE REVIEW

**Comment by slouken** [comment]
@danginsburg, can you please take a look?

**Comment by danginsburg** [comment]
> @danginsburg, can you please take a look?

LGTM!

**Comment by slouken** [comment]
Merged, thanks!

**Comment by sezero** [comment]
This brought back type redefinition errors from older compilers.
Testing [this patch](https://github.com/sezero/SDL/commit/767bfbdc0dd61a2923b2d3217af5bd5a53f588e8) for now.

<details>

```
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11clipboard.c:27:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11clipboard.c:27:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11clipboard.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11events.c:31:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11events.c:31:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11events.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11framebuffer.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11framebuffer.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11framebuffer.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11keyboard.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11keyboard.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11keyboard.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11messagebox.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11messagebox.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11messagebox.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11modes.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11modes.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11modes.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11mouse.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11mouse.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11mouse.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11opengl.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11opengl.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11opengl.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11opengles.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11opengles.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11opengles.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.c:27:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.c:27:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11pen.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11shape.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11shape.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11shape.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11touch.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11touch.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11touch.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.c:34:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.c:34:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11video.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11window.c:32:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11window.c:32:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11window.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11xfixes.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11xfixes.c:26:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11xfixes.c.o] Error 1
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28,
                 from /tmp/SDL3/src/video/x11/SDL_x11xinput2.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28,
                 from /tmp/SDL3/src/video/x11/SDL_x11xinput2.c:25:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/video/x11/SDL_x11xinput2.c.o] Error 1
In file included from /tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/core/linux/../../video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/core/linux/SDL_ibus.c:33:
/tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/core/linux/../../video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/core/linux/SDL_ibus.c:33:
/tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/core/linux/SDL_ibus.c.o] Error 1
In file included from /tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/core/linux/../../video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/core/linux/SDL_fcitx.c:30:
/tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan_core.h:101: error: redefinition of typedef ‘VkInstance’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53: note: previous declaration of ‘VkInstance’ was here
In file included from /tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan.h:11,
                 from /tmp/SDL3/src/core/linux/../../video/x11/../SDL_vulkan_internal.h:52,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11vulkan.h:26,
                 from /tmp/SDL3/src/core/linux/../../video/x11/SDL_x11video.h:40,
                 from /tmp/SDL3/src/core/linux/SDL_fcitx.c:30:
/tmp/SDL3/src/core/linux/../../video/x11/.././khronos/vulkan/vulkan_core.h:7549: error: redefinition of typedef ‘VkSurfaceKHR’
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54: note: previous declaration of ‘VkSurfaceKHR’ was here
make[2]: *** [CMakeFiles/SDL3-shared.dir/src/core/linux/SDL_fcitx.c.o] Error 1
make[2]: Target `CMakeFiles/SDL3-shared.dir/build' not remade because of errors.
make[1]: *** [CMakeFiles/SDL3-shared.dir/all] Error 2
make[1]: Target `all' not remade because of errors.
make: *** [all] Error 2
```

</details>

**Comment by sezero** [comment]
> This brought back type redefinition errors from older compilers. Testing [this patch](https://github.com/sezero/SDL/commit/767bfbdc0dd61a2923b2d3217af5bd5a53f588e8) for now.

https://github.com/libsdl-org/SDL/pull/9818

**Comment by Lephar** [comment]
@sezero strange, these errors didn't trigger on my X11 and Wayland builds, didn't test on Win though.

**Comment by sezero** [comment]
Ali Emre: Older compilers don't tolerate type redefinitions, new compilers tolerate them as an extension until C23. See e.g. https://github.com/libsdl-org/SDL/issues/9620 for how clang warns if you explicitly use -std=c99. Even with clang-8, you get a warning:
```
In file included from /tmp/SDL3/src/video/x11/SDL_x11video.c:34:
In file included from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28:
In file included from /tmp/SDL3/src/video/x11/SDL_x11video.h:40:
In file included from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26:
In file included from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52:
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:101:18: warning: redefinition of typedef 'VkInstance' is a C11 feature [-Wtypedef-redefinition]
VK_DEFINE_HANDLE(VkInstance)
                 ^
/tmp/SDL3/include/SDL3/SDL_vulkan.h:53:18: note: previous definition is here
VK_DEFINE_HANDLE(VkInstance)
                 ^
In file included from /tmp/SDL3/src/video/x11/SDL_x11video.c:34:
In file included from /tmp/SDL3/src/video/x11/SDL_x11pen.h:28:
In file included from /tmp/SDL3/src/video/x11/SDL_x11video.h:40:
In file included from /tmp/SDL3/src/video/x11/SDL_x11vulkan.h:26:
In file included from /tmp/SDL3/src/video/x11/../SDL_vulkan_internal.h:52:
In file included from /tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan.h:11:
/tmp/SDL3/src/video/x11/.././khronos/vulkan/vulkan_core.h:7549:35: warning: redefinition of typedef 'VkSurfaceKHR' is a C11 feature [-Wtypedef-redefinition]
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkSurfaceKHR)
                                  ^
/tmp/SDL3/include/SDL3/SDL_vulkan.h:54:35: note: previous definition is here
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkSurfaceKHR)
                                  ^
2 warnings generated.
```

**Pull request merged**
