### PR TITLE
Log SDL_OutOfMemory without allocation

### PR DESCRIPTION
**Pull request by 1bsyl**
Log SDL_OutOfMemory without allocation !

see https://github.com/libsdl-org/SDL/issues/8642

### CODE REVIEW

**Comment by slouken** [comment]
Most logging functions end up calling memory allocation. The trick here is we want to set the SDL error without an allocation, which was removed in https://github.com/libsdl-org/SDL/commit/cbd01874759dad39718e1496d241c4ae5eceaff1

**Comment by 1bsyl** [comment]
@slouken 
though, `return SDL_SetError("Out of memory");`
would have logged a message 
when using SDL_LogSetAllPriority(SDL_LOG_PRIORITY_DEBUG); 

now it doesn't log a message anymore

**Comment by slouken** [comment]
I think in this case we don't want to call the logging function. @icculus, what do you think?

**Comment by icculus** [comment]
Yeah, I don't think this is the right move. It could be useful to have _something_ broadcast that a dire situation has happened, but it's not really SDL's place to do so.

Also, this would trigger for "omg the system is ruined" and also "oops, the application accidentally tried to allocate a terrabyte of memory, but any reasonable allocation in the future will totally work."

**Comment by slouken** [comment]
Let's just leave it as-is for now.

**Pull request closed without merging**
