### PR TITLE
Updated Haiku buildtools to r1beta5

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by madebr** [comment]
This pr will have to wait until r1beta5 becomes available at https://hub.docker.com/r/haiku/cross-compiler/tags

**Comment by slouken** [comment]
I'll just close it, thanks.

**Comment by kallisti5** [comment]
Hi! I'm on the Haiku infrastructure team. I actually wasn't aware of these containers :sweat_smile: 

I'm migrating them over to ghcr.io (our current registry choice), and going to work on documenting them / automating their generation.

After this is complete, they should appear at `ghcr.io/haiku/cross-compiler:` under the same naming.

Sorry for missing these!

**Comment by slouken** [comment]
Oh, thanks for letting us know!

**Pull request closed without merging**
