### PR TITLE
Fix dialog filters on Windows

### LINKED ISSUE #11653: Random garbage filters appearing in the drop-down in file dialogs
image

This is quite easy to reproduce. Latest SDL3, Windows 10.
```
#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL_main.h>
#include <SDL3/SDL.h>

SDL_AppResult SDL_AppInit(void ** win, int, char**) {
	SDL_Init(SDL_INIT_VIDEO);
	*win = (void*) SDL_CreateWindow(nullptr, 1000, 500, 0);
	return SDL_APP_CONTINUE;
}

SDL_AppResult SDL_AppIterate(void*) {
	SDL_Delay(1);
	return SDL_APP_CONTINUE;
}

static void SDLCALL Callback(void* userdata, const char* const* files, int filter) {
}
const SDL_DialogFileFilter filters[3] = {
	{ "PNG images", "png" },
	{ "BMP images", "bmp" },
	{ "All files", "*" }
};

SDL_AppResult SDL_AppEvent(void * win, SDL_Event* event) {
	switch (event->type) {
	case SDL_EVENT_KEY_UP:
		SDL_ShowOpenFileDialog(Callback, nullptr, (SDL_Window*)win, filters, sizeof(filters) / sizeof(*filters), nullptr, false);
		break;
	case SDL_EVENT_QUIT:
		return SDL_APP_SUCCESS;
	}
	return SDL_APP_CONTINUE;
}

void SDL_AppQuit(void*, SDL_AppResult result) {
}
```

### PR DESCRIPTION
**Pull request by Semphriss**
## Description

This fixes two bugs with file filters for dialogs on Windows. The details of the bugs are in the commit messages:

- convert_filters: For some obscure reason I can't remember, I had made it so the suffix would be added only if the filter list was empty. That isn't the expected behavior and caused a mishandling of memory on Windows, which requires a two-null-bytes suffix.
- clear_filt_names: The Windows implementation of dialogs use the Win32 API, which expects the file filters to have null bytes as separator, and two null bytes at the end of the filter list. To help with string manipulation, the internal code uses 0x01 bytes instead of null bytes, and converts all 0x01 bytes into null bytes at the last moment. If someone decides to put two consecutive 0x01 bytes in their filter names, the code might mistakenly pick them up and convert them to null bytes, leading to Windows failing to pick up later filters. In practice, this is probably not so bad, since it requires someone to have control over file filters already, and allows at most ignoring the following file filters. It is also unlikely to happen by accident since 0x01 is not printable. This commit fixes that by replacing all the pre-existing 0x01 bytes with the space character.

## Existing Issue(s)

Fixes #11653 -- @AntTheAlchemist @RT2Code @adamkewley Can you confirm that the bug is fixed with this PR?

### CODE REVIEW

**Comment by slouken** [comment]
Merged, thanks!

**Comment by RT2Code** [comment]
Thanks for the quick fix. Now the filters work fine. But I still have this issue with titles:
Screenshot (9)

And, I don't know if others have this issue, but if I set a parent window, the dialog never opens.

**Comment by slouken** [comment]
Can you please enter separate bugs for these issues, for tracking?

Thanks!

**Comment by AntTheAlchemist** [comment]
@Semphriss looks like it's fixed, thanks and good job - that looked a tricky one.

@RT2Code It's working for me when I set a parent window.

**Comment by Semphriss** [comment]
> Thanks for the quick fix. Now the filters work fine. But I still have this issue with manually set titles:

Yes, I'll be fixing that in a separate PR.

Can you open an issue and @ me in it? Just to make sure I don't forget :)

**Comment by RT2Code** [comment]
Will do.

About the parent window issue, I did more tests, and it happened because I was blocking the thread right after the open dialog call to get the callback return value. For it to work with a parent window, I have to let the main loop run and check periodically if the return value is available. I guess dialogs require events to be processed. Maybe this should be added to the documentation?

**Comment by Semphriss** [comment]
I noticed the XDG Portals implementation required a running loop to work properly, I guess I can generalize the documentation to say that it always require a running loop. Pushing this on my to-do list.

**Pull request merged**
