### PR TITLE
Added SDL_RWprintf() to do formatted printing to an SDL_rwops stream 

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by slouken** [comment]
@madebr, do you have any idea why the 32-bit GNU builds are failing here?

**Comment by sezero** [comment]
I'm on i686-linux and `./testautomation --filter RWops` fails similarly for me:

```
INFO:  11/05/23 00:38:00: Assert 'Call to SDL_RWread succeeded': Passed
INFO:  11/05/23 00:38:00: Assert 'Verify result from SDL_RWread, expected 12, got 12': Passed
ERROR: 11/05/23 00:38:00: Assert 'Verify read bytes match expected string, expected 'Hello World!', got ' 11/05/23 00'': Failed
[...]
INFO:  11/05/23 00:38:00: Assert 'Verify seek to 0 with SDL_RWseek (SDL_RW_SEEK_SET), expected 0, got 0': Passed
INFO:  11/05/23 00:38:00: Assert 'Call to SDL_RWprintf succeeded': Passed
ERROR: 11/05/23 00:38:00: Assert 'Verify result of writing with SDL_RWprintf, expected 12, got 6': Failed
```

**Comment by madebr** [comment]
Can dynapi handle `...` functions?

**Comment by slouken** [comment]
Ohh, there’s some special fix up that needs to happen for varargs functions. I can do that, thanks!

**Comment by sezero** [comment]
No errors from `testautomation --filter RWops` on my i686-linux as of 67c9945f94a7485846d5dc443929d1aefea206af

**Comment by sezero** [comment]
Maybe this clean-up?
- The early error-return avoids overwriting of ENOMEM in `SDL_RWwrite`.
- `SDL_vasprintf` already initializes `string`. My gcc doesn't emit a warning for it.
- Explicit size_t cast on `size` when feeding to `SDL_RWwrite`

```diff
diff --git a/src/file/SDL_rwops.c b/src/file/SDL_rwops.c
index b6f943f..a18838c 100644
--- a/src/file/SDL_rwops.c
+++ b/src/file/SDL_rwops.c
@@ -813,5 +813,5 @@ size_t SDL_RWprintf(SDL_RWops *context, SDL_PRINTF_FORMAT_STRING const char *fmt
     va_list ap;
     int size;
-    char *string = NULL;
+    char *string;
     size_t bytes;
 
@@ -819,6 +819,9 @@ size_t SDL_RWprintf(SDL_RWops *context, SDL_PRINTF_FORMAT_STRING const char *fmt
     size = SDL_vasprintf(&string, fmt, ap);
     va_end(ap);
+    if (size < 0) {
+        return 0;
+    }
 
-    bytes = SDL_RWwrite(context, string, size);
+    bytes = SDL_RWwrite(context, string, (size_t)size);
     SDL_free(string);
     return bytes;
```

**Comment by madebr** [comment]
Don't forget to free the string in the early return.

**Comment by sezero** [comment]
> Don't forget to free the string in the early return.

Huh.. `-1` can be from `SDL_vsnprintf` (even though unlikely..)

**Comment by slouken** [comment]
I forgot that snprintf can return -1, this is a good cleanup.

**Comment by sezero** [comment]
> I forgot that snprintf can return -1, this is a good cleanup.

Well, was not good enough, as @madebr noticed:

`SDL_vasprintf` can return `-1` because of a malloc failure, _but_ it can
also return `-1` because `SDL_vsnprintf` (called by `SDL_vasprintf`) _can_
return `-1` for who knows what reason -- i.e. `string` might be non-NULL at
that point. I suggest the following against current HEAD: (or revert the
cleanup.)

```diff
diff --git a/src/file/SDL_rwops.c b/src/file/SDL_rwops.c
index 3bfb969..9afb882 100644
--- a/src/file/SDL_rwops.c
+++ b/src/file/SDL_rwops.c
@@ -812,13 +812,14 @@ size_t SDL_RWprintf(SDL_RWops *context, SDL_PRINTF_FORMAT_STRING const char *fmt
 {
     va_list ap;
     int size;
-    char *string;
+    char *string = NULL;
     size_t bytes;
 
     va_start(ap, fmt);
     size = SDL_vasprintf(&string, fmt, ap);
     va_end(ap);
     if (size < 0) {
+        SDL_free(string);
         return 0;
     }
 
@@ -830,11 +831,12 @@ size_t SDL_RWprintf(SDL_RWops *context, SDL_PRINTF_FORMAT_STRING const char *fmt
 size_t SDL_RWvprintf(SDL_RWops *context, const char *fmt, va_list ap)
 {
     int size;
-    char *string;
+    char *string = NULL;
     size_t bytes;
 
     size = SDL_vasprintf(&string, fmt, ap);
     if (size < 0) {
+        SDL_free(string);
         return 0;
     }
 
```

**Comment by sezero** [comment]
> > I forgot that snprintf can return -1, this is a good cleanup.
> 
> Well, was not good enough, as @madebr noticed:
> 
> `SDL_vasprintf` can return `-1` because of a malloc failure, _but_ it can also return `-1` because `SDL_vsnprintf` (called by `SDL_vasprintf`) _can_ return `-1` for who knows what reason -- i.e. `string` might be non-NULL at that point. I suggest the following against current HEAD: (or revert the cleanup.)

Actually no: `SDL_vasprintf` has a leak, and my initial clean-up should
be correct: `SDL_vasprintf` stores the malloc'ed string only upon success
but forgets free'ing it in one of the two failure cases.
@madebr, @slouken: I intend to apply the following to all active branches
OK?
```diff
diff --git a/src/stdlib/SDL_string.c b/src/stdlib/SDL_string.c
index 0c97cc0..9f434a4 100644
--- a/src/stdlib/SDL_string.c
+++ b/src/stdlib/SDL_string.c
@@ -2199,10 +2199,11 @@ int SDL_vasprintf(char **strp, const char *fmt, va_list ap)
         retval = SDL_vsnprintf(p, size, fmt, aq);
         va_end(aq);
 
         /* Check error code */
         if (retval < 0) {
+            SDL_free(p);
             return retval;
         }
 
         /* If that worked, return the string */
         if (retval < size) {
```

**Comment by madebr** [comment]
Looks good for me.
Is it possible to create a regression test for this, or is it hard to reproduce?

**Comment by sezero** [comment]
> Looks good for me.

OK, will be pushing it shortly

> Is it possible to create a regression test for this, or is it hard to reproduce?

Don't know how I'd make `SDL_vsnprintf` to fail (haven't read that part of the code)
Feel free to do so, though.

**Comment by slouken** [comment]
> Actually no: `SDL_vasprintf` has a leak, and my initial clean-up should be correct: `SDL_vasprintf` stores the malloc'ed string only upon success but forgets free'ing it in one of the two failure cases. @madebr, @slouken: I intend to apply the following to all active branches OK?
> 
> ```diff
> diff --git a/src/stdlib/SDL_string.c b/src/stdlib/SDL_string.c
> index 0c97cc0..9f434a4 100644
> --- a/src/stdlib/SDL_string.c
> +++ b/src/stdlib/SDL_string.c
> @@ -2199,10 +2199,11 @@ int SDL_vasprintf(char **strp, const char *fmt, va_list ap)
>          retval = SDL_vsnprintf(p, size, fmt, aq);
>          va_end(aq);
>  
>          /* Check error code */
>          if (retval < 0) {
> +            SDL_free(p);
>              return retval;
>          }
>  
>          /* If that worked, return the string */
>          if (retval < size) {
> ```

Yes, this looks great, and should probably be cherry-picked to SDL2.

**Comment by sezero** [comment]
> Yes, this looks great, and should probably be cherry-picked to SDL2.

Already did :)

**Pull request merged**
