### PR TITLE
Check the SDL_VIDEO_RENDER_??? macros with #if instead of #ifdef

### PR DESCRIPTION
**Pull request by sezero**
Allows users to disable them by defining them as 0.

Closes https://github.com/libsdl-org/SDL/issues/8996

Patch is against the SDL2 branch, applies cleanly to release-2.30.x too.

Does not apply to SDL3: needs manual tweaking.

@slouken, @madebr: Please review.

### CODE REVIEW

**Review by madebr — APPROVED** [review]

**Comment by sezero** [comment]
Should we also do something like the following to avoid user-shoot-foot cases?
I.e. `render_drivers[]` in SDL_render.c shouldn't have an empty initializer list.

```diff
diff --git a/src/SDL_internal.h b/src/SDL_internal.h
index ae638e8..b193ede 100644
--- a/src/SDL_internal.h
+++ b/src/SDL_internal.h
@@ -187,6 +187,24 @@
 #define SDL_VIDEO_RENDER_VITA_GXM 0
 #endif /* SDL_RENDER_DISABLED */
 
+#define SDL_HAS_RENDER_DRIVER \
+       (SDL_VIDEO_RENDER_SW       | \
+        SDL_VIDEO_RENDER_D3D      | \
+        SDL_VIDEO_RENDER_D3D11    | \
+        SDL_VIDEO_RENDER_D3D12    | \
+        SDL_VIDEO_RENDER_METAL    | \
+        SDL_VIDEO_RENDER_OGL      | \
+        SDL_VIDEO_RENDER_OGL_ES   | \
+        SDL_VIDEO_RENDER_OGL_ES2  | \
+        SDL_VIDEO_RENDER_DIRECTFB | \
+        SDL_VIDEO_RENDER_PS2      | \
+        SDL_VIDEO_RENDER_PSP      | \
+        SDL_VIDEO_RENDER_VITA_GXM)
+
+#if !defined(SDL_RENDER_DISABLED) && !SDL_HAS_RENDER_DRIVER
+#error SDL_RENDER enabled without any backend drivers.
+#endif
+
 #include "SDL_assert.h"
 #include "SDL_log.h"
 
```

**Comment by sezero** [comment]
And here is the SDL3 version of the patch: [sdl3.patch.txt](https://github.com/libsdl-org/SDL/files/14295384/sdl3.patch.txt)

Waiting for an answer for my question above.

**Comment by slouken** [comment]
> Should we also do something like the following to avoid user-shoot-foot cases? I.e. `render_drivers[]` in SDL_render.c shouldn't have an empty initializer list.

Yes, that seems like a good idea.

**Review by slouken — APPROVED** [review]

**Comment by sezero** [comment]
Merged and cherry-picked to release-2.30.x

**Comment by sezero** [comment]
SDL3 version pushed via #9070

**Pull request merged**
