### PR TITLE
Rollup of downstream changes from HaikuPorts

### PR DESCRIPTION
**Pull request by waddlesplash**
As in the title, this rolls up a number of changes made in the HaikuPorts downstream. They should generally be self-explanatory, or have explanations in their commit messages.

### CODE REVIEW

**Comment by waddlesplash** [comment]
CC @icculus.

**Comment by sezero** [comment]
Some of the changes, e.g. at least SDL_string.c, has already been merged, therefore this has conflicts.

**Comment by waddlesplash** [comment]
Ah, I missed #5218, indeed.

Strange that GitHub shows no conflicts, though...

**Comment by sezero** [comment]
Mine does:

Screenshot

**Comment by waddlesplash** [comment]
So, it turns out #5218 actually broke the build on Haiku due to an incomplete merge! This PR now contains only the remaining changes it missed.

**Comment by icculus** [comment]
I'm merging this, but let us know if anything else broke due to the previous incomplete patchset!

**Comment by waddlesplash** [comment]
So far as I can tell, this was all that's needed to bring things in line. Thanks for the merge!

**Pull request merged**
