### PR TITLE
ci: merge all workflows into one

### PR DESCRIPTION
**Pull request by madebr**
## Description
This pr merges all workflows into a [reusable](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) parameterized generic one (`.github/workflow/generic.yml`).
The `build.yml` workflow then uses this generic one.
The parameters are calculated by a python script (`.github/workflows/create-test-plan.py`).

Pros:
- only one GitHub action is started, and only one actions be stopped/canceled when force pushing to a pr
- not yet implemented, but the re-usable workflow allows for canary builds, and multiple levels

Cons:
- Test plan generation causes an initial delay
- Slightly more complicated generic workflow
- Custom slightly complicated python script (but can be run on any system)

## Existing Issue(s)
#10200

### CODE REVIEW

**Comment by slouken** [comment]
I'm excited about this, especially once we have the canary builds in. That will greatly reduce iteration time. :)

**Comment by madebr** [comment]
> I'm excited about this, especially once we have the canary builds in. That will greatly reduce iteration time. :)

Do you have a preference for what jobs to put in the canary?
I propose one build each of Linux, MSVC and macos.
Those are relatively slow, but they also run build-time tests.

Alternatively, looking [at the matrix](https://github.com/libsdl-org/SDL/actions/runs/10099628457?pr=10372),
Android, Haiku and the xcode projects are very fast (they don't do cmake configuration and also no runtime tests)

**Comment by slouken** [comment]
Ironically, the haiku build is probably the best canary. It's fast, and the compiler runs with options that catch issues that Visual Studio doesn't.

I'd probably do that one first, and then a second tier of canaries would be:
a Linux build, an MSVC build, and an Xcode build.

We could probably get away with just the Haiku build as our canary though.

**Comment by slouken** [comment]
Another benefit of this is we could have a smaller set of platforms that build with each commit and then a daily build that covers all the platforms, right?

**Comment by slouken** [comment]
Actually, never mind on that. We'd want to make sure any PRs that we integrate have always gone through a full platform CI build.

**Comment by icculus** [comment]
If we were to do a daily build, it would be static analysis: takes forever, but finds subtle bugs.

**Comment by madebr** [comment]
> Another benefit of this is we could have a smaller set of platforms that build with each commit and then a daily build that covers all the platforms, right?

 The canary is to avoid crowdstrike-like ci situations where all jobs fail due to a small oversight (saving CO2), but costing extra time because of the small serialization.
If you believe the extra delay is unwanted, I can remove the canary commit.

My main goal of this pr was to merge all workflows so canceling a job becomes much easier and less spammy.
I'm also going to add some code to filter jobs.
e.g. by adding `[sdl-ci-filter msvc-*]` to a commit message, only the MSVC jobs will run.

**Comment by slouken** [comment]
Yes, this sounds great. Thank you!

**Comment by madebr** [comment]
The commit message is only available in push events, not in pull requests.
So the filtering only works in commits.
I think this is good: we don't want partial ci in pull requests.

As an example, I added `[sdl-ci-filter msvc-*]` to the (current) last commit, which results in only haiku (=canary) and msvc builds running.
See https://github.com/madebr/SDL/actions/runs/10114774278

**Comment by slouken** [comment]
Nice!

**Comment by slouken** [comment]
I can't wait for this to land. :)

**Comment by madebr** [comment]
> I can't wait for this to land. :)

I feel your pain seeing your force pushes :)

**Comment by slouken** [comment]
Thank you! :)

**Comment by slouken** [comment]
By the way, it is SO much nicer to look at the pending workflows and see a single workflow for each commit. Thanks again!

**Pull request merged**
