### PR TITLE
cleanup of SDL_video.c (mainly Re(create)window)

### PR DESCRIPTION
**Pull request by pionere**
1. solve FIXMEs in SDL_GetDisplayBounds and SDL_GetDisplayUsableBounds by returning SDL_InvalidParamError("rect") in case rect is NULL
2. consistently check against __ANDROID__ (instead of ANDROID)
3. add SDL_ContextNotSupported to create error message in case the given graphics backend is not supported
4. use SDL_ContextNotSupported in SDL_GL_LoadLibrary instead of a custom error message
5. add NOT_AN_OPENGL_WINDOW define similar to NOT_A_VULKAN_WINDOW
6. no need to check if _this->Metal_CreateView, since it is already checked in Re(create)Window (similar to GL_CreateContext and Vulkan_CreateSurface)
7. set only one of SDL_WINDOW_OPENGL/SDL_WINDOW_METAL as default backend (might want to extend CMakeList to warn the user)
8. simplify check of SDL_WINDOW_UTILITY/SDL_WINDOW_TOOLTIP/SDL_WINDOW_POPUP_MENU flags assuming each of these is a single bit flag
9. simplify check of SDL_WINDOW_OPENGL/SDL_WINDOW_METAL/SDL_WINDOW_VULKAN flags assuming each of these is a single bit flag

### CODE REVIEW

**Comment by sezero** [comment]
Is this eligible for 2.0.22 (reviewed?) or should wait for later?

**Comment by slouken** [comment]
We're close enough on 2.0.22 that these should wait for the next milestone.

**Comment by slouken** [comment]
@pionere, can you rebase this PR on the latest main?

**Comment by slouken** [comment]
It looks like you're submitting each change as a separate PR. That's a good way for us to review and easily accept individual changes, thanks!

**Comment by slouken** [comment]
We should look at what actually happens when both OpenGL and Metal are set, especially in the macOS Cocoa case. I'm inclined not to touch this right now, and revisit in SDL 3.0, where Metal would be the default on any platform that supports it.

**Comment by slouken** [comment]
We did end up needing your last patch, to fix window recreation on macOS.

Thanks!

**Pull request closed without merging**
