### PR TITLE
Add test program to test yuv conversion / future non-contiguous planes support

### PR DESCRIPTION
**Pull request by 1bsyl**
Add test program to test yuv conversion / future non-contiguous planes support

### CODE REVIEW

**Comment by slouken** [comment]
Can we instead add these tests to testautomation?

**Comment by 1bsyl** [comment]
Yes, maybe at some point... currently it seems more usable like this if we do the plane/yuv thing

**Comment by slouken** [comment]
What is the overlap between this new program and the existing conversion tests in `testyuv --automated`? Maybe the testing here should be folded into that?

**Comment by 1bsyl** [comment]
indeed, testyuv has more features! let close this

**Pull request closed without merging**
