### PR TITLE
metadata: Added SDL_SetAppMetadata and SDL_SetAppMetadataWithProperties.

### PR DESCRIPTION
**Pull request by slouken**
Removed duplicate hints SDL_HINT_APP_NAME, SDL_HINT_APP_ID, and SDL_HINT_AUDIO_DEVICE_APP_NAME.

Wired up a few things to use the metadata; more to come!

Fixes https://github.com/libsdl-org/SDL/issues/4703

### CODE REVIEW

**Comment by icculus** [comment]
This cleans up the internals really nicely, and the public API is good.

I'm not sure what PulseAudio does with a NULL name here, but I think I'd like everything that didn't bother with adding metadata to be called "SDL Application" until people complain and they fix it.  :)

**Review by icculus — APPROVED** [review]

**Comment by madebr** [comment]
> This cleans up the internals really nicely, and the public API is good.
> 
> I'm not sure what PulseAudio does with a NULL name here, but I think I'd like everything that didn't bother with adding metadata to be called "SDL Application" until people complain and they fix it. :)

Does SDL print warnings?
Running testautomation on my machine, I see the following gtk one:
```
(testautomation:47446): Gtk-WARNING **: 16:18:07.241: gtk_disable_setlocale() must be called before gtk_init()
```

**Comment by slouken** [comment]
> This cleans up the internals really nicely, and the public API is good.
> 
> I'm not sure what PulseAudio does with a NULL name here, but I think I'd like everything that didn't bother with adding metadata to be called "SDL Application" until people complain and they fix it. :)

Yep, that's behavior with this patch. Thanks!

**Comment by slouken** [comment]
> > This cleans up the internals really nicely, and the public API is good.
> > I'm not sure what PulseAudio does with a NULL name here, but I think I'd like everything that didn't bother with adding metadata to be called "SDL Application" until people complain and they fix it. :)
> 
> Does SDL print warnings? Running testautomation on my machine, I see the following gtk one:
> 
> ```
> (testautomation:47446): Gtk-WARNING **: 16:18:07.241: gtk_disable_setlocale() must be called before gtk_init()
> ```

No, this is gtk complaining. I'm not sure what's calling gtk_init()?

**Comment by slouken** [comment]
> This cleans up the internals really nicely, and the public API is good.
> 
> I'm not sure what PulseAudio does with a NULL name here, but I think I'd like everything that didn't bother with adding metadata to be called "SDL Application" until people complain and they fix it. :)

Do we want a hint to override the default metadata for an application?

**Comment by madebr** [comment]
> No, this is gtk complaining. I'm not sure what's calling gtk_init()?

Probably libdecor.
I was asking about SDL doing similar things to inform developers.

**Comment by slouken** [comment]
> > No, this is gtk complaining. I'm not sure what's calling gtk_init()?
> 
> Probably libdecor. I was asking about SDL doing similar things to inform developers.

We tend not to, relying on the application to check function return values.

**Pull request merged**
