### PR TITLE
cmake: avoid copy of headers by moving generated headers to include/build_config

### PR DESCRIPTION
**Pull request by madebr**
Shove all build system generated headers in `include/build_config`.
Doing this, cmake does not need to copy the headers anymore.
This was done for external projects vendoring SDL.

See https://github.com/libsdl-org/SDL/issues/6641#issuecomment-1328092535

@slouken 
I broke the xcode projects.
Could you please fix these to additionally include `include/build_config`?

### CODE REVIEW

**Comment by ccawley2011** [comment]
It might be worth going one step further and putting these headers into `src/` instead of `include/`.

**Comment by slouken** [comment]
I have an alternate approach, I'll generate a PR shortly.

**Comment by slouken** [comment]
Actually, if we move this header into build_config, then we need to remove it from the public API, since people will no longer be able to reference it externally from a source archive (e.g. downloading the source archive and pointing their include path at the SDL include directory)

**Comment by slouken** [comment]
So I think this can be done more simply by reordering the include path. Can you take a look at https://github.com/libsdl-org/SDL/pull/6664 and see if that makes sense?

The idea is that SDL_revision.h still remains in the API, and if you're not using CMake you'll use the version in the include directory, which for git versions will be empty, and for releases will have the tag of the release, and if you're using CMake you'll get the one generated by CMake for SDL library builds and in-tree builds.

Did I get that right?

**Comment by madebr** [comment]
Makes total sense. I think the previous approach was perhaps too complicated.
Thanks for simplifying this.

**Comment by slouken** [comment]
You’re welcome!

**Pull request closed without merging**
