### PR TITLE
Fix joystick (/dev/input/xxx) support on FreeBSD

### PR DESCRIPTION
**Pull request by martymac**
Backport f8ad4abe from main branch.

When switching to CMake, src/joystick/linux/SDL_sysjoystick.c file got excluded from FreeBSD builds, losing support for /dev/input/xxx devices.

See also: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279907
and: https://github.com/libsdl-org/SDL/pull/10087

### CODE REVIEW

**Comment by martymac** [comment]
Hello again, this is a followup to :
https://github.com/libsdl-org/SDL/pull/10087

The same patch can be applied to SDL2 branch too.

**Comment by slouken** [comment]
Merged, thanks! This is also cherry-picked out for the next release.

**Comment by martymac** [comment]
Thanks a lot!

Have a nice week-end,
Ganael

**Comment by slouken** [comment]
You too! :)

**Pull request merged**
