### PR TITLE
Removed the window shape API for SDL 3.0

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/6654
Fixes https://github.com/libsdl-org/SDL/issues/6897

### CODE REVIEW

**Comment by madebr** [comment]
Can the `test/shapes` directory also be deleted?

**Comment by slouken** [comment]
Yep!

**Comment by madebr** [comment]
sdl2-compat will need a workaround for shaped windows.

**Comment by slouken** [comment]
Yep, I'm working on it now.

**Comment by sezero** [comment]
There is the old https://github.com/libsdl-org/sdl2-compat/pull/66 by @1bsyl

**Comment by slouken** [comment]
> sdl2-compat will need a workaround for shaped windows.

I have this almost done, but I'm going offline for a few days.

Cheers!

**Pull request merged**
