### PR TITLE
fix CheckCOCOA on modern CMake

### PR DESCRIPTION
**Pull request by ShuangLiu1992**
Modern CMake doesn't need "LANGUAGE C" for Objective-C
set_source_files_properties(${COCOA_SOURCES} PROPERTIES LANGUAGE C) should be removed fro video/cocoa/*.m as well otherwise project won't compile
see also https://github.com/libsdl-org/SDL/commit/d3cc5764c0f66872a6b87c0ffbca66c85dccbea3

### CODE REVIEW

**Review by madebr — APPROVED** [review]
Settings this property was also not needed for supporting ImageIO in SDL_image.

**Comment by slouken** [comment]
We've had a bunch of issues with CMake and Objective C on older macOS versions over the years. Now that we require macOS 10.7, maybe this is no longer an issue. Let's revisit this and look at the old bugs again for 2.24.0.

**Comment by slouken** [comment]
Actually, never mind. Since we've already accepted https://github.com/libsdl-org/SDL/commit/d3cc5764c0f66872a6b87c0ffbca66c85dccbea3, let's make the same change here.

**Comment by sezero** [comment]
Don't know how or why, but with this, CI macOS builds are failing (which is the same failure here in the PR's CI runs):
https://github.com/libsdl-org/SDL/runs/6538204860?check_suite_focus=true#step:7:371
```
/Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DSDL2_EXPORTS -DUSING_GENERATED_CONFIG_H -I/Users/runner/work/SDL/SDL/build/include -I/Users/runner/work/SDL/SDL/include -x objective-c -isysroot /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -mmacosx-version-min=11.6 -fPIC -fobjc-arc -std=gnu17 -MD -MT CMakeFiles/SDL2.dir/src/video/cocoa/SDL_cocoaclipboard.m.o -MF CMakeFiles/SDL2.dir/src/video/cocoa/SDL_cocoaclipboard.m.o.d -o CMakeFiles/SDL2.dir/src/video/cocoa/SDL_cocoaclipboard.m.o -c /Users/runner/work/SDL/SDL/src/video/cocoa/SDL_cocoaclipboard.m
In file included from /Users/runner/work/SDL/SDL/src/video/cocoa/SDL_cocoaclipboard.m:25:
In file included from /Users/runner/work/SDL/SDL/src/video/cocoa/SDL_cocoavideo.h:41:
In file included from /Users/runner/work/SDL/SDL/src/video/cocoa/SDL_cocoawindow.h:29:
In file included from /Users/runner/work/SDL/SDL/src/video/cocoa/../SDL_egl_c.h:28:
/Users/runner/work/SDL/SDL/include/SDL_egl.h:33:10: fatal error: 'EGL/egl.h' file not found
#include <EGL/egl.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/SDL2.dir/src/video/cocoa/SDL_cocoaclipboard.m.o] Error 1
make[1]: *** [CMakeFiles/SDL2.dir/all] Error 2
make: *** [all] Error 2
Error: Process completed with exit code 2.
```

**Comment by slouken** [comment]
That doesn't make any sense to me. @icculus, any ideas?

**Comment by icculus** [comment]
I was wondering this, too. I'll dig in.

**Comment by icculus** [comment]
Build command line before f4fc4719a5ed2efa76da32bbdcd6940b69c01422 ...

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc \
    -DSDL2_EXPORTS -DUSING_GENERATED_CONFIG_H -I/Users/icculus/projects/SDL/good-build/include \
    -I/Users/icculus/projects/SDL/include -idirafter "/Users/icculus/projects/SDL/src/video/khronos" -D_THREAD_SAFE \
    -Wshadow -fvisibility=hidden -Wdeclaration-after-statement -Werror=declaration-after-statement -fno-strict-aliasing -Wall \
    -DSDL_BUILD_MAJOR_VERSION=2 -DSDL_BUILD_MINOR_VERSION=23 -DSDL_BUILD_MICRO_VERSION=0 \
    -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk \
    -fPIC -fobjc-arc -MD -MT CMakeFiles/SDL2.dir/src/video/cocoa/SDL_cocoaclipboard.m.o \
    -MF CMakeFiles/SDL2.dir/src/video/cocoa/SDL_cocoaclipboard.m.o.d \
    -o CMakeFiles/SDL2.dir/src/video/cocoa/SDL_cocoaclipboard.m.o -c \
    /Users/icculus/projects/SDL/src/video/cocoa/SDL_cocoaclipboard.m
```

Build command line after f4fc4719a5ed2efa76da32bbdcd6940b69c01422 ...

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc \
    -DUSING_GENERATED_CONFIG_H -I/Users/icculus/projects/SDL/build/include -I/Users/icculus/projects/SDL/include \
    -x objective-c -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk \
    -fobjc-arc -std=gnu17 -MD -MT CMakeFiles/SDL2-static.dir/src/video/cocoa/SDL_cocoaclipboard.m.o \
    -MF CMakeFiles/SDL2-static.dir/src/video/cocoa/SDL_cocoaclipboard.m.o.d \
    -o CMakeFiles/SDL2-static.dir/src/video/cocoa/SDL_cocoaclipboard.m.o -c \
    /Users/icculus/projects/SDL/src/video/cocoa/SDL_cocoaclipboard.m
```

So we lost tons of stuff for some reason. Still looking.

**Comment by icculus** [comment]
CMake has `CMAKE_C_FLAGS` as usual, but it _also_ has a `CMAKE_OBJC_FLAGS` and I'll bet you anything that when we didn't force this to be compiled as C, it started using a different variable to compile it.

**Comment by icculus** [comment]
Sure enough, stuffed this at the bottom of CMakeLists.txt and the problem goes away:

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 2ce31aba8..0a77db641 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -3122,3 +3122,6 @@ endif()
 if(SDL_TEST)
   add_subdirectory(test)
 endif()
+
+set(CMAKE_OBJC_FLAGS "${CMAKE_OBJC_FLAGS} ${CMAKE_C_FLAGS}")
+
```

Not that I'm recommending that, as it feels like a nuclear option.

But also: it might be the correct approach. I don't know.

**Comment by icculus** [comment]
Moving this to a separate bug, since this PR is merged and looks done.

**Pull request merged**
