### PR TITLE
docs/README-android.md: Update minimal required Android SDK version

### PR DESCRIPTION
**Pull request by dustdfg**

### CODE REVIEW

**Comment by icculus** [comment]
...we require Android 31 now? @1bsyl, is that right?

**Comment by dustdfg** [comment]
> ...we require Android 31 now? @1bsyl, is that right?

Now [build.gradle](https://github.com/libsdl-org/SDL/blob/1fc7f681187f80ccd6b9625214b47db665cd9aaf/android-project/build.gradle) uses build gradle plugin with version 7.0.3. As mentioned [here](https://developer.android.com/studio/releases/gradle-plugin#7-0-0) current version of the plugin requires android sdk 30+

**Comment by slouken** [comment]
Given Google now requires SDK 31 for Play Store apps (https://developer.android.com/google/play/requirements/target-sdk), I think this is a fine change to make.

**Comment by 1bsyl** [comment]
targetSdk version was bumped here, from 26 to 31 (november 21) https://github.com/libsdl-org/SDL/commit/7ad64357ee6290ed811ef597136d36cd9769fb22

This is not clear to me where the gradle plugin would depend on android sdk 30+.
ok, it depends on build tools ("buildToolsVersion of build.gradle"). ok, some feature may be available or not based on {min,compile,target}Sdk of the build.gradle file.
but I don't think it's a dependance of android sdk.

Indeed, from @slouken  post: 
> New apps must target Android 12 (API level 31) or higher; except for [Wear OS](https://developer.android.com/wear) apps, which must target Android 11 (API level 30) or higher.
> 
> Starting in November 2022, app updates must target API level 31 or above and adjust for behavioral changes in Android 12; except for Wear OS apps, which must target API level 30 or higher.


https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd#.bpqsg4ili
ideally:
minSdkVersion (lowest possible) <= targetSdkVersion == compileSdkVersion (latest SDK)

**Pull request merged**
