### PR TITLE
Audio conversion cleanup

### PR DESCRIPTION
**Pull request by 0x1F9F1**
A collection of changes to the audio converter, most notably:
* Removing the future_buffer, left_padding, and right_padding buffers
* Removing the ResamplerFilterDifference table
* Optimising ResampleAudio (allowing for potential SIMD optimisations in the future)

### CODE REVIEW

**Review by icculus — APPROVED** [review]
Looks good to me.

**Comment by icculus** [comment]
Let me know when you're ready to merge!

**Comment by slouken** [comment]
Is this build error fixed in this PR?
```
..\..\src\audio\SDL_audiotypecvt.c(104): error C2059: syntax error : 'bad suffix on number' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(104): error C2146: syntax error : missing ';' before identifier 'p' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(104): error C2065: 'p' : undeclared identifier [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(104): error C2146: syntax error : missing ';' before identifier 'f' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(104): error C2065: 'f' : undeclared identifier [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(322): error C2059: syntax error : 'bad suffix on number' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(322): error C2146: syntax error : missing ')' before identifier 'p' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(322): error C2059: syntax error : ')' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(496): error C2059: syntax error : 'bad suffix on number' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(496): error C2146: syntax error : missing ')' before identifier 'p31f' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
..\..\src\audio\SDL_audiotypecvt.c(496): error C2059: syntax error : ')' [c:\buildslave\sdl3_win32\build\dev\VisualC\SDL\SDL.vcxproj]
```

**Comment by 0x1F9F1** [comment]
> Is this build error fixed in this PR?

Ah no, that's from the audio converters stuff I did before this. With SDL3 supporting C99 I hoped using hex floats would be ok, but I can change them back if necessary (there's no functional change, they were just alot nice to look at). A bit surprised MSVC is complaining about it though. Is that quite an old version of the compiler?

**Comment by icculus** [comment]
Weird, I thought we already had some in there that MSVC was okay with. Those can be rolled back, then.

**Comment by slouken** [comment]
Yeah, it's an older version of the compiler. Our official language target is C89 + mixed declarations and C++ comments.

**Comment by icculus** [comment]
The PS2 failure appears to be unrelated; are we ready to merge?

**Comment by 0x1F9F1** [comment]
Yeah sorry, I realised there were some edge-cases I wasn't properly handling, but it should be ready now.
The new commit is fairly large but I think it was a worthwhile change.

**Pull request merged**
