### PR TITLE
Improved API consistency for flag data types

### PR DESCRIPTION
**Pull request by slouken**
Flag data types are always unsigned and have the valid values following the typedef.

### CODE REVIEW

**Review by sezero — APPROVED** [review]
Looks OK to me

**Comment by icculus** [comment]
That wasn't as bad as I expected. Let's have the buildbots finish and then it can be merged, as far as I'm concerned.

**Comment by Sackzement** [comment]
Impressive work!

https://github.com/libsdl-org/SDL/blob/4928d0e479d97820cee8ada3d1f72e2ecb697efa/include/SDL3/SDL_joystick.h#L998-L1008
What's the opinion about a type `typedef Uint8 SDL_JoystickHatPosition` for these?

**Comment by slouken** [comment]
> https://github.com/libsdl-org/SDL/blob/4928d0e479d97820cee8ada3d1f72e2ecb697efa/include/SDL3/SDL_joystick.h#L998-L1008
> 
> What's the opinion about a type `typedef Uint8 SDL_JoystickHatPosition` for these?

I thought about that, but it's probably not worth it. If you think it would be, feel free to create a PR for this.

**Comment by Sackzement** [comment]
If the name `SDL_JoystickHatPosition` just wasn't that long.
Any shorter version of the name wouldn't suit or wouldn't be descriptive enough.
I think `Uint8` is better than the alternatives.

**Pull request merged**
