### PR TITLE
SDL_Log: don't rely on printf to forward stderr to the debug stream

### PR DESCRIPTION
**Pull request by madebr**
This partially reverts 125ce7137987ec91b931b4fb97d9c3c7af88c377

## Existing Issue(s)
See #10523

### CODE REVIEW

**Comment by slouken** [comment]
Does this reintroduce the doubled output where we're outputting to stderr and debug output and they're both showing up?

**Comment by madebr** [comment]
Yes. My suggestion for a fix is to not use libc in `SDL_Log`.
This has the disadvantage that people cannot do `freopen` to forward stderr.

**Comment by slouken** [comment]
> Yes.
> 
> My suggestion for a fix is to not use libc in `SDL_Log`. This has the disadvantage that people cannot do `freopen` to forward stderr.

Does that mean that all the tests will no longer output to the console when run under the debugger?

**Comment by madebr** [comment]
> Does that mean that all the tests will no longer output to the console when run under the debugger?

My suggestion is to always do `OutputDebugStream` and `WriteFile`/`WriteConsole` on Windows.
https://github.com/libsdl-org/SDL/blob/d6ad28a4cb87b8bb00893f049f7e6e72063fc3b6/src/SDL_log.c#L586-L611

Remove the `defined(HAVE_STDIO_H)`'s in the above snippet.

**Comment by slouken** [comment]
> My suggestion is to always do `OutputDebugStream` and `WriteFile`/`WriteConsole` on Windows.

Okay, sounds good!

**Comment by madebr** [comment]
Can you review this?

I tested this:
- on the terminal
- running with `sdlprocdump.exe --debug-stream --  testsprite.exe` (double output is expected here)
- running with a C# project https://github.com/libsdl-org/SDL/issues/10049#issuecomment-2177584225
- running with RAD debugger

**Review by slouken — APPROVED** [review]
This looks good to me, thanks!

**Pull request merged**
