### PR TITLE
Added support for ALSA dmix audio output (thanks @sylware!)

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/8577

### CODE REVIEW

**Comment by slouken** [comment]
I did some testing and this appears to work here, except for hotplug. @sylware, did you test hotplugging different devices?

**Comment by sylware** [comment]
(I will need some time to get used to that code again)

As far as I can recall, I did a bit of hotplug testing-ish with an USB soundcard when I was working that part of the code and I used text logging because dota2 seemed to query the device list only once.

If I recall properly, I used adev->name to give to SDL the "$ctl_card_info_get_name:$pcm_info_get_name" string for its device name via SDL_AddAudioDevice (it seems I presumed SDL to take over the life-cyle of that string then did not add the SDL_free you added, wrong?), but internaly I only keep $pcm_info_get_name in adev->name. If I don't miss anything I can recall, I should have used a different variable name for that.

What is the "git clone" URL for this pull request with your commits? (or is there specific mangled branch name to pull from the main repo?)

(I use noscript/basic (x)hmtl browsers, then I can access only github features which were implemented to interop with those browsers)

**Comment by sylware** [comment]
(I will need some time to get used to that code again)

As far as I can recall, I did a bit of hotplug testing-ish with an USB soundcard when I was working that part of the code and I used text logging because dota2 seemed to query the device list only once.

If I recall properly, I used adev->name to give to SDL the "$ctl_card_info_get_name:$pcm_info_get_name" string for its device name via SDL_AddAudioDevice (it seems I presumed SDL to take over the life-cyle of that string then did not add the SDL_free you added, I was probably wrong), but internally I only keep $pcm_info_get_name in adev->name. If I don't miss anything I can recall.

What is the "git clone" URL for this pull request with your commits? (or is there specific mangled branch name to pull from the main repo?)

(I use noscript/basic (x)hmtl browsers, then I can access only github features which were implemented to interop with those browsers)

**Comment by sylware** [comment]
(oops, I posted twice)

That said, I remember I had to restart dota2 to get it to re-list the audio devices to output sound on the USB soundcard, but text-logging showed but that "internally" the device list seemed to be updated fine by the hotplug code.

**Comment by sylware** [comment]
I did check the SDL_AddAudioDevice call graph, it is properly SDL_strdup the name, so that SDL_free seems missing (amazing you got used to that code that fast and already are catching bugs).

I found how to git clone a github pull request on the web.

Regarding hotplug, we need to test it with $SDL_src/test/testaudiohotplug.c or be sure dota2/cs2 are re-query-ing their audio device list from SDL.

I'll give a try to $SDL_src/test/testaudiohotplug.c soon.

**Comment by sylware** [comment]
I retested dota2 SDL3 build but with your modifications and with your SDL test code which I did minimal-ized.

Hotplug is working fine on my end, tested with a USB soundcard.

The minimal-ized testing code is here,
testaudiohotplug_minimal.c :

https://paste.c-net.org/PodiumAdvice

(note, I added SDL_AUDIO_ALSA_PCM_CAPTURE and SDL_AUDIO_ALSA_PCM_PLAYBACK environment variables to allow a user to be able force specific alsa pcms different for capture and playback)

**Comment by sylware** [comment]
Dota2 SDL3 broke again today.

I updated SDL3. This pull request is still not into main and the modified code (renamed capture->recording and factorized out channel map swizzling) is still wrong.

The current dota2 SDL3 is not yet using the factorized out channel map swizzling and only the renaming. I link here renamed capture->recording source file still using its own channel map swizzling code:

SDL_alsa_audio.c https://paste.c-net.org/MatthewWedding

SDL_alsa_audio.h
https://paste.c-net.org/TradingSorcerer

**Comment by sylware** [comment]
Added a github sshd key to my account (still working with noscript/basic (x)html browsers), did a merge of today main into my copy of the pull request repo: seems I don't have the rights to push on the pull request branch.

Here are the latest source files, brutally copying them should be enough.

SDL_alsa_audio.c:

https://paste.c-net.org/PromoIncident

SDL_alsa_audio.h:

https://paste.c-net.org/TradingSorcerer

**Comment by slouken** [comment]
I've updated the PR, thanks!

**Comment by sylware** [comment]
Great news!

I will try to improve the heuristics of multichannel-major configuration in order to make it less likely to fail.

I am going to do that because I think it is more appropriate to scan the whole range of SDL supported number of channels, and not only equal or less than the number of channel requested as it is currently (which is kind of wrong for recording devices, see below).

As an example: on my hardware with my testing programs, I have stereo recording devices (USB audio and HDA-Intel), and the HDA-Intel does fail to configure using the "reasonable default" of 1 channel (mono), dsnoop seems very minimal (the recording equivalent of the playback dmix hardware device sharing with basic conversions). It would mean that user code had to explicitely set the number of channels in the openaudiodevice hint until it got successful, then queried the actual channel number and channel map if any. With this heuristics improvement, user code should be much more likely to get an opened device with some SDL supported number of channels, recording or playback.

At some point, this code will have to be ported to use the SDL generic channel map swizzler code.

**Comment by sylware** [comment]
Hi, coded the scanner of target channel numbers, now stereo recording devices should open successfully seamlessly with dsnoop even with a "requested reasonable default" of 1 channel (mono).

SDL_alsa_audio.c:

https://paste.c-net.org/VolvoYearly

**Comment by sylware** [comment]
dota2 SDL3 broke again, did fix the pull code with the new bool migration code (git of "today"), I did upload the code on paste.c-net.org".

SDL_alsa_audio.c:

https://paste.c-net.org/NinerKidding

**Comment by sylware** [comment]
dota2 updated its libSDL3, still without the fix then audio is still broken. Did fix it on dota git, new code (.c only singe the .h is still the same), available here:

SDL_alsa_audio.c:
https://paste.c-net.org/LouiseHanson

**Comment by icculus** [comment]
Omg, this is totally my fault, I keep getting distracted on other things.

If I don't merge your patch on Monday, please feel free to harass me continuously until I do!

**Comment by sylware** [comment]
Allright :)

Hopefully it won't add too many new bugs.

**Comment by icculus** [comment]
I've got this rebased to the latest in revision control; going to make a pass over it to clean some things up, and then I think we'll merge it.

**Comment by icculus** [comment]
> `If the stdlib usage is intentional, add a '// This should NOT be SDL_<symbol>()' line comment.`

Whoever added this to GitHub Actions (@madebr?)... this is awesome!

**Comment by madebr** [comment]
> > `If the stdlib usage is intentional, add a '// This should NOT be SDL_<symbol>()' line comment.`
> 
> Whoever added this to GitHub Actions (@madebr?)... this is awesome!

I added it to ci, but @1bsyl was the original author (in 70ccf3458701d8563f4b213b1713eafcc052e34e)

**Comment by icculus** [comment]
Okay, I think we're good to go here. It works for me, including hotplug.

@sylware, it would be helpful if you could try this at some point and make sure I didn't break anything.

Notable changes that might cause issues:

- Hints for default device choice got adjusted here: 7f8c7b4a12728524f9320d5678fcd8f14eb05f27 ... these will still work as environment variables, so this _shouldn't_ break anything.

- We try to decide if device name prefixes are "hw:", "default:", etc. This is a modified version of what was in the original hotplug code. This PR had "default:" hardcoded but Ubuntu seems to want "hw:" so I needed this fix. I'd like to make sure this didn't blow up @sylware's setup, though.

- I restored SDL's swizzle code in df483ca0ccbb144bf9f285ab4bf22e06fd67460d, for when ALSA doesn't handle it. I _think_ this is correct, but I can't test it.

**Comment by icculus** [comment]
(I'll push the Merge button on Monday, unless someone says not to before then.)

**Comment by icculus** [comment]
> Did you test this on a recent Raspberry Pi Lite? That's a platform that still uses ALSA by default.

Just tried it on a Pi Zero 2, running the latest Raspberry Pi OS...it worked, including hotplug, with testaudio.

So...last call for feedback, then we merge.

**Comment by slouken** [comment]
Nice! Let's do it!

**Comment by icculus** [comment]
Okay, this will make its way to DOTA2 and the Steam Runtime sooner or later. If more issues crop up, let us know!

**Pull request merged**
