### PR TITLE
Fix iOS build

### LINKED ISSUE #5452: No longer compiles for iOS
SDL2 no longer compiles for iOS:

```
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_OBJC_COMPILE_OBJECT
```

https://github.com/diasurgical/devilutionX/runs/5703068294?check_suite_focus=true

Using the toolchain file from https://github.com/leetal/ios-cmake

Builds just fine for macOS but not iOS

Possibly caused by https://github.com/libsdl-org/SDL/pull/5011

/cc @ericwa @pionere

### PR DESCRIPTION
**Pull request by glebm**
iOS build fails with the following error if `enable_language(OBJC)` is used:

    CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
    Missing variable is:
    CMAKE_OBJC_COMPILE_OBJECT

Avoids `enable_language(OBJC)` on iOS and skips `check_objc_source_compiles` checks.

Fixes https://github.com/libsdl-org/SDL/issues/5452

I have no idea what the actual root cause is but this does fix the iOS build of DevilutionX (https://github.com/diasurgical/devilutionX/pull/4232)

### CODE REVIEW

**Comment by sezero** [comment]
Was 0979cdd not enough on its own?

P.S.: This should be considered for 2.0.22.

**Comment by glebm** [comment]
It's not enough because the `check_objc_source_compiles` check fails without it

**Comment by sezero** [comment]
Is this some kind of cmake bug then??

**Comment by glebm** [comment]
Yeah that is quite possible. Or it could be a bug in ios.toolchainfile.cmake (https://github.com/leetal/ios-cmake)

**Comment by glebm** [comment]
In any case, I don't think we need the `check_objc_source_compiles` checks on iOS because all supported iOS versions also have all these frameworks.

**Comment by ericwa** [comment]
> It's not enough because the check_objc_source_compiles check fails without it

What about just moving this block to the top of `CMakeLists.txt` without adding `AND NOT IOS`?

```
  if (APPLE)
      enable_language(OBJC)
  endif()
```

Based on https://cmake.org/cmake/help/latest/command/enable_language.html it sounds like the `enable_language(OBJC)` call was expected to not work in the old location in `macros.cmake`.

**Comment by icculus** [comment]
Do we still support iOS builds that don't have the GameController framework, etc? I guess it's not unreasonable to say you need to have a newer SDK even if we weak-link to those frameworks. (also, these frameworks might be _ancient_ by now and assumed to be available).

**Comment by glebm** [comment]
> What about just moving this block to the top of CMakeLists.txt without adding AND NOT IOS?

That does not seem to work

**Comment by glebm** [comment]
I don't think you can even submit to the AppStore when targeting older versions, so should be OK for now? Might become an issue if new frameworks are added and we want to check for them, but hopefully the CMake bug is fixed by then.

**Comment by glebm** [comment]
Looks like this may be a bug in ios-cmake: https://github.com/leetal/ios-cmake/issues/138

**Comment by glebm** [comment]
This is indeed fixed by the patch in https://github.com/leetal/ios-cmake/issues/139

**Pull request closed without merging**
