### PR TITLE
Added virtual keyboard support for Xbox (thanks @ts-13512!)

### PR DESCRIPTION
**Pull request by slouken**
This is a port of https://github.com/libsdl-org/SDL/pull/7461 to main, completely untested.

@chalonverse, @ts-13512, can you take a look?

### CODE REVIEW

**Comment by nkrapivin** [comment]
I assume I submitted a similar PR before and it got merged? I might be wrong though...

**Comment by slouken** [comment]
> I assume I submitted a similar PR before and it got merged? I might be wrong though...

No, you didn't. I'll go ahead and merge, please let me know if I got anything wrong?

**Comment by sezero** [comment]
Is #7461 of interest for SDL2 branch?

**Comment by slouken** [comment]
@nkrapivin, wait, you did, in https://github.com/libsdl-org/SDL/pull/7728. I'm confused. Should I back this out, or is this PR complimentary with yours?

**Comment by slouken** [comment]
Sorry about that, I went ahead and reverted this PR.

**Pull request merged**
