### PR TITLE
Added the ability to specify a gamepad type in the mapping

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by sezero** [comment]
In sdl2-compat, we shall map `SDL_GAMEPAD_TYPE_STANDARD` to `SDL_CONTROLLER_TYPE_UNKNOWN` yes?

**Comment by sezero** [comment]
There is no such enumeration or macro as `SDL_GAMEPAD_TYPE_INVALID`

**Comment by slouken** [comment]
> In sdl2-compat, we shall map `SDL_GAMEPAD_TYPE_STANDARD` to `SDL_CONTROLLER_TYPE_UNKNOWN` yes?

Yes.

**Comment by slouken** [comment]
> There is no such enumeration or macro as `SDL_GAMEPAD_TYPE_INVALID`

Fixed, thanks!

**Pull request merged**
