### PR TITLE
Support X11 incremental clipboard transfers.

### LINKED ISSUE #8871: Support X11 incremental clipboard transfers
In our game, copy/pasting very large strings is relatively common, as users can share "blueprint strings" that can grow to be several megabytes large. I attempted to change our codebase to rely on SDL's clipboard functions in lieu of our custom implementations, but that made users unable to [paste large blueprint strings](https://forums.factorio.com/105915) on X11.

Some investigation has revealed the existence of the [INCR mechanism](https://tronche.com/gui/x/icccm/sec-2.html#s-2.5) in X11 to transfer large selections in the clipboard. Our custom X11 clipboard code implements this, but it appears that the SDL X11 clipboard does not, meaning that if this mechanism is used, pasting into the SDL application will not work. I would love it if this could be supported so I can fully rely on the SDL clipboard functions in the future!

Attached below is the problematic string.

[huge-blueprint.txt](https://github.com/libsdl-org/SDL/files/13980251/huge-blueprint.txt)

### PR DESCRIPTION
**Pull request by ramezgerges**
## Description

This adds support for pasting large clipboard contents using the INCR property mechanism
## Existing Issue(s)

Fixes #8871

### CODE REVIEW

**Comment by ramezgerges** [comment]
I couldn't run `testautomation` as it's complaining about audio devices (`Couldn't open audio: No default audio device available`), but otherwise, the change looks functional.

@raiguard, apologies if I'm overstepping here, but I saw the issue has been stale for many months, so I thought I would give it a try.

**Comment by madebr** [comment]
Run the tests with `-DSDL_AUDIO_DRIVER=dummy` to force a dummy audio driver.

**Comment by raiguard** [comment]
Thanks for doing this! It was still on my radar, but other work has taken priority so I wasn't able to dedicate time to this yet. I will give this a test and let you know if I find any problems.

**Comment by ramezgerges** [comment]
> Run the tests with `-DSDL_AUDIO_DRIVER=dummy` to force a dummy audio driver.

@madebr I'm not sure if I'm following correctly, but
```bash
cd `root_of_repo`
cmake -S . -B ./build -DSDL_TEST_LIBRARY=ON -DSDL_TESTS=ON -DSDL_AUDIO_DRIVER=dummy && cmake --build ./build && ./build/test/testautomation
```

didn't work.

**Comment by madebr** [comment]
Oh oops, I meant as an environment variable. The `-D` was not needed at all. Sorry!

**Comment by raiguard** [comment]
I made a small app to test this and it appears to work great! Unfortunately I cannot test it with the actual game since we are still on SDL2, but it should theoretically work just the same.

**Comment by slouken** [comment]
Merged, thanks!

**Pull request merged**
