### PR TITLE
add SDL_LOCALE_DISABLED to SDL_config.h

### PR DESCRIPTION
**Pull request by pionere**
## Existing Issue(s)
None.

### CODE REVIEW

**Comment by sezero** [comment]
As far as I can see, that macro isn't actually used anywhere in the source.
The cmake'ry seems to define it only by following other examples, i.e. it is
a nop.

**Comment by pionere** [comment]
> As far as I can see, that macro isn't actually used anywhere in the source.
At the moment...

> The cmake'ry seems to define it only by following other examples, i.e. it is a nop.
If it would follow the other examples, it would be defined in SDL_config.h

**Comment by sezero** [comment]
> If it would follow the other examples, it would be defined in SDL_config.h

Or, just remove the thing from cmake script: autotools doesn't define it, so why
should cmake.

**Comment by pionere** [comment]
> Or, just remove the thing from cmake script: autotools doesn't define it, so why should cmake.

I don't know about you, but if there is a list of 20 elements which are handled the same way, then I would prefer to handle them everywhere the same way to avoid inconsistencies...

Where is SDL_FILE_DISABLED used?

**Comment by pionere** [comment]
obsolete since #5248

**Pull request closed without merging**
