### PR TITLE
Added property types: pointer, string, number, float

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by slouken** [comment]
@icculus, good? bad? ugly? If good, what do you think about returning const char* vs char* from SDL_GetStringProperty()?

**Comment by icculus** [comment]
Const char; app doesn't own the pointer and should not modify or free it.

**Comment by icculus** [comment]
Also, the Get functions might benefit from a default value: "if this key doesn't exist, return this value instead."

Just an idea.

**Comment by slouken** [comment]
> Also, the Get functions might benefit from a default value: "if this key doesn't exist, return this value instead."
> 
> Just an idea.

I dig it, adding now...

**Pull request merged**
