### PR TITLE
Add SDL_migration.cocci for SDL2 to 3 migration

### PR DESCRIPTION
**Pull request by 1bsyl**
semantic patch for project migration

// - all function renaming (without parameter change) as in SDL_oldnames.h
// - remove SDL_WINDOW_SHOWN
// - migrate SDL_CreateRGB* and SDL_ConvertSurface* functions

### CODE REVIEW

**Comment by slouken** [comment]
Cool, do you want to update rename_api.py to also add to this file, and add documentation to README-migration.md?

**Comment by 1bsyl** [comment]
done!

**Comment by slouken** [comment]
This looks really useful. Feel free to merge when you're comfortable with it.

**Comment by 1bsyl** [comment]
I think this ok now, so this keep track of the remape_api.ph changes.
It can be updated by incremented

**Pull request merged**
