### PR TITLE
Fix SDL2Config.cmake to support static-only builds.

### LINKED ISSUE #4797: SDL2Config.cmake does not check for SDL2::SDL2 and does not handle SDL2-static
I build SDL with

    -DSDL_STATIC=1 
    -DBUILD_SHARED_LIBS=0

which means that there is no SDL2::SDL2 target exported in `SDL2Targets.cmake`. 

But the SDL2Config.cmake still tries to set stuff on SDL2::SDL2, which is incorrect (and rightfully fails).

This worked in 2.0.14.

### PR DESCRIPTION
**Pull request by jcelerier**
Fixes #4797

### CODE REVIEW

**Comment by jcelerier** [comment]
@DanielGibson @slouken review would be welcome :smiley_cat:

**Comment by DanielGibson** [comment]
Looks good to me, thanks for fixing this! :)

**Review by DanielGibson — APPROVED** [review]
looks good!

**Comment by DomGries** [comment]
Isn't this a different version of #4502?

**Comment by DanielGibson** [comment]
True, and maybe #4502 even is a better solution for the problem

**Comment by jcelerier** [comment]
Yes, that would definitely work too!

**Pull request closed without merging**
