### PR TITLE
Windows GDK Support

### PR DESCRIPTION
**Pull request by chalonverse**
## Description
This pull request includes the code changes and Visual Studio project files needed to build SDL2 for Windows GDK. It also includes sample test projects as well as instructions for how to port an existing SDL2 Windows x64 game to Windows GDK. 

Nearly everything that is supported in the normal Windows x64 build will also work in Windows GDK, as Windows GDK does allow you to use the full set of Win32 APIs, renderers, devices, etc.

## Details
* The platform detection declares a `__WINGDK__` define as well as a `__GDK__` define. Two separate defines are needed because Windows GDK supports a much larger set of APIs than Xbox GDK does. This way, it's possible to say whether something is supported on "any GDK" or something works _only_ on Windows GDK. I've gone through and updated all the platform checks in the source code where needed.
* The `SDL_config_wingdk.h` is essentially config_windows except it removes all the Windows SDK versioning checks, and also removes references to compilers other than MSVC or clang (as these are likely the only compilers Microsoft GDK will support any time soon).
* The new set of solution/project files as well as some support files for the tests were added to the new `VisualC-GDK` directory. The solution has only been tested with Visual Studio 2022, but it should work for 2017/2019, as well.
* A recommended `WinMain` implementation is included in `SDL_main_gdk.cpp`, and there is a corresponding `SDL2main.lib` that customers can link against.
* Setup/teardown of GDK and Xbl (in SDL_main_gdk.cpp)
* Support for the global task queue (which is used for all async tasks in GDK). The callbacks are dispatched during `WIN_PumpEvents` on GDK.
* A new `SDL_GDKGetTaskQueue` function that customers can use to get the handle to the global task queue, if needed.
* Projects demonstrating testsprite2 and testgamecontroller working as Windows GDK games
* A new testgdk test program that demonstrates an Xbox Live login workflow using the global task queue.
_NOTE_: This can only be tested with a valid TitleId and MSAAppId -- the ones included in the sample data are test IDs that work okay for local testing but cannot provision Xbox Live services.
* The new `README-gdk.md` includes detailed instructions on how to take an existing SDL Windows x64 game and get it to work for Windows GDK.

## Future Work
This pull request _does not include_:
* Support for tests other than testsprite2, testgamecontroller, and the new testgdk. All the normal Win32 tests should also work on GDK, but it's a bit time consuming to set these up due to the additional data requirements needed to build/package successfully for GDK. I can add more of the tests if that's desired.
* Support for building through CMake. Right now, you can only build through the Visual Studio solution. The samples include a [toolchain file](https://github.com/microsoft/Xbox-GDK-Samples/blob/5c4b7d2c726280ae34d5eac36f269ed3d40761da/Samples/Tools/CMakeExample/Desktop/CMakeGDKDesktop.cmake) so it may be possible to adapt this to work for SDL
* CI build support. This is a little more complicated because the expected workflow is to build after running the GDK installer. This may be possible to do in CI, or alternatively it may be possible to use the "build without installing" workflow that does exist.
* Xbox GDK support. I've not started on this yet, and am still trying to determine from Microsoft whether or not this could be included in the public SDL repo.

## Existing Issue(s)
This (at least partially) fulfills the request in #4519.

### CODE REVIEW

**Review by flibitijibibo — COMMENTED** [review]
This all looks okay, since it's mostly defs to account for Win32 and GDK _technically_ not being the same... all I found were tiny whitespace things.

I guess it'd be neat if main could be a C file but that's assuming those headers support CINTERFACE, which seems less common with new SDKs...

**Comment by chalonverse** [comment]
> I guess it'd be neat if main could be a C file but that's assuming those headers support CINTERFACE, which seems less common with new SDKs...

Unfortunately, basically all the GDK headers have this at the top:
```c++
#if !defined(__cplusplus)
    #error C++11 required
#endif
```

It seems a bit silly because everything is a flat function and structs (there's no COM shenanigans). As far as I can tell, the only C++11 features the headers use are `enum class` and `noexcept`, which it seems like it would be easy to make a C version without those but I guess they _really_ wanted those enum names not polluting the global namespace (or didn't want to spend time supporting C).

I pushed the formatting fixes.

**Comment by flibitijibibo** [comment]
One more thing came up while I was revisiting FNA's existing Xbox support - normally it's not a huge deal if SDLmain has a C++ dependency, but: It may be worth considering declaring the XGameRuntime functions manually, so that we can still call them from C without dealing with the hardcoded language requirement in the GDK headers. The big reason we would want to do this is so that we can do what [iOS/tvOS and WinRT do](https://github.com/libsdl-org/SDL/blob/main/include/SDL_main.h#L195-L225), which is turn the static `main_getcmdline` into an exported `SDL_GDKRunApp` that's built into SDL2.dll. This is particularly helpful for situations like C# applications [which don't have a better way to access SDLmain](https://github.com/FNA-XNA/FNA/wiki/Appendix-B:-FNA-on-Consoles#code-differences) without duplicating the code in various languages (and risking getting desync'd with upstream).

**Comment by chalonverse** [comment]
Ah, so _that's_ why it's setup that way for WinRT.

It's okay if SDL2.dll has the C++ dependency, right? If that's the case, I could probably just make the `SDL_GDKRunApp` function within the SDL2.dll be the one that actually does all the GDK calls (and includes the GDK headers), and then the SDL2main WinMain wouldn't need to do anything other than setup that function.

I don't think declaring C version of the XGameRuntime functions would work because I don't think there's a way to declare a function that takes in an enum class as a parameter in C, and because of that I'm fairly certain they aren't declared extern "C".

**Comment by chalonverse** [comment]
I converted this to draft while I work on those changes. Adding the `SDL_GDKRunApp` is easy enough, I already have that setup locally.

I think I understand how I can remove all the C++ runtime/GDK linker dependencies from the SDL2.dll, also, so I'll try that out. Originally, I had tried that approach, but it didn't find the functions when I used `SDL_LoadFunction`. I realize now that's likely because I was trying to use an unmangled name. Since the functions are not `extern `"C"` and C++, I'm pretty sure if I use the mangled names for them, I'll be able to access them without needing to link all those GDK libs which in turn should mean I won't need to link in any of the MSVC C/C++ runtime libs.

Unfortunately, I'm currently out of town and the cloud VM I'm trying to use doesn't seem to agree with Microsoft Gaming Services (I suspect it just doesn't work on Windows Desktop mode in Windows Server, since Windows Server doesn't support the Microsoft Store and such). So it seems like I need to wait until I get back next week before I can properly test it.

**Comment by flibitijibibo** [comment]
No rush, more time for review - I'll try and get some other FNA maintainers to review this in the meantime.

**Comment by chalonverse** [comment]
Ok, I moved all the GDK initialization into the DLL and `SDL_GDKRunApp`, so should now be possible to use the same pattern as with WinRT or IOS. I also changed `sdl_gdk_main` to just be a C file now (that just has a `WinMain` which calls `SDL_GDKRunApp`). I was able to test these properly on Windows 10 (my theory about Windows Server not supporting the Game Runtime was correct), and the test programs still work as expected.

Unfortunately, it doesn't look like it will be possible to remove the C/C++ runtime and GDK library dependencies for SDL2.dll for GDK. I looked at xgameruntime.dll and it turns out that basically nothing is in the export table, so it's impossible to use the "don't link against the lib and just load the DLL" pattern. That leaves us with needing to link xgameruntime.lib, which brings with it all of the C++ runtime dependencies.

Changing this back to ready for review.

**Review by flibitijibibo — APPROVED** [review]
At least from my end this all looks good to go.

Some points that other maintainers may want to review include dynapi and maybe the tests; the changes in `include` and `src` should be fine. The docs looked fine to me (and will definitely be familiar to anyone working with WinRT or XSAPI elsewhere), the FNA team will be stress-testing that in the near future.

**Comment by Cacodemon345** [comment]
Is this PR really needed though? It looks useful only for PC-exclusive games, and the ones on both Xbox and PC will be relying on NDA'd APIs which implies a private SDL repo.

**Comment by flibitijibibo** [comment]
> Is this PR really needed though? It looks useful only for PC-exclusive games, and the ones on both Xbox and PC will be relying on NDA'd APIs which implies a private SDL repo.

Yes. I fully expect the NDA'd portions to largely be for Xbox Live, rather than the system-level stuff that this covers. WinRT is roughly the same story: Shared OS layer with networking stuff implemented in the app internally. If there are features which require the use of private extensions, those portions can be isolated similar to how WinRT is separated in the shared Windows backends. Nothing I have seen of the private extensions suggests that this will be trampled on significantly, if at all.

**Comment by chalonverse** [comment]
> Is this PR really needed though? It looks useful only for PC-exclusive games, and the ones on both Xbox and PC will be relying on NDA'd APIs which implies a private SDL repo.

Actually, all the shared of the Xbox Live APIs that both PC and Xbox use for GDK are _not_ under NDA anymore. In fact, the testgdk sample (and the SDL_gdk.cpp) uses some of those Xbox Live APIs.

Only a some of Xbox console-specific APIs are still under NDA. And in fact, many of the Xbox console-specific APIs are _not_ still under NDA. For example, [`XSystemGetDeviceType`](https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/reference/system/xsystem/functions/xsystemgetdevicetype) is only for Xbox, but it's not NDA'd anymore. The guidance I got from Microsoft is that if the API is either a.) referenced by the public GDK documentation or b.) is visible from the headers included with the public GDK release, it's fine for 3rd parties to include in publicly shared code.

All of the GDK-specific code in this PR will also work on Xbox. The main things that SDL for Xbox will need to do is disable many Win32 modules, add platform-defines, add some special Xbox code for DirectX 12, and potentially have an implementation of GameInput (though initially, my plan is to use [XInputOnGameInput](https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/reference/input/xinputongameinput/xinputongameinput_members)). Additionally, it will need different/modified Visual Studio Project files.

Out of all of that, the only thing that is still under NDA is the special DirectX 12 Xbox code (and I'm hoping Microsoft will relax this, too). So almost _all_ the SDL Xbox GDK code could be in the public repo, and I will be submitting that in a future PR. I'm pretty sure that the private repo just need a special versionof `SDL_render_d3d12.c` and `SDL_shaders_d3d12.c`, and I would propose for maintenance/merging purposes it makes sense that anything that can be public stay in the public repo.

Obviously, you wouldn't be able to build for the Xbox targets without GDKX, though.

**Comment by TheSpydog** [comment]
> Out of all of that, the only thing that is still under NDA is the special DirectX 12 Xbox code (and I'm hoping Microsoft will relax this, too).

Given that [the public Xbox GDK samples](https://github.com/microsoft/Xbox-GDK-Samples) use the special DirectX 12 Xbox APIs, I wonder if these fall into the category of "public GDK documentation" as well.

**Comment by chalonverse** [comment]
Yeah, that's what I'm hoping I can use to convince Microsoft that it is public enough already.

**Comment by slouken** [comment]
Just as a sanity check, what's the benefit of adding GDK support?

Once the conflicts are resolved, I'm fine with merging this.

**Pull request merged**
