### PR TITLE
Handle subsystem dependencies recursively

### LINKED ISSUE #8381: [SDL2 & SDL3] Potential subsystem reference miscount from initialized "dependencies"
**NOTE:** I have not looked too close, but *possibly* this may be also an issue in SDL3.

I was pointed out to this issue by another person (@ericoporto). Apparently SDL2 can end up with extra or not enough reference count for subsystems, which may result in either subsystems never removed (until ending SDL_Quit() call) or removed **too early**, maybe to a user's surprise.

This may happen when user calls SDL_InitSubSystem for subsystems that have dependencies, for example: Controller requires Joystick, several systems require Events, and so forth. As may be seen in this code here, SDL2 adds dependencies to initialization, which also leads to incrementing their reference counts:
https://github.com/libsdl-org/SDL/blob/32587bd7de23c057cf791e1b93e74885688c3e56/src/SDL.c#L190-L193

This dependency check is mirrored in SDL_QuitSubSystem, leading to decrementing the reference count of the "dependencies":
https://github.com/libsdl-org/SDL/blob/32587bd7de23c057cf791e1b93e74885688c3e56/src/SDL.c#L415-L417

So how may this be an issue?

Let's investigate two code examples.

Example 1:
```
// Init at program start one by one, maybe I do a step by step init reading from config, or something
SDL_InitSubSystem(SDL_INIT_VIDEO); // +1 EVENTS ref count
SDL_InitSubSystem(SDL_INIT_AUDIO); // +1 EVENTS ref count
SDL_InitSubSystem(SDL_INIT_JOYSTICKS); // +1 EVENTS ref count

// Uninit later, all at once
SDL_QuitSubSystem(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICKS); // -1 EVENTS ref count

// +2 EVENTS ref count remaining
```

Here, from a user's perspective, everything is fine, as the number of subsystems inits and uninits match. What user does not realize is that the number of dependencies inits and uninits does **not** match, leaving "dangling" references.

But this case is not as dangerous, because SDL_Quit will clear them anyway. However, there may be an opposite scenario

Example 2:
```
// Init at program start
SDL_InitSubSystem(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICKS); // +1 EVENTS ref count

// Uninit later, maybe i don't want audio for some reason
SDL_QuitSubSystem(SDL_INIT_AUDIO); // -1 EVENTS ref count

// EVENTS subsystem was removed at this point
```

Here EVENTS subsystem will be removed while there are still subsystems that supposedly require it.
This may be proved by calling `SDL_WasInit(SDL_INIT_EVENTS)` in between these steps.

---

I gave this a bit of thought, and the first solution that comes to mind is to increment dependency's refcounts *by the number of dependents*.

In other words, in case of:
```
SDL_InitSubSystem(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICKS);
```
there should be +3 EVENTS ref counts added. And same mirrored in SDL_QuitSubSystem.

But I don't know how compatible this is with the SDL's design, because user may also call SDL_QuitSubSystem(SDL_INIT_EVENTS) and probably expect to have it removed at once? Another approach may be to keep separate record of "internal" ref counts, but that will increase the code complexity.

### PR DESCRIPTION
**Pull request by ivan-mogilko**
## Description
This applies to subsystem dependencies such as Joystick necessary for Gamepad, Events needed for multiple other systems.
Existing code is erroneous, because it adds or removes dependency's ref count based on number of InitSubSystem/QuitSubSystem calls, while ref count diff should depend on number of inited or quit dependents. Recursive approach seems to be simplest solution that guarantees proper ref count. I hope it's okay to do this as supposedly this should not affect performance much.

Used following code sample to test its work:
```
    // Init 3 subsystems separately
    SDL_InitSubSystem(SDL_INIT_VIDEO); // +1 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_VIDEO | SDL_INIT_EVENTS) == SDL_INIT_VIDEO | SDL_INIT_EVENTS);
    SDL_InitSubSystem(SDL_INIT_AUDIO); // +1 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_AUDIO | SDL_INIT_EVENTS) == SDL_INIT_AUDIO | SDL_INIT_EVENTS);
    SDL_InitSubSystem(SDL_INIT_JOYSTICK); // +1 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_JOYSTICK | SDL_INIT_EVENTS) == SDL_INIT_JOYSTICK | SDL_INIT_EVENTS);

    // Uninit all at once
    SDL_QuitSubSystem(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICK); // -3 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICK | SDL_INIT_EVENTS) == 0);

    // Init 3 subsystems at once
    SDL_InitSubSystem(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICK); // +3 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICK | SDL_INIT_EVENTS) ==
        SDL_INIT_VIDEO | SDL_INIT_AUDIO | SDL_INIT_JOYSTICK | SDL_INIT_EVENTS);

    // Uninit subsystems one by one
    SDL_QuitSubSystem(SDL_INIT_VIDEO); // -1 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_VIDEO | SDL_INIT_EVENTS) == SDL_INIT_EVENTS);
    SDL_QuitSubSystem(SDL_INIT_AUDIO); // -1 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_AUDIO | SDL_INIT_EVENTS) == SDL_INIT_EVENTS);
    SDL_QuitSubSystem(SDL_INIT_JOYSTICK); // -1 EVENTS ref count
    SDL_assert(SDL_WasInit(SDL_INIT_JOYSTICK | SDL_INIT_EVENTS) == 0);

    SDL_Quit();
```

## Existing Issue(s)
Fix #8381

### CODE REVIEW

**Comment by ivan-mogilko** [comment]
From reading the build logs, if i get this right, there are 2 automatic tests failing:

1. events_pushPumpAndPollUserevent (`Check result from SDL_PollEvent, expected: 1, got: 0`)
2. video_getSetWindowGrab (`Expectded window with focus`)

**Comment by ivan-mogilko** [comment]
Alright, that was a stupid mistake by me, I was "quitting" the dependencies in a wrong place.

But while debugging this, I noticed that some of the subsystems actually init and uninit Events subsystem again in their own Init/Quit functions, and that's not fully consistent: SDL_InitJoysticks() and SDL_VideoInit() do that, but SDL_InitAudio does not, although it requires events in InitSubSystem. I guess that should not be an issue so long as it's all paired in Quit functions correctly, but I thought I'd mention this.

**Comment by ivan-mogilko** [comment]
@slouken Do you think that it will be worth adding automatic tests for subsystem refcounts as a part of this PR?

**Comment by slouken** [comment]
> @slouken Do you think that it will be worth adding automatic tests for subsystem refcounts as a part of this PR?

Yes, that seems like a good idea.

**Comment by slouken** [comment]
> I noticed that some of the subsystems actually init and uninit Events subsystem again in their own Init/Quit functions, and that's not fully consistent: SDL_InitJoysticks() and SDL_VideoInit() do that, but SDL_InitAudio does not, although it requires events in InitSubSystem. This means that if a Video is inited, the Event's refcount raises +2 at once, and lowers -2 when Video is shut down. I guess that should not be an issue so long as it's all paired in Quit functions correctly, but I thought I'd mention this.

@icculus, do you think we should do anything about this?

**Comment by ivan-mogilko** [comment]
> > @slouken Do you think that it will be worth adding automatic tests for subsystem refcounts as a part of this PR?
> 
> Yes, that seems like a good idea.

I looked into this, and am in doubts about how to approach this, or whether this is even doable at this point.
The test program initializes certain systems at startup prior to running any "test suites" ([e.g. see here](https://github.com/libsdl-org/SDL/blob/9aeabb0b05e04b40cad9ccddd6b40a3de0ae3c54/src/test/SDL_test_common.c#L1173)), and also other subsystems may be initialized during random tests and kept. For instance, the events subsystem is never initialized explicitly, but events test suite assumes that it is ready (and it's ready because it was inited by others which depend on it).

**Comment by madebr** [comment]
> I looked into this, and am in doubts about how to approach this, or whether this is even doable at this point. The test program initializes certain systems at startup prior to running any "test suites" ([e.g. see here](https://github.com/libsdl-org/SDL/blob/9aeabb0b05e04b40cad9ccddd6b40a3de0ae3c54/src/test/SDL_test_common.c#L1173)), and also other subsystems may be initialized during random tests and kept. For instance, the events subsystem is never initialized explicitly, but events test suite assumes that it is ready (and it's ready because it was inited by others which depend on it).

I also ran into this in https://github.com/libsdl-org/SDL/pull/8347/files, and added setup and teardown functions for the events tests.

**Comment by slouken** [comment]
It also doesn't have to be part of the automated tests, we could create a specific test for this and add it to CI.

**Comment by ivan-mogilko** [comment]
So, I added the tests (see last commit [dc5d98a](https://github.com/libsdl-org/SDL/pull/8385/commits/dc5d98ab29c1cf4ef07f7d7c0589fffe7e15f96b)), and they seem to be passing according to the build logs.

But I had to add it last in the list of "suites", for the time being, in order to not interfere with the other tests. I noticed that few tests could fail if it's run earlier. Possibly this could be fixed by writing proper "startup" functions for those, but maybe it's best to leave this for a separate task?

**Comment by ericoporto** [comment]
Hey, any chance this gets picked to SDL2 too?

**Comment by slouken** [comment]
It doesn't cleanly cherry-pick. @ivan-mogilko, can you create an SDL2 PR for this?

**Comment by ivan-mogilko** [comment]
Opened a PR for SDL2: #8493

**Pull request merged**
