### PR TITLE
Fix SDL_GetRectAndLineIntersectionFloat()

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/6791

### CODE REVIEW

**Comment by icculus** [comment]
I think this can be merged, I'll try to get the conflicts resolved in a moment.

**Comment by sezero** [comment]
This was possibly against SDL2...

**Comment by icculus** [comment]
Oh, actually, this shouldn't merge as-is:

https://github.com/libsdl-org/SDL/issues/6791#issuecomment-1593848158

**Comment by slouken** [comment]
I'm going to go ahead and close this, since this isn't the fix we're looking for...

**Pull request closed without merging**
