### PR TITLE
X11: handle fullscreen event

### PR DESCRIPTION
**Pull request by wooosh**
Solves #5390. Detects the fullscreen property of an x11 window changing and updates the SDL window flags.

@jo-valve Do you mind testing this to confirm it works?

### CODE REVIEW

**Comment by jo-valve** [comment]
In the example program from https://github.com/libsdl-org/SDL/issues/5390, if I toggle fullscreen in the window manager, the window color gets set accordingly, but the next time I try to toggle fullscreen using the SDL keyboard event, the window color changes without its style changing.

**Comment by jo-valve** [comment]
Differentiating between `SDL_WINDOW_FULLSCREEN` and `SDL_WINDOW_FULLSCREEN_DESKTOP` complicates this somewhat. See https://github.com/libsdl-org/SDL/issues/5390#issuecomment-1064304165

**Comment by slouken** [comment]
@icculus, we decided not to do this, right?

**Comment by icculus** [comment]
We did. Closing.

**Pull request closed without merging**
