### PR TITLE
GDK: Fix some Xbox regressions / code rot

### PR DESCRIPTION
**Pull request by 0x0ade**
## Description
This PR fixes a bunch of regressions. I figured it'd make sense to batch together all commits into one PR, as it's mostly smaller fixes related to one or another piece of the Win32 API being desktop-only.

The largest chunk that isn't basic .vcxproj / Win32 / C-vs-C++ cleanup is getting rid of the duplicated (and by now outdated) shaders in the GDK directory, changing the build .bat to support both Windows and Xbox (hopefully preventing future desyncs), and fixing the existing shader sources to make them run properly on Xbox again (the root signatures were mismatched across .hlsl files, so I've shoved them into yet another .hlsl include file).

Confirmed building and running for Windows using the VisualC solution, and Scarlett using the VisualC-GDK solution.

### CODE REVIEW

**Comment by 0x0ade** [comment]
As an aside: The first commit in this patchset also applies to SDL2, as the commit to use `MsgWaitForMultipleObjects` has been cherry-picked onto that branch too. Should I submit a separate PR to that branch, or will the partial revert be cherry-picked once this PR is merged? 😅

**Review by flibitijibibo — APPROVED** [review]
lgtm but I didn't look too much into the shader changes, will let someone look at that before mashing merge.

**Comment by slouken** [comment]
Looks good, thanks!

**Comment by sezero** [comment]
> As an aside: The first commit in this patchset also applies to SDL2, as the commit to use `MsgWaitForMultipleObjects` has been cherry-picked onto that branch too. Should I submit a separate PR to that branch, or will the partial revert be cherry-picked once this PR is merged?

A separate pull request would be good, I think

**Comment by sezero** [comment]
> > As an aside: The first commit in this patchset also applies to SDL2, as the commit to use `MsgWaitForMultipleObjects` has been cherry-picked onto that branch too. Should I submit a separate PR to that branch, or will the partial revert be cherry-picked once this PR is merged?
> 
> A separate pull request would be good, I think, at least because platform check macros are not the same between SDL2 and SDL3

Got no response, I cooked the following: Is it correct? (Not even build-tested, don't have the env..)

```diff
diff --git a/src/video/windows/SDL_windowsevents.c b/src/video/windows/SDL_windowsevents.c
index 8e05c41..d51cc2a 100644
--- a/src/video/windows/SDL_windowsevents.c
+++ b/src/video/windows/SDL_windowsevents.c
@@ -1802,16 +1802,48 @@ void SDL_SetWindowsMessageHook(SDL_WindowsMessageHook callback, void *userdata)
 
 int WIN_WaitEventTimeout(_THIS, int timeout)
 {
     if (g_WindowsEnableMessageLoop) {
+#if !defined(__XBOXONE__) && !defined(__XBOXSERIES__)
         DWORD dwMilliseconds, ret;
         dwMilliseconds = timeout < 0 ? INFINITE : (DWORD)timeout;
         ret = MsgWaitForMultipleObjects(0, NULL, FALSE, dwMilliseconds, QS_ALLINPUT);
         if (ret == WAIT_OBJECT_0) {
             return 1;
         } else {
             return 0;
         }
+#else
+        /* MsgWaitForMultipleObjects is desktop-only. */
+        MSG msg;
+        BOOL message_result;
+        UINT_PTR timer_id = 0;
+        if (timeout > 0) {
+            timer_id = SetTimer(NULL, 0, timeout, NULL);
+            message_result = GetMessage(&msg, 0, 0, 0);
+            KillTimer(NULL, timer_id);
+        } else if (timeout == 0) {
+            message_result = PeekMessage(&msg, NULL, 0, 0, PM_REMOVE);
+        } else {
+            message_result = GetMessage(&msg, 0, 0, 0);
+        }
+        if (message_result) {
+            if (msg.message == WM_TIMER && !msg.hwnd && msg.wParam == timer_id) {
+                return 0;
+            }
+            if (g_WindowsMessageHook) {
+                if (!g_WindowsMessageHook(g_WindowsMessageHookData, &msg)) {
+                    return 1;
+                }
+            }
+            /* Always translate the message in case it's a non-SDL window (e.g. with Qt integration) */
+            TranslateMessage(&msg);
+            DispatchMessage(&msg);
+            return 1;
+        } else {
+            return 0;
+        }
+#endif /*!defined(__XBOXONE__) && !defined(__XBOXSERIES__)*/
     } else {
         /* Fail the wait so the caller falls back to polling */
         return -1;
     }
```

**Comment by 0x0ade** [comment]
Sorry for not replying sooner 😅 IIRC I saw a comment on another PR that pointed towards `_GAMING_XBOX` being a better substitute, but SDL2 uses those macros everywhere else, so that checks out. And I just plopped in the changes to do a test build, and it builds 👍 sadly won't have the time to actually run SDL2 testsprite2 / testgamecontroller on consoles until later in the week, but given that SDL3 ran fine with that change, LGTM.

**Comment by sezero** [comment]
OK, patch applied to SDL2 as da9bfc43e796182f7d5c8bfc86a5ec2e50ae90d0 and cherry-picked to 2.30.x as dae123248910467efd48bc3df3da8a77cef667cc. Thanks.

**Pull request merged**
