### PR TITLE
vsync support on darwin change proposal.

### PR DESCRIPTION
**Pull request by devnexen**
## Description

using the CGL inner object rather than the objective C wrapper.
as mentionned in the code comment, as long apple supports OpenGL,
 we still have the possibility to do so.

Tip used by the godot engine and a handful of video games bypassing
 SDL_GL_SetSwapInterval.

### CODE REVIEW

**Comment by slime73** [comment]
Does this allow SetSwapInterval to work better or fix an issue or something?

**Comment by slime73** [comment]
> more reliably it seems especially with external monitors

I ran a quick test with and without this change, and vsync seems to be working fine for me with an external monitor either way. I was creating the window on my main (laptop) screen and dragging it to my other display. Do you have specific repro steps for the current NSOpenGL code not working?

(as an aside, macOS seems to turn vsync off for an OpenGL window while it's minimized or in another Space that's hidden. This change doesn't seem to affect that either.)

**Comment by devnexen** [comment]
So far tested with yquake2 (a bug was reported) then I saw godot engine did the same https://github.com/godotengine/godot/blob/c2a616f3ecc5fa0ee7d85507b971e7578000a562/platform/osx/context_gl_osx.mm#L63 while also gzdoom reported working better with it too https://github.com/coelckers/gzdoom/blob/567bff403a0e52d32e946310d94689e1258a8475/src/common/platform/posix/sdl/sdlglvideo.cpp#L692 so it seems contextually working better or working equally as the actual situation.

> (as an aside, macOS seems to turn vsync off for an OpenGL window while it's minimized or in another Space that's hidden. This change doesn't seem to affect that either.)

I do not think we can do anything about this unless sorting ugly hacks, I do not see it changed anytime soon metal being apple forefront solution now.

**Comment by DanielGibson** [comment]
@icculus @slime73 Could we get this patch into 2.0.20? Or does it look like it might break anything?
@devnexen can you do adjust the xcode project to also link the opengl framework (to fix https://github.com/libsdl-org/SDL/pull/4839#discussion_r730334229)?

**Comment by slime73** [comment]
I still don't really understand if it solves any known issue. The yquake2 issue hasn't discussed this change as a potential fix for the issue they're having (which might just be a general macOS OpenGL vsync issue, I'm not sure). The linked gzdoom code was written before SDL2 was released (indicating it might not have to do with this API working better), etc.

That's not to say this change is guaranteed to make no difference, I just don't know what the difference is, so it makes me a bit nervous to merge it especially since it involves build system changes.

**Comment by DanielGibson** [comment]
> I still don't really understand if it solves any known issue. The yquake2 issue hasn't discussed this change as a potential fix for the issue they're having

Good point. For reference, the YQ2 issue is https://github.com/yquake2/yquake2/issues/745 (vsync limits to 80fps on a 120Hz screen), the YQ2 PR that wanted to merge this change into YQ2 (where I suggested getting it upstream into SDL instead) is https://github.com/yquake2/yquake2/pull/749
@slime73 do you have a 120Hz screen to test?

@devnexen were you able to test this yourself (do you have a 120Hz screen) or did you apply a patch that was reported working for gzdoom without being able to verify if it helps?

**Comment by DanielGibson** [comment]
FWIW, https://github.com/libsdl-org/SDL/issues/4918#issuecomment-993377592 and following report the same issue (80Hz on 120Hz display when enabling vsync)

**Comment by slime73** [comment]
> do you have a 120Hz screen to test?

I have a 120hz monitor but unfortunately I don't have the right connectors to hook it up to my Mac machines at 120+hz, only 60hz (since they don't have DisplayPort and I don't have a new enough HDMI cable).

**Comment by slime73** [comment]
Maybe we could get some people in #4918 to test a build of this? I don't think it's very likely to fix their issue because the higher level NSOpenGL code should be calling into the same stuff as the lower level CGL code does, but it's worth a shot I suppose.

**Comment by DanielGibson** [comment]
Good idea!
Can you provide them a build? (I can't, I don't even have a Mac)

**Comment by icculus** [comment]
Also, if this is a workaround for a legit macOS bug, I would like to pass it on to our Apple contacts to see if the OS can get a fix instead.

**Comment by devnexen** [comment]
> > I still don't really understand if it solves any known issue. The yquake2 issue hasn't discussed this change as a potential fix for the issue they're having
> 
> Good point. For reference, the YQ2 issue is [yquake2/yquake2#745](https://github.com/yquake2/yquake2/issues/745) (vsync limits to 80fps on a 120Hz screen), the YQ2 PR that wanted to merge this change into YQ2 (where I suggested getting it upstream into SDL instead) is [yquake2/yquake2#749](https://github.com/yquake2/yquake2/pull/749) @slime73 do you have a 120Hz screen to test?
> 
> @devnexen were you able to test this yourself (do you have a 120Hz screen) or did you apply a patch that was reported working for gzdoom without being able to verify if it helps?

sorry for late reply, I tested on external screen but not a 120Hz unfortunately.

**Comment by devnexen** [comment]
> Also, if this is a workaround for a legit macOS bug, I would like to pass it on to our Apple contacts to see if the OS can get a fix instead.

I doubt they would accept, they might answer just use Metal, other OpenGL bugs had been reported in the past.

**Comment by DanielGibson** [comment]
> Also, if this is a workaround for a legit macOS bug, I would like to pass it on to our Apple contacts to see if the OS can get a fix instead.

Good idea - you could do that anyway, as it definitely is a bug, no matter if this workaround helps or not

**Comment by NuclearMonster** [comment]
I was asked to test this out, and went through a long journey of realizing I had to reinstall homebrew (brew bundle is your friend) and then code signing (make a new self-signed certificate in Keychain Access and sign (or re-sign if you're starting from Tom Kidd's yquake2 binary and just want to replace SDL) **the entire .app** using [this guide](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW2) because MacOS won't let you have a library loaded with a different certificate than the rest of the app bundle, the final command was `codesign -s "Nuclear Code Signing" -v --deep --force yquake2.app`)

Anyway, here's my test result with this patch which seems entirely bizarre: 
On either the internal MacBook Pro (2021) (running MacOS 12.1) display (set to ProMotion/up to 120fps) or an external VRR monitor I don't get a 120 FPS locked framerate unless I turn vsync off in yquake2. With vsync on I get a variable framerate (that is often below 70 or 80 frames per second) but staring at the ground in yquake2 should give me a ton of frames and instead it is usually under a hundred according to the in-game counter. 
So, to be clear: turning vsync off in yquake2 (originally compiled by Tom Kidd) gave me a locked 120 using an SDL dylib compiled (by me) with this patch.

**Comment by DanielGibson** [comment]
Thanks for testing!

So I guess @slime73 was right with
> I don't think it's very likely to fix their issue because the higher level NSOpenGL code should be calling into the same stuff as the lower level CGL code does (and this change is basically just swapping out which API is called that sets the same flags, rather than changing the method of vsync itself)

Your comment in the MacSourcePorts Discord sounds like it might go in the right direction:
> I wonder if you need to tell the OS that you want/need “ProMotion” to get 120 vsync

(posting it here in case someone else has an idea how to enable ProMotion from code so you could test the hypothesis)

**Comment by icculus** [comment]
We ended up moving back to CVDisplayLink for 2.26.0, and fixed it up to work across different monitors...also, Apple's GL is becoming untrustworthy for managing this directly, at the Cocoa or CG level, so this patch isn't necessary now.

**Pull request closed without merging**
