### PR TITLE
Fix uses of undefined macro identifiers (-Wundef) [SDL2]

### PR DESCRIPTION
**Pull request by madebr**
This is the SDL2 equivalent of https://github.com/libsdl-org/SDL/pull/7551

## Description
- Every commit fixes use of a certain macro identifier.
Therefore, this pr is very bloated and should be squashed if accepted.
- define `__(IPHONE|APPLETV|MAC)_OS_VERSION_MAX_ALLOWED` to 0 in `src/joystick/iphoneos/SDL_mfijoystick.m`, when these are not defined.
- Add `SDL_WINAPI_FAMILY_PHONE` to `SDL_platform.h`
- Add `-Wundef` when building with a gcc-compatible compiler.

## Existing Issue(s)
#7551

Perhaps it's best to not merge this before the next minor SDL2 release. Just playing safe here.

### CODE REVIEW

**Comment by sezero** [comment]
I think this needs a rebase and then can be merged?

**Comment by madebr** [comment]
@sezero Can you run the diff again?

**Comment by sezero** [comment]
Here it is: Looks like style / whitespace differences only. (Irrelevant parts excluded)

```diff
diff -ur sdl2-compat/src/dynapi/SDL_dynapi.c SDL-sezero/src/dynapi/SDL_dynapi.c
--- sdl2-compat/src/dynapi/SDL_dynapi.c
+++ SDL-sezero/src/dynapi/SDL_dynapi.c
@@ -509,7 +505,7 @@
     /* SDL_AtomicLock calls SDL mutex functions to emulate if
        SDL_ATOMIC_DISABLED, which we can't do here, so in such a
        configuration, you're on your own. */
-    #if !defined(SDL_ATOMIC_DISABLED)
+    #ifndef SDL_ATOMIC_DISABLED
     static SDL_SpinLock lock = 0;
     SDL_AtomicLock_REAL(&lock);
     #endif
@@ -519,7 +515,7 @@
         already_initialized = SDL_TRUE;
     }
 
-    #if !defined(SDL_ATOMIC_DISABLED)
+    #ifndef SDL_ATOMIC_DISABLED
     SDL_AtomicUnlock_REAL(&lock);
     #endif
 }
diff -ur sdl2-compat/test/testgl2.c SDL-sezero/test/testgl2.c
--- sdl2-compat/test/testgl2.c
+++ SDL-sezero/test/testgl2.c
@@ -45,7 +40,7 @@
 
 static int LoadContext(GL_Context *data)
 {
-#if  defined(SDL_VIDEO_DRIVER_UIKIT)
+#ifdef SDL_VIDEO_DRIVER_UIKIT
 #define __SDL_NOGETPROCADDR__
 #elif defined(SDL_VIDEO_DRIVER_ANDROID)
 #define __SDL_NOGETPROCADDR__
@@ -53,7 +48,7 @@
 #define __SDL_NOGETPROCADDR__
 #endif
 
-#if defined(__SDL_NOGETPROCADDR__)
+#if defined __SDL_NOGETPROCADDR__
 #define SDL_PROC(ret, func, params) data->func = func;
 #else
 #define SDL_PROC(ret, func, params)                                                         \
diff -ur sdl2-compat/test/testgles2.c SDL-sezero/test/testgles2.c
--- sdl2-compat/test/testgles2.c
+++ SDL-sezero/test/testgles2.c
@@ -69,7 +65,7 @@
 
 static int LoadContext(GLES2_Context *data)
 {
-#if defined(SDL_VIDEO_DRIVER_UIKIT)
+#ifdef SDL_VIDEO_DRIVER_UIKIT
 #define __SDL_NOGETPROCADDR__
 #elif defined(SDL_VIDEO_DRIVER_ANDROID)
 #define __SDL_NOGETPROCADDR__
@@ -77,7 +73,7 @@
 #define __SDL_NOGETPROCADDR__
 #endif
 
-#if defined(__SDL_NOGETPROCADDR__)
+#if defined __SDL_NOGETPROCADDR__
 #define SDL_PROC(ret, func, params) data->func = func;
 #else
 #define SDL_PROC(ret, func, params)                                                            \
@@ -901,9 +893,9 @@
         SDL_Log("%2.2f frames per second\n",
                 ((double)frames * 1000) / (now - then));
     }
-#if !defined(__ANDROID__) && !defined(__NACL__)  
+#if !defined(__ANDROID__) && !defined(__NACL__)
     quit(0);
-#endif    
+#endif
     return 0;
 }
 
diff -ur sdl2-compat/test/testgles2_sdf.c SDL-sezero/test/testgles2_sdf.c
--- sdl2-compat/test/testgles2_sdf.c
+++ SDL-sezero/test/testgles2_sdf.c
@@ -68,7 +63,7 @@
 
 static int LoadContext(GLES2_Context *data)
 {
-#if defined(SDL_VIDEO_DRIVER_UIKIT)
+#ifdef SDL_VIDEO_DRIVER_UIKIT
 #define __SDL_NOGETPROCADDR__
 #elif defined(SDL_VIDEO_DRIVER_ANDROID)
 #define __SDL_NOGETPROCADDR__
@@ -76,7 +71,7 @@
 #define __SDL_NOGETPROCADDR__
 #endif
 
-#if defined(__SDL_NOGETPROCADDR__)
+#if defined __SDL_NOGETPROCADDR__
 #define SDL_PROC(ret, func, params) data->func = func;
 #else
 #define SDL_PROC(ret, func, params)                                                            \
diff -ur sdl2-compat/test/testime.c SDL-sezero/test/testime.c
--- sdl2-compat/test/testime.c
+++ SDL-sezero/test/testime.c
@@ -29,7 +29,7 @@
 #ifdef HAVE_SDL_TTF
 #ifdef __MACOSX__
 #define DEFAULT_FONT "/System/Library/Fonts/华文细黑.ttf"
-#elif __WIN32__
+#elif defined(__WIN32__)
 /* Some japanese font present on at least Windows 8.1. */
 #define DEFAULT_FONT "C:\\Windows\\Fonts\\yugothic.ttf"
 #else
diff -ur sdl2-compat/src/test/SDL_test_common.c SDL-sezero/src/test/SDL_test_common.c
--- sdl2-compat/src/test/SDL_test_common.c
+++ SDL-sezero/src/test/SDL_test_common.c
@@ -1121,7 +1121,7 @@
             SDL_DisplayMode mode;
             int bpp;
             Uint32 Rmask, Gmask, Bmask, Amask;
-#if defined(SDL_VIDEO_DRIVER_WINDOWS)
+#ifdef SDL_VIDEO_DRIVER_WINDOWS
             int adapterIndex = 0;
             int outputIndex = 0;
 #endif
```

**Comment by madebr** [comment]
Thanks, the diff looks good.
I have another pending pr where the sdl2 tests are getting fixed for ci. Let's recopy the tests to sdl2-compat after that.

**Comment by sezero** [comment]
OK

**Comment by sezero** [comment]
@madebr: Pushed https://github.com/libsdl-org/SDL/commit/7a34e14c8e5d577b2fedb36c7d8e2ce8acb22696 to fix -Wundef errors in OpenBSD buildbot. Make sure nothing is amiss.

**Pull request merged**
