### PR TITLE
Added an automated test to check creation of minimized windows

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by slouken** [comment]
@madebr, any idea how the test can fail without any of the debug spew that was added in my last commit?

**Comment by slouken** [comment]
It doesn't fail locally, of course. :)

**Comment by madebr** [comment]
It fails with the dummy video driver.
Run the tests with `--video dummy`.

**Comment by slouken** [comment]
Oh... because restore is not implemented there. Hah, thanks!

**Pull request merged**
