### PR TITLE
Add support for building SDL with Watcom compilers using CMake

### PR DESCRIPTION
**Pull request by madebr**
This pr ports `Makefile.w32` and `Makefile.os2` to the cmake build script.

### CODE REVIEW

**Comment by sezero** [comment]
When targeting windows with watcom, `__cdecl` gets in the way and needs
handling properly: Our current solution is defining `DECLSPEC` as an empty
macro and using an exports file. See lines 36 and 252 of Makefile.w32 if
you haven't handled that already.

**Comment by sezero** [comment]
Does cmake automatically add `-bd` to compiler switches when building a dll?

**Comment by madebr** [comment]
> When targeting windows with watcom, `__cdecl` gets in the way and needs handling properly: Our current solution is defining `DECLSPEC` as an empty macro and using an exports file. See lines 36 and 252 of Makefile.w32 if you haven't handled that already.

I saw those lines, but forgot to port these as I didn't see any link errors when using/testing the DLL.
I'll add those lines.

> Does cmake automatically add `-bd` to compiler switches when building a dll?

Yes, it's [added automatically](https://github.com/Kitware/CMake/blob/57ccad00010cd32d07592f6cefd004714e6993ad/Modules/Platform/Windows-OpenWatcom.cmake#L13).

**Comment by sezero** [comment]
> > When targeting windows with watcom, `__cdecl` gets in the way and needs handling properly: Our current solution is defining `DECLSPEC` as an empty macro and using an exports file. See lines 36 and 252 of Makefile.w32 if you haven't handled that already.
> 
> I saw those lines, but forgot to port these as I didn't see any link errors when using/testing the DLL

The issue is, if you don't do that the dll will only work exes built with watcom against a
watcom-generated import library. This way you can replace the mingw- or msvc-built dll
with a watcom-built one and the corresponding exe will still work correctly.

**Comment by madebr** [comment]
Thanks for explaining to me, I fixed it in the latest commit.

If you test this on your local machine, make sure to use the latest nightly open watcom 2.0 build because older versions cannot handle response files that are too big.

**Comment by slouken** [comment]
Is this something that someone asked for? It seems like Makefile.os2 has been around and does what we need for that platform.

**Comment by madebr** [comment]
The cost of supporting Watcom in the cmake script is low.
There were already some references to OS2 in the cmake script, but they were not used (until now).
Adding CMake support allows our users to keep using their cmake based build system when targeting these legacy operating systems.

**Comment by sezero** [comment]
>  There were already some references to OS2 in the cmake script, but they were not used (until now).

They were there for emx (gcc-based toolchain targeting os/2 but native-only, no cross-solutions at all.)

**Comment by slouken** [comment]
@sezero, you just removed the custom Watcom Makefiles, is this something you still want?

**Comment by sezero** [comment]
> @sezero, you just removed the custom Watcom Makefiles, is this something you still want?

No, we don't want this anymore

**Pull request closed without merging**
