### PR TITLE
wayland: Avoid busy waiting for vsync

### LINKED ISSUE #4609: wayland: High CPU usage with v-sync on
Tested on a Librem 5 running phoc.

With SDL 2.0.12, Neverball while in its graphics menu eats about 60-62% of CPU with v-sync off and about 20% with v-sync on.

With SDL 2.0.16, it's slightly better with v-sync off - 55-57%, but with v-sync on it goes up to 100%, constantly eating one whole CPU core - even when the screen is locked and turned off.

Reverting c54c16d353f206162cdbb125c0847b4645e096a3 brings it down to reasonable levels again.

### PR DESCRIPTION
**Pull request by cgutman**
## Description
Use `SDL_IOReady()` to sleep until we have events to dispatch rather than busy looping

## Existing Issue(s)
Fixes #4609

### CODE REVIEW

**Review by flibitijibibo — APPROVED** [review]
Makes sense to me. @icculus, if this looks good to you we can sneak this into .16.

**Comment by icculus** [comment]
Doesn't the dispatch function block indefinitely if there's no new event?

**Comment by cgutman** [comment]
`wl_display_dispatch()` does a blocking read on the display fd, but the `SDL_IOReady()` call has already ensured data will be there to read immediately. If there aren't events to read within the 10 frames timeout, we'll bail out of the loop and render.

**Comment by icculus** [comment]
> but the SDL_IOReady() call has already ensured data will be there

Yes, sorry, I missed the "_pending" on that first call; you're right.

**Pull request merged**
