### PR TITLE
Added HIDAPI backend for Amazon Luna Controller Model T28B69 connected via Bluetooth LE (VID:0171, PID:0419)

### PR DESCRIPTION
**Pull request by DJm00n**
To enter Bluetooth pairing mode hold B and Action (button with circle) buttons for 3 seconds.

It works via usual HIDAPI if special filter driver is not installed:
https://www.amazon.com/gp/help/customer/display.html?nodeId=GZCT4CTFHXLHEB9T

With driver installed it mimics Xbox One controller and works via XInput under Windows.

### CODE REVIEW

**Comment by slouken** [comment]
Can you check this commit with your controller?
https://github.com/libsdl-org/SDL/commit/863f56694115f801ec868ef2a4d9f295297335f7

**Comment by DJm00n** [comment]
@slouken I'll check it tomorrow.

**Comment by slouken** [comment]
Thanks!

**Comment by DJm00n** [comment]
@slouken I have checked my Luna controller on latest code - seems all fine.

You can remove that comment:
```cpp
        /* The mic button appears to be in byte 16 in firmware version 305164320 */
        /*SDL_PrivateJoystickButton(joystick, SDL_CONTROLLER_BUTTON_LUNA_MIC, (data[15] & 0x02) ? SDL_PRESSED : SDL_RELEASED);*/
```

**Comment by slouken** [comment]
Great, thanks!

**Pull request merged**
