### PR TITLE
Added the timerID to the SDL timer callback

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/2593

### CODE REVIEW

**Comment by sezero** [comment]
OK, the obvious question: how will you handle this in sdl2-compat?

**Comment by sezero** [comment]
Besides, timerid is something the users can handle by themselves, is it
not? E.g.:
```c
struct timerparam {
  void *myparam;
  SDL_TimerID id;
}
my_timercb (Uint32 interval, void *param) {
  void *myparam = ((struct timerparam *)param)->myparam;
  SDL_TimerID mytimerid = ((struct timerparam *)param)->id;
  /* do stuff */
}
```

**Comment by slouken** [comment]
> OK, the obvious question: how will you handle this in sdl2-compat?

https://github.com/libsdl-org/sdl2-compat/pull/166

**Comment by icculus** [comment]
> Besides, timerid is something the users can handle by themselves,

They can, but since the information is readily available to SDL when it calls this callback, we can save them the effort of managing memory to access this value.

**Comment by slouken** [comment]
It's also potentially possible for the callback to be called before SDL_AddTimer() returns the new timer ID.

**Pull request merged**
