### PR TITLE
WASAPI: Set sample rate via IAudioClockAdjustment

### PR DESCRIPTION
**Pull request by glebm**
Potential fix for #5538

### CODE REVIEW

**Comment by cgutman** [comment]
This might reintroduce the quality issues fixed by b98b5adcaea159fc6a9753f808875acf7d3ee945 and may cause resampling failures in other cases.

I've not tested with both `AUDCLNT_STREAMFLAGS_RATEADJUST` and `AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM` together, but I know from previous experience that using `AUDCLNT_STREAMFLAGS_RATEADJUST` alone will fail in the 48000 Hz -> 192000 Hz resampling case. In that case, `SetSampleRate()` fails with` E_INVALIDARG`.

Previous discussions for context:
https://github.com/libsdl-org/SDL/issues/4604
https://github.com/libsdl-org/SDL/issues/4608

Repro steps for `SetSampleRate()` issue with 192KHz mix format:
https://github.com/andrewrk/libsoundio/pull/194

Other comments mentioning limitations of `IAudioClockAdjustment` resampling:
https://bugzilla.mozilla.org/show_bug.cgi?id=894801#c21

**Comment by glebm** [comment]
@cgutman https://github.com/libsdl-org/SDL/commit/b98b5adcaea159fc6a9753f808875acf7d3ee945 has already been reverted in https://github.com/libsdl-org/SDL/commit/ac32c522ada13ba39b166f84cad13e0b74738388

The system resampler is what's used currently and it does have quality issues

This PR may or may not fix these quality issues -- we're currently testing it

**Comment by cgutman** [comment]
> @cgutman https://github.com/libsdl-org/SDL/commit/b98b5adcaea159fc6a9753f808875acf7d3ee945 has already been reverted in https://github.com/libsdl-org/SDL/commit/ac32c522ada13ba39b166f84cad13e0b74738388

I know. It was my suggestion to use AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM in #4604 :)

> The system (WASAPI) resampler is what's used currently and it does have quality issues

Does SDL's resampler work okay for this case?

**Comment by glebm** [comment]
We might have to revert to using SDL for resampling if this does not fix quality issues or if `SetSampleRate` has a limited range even with `AUDCLNT_STREAMFLAGS_AUTOCONVERTPCM`.

**Comment by glebm** [comment]
This does not fix the problem

Can we go back to SDL's resampling?

**Comment by cgutman** [comment]
@icculus do you think reverting ac32c522ada13ba39b166f84cad13e0b74738388 is safe enough for 2.0.22?

**Comment by icculus** [comment]
I don't mind changing back, but I'm extremely hesitant to do it right before 2.0.22 ships.

I'm okay with it if @slouken gives the greenlight, otherwise we can flip this as soon as 2.0.22 ships.

**Comment by slouken** [comment]
Yep, I flipped it back in https://github.com/libsdl-org/SDL/commit/9e264b921b2f81e2c3d55693f76e06d143c2fbb7

**Comment by glebm** [comment]
Thanks!

**Comment by slouken** [comment]
You're welcome!

**Pull request closed without merging**
