### PR TITLE
build: Compile with large inode number support where possible

### PR DESCRIPTION
**Pull request by smcv**
On filesystems with large inode numbers, such as overlayfs, attempting
to stat() a file on a 32-bit system using legacy syscalls can fail
with EOVERFLOW. If we opt-in to more modern "large file support"
syscalls, then source code references to functions like stat() are
transparently replaced with ABIs that support large file sizes and
inode numbers, such as stat64().

This cannot safely be done globally by Linux distributions, because
some libraries expose types like `off_t` or `struct stat` in their
ABI, meaning that enabling large file support would be an incompatible
change that would cause crashes. However, SDL appears to be careful to
avoid these types in header files, so it should be OK to enable this.

---

This is the sort of potentially breaking change that should happen early in a release cycle, so that it can be reverted if it turns out to have broken the ABI. It's probably a good idea to put SDL through something like https://github.com/lvc/abi-compliance-checker before and after this change.

### CODE REVIEW

**Comment by smcv** [comment]
See also https://github.com/libsdl-org/SDL_ttf/pull/222.

**Review by madebr — APPROVED** [review]

**Comment by sezero** [comment]
After this cmake-3.0 compatibility is broken. Error message from my cmake-3.9.6:
```
-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
CMake Error at CMakeLists.txt:62 (add_compile_definitions):
  Unknown CMake command "add_compile_definitions".


-- Configuring incomplete, errors occurred!
```

What mininum cmake version is required for that `add_compile_definitions` thing?
Or, an alternative to it, `add_definitions` maybe? 

CC: @madebr

**Comment by sezero** [comment]
Well, you guys should choose the solution :)

**Comment by madebr** [comment]
Fixed in d460000b4586ff1a10cf2f7cb4e922db3efb9400

**Pull request merged**
