### PR TITLE
SDL_CreateTexture() uses the SDL_TextureAccess type for the access parameter

### PR DESCRIPTION
**Pull request by slouken**

### CODE REVIEW

**Comment by sezero** [comment]
Is sdl2-compat solution plainly casting, i.e.: 

```diff
diff --git a/src/sdl2_compat.c b/src/sdl2_compat.c
index 26b0bc0..f71cc6b 100644
--- a/src/sdl2_compat.c
+++ b/src/sdl2_compat.c
@@ -5172,7 +5172,7 @@ static SDL_ScaleMode SDL_GetScaleMode(void)
 SDL_DECLSPEC SDL_Texture * SDLCALL
 SDL_CreateTexture(SDL_Renderer * renderer, Uint32 format, int access, int w, int h)
 {
-    SDL_Texture *texture = SDL3_CreateTexture(renderer, (SDL_PixelFormat)format, access, w, h);
+    SDL_Texture *texture = SDL3_CreateTexture(renderer, (SDL_PixelFormat)format, (SDL_TextureAccess)access, w, h);
     if (texture) {
         SDL3_SetTextureBlendMode(texture, SDL_BLENDMODE_NONE);
         SDL3_SetTextureScaleMode(texture, SDL_GetScaleMode());
diff --git a/src/sdl3_syms.h b/src/sdl3_syms.h
index ccb4f34..84f862d 100644
--- a/src/sdl3_syms.h
+++ b/src/sdl3_syms.h
@@ -296,7 +296,7 @@ SDL3_SYM(SDL_Renderer*,CreateSoftwareRenderer,(SDL_Surface *a),(a),return)
 SDL3_SYM_PASSTHROUGH(SDL_Renderer*,GetRenderer,(SDL_Window *a),(a),return)
 SDL3_SYM(const char*,GetRendererName,(SDL_Renderer *a),(a),return)
 SDL3_SYM_RENAMED(int,GetRendererOutputSize,GetRenderOutputSize,(SDL_Renderer *a, int *b, int *c),(a,b,c),return)
-SDL3_SYM(SDL_Texture*,CreateTexture,(SDL_Renderer *a, SDL_PixelFormat b, int c, int d, int e),(a,b,c,d,e),return)
+SDL3_SYM(SDL_Texture*,CreateTexture,(SDL_Renderer *a, SDL_PixelFormat b, SDL_TextureAccess c, int d, int e),(a,b,c,d,e),return)
 SDL3_SYM(SDL_Texture*,CreateTextureFromSurface,(SDL_Renderer *a, SDL_Surface *b),(a,b),return)
 SDL3_SYM_PASSTHROUGH(int,SetTextureColorMod,(SDL_Texture *a, Uint8 b, Uint8 c, Uint8 d),(a,b,c,d),return)
 SDL3_SYM_PASSTHROUGH(int,GetTextureColorMod,(SDL_Texture *a, Uint8 *b, Uint8 *c, Uint8 *d),(a,b,c,d),return)
```

**Comment by slouken** [comment]
> Is sdl2-compat solution plainly casting, i.e.:

Yep, that looks great.

**Comment by sezero** [comment]
> > Is sdl2-compat solution plainly casting, i.e.:
> 
> Yep, that looks great.

Applied

**Comment by slouken** [comment]
> Applied

Thanks!

**Pull request merged**
