### PR TITLE
Set var and add define for IME

### PR DESCRIPTION
**Pull request by weitjong**
Minor change to make it consistent with the rest.

### CODE REVIEW

**Comment by weitjong** [comment]
Actually it still does. Both FCITX and IBUS when detected by the CMake build system will then set this var.

I almost added another dep_option for "enable_ime" (taking cue from the `configure` script), but I didn't in the end. I realize that currently CMake build script does not do exactly the same thing as the other build script.

**Comment by cgutman** [comment]
Looks like this was fixed by #4969

**Comment by weitjong** [comment]
Well, not entirely. My fix for the FCITX is still lost. If you look carefully the implementation of the "configure" script, both FCITX and IBUS requires USE_IME.

**Comment by cgutman** [comment]
Both FCITX and IBUS do cause `SDL_USE_IME` to be set.

https://github.com/libsdl-org/SDL/blob/d2cf19193638756e48afc19f4ad1fcc753790b30/CMakeLists.txt#L1321-L1323

Am I missing something obvious?

**Comment by weitjong** [comment]
Ah, my bad. I only looked at your PR with the unified diff format and did not double check the final merged result, and somehow I overlooked there is still remaining "if()" block as you have just pointed out. In my version I opted to set the `SDL_USE_IME` in the respective check result and avoided this "if()". Although it would not make the CMake script to be any slower, I just feel the relevant variables should be set together. Otherwise, yes, you are right that my PR has been superseded by yours.

**Comment by sezero** [comment]
OK, re-closing.

**Pull request closed without merging**
