### PR TITLE
thread: Locking mutexes and rwlocks are now void functions.

### PR DESCRIPTION
**Pull request by icculus**
Almost nothing checks these return values, and there's no reason a valid lock should fail to operate. The cases where a lock isn't valid (it's a bogus pointer, it was previously destroyed, a thread is unlocking a lock it doesn't own, etc) are undefined behavior and always were, and should be treated as an application bug.

Reference Issue #8096.

(This is a draft PR until the builders all pass, but it's otherwise ready to merge, if we want to do this.)

### CODE REVIEW

**Comment by icculus** [comment]
Okay, this can merge now.

If we're putting this one in, we should probably do the same work to semaphores and condition variables.

**Comment by sezero** [comment]
sdl2-compat should always return success (0) ?

**Comment by sezero** [comment]
> sdl2-compat should always return success (0) ?

I mean, do we want the following?

```diff
diff --git a/src/sdl2_compat.c b/src/sdl2_compat.c
index 4e555f9..5bbe221 100644
--- a/src/sdl2_compat.c
+++ b/src/sdl2_compat.c
@@ -3439,6 +3439,21 @@ SDL_RenderGetIntegerScale(SDL_Renderer *renderer)
     return SDL_FALSE;
 }
 
+
+DECLSPEC int SDLCALL
+LockMutex(SDL_Mutex *a)
+{
+    SDL3_LockMutex(a);
+    return 0;
+}
+
+DECLSPEC int SDLCALL
+UnlockMutex(SDL_Mutex *a)
+{
+    SDL3_UnlockMutex(a);
+    return 0;
+}
+
 DECLSPEC int SDLCALL
 SDL_AudioInit(const char *driver_name)
 {
diff --git a/src/sdl3_syms.h b/src/sdl3_syms.h
index 473f448..36215ed 100644
--- a/src/sdl3_syms.h
+++ b/src/sdl3_syms.h
@@ -238,9 +238,9 @@ SDL3_SYM_PASSTHROUGH(SDL_Cursor*,GetCursor,(void),(),return)
 SDL3_SYM_PASSTHROUGH(SDL_Cursor*,GetDefaultCursor,(void),(),return)
 SDL3_SYM_RENAMED(void,FreeCursor,DestroyCursor,(SDL_Cursor *a),(a),)
 SDL3_SYM_PASSTHROUGH(SDL_Mutex*,CreateMutex,(void),(),return)
-SDL3_SYM_PASSTHROUGH(int,LockMutex,(SDL_Mutex *a),(a),return)
+SDL3_SYM(void,LockMutex,(SDL_Mutex *a),(a),)
 SDL3_SYM_PASSTHROUGH(int,TryLockMutex,(SDL_Mutex *a),(a),return)
-SDL3_SYM_PASSTHROUGH(int,UnlockMutex,(SDL_Mutex *a),(a),return)
+SDL3_SYM(void,UnlockMutex,(SDL_Mutex *a),(a),)
 SDL3_SYM_PASSTHROUGH(void,DestroyMutex,(SDL_Mutex *a),(a),)
 SDL3_SYM_PASSTHROUGH(SDL_Semaphore*,CreateSemaphore,(Uint32 a),(a),return)
 SDL3_SYM_PASSTHROUGH(void,DestroySemaphore,(SDL_Semaphore *a),(a),)
```

**Comment by icculus** [comment]
Yes, go ahead and commit that, please!

**Comment by sezero** [comment]
Done

**Pull request merged**
