### PR TITLE
Android life cycle behavior more closely matches iOS

### PR DESCRIPTION
**Pull request by slouken**
This change also decouples the pause/resume handling from the video subsystem on Android, so applications that don't use SDL for video can get application life cycle events.
    
The semantics for the life cycle events are that they need to be handled in an event watch callback, and once they've been delivered, the application will block until it's been resumed. SDL_HINT_ANDROID_BLOCK_ON_PAUSE can be used to control that behavior, and if that's set to "0", then the application will continue to run in the background at low CPU usage until being resumed or stopped.
    
SDL_HINT_ANDROID_BLOCK_ON_PAUSE_PAUSEAUDIO has been removed, and the audio will be paused when the application is paused.
    
Fixes https://github.com/libsdl-org/SDL/issues/3193

### CODE REVIEW

**Comment by slouken** [comment]
@AntTheAlchemist, can you please check this change once it goes in?

**Comment by 1bsyl** [comment]
I cant try/look carrefully right now but:
- before we could accumulate several activity pause request/resume (maybe still ok now).

- the thread that push an event is not always the same as the one that read the event. I think both android activity thread and main C sdl thread can queue a pause request. But only the sdl main thread read the events. If now the event callback are run/called in the android activity thread, this will break apps. I think that the issue with SDL_CallEventWatchers(): the callback are callled in the pushing thread.

( please separate commits with renaming from behavior commit so that s easier to follow )

**Comment by AntTheAlchemist** [comment]
> @AntTheAlchemist, can you please check this change once it goes in?

Looking at it now. In about 4 days I'll be able to see how it performs in the real world after uploading a beta to Play Store. 

I've updated AdMob  and Billing API versions (due to going from min SDK 16), which has introduced some new bugs from Google's side, annoyingly, so it'll be a bit tricky 🤞🏼. Interesting to note: Android 4.* only accounts for 0.001375% of my current users (110 out of 80,000). Similar again for Android 5.*. A future jump to SDK 23 would also be reasonable if needed.

**Comment by AntTheAlchemist** [comment]
Too early to ask. I've still not got a working build yet - lots of updates happening due to API hikes. I'll post here as soon as I have feedback.

**Comment by AntTheAlchemist** [comment]
I use an old Nexus 7 (Android 4.4) as a test unit. Sad to have to abandon it 😭. On the plus side, I'm getting better at letting go and moving on 😆

**Comment by slouken** [comment]
@AntTheAlchemist, okay, FYI, I have more refinements to this coming...

**Comment by sezero** [comment]
Pushed https://github.com/libsdl-org/sdl2-compat/commit/fd4984455dc0af4860d5964d19c03d2cd1332813 to sdl2-compat. If there are more changes needed in there, leaving them to you.

**Comment by slouken** [comment]
That should be fine. sdl2-compat doesn't work on Android, so we're not trying to provide any compatibility here for Android behavior.

**Comment by AntTheAlchemist** [comment]
@slouken App bombs: `No static method systemOverlays()` exception. Android Studio claims that `Call requires API level 34 (current min is 21): android.view.WindowInsets.Type#systemOverlay`. Even `.getInsets()` requires API 30.

**Comment by AntTheAlchemist** [comment]
So that I could test something, I deleted all the insets stuff & kept min API 21. Nothing else obvious broke. I did find a problem with a crash relating to deleting temp memory when getting locales though - I'll create an issue for that once I set up a basic repro.

**Comment by AntTheAlchemist** [comment]
Thanks for the fixes.

I noticed `SDL_SetWindowFullscreen()` is now delayed by about 1/3 or a second. Before, it seemed instant. This might impact on delayed start issues on Google Play.

**Comment by slouken** [comment]
Nothing I did should have changed startup time. Can you go back before my changes and isolate which commit broke that?

**Comment by 1bsyl** [comment]
@slouken 
IIRC. Usually there is an acknowledge:
Java onPause / onNativePaused is called.
It should signal pause semaphore
App should take into account and stop rendering.
Then OnPause can return. 

Same (easier for onResume).

Otherwise rendering is broken. Maybe it doesnt affect all device. You can test with a Sdl_delay() so that main c sdl is late to stop rendering.

If you quickly. Pause/ resume. OnPause() onResume() are called immediatly one after the other.

**Comment by AntTheAlchemist** [comment]
Not start up per se; it's just that SDL_SetWindowFullscreen will be used at start-up in some apps.

it's only happening on newer devices, and it's not affecting my old tablet (which I discovered is Lollypop, not KitKat - happy days!) which toggles full screen instantly, which makes me think it's the new inset stuff that's adding the delay. I'll dig around the code and find out.

**Pull request merged**
