### PR TITLE
Backed out the viewport and cliprect changes in 9fb5a9ccac0a6bb6af02e72644c1c56dc6ab6f3e

### PR DESCRIPTION
**Pull request by slouken**
This ended up being lots of application code churn without any real benefit in practice.

### CODE REVIEW

**Comment by sezero** [comment]
GetTextureSize stays the same running with float args?

**Comment by slouken** [comment]
> GetTextureSize stays the same running with float args?

Yep. That was an overall improvement.

**Comment by icculus** [comment]
Was it that bad?  😯

**Comment by slouken** [comment]
> Was it that bad? 😯

Yeah

**Pull request merged**
