### PR TITLE
directsound: For channel counts > 2, generate a dwChannelMask for CreateSoundBuffer

### LINKED ISSUE #5920: DirectSound and multichannel audio support...
In doing some work to try and prioritize DirectSound support, I ran into something that apparently someone else filed 2 years ago:

https://discourse.libsdl.org/t/sdl-openaudiodevice-and-sdl-openaudio-fails-when-setting-more-that-2-channels-in-specs/27412

... and in fact, while trying to find _that_ report for this ticket, I found another report from _2012_:

http://quakeone.com/forum/quake-help/quake-clients/9269-5-1-channel-audio-unable-to-initialize-darkplaces-sdl-exe

We don't get good error messages from DirectSound (as far as I know) and the parameters for CreateSoundBuffer are completely valid - I even tweaked the AudioSpec to try and replicate the exact buffer size with stereo output and that didn't break like I'd hoped.

It seems like we're looking at one of three things:

- DirectSound wants a WAVEFORMATEXTENSIBLE for multichannel, to grab the dwChannelMask value
- Secondary buffers don't support more than stereo. Maybe primary buffers do?
- When Vista said DirectSound and 3D didn't work anymore, they weren't just talking about DirectSound3D!

I'm filing this mostly to have it on the GitHub tracker, and to run it by @slouken and @icculus to see if either of them know what could be the real issue here. For the new IMMDevice work this isn't nuclear or anything, if it turns out I'm actually right on the latter two possibilities all we have to do is clamp the channels value to 2 or less (the format and freq values will still be useful untouched).

### PR DESCRIPTION
**Pull request by flibitijibibo**
Fixes #5920.

### CODE REVIEW

**Comment by flibitijibibo** [comment]
Looks like Watcom doesn't like `WAVEFORMATEXTENSIBLE` or the speaker mask values. Is that unsupported or am I just missing an obvious header somewhere...?

**Comment by madebr** [comment]
> Looks like Watcom doesn't like `WAVEFORMATEXTENSIBLE` or the speaker mask values. Is that unsupported or am I just missing an obvious header somewhere...?

They are available [here](https://github.com/open-watcom/open-watcom-v2/blob/047386398d3b538c8ba9792714e6143b1f44f0ca/ci/ow/h/nt/ksmedia.h#L470-L482) and [here](https://github.com/open-watcom/open-watcom-v2/blob/047386398d3b538c8ba9792714e6143b1f44f0ca/ci/ow/h/nt/ksmedia.h#L76-L95).
Aren't these available through including `mmreg.h`, as documented [here](https://docs.microsoft.com/en-us/windows/win32/api/mmreg/ns-mmreg-waveformatextensible)?

**Comment by flibitijibibo** [comment]
> > Looks like Watcom doesn't like `WAVEFORMATEXTENSIBLE` or the speaker mask values. Is that unsupported or am I just missing an obvious header somewhere...?
> 
> They are available [here](https://github.com/open-watcom/open-watcom-v2/blob/047386398d3b538c8ba9792714e6143b1f44f0ca/ci/ow/h/nt/mmreg.h#L2321-L2339) and [here](https://github.com/open-watcom/open-watcom-v2/blob/047386398d3b538c8ba9792714e6143b1f44f0ca/ci/ow/h/nt/mmreg.h#L2142-L2160). Aren't these available through including `mmreg.h`, as documented [here](https://docs.microsoft.com/en-us/windows/win32/api/mmreg/ns-mmreg-waveformatextensible)?

That's the weird part: It's all in mmreg and we include it for WAVEFORMATEX... so I'm not totally sure what's up. For now I have a separate commit to define them for platforms that have old mmreg.h versions.

**Review by sezero — COMMENTED** [review]
I suggest keeping the `WAVE_FORMAT_IEEE_FLOAT` ifdef as is for very old crappy SDKs. Other than that, OK by me.

**Pull request merged**
