### PR TITLE
Remove now duplicated section in emscripten docs

### PR DESCRIPTION
**Pull request by Daft-Freak**
## Description
Since the default is now cmake, we don't need an "or with cmake" section. Might push some more updates while I'm here...

### CODE REVIEW

**Comment by Daft-Freak** [comment]
The audio section needs some changes, but I'm not sure how to word it. We already automatically resume audio contexts on any input and SDL_OpenAudioDevice doesn't fail, you just don't get any sound until there's some input. (https://github.com/libsdl-org/SDL/blob/73994bf0db6a199f90058b5acf05c55b8cef3672/src/audio/emscripten/SDL_emscriptenaudio.c#L227)

**Comment by slouken** [comment]
@Daft-Freak, can you update this PR for merging?

**Comment by Daft-Freak** [comment]
Hmm, seems this PR is now redundant.

**Comment by slouken** [comment]
Okay, thanks!

**Pull request closed without merging**
