### PR TITLE
Update SDL_gamecontrollerdb.h

### PR DESCRIPTION
**Pull request by offalynne**
Updating PS4 Android map per https://github.com/gabomdq/SDL_GameControllerDB/issues/379.

Seems like the device mapping updated in this Linux kernel patch https://github.com/aosp-mirror/kernel_common/commit/9131f8cc2b4eaf7c08d402243429e0bfba9aa0d6 though for some reason the version field tweak intended for SDL's benefit is not reflecting in the GUID on Android. As of Android 5.4 this new mapping is correct.

### CODE REVIEW

**Comment by Cacodemon345** [comment]
This was already privately discussed with the SDL2 developers.

**Comment by offalynne** [comment]
@Cacodemon345 did you actually read the content of the issue

**Comment by Cacodemon345** [comment]
I actually overlooked it, sorry.

**Comment by offalynne** [comment]
@Cacodemon345 I don’t have any idea what your comment has to do with the content or subject of this PR but OK

**Comment by cgutman** [comment]
Unfortunately, it's not really possible to handle this properly using a static mapping. This change would break devices with earlier kernels that lack the patch.

To support both, SDL needs to do runtime detection using `InputDevice.hasKeys()` or similar. I did something along those lines here: https://github.com/moonlight-stream/moonlight-android/commit/b6315a715a6b04db9fff3cf864d481d6e4f8a0c9

**Comment by offalynne** [comment]
@cgutman That’s right, but as things stand the DB currently has a number of mappings that are incorrect on older kernel versions, and this one that’s wrong on those that are up to date. I agree a more thorough fix is needed but the time being it seems to me most sensible things work in the modern case as opposed to being broken in both cases.

**Comment by offalynne** [comment]
https://github.com/libsdl-org/SDL/pull/5091#issuecomment-1075424050

**Pull request closed without merging**
