### PR TITLE
Check build-time SDK in LoadMainMenuNibIfAvailable

### PR DESCRIPTION
**Pull request by jmroot**
Fixes building against OS X 10.7 SDK.

### CODE REVIEW

**Comment by slime73** [comment]
See #5956

**Comment by jmroot** [comment]
Oh, well that's unfortunate, since it builds and runs fine on 10.7 apart from this (autotools build, not Xcode of course).

**Comment by slime73** [comment]
The minimum supported runtime version is still 10.7 (as long as it's built using the 10.9 SDK or newer). Personally I don't think it's going to get any easier to support building while using the 10.7 and 10.8 SDKs in the future, and in the past any change to the Cocoa backend has often come with an extra (usually hidden until after the initial change) cost of needing to fix up support for building with older SDKs, so slightly raising the min SDK reduces that cost a bit at least.

**Comment by slouken** [comment]
Is this the only change needed to build against the 10.7 SDK?

**Pull request merged**
