### PR TITLE
Add 'return' comment to SDL_ClearClipboardData

### PR DESCRIPTION
**Pull request by 1bsyl**

### CODE REVIEW

**Comment by slouken** [comment]
Thanks!

**Comment by 1bsyl** [comment]
:) 
there's an option to `gendynapi.py --check-comment`

**Comment by slouken** [comment]
Can we enable that by default?

**Comment by 1bsyl** [comment]
yes done by default now, so I also removed the options 
https://github.com/libsdl-org/SDL/commit/6763369f5be63c0f1afcb591fc9df49fbe7c0911

**Pull request merged**
