### PR TITLE
Add BytePusher example

### PR DESCRIPTION
**Pull request by maia-s**
I wrote a BytePusher VM implementation and thought it could be a good example. See here for more information about BytePusher and example programs: https://esolangs.org/wiki/BytePusher

It's written in C99. I don't know if examples are required to be C89, but I can fix that if you're interested

edit: Looks like they are, and I forgot to update the Visual Studio projects. Anyway, let me know if you want this and I'll fix it

### CODE REVIEW

**Comment by slouken** [comment]
Sure, this looks fun. I don't know if it goes in the games category though, @icculus, thoughts?

**Comment by icculus** [comment]
> Maybe games should be renamed demos?

Yes. I'm going to merge this and then make that change.

**Comment by icculus** [comment]
(Okay, this thing is awesome.)

**Comment by madebr** [comment]
With my wip work of https://github.com/libsdl-org/SDL/issues/9882#issuecomment-2492767421, I got it working on emscripten.
[BytePusher at https://examples.libsdl.org](https://examples.libsdl.org/SDL3/demo/04-bytepusher/) is currently sad.

**Comment by icculus** [comment]
I have a local fix for the out of memory issue, if you've got drag and drop working.

**Comment by icculus** [comment]
OOM fixed in 61ba8010d3c3c372226b3ce6af28b458fe7dda16.

**Pull request merged**
