### PR TITLE
Adding support for mouse/keyboard hotplug

### PR DESCRIPTION
**Pull request by slouken**
This is the first step in implementing the fix for https://github.com/libsdl-org/SDL/issues/9309

@Kontrabant, could you add the Wayland support for detecting mice and keyboards?

### CODE REVIEW

**Comment by Kontrabant** [comment]
Yep, the add/remove handler is already there and wired up to handle keyboards and mice arbitrarily appearing/disappearing, so we just have to send the new events.

**Comment by Kontrabant** [comment]
Added the commit with Wayland support.  Note that Wayland only exposes one generic keyboard and mouse object per seat. It is theoretically possible for multiple seats to be exposed to one application, but I don't think that anything actually does that right now.

**Comment by slouken** [comment]
Okay, great! Can I suggest that you use SDL_GetNextObjectID() for each keyboard and mouse that’s added and then use those IDs when sending keyboard and mouse events? I’m going to do the same for the other platforms that have a mouse and keyboard, but no low level handle that makes sense to use.

**Comment by slouken** [comment]
Thanks!

**Comment by slouken** [comment]
@Kontrabant, it looks like Wayland provides a keyboard and mouse even when there are non physically connected to the system. Is that expected?

**Comment by Kontrabant** [comment]
It seems to depend on the desktop.  GNOME always seems to report a keyboard and mouse connected, even if I unplug them, but we've also had to fix some crashing bugs because others didn't expose them (or even a higher level seat object at all) when nothing was connected.

We're forwarding what's reported, which is all we can really do here.

**Comment by slouken** [comment]
Yep, makes sense. Thanks!

**Comment by slouken** [comment]
@icculus, I added a test program, testmanymouse.c

What's odd here is that there's the concept of a shared mouse with ID 0.
This shared mouse covers the case of Windows and X11 where there may be multiple mice, but we don't know which one the mouse event comes from when we're not in raw input mode. We can't use it to generate events for active attached mice because we may not have entered raw input mode to determine which mice are active.

This also covers the case of other operating systems where they register a mouse so SDL_HasMouse() returns true, but then use the mouse ID 0 whenever they send events. This we can fix if we can solve the situation above.

**Comment by slouken** [comment]
Okay, per our discussion, we now have a separation between the system mouse, and distinct hardware mice. Unique mouse IDs are only available in relative (raw) mode. The same will be true for keyboards, once we have keyboard raw mode.

**Comment by slouken** [comment]
@Kontrabant, is the Wayland device name available for SDL_AddMouse() and SDL_AddKeyboard()?

**Comment by Kontrabant** [comment]
All we have available is the name of the seat object they are under ("seat0").

**Comment by Kontrabant** [comment]
We could do something like "seat0:keyboard" and "seat0:mouse"?

**Comment by slouken** [comment]
I guess that might be useful for multi-seat setups? All the Windows keyboards are called “HID-compliant keyboard”, so I’m not sure how useful the name is going to be.

**Comment by Kontrabant** [comment]
I guess the question then is, would something short and to the point like "seat0:keyboard" or something more human readable like "Wayland Keyboard (seat0)" be preferable?

Using "HID-compliant" here would be a bit misleading, as the keyboard could be virtual.

**Comment by slouken** [comment]
Oh, I wasn't suggesting that we emulate Windows behavior, I was just pointing out that the name doesn't seem to be very helpful in the general case. xinput returns something reasonable on XWayland, maybe we should use that?

**Comment by Kontrabant** [comment]
Let's do that. It will maintain uniformity as well.

"Virtual core keyboard"
"Virtual core pointer"

We can append the seat designation later if/when there is actually a reason to support Wayland multi-seat.

**Comment by madebr** [comment]
Should `SDL_EVENT_MOUSE_ADDED` and `SDL_EVENT_MOUSE_REMOVED` work under Linux?

Using the minimal exampe below, the `SDL_MouseID`s of mouse motion events do not match that of the mouse added event.

with wayland, I get:
```
INFO: SDL_EVENT_MOUSE_ADDED Virtual core pointer (1)
INFO: SDL_EVENT_MOUSE_MOTION (null) (0)
```

with x11, I get:
```
INFO: SDL_EVENT_MOUSE_MOTION (null) (0)
```
(No `SDL_EVENT_MOUSE_ADDED` event)

<details>

<summary>Try SDL_EVENT_MOUSE_ADDED and SDL_EVENT_MOUSE_REMOVED</summary>

```c

#include "SDL3/SDL.h"
#include "SDL3/SDL_main.h"

int main(int argc, char *argv[]) {
    if (SDL_Init(SDL_INIT_VIDEO) < 0) {
        SDL_Log("SDL_Init failed (%s)", SDL_GetError());
        return 1;
    }

    SDL_Window *window;
    SDL_Renderer *renderer;
    if (SDL_CreateWindowAndRenderer(640, 480, 0, &window, &renderer) < 0) {
        SDL_Log("SDL_CreateWindowAndRenderer failed (%s)", SDL_GetError());
        return 1;
    }

    for (SDL_bool running = SDL_TRUE; running; ) {
        SDL_Event event;
        while (SDL_PollEvent(&event)) {
            if (event.type == SDL_EVENT_QUIT) {
                running = SDL_FALSE;
            } else if (event.type == SDL_EVENT_MOUSE_ADDED) {
                SDL_Log("SDL_EVENT_MOUSE_ADDED %s (%d)", SDL_GetMouseInstanceName(event.mdevice.which), event.mdevice.which);
            } else if (event.type == SDL_EVENT_MOUSE_REMOVED) {
                SDL_Log("SDL_EVENT_MOUSE_REMOVED %s (%d)", SDL_GetMouseInstanceName(event.mdevice.which), event.mdevice.which);
            } else if (event.type == SDL_EVENT_MOUSE_MOTION) {
                SDL_Log("SDL_EVENT_MOUSE_MOTION %s (%d)", SDL_GetMouseInstanceName(event.motion.which), event.motion.which);
            }
        }
        SDL_SetRenderDrawColor(renderer, 255, 255, 255, SDL_ALPHA_OPAQUE);
        SDL_RenderClear(renderer);
        SDL_RenderPresent(renderer);
    }

    SDL_DestroyRenderer(renderer);
    SDL_DestroyWindow(window);

    SDL_Quit();
    return 0;
}
```


</details>

**Comment by madebr** [comment]
Windows 10 has the same behavior as x11:
```
INFO: SDL_EVENT_MOUSE_MOTION (null) (0)
```

I'm not sure what is the expected behavior.

**Comment by slouken** [comment]
Mouse device IDs are only sent in relative mouse mode.

**Pull request merged**
