### PR TITLE
Removed non-float versions of SDL render API drawing functions

### PR DESCRIPTION
**Pull request by slouken**
This simplifies the API and removes a level of API translation between the int variants of the functions and the float implementation

Fixes https://github.com/libsdl-org/SDL/issues/6656

### CODE REVIEW

**Comment by slouken** [comment]
@AntTheAlchemist, @libsdl-org/a-team, this is by far the most application-invasive change to the API so far. Do you think this is a good change?

**Comment by AntTheAlchemist** [comment]
@slouken I hear you. Can I have a few days to play around with it?

If it doesn't remove functionality and only forces the game-side code to use SDL-side types, is the only problem that we're clinging on to SDL2 compatibility? 3D stuff uses floats. Pixel alignment is a special case, I vote that SDL doesn't take the burden of pixel alignment, so there's no place to provide int coordinate functions that call the float functions anyway. I could be very wrong though, I would like to hear what others think.

**Comment by slouken** [comment]
Yep, I feel like this patch is complete and can be merged, but I’ll leave it here for a few days for people to play with and provide feedback.

**Comment by slouken** [comment]
@libsdl-org/a-team, any other feedback, or is this ready to go in?

**Comment by icculus** [comment]
Thinking on this, it's not hard for an app to wrap their int-using code in a handful of helper functions if they don't want to fix this up everywhere.

I mean, if our int versions are just one-liners that cast int to float, they can write a one-liner `RenderDrawRectInt` wrapper function and search/replace for it, or #define around it. It wouldn't be a murderously difficult migration.

**Comment by 1bsyl** [comment]
or they can  use sdl2-compat :)

- haven't really look the test/ could have less (float) casting every, eg: to be more float friendly ...

**Comment by slouken** [comment]
Okay cool. I'll merge this then.

Thanks!

**Pull request merged**
