### PR TITLE
Rename SDL_GetDisplayDPI to SDL_GetDisplayPhysicalDPI

### PR DESCRIPTION
**Pull request by 1bsyl**
to avoid confusion ...

### CODE REVIEW

**Comment by 1bsyl** [comment]
see #7134

**Comment by slouken** [comment]
I'm in favor of this change, but can we simplify it? @libsdl-org/a-team, is there any case where the diagonal DPI value of a display is going to be different from the horizontal and vertical?

**Comment by 1bsyl** [comment]
indeed, diagonal dpi seems more like  a helper for `dpi * sqrt(2)`.
to be removed ?

**Comment by slouken** [comment]
Let's pull this out as a separate issue for discussion.

**Comment by 1bsyl** [comment]
https://github.com/libsdl-org/SDL/issues/7147

**Comment by ericwa** [comment]
Currently `WIN_GetDisplayPhysicalDPI` returns the user's DPI scale factor relative to 96, not physical, so it's inconsistent with the new function name.

Using `GetDpiForMonitor(displaydata->MonitorHandle, MDT_RAW_DPI` we should be able to get physical DPI. But we'll still need a function to get DPI scale (the SDL Windows backend depends on it in a few places for one thing.), so we'll probably want to split `WIN_GetDisplayPhysicalDPI` into DPI scale and physical.

**Comment by slime73** [comment]
> we'll probably want to split WIN_GetDisplayPhysicalDPI into DPI scale and physical.

With the upcoming changes to display modes and possible conversion functions, could the active display mode's dpi scale be queried instead? Or would a separate function like you're talking about make more logical sense

**Comment by 1bsyl** [comment]
@ericwa so for SDL_GetDisplayPhysicalDPI this sounds a bug now. 
WIN_GetDisplayPhysicalDPI should provide the physical dpi instead.
I have no windows SDL3 setup, so would be nice if you could make a pr with the changes I guess. 

(And the current DPI should be kept for the high dpi interface)

**Comment by slouken** [comment]
I can make this change. I think we also only need a single DPI value, so I'll make that change as well.

I'm seriously considering removing the API though, since it's not reliable in so many circumstances.

**Pull request merged**
