### PR TITLE
loongarch: Fix bugs when compiling the program

### PR DESCRIPTION
**Pull request by HecaiYuan**
Added SIMD compilation options "-mlsx" and "-mlasx"

### CODE REVIEW

**Comment by HecaiYuan** [comment]
Welcome to review. @madebr

**Comment by madebr** [comment]
Would you mind adding a test to `test/testautomation_intrinsics.c` for lsx/lasx?

https://github.com/libsdl-org/SDL/blob/9667aa18e6c29885d8cd45efc2cf8bcb97270d7d/test/testautomation_intrinsics.c#L13

With your changes, I see the following in the output of CMake configure:
```
-- Performing Test COMPILER_SUPPORTS_LSX
-- Performing Test COMPILER_SUPPORTS_LSX - Failed
-- Looking for lsxintrin.h
-- Looking for lsxintrin.h - not found
-- Performing Test COMPILER_SUPPORTS_LASX
-- Performing Test COMPILER_SUPPORTS_LASX - Failed
-- Looking for lasxintrin.h
-- Looking for lasxintrin.h - not found
```

**Comment by HecaiYuan** [comment]
No problem. I'll do it as soon as possible.

**Comment by HecaiYuan** [comment]
I'm sorry I didn't reply until now. The LoongArch64 gcc+glibc toolchain in loongarch64.yml does not contain 'lsxintrin.h' and 'lasxintrin.h', and needs to wait for the latest version. I will update the link as soon as the new version is released.  "-mlsx" and "-mlasx" are required for SIMD compilation. @madebr

**Pull request closed without merging**
