### PR TITLE
Addition to  #5114

### PR DESCRIPTION
**Pull request by Wohlstand**
Small simplification made by @sezero 

Addition to #5114

### CODE REVIEW

**Comment by sezero** [comment]
Thanks

**Comment by sezero** [comment]
Well, I think we can actually replace the whole thing to the following: OK to apply?
```diff
diff --git a/cmake/sdlchecks.cmake b/cmake/sdlchecks.cmake
index b472a59..722c2a3 100644
--- a/cmake/sdlchecks.cmake
+++ b/cmake/sdlchecks.cmake
@@ -646,16 +646,8 @@ macro(CheckWayland)
       endif()
       string(REPLACE "wayland-scanner " "" WAYLAND_SCANNER_VERSION ${WAYLAND_SCANNER_VERSION})
 
-      if(CMAKE_VERSION VERSION_LESS 3.7.0)
-        string(COMPARE LESS ${WAYLAND_SCANNER_VERSION} "1.15.0" WAYLAND_SCANNER_1_15_NOTFOUND)
-        if(NOT WAYLAND_SCANNER_1_15_NOTFOUND)
-          set(WAYLAND_SCANNER_1_15_FOUND TRUE)
-        endif()
-      else()
-        string(COMPARE GREATER_EQUAL ${WAYLAND_SCANNER_VERSION} "1.15.0" WAYLAND_SCANNER_1_15_FOUND)
-      endif()
-
-      if(WAYLAND_SCANNER_1_15_FOUND)
+      string(COMPARE LESS ${WAYLAND_SCANNER_VERSION} "1.15.0" WAYLAND_SCANNER_1_15_NOTFOUND)
+      if(NOT WAYLAND_SCANNER_1_15_NOTFOUND)
         set(WAYLAND_SCANNER_CODE_MODE "private-code")
       else()
         set(WAYLAND_SCANNER_CODE_MODE "code")
```

**Comment by Wohlstand** [comment]
@sezero, yea, reasonable, should work

**Comment by Wohlstand** [comment]
Or, maybe something more human-friendly? (I mean in the logic term)
```cmake
string(COMPARE LESS ${WAYLAND_SCANNER_VERSION} "1.15.0" WAYLAND_SCANNER_PRE_1_15_FOUND)
if(WAYLAND_SCANNER_PRE_1_15_FOUND)
    set(WAYLAND_SCANNER_CODE_MODE "code")
else()
    set(WAYLAND_SCANNER_CODE_MODE "private-code")
endif()
```
I mean, swap "code" and "private-code" blocks

**Comment by sezero** [comment]
OK pushed https://github.com/libsdl-org/SDL/commit/398c0fdff0946ddb87853a474be286d3c01b89ca, is it OK, and with all cmake versions?

**Comment by Wohlstand** [comment]
Tested, works just fine :fox_face: :+1:

**Pull request merged**
