### PR TITLE
Fix Button Mapping for PS5 Dualsense Controller

### PR DESCRIPTION
**Pull request by TheBagarius**
Fixed mapping for PS5 DualSense Controller. Added a GUID for Bluetooth connection for PS5 DualSense Controller

## Description
The existing button mappings for the DualSense Controller had mixed up the A.B,X,Y,LT,RT, RightX,RightY, and a few more mappings. I generated new mappings with AntiMicroX.

The GUID for my controller when connected over bluetooth wasn't present in the file so I added that 

## Existing Issue(s)
https://github.com/libsdl-org/SDL/issues/4616

### CODE REVIEW

**Comment by slouken** [comment]
We definitely shouldn't replace existing mappings, as they were generated from a PS5 controller on an older Linux kernel and we don't want to introduce regressions. We somehow need to encode the fact that these are using the new Sony PS driver in the guid. Suggestions for how to detect this?

**Comment by TheBagarius** [comment]
That is a fair point, however I am already in way over my head with this. When I have some time, I'll learn how this library works and maybe come up with a solution.

**Comment by TheBagarius** [comment]
Hi,

Here is a table comparing the physical button pressed with what `evdev` would report and what `SDL2` maps to according to the mappings I generated. If all other controller combinations on linux produce the same/similar output, maybe somekind of generic mapping could be used instead?

|            evtest           | PlayStation 5 DualSense |       SDL2       |
|:---------------------------:|:-----------------------:|:----------------:|
|         Event Type 0        |                         |                  |
|:---------------------------:|:-----------------------:|:----------------:|
|         Event Type 1        |                         |                  |
|  Event Code 304 (BTN_SOUTH) |            X            |         A        |
|  Event Code 305 (BTN_EAST)  |          CIRCLE         |         B        |
|  Event code 307 (BTN_NORTH) |         TRIANGLE        |         Y        |
|  Event code 308 (BTN_WEST)  |          SQUARE         |         X        |
|   Event code 310 (BTN_TL)   |            L1           |   LEFTSHOULDER   |
|   Event code 311 (BTN_TR)   |            R1           |   RIGHTSHOULDER  |
|   Event code 312 (BTN_TL2)  |            L2           |                  |
|   Event code 313 (BTN_TR2)  |            R2           |                  |
| Event code 314 (BTN_SELECT) |          Create         |       BACK      |
|  Event code 315 (BTN_START) |           Menu          |       START      |
|  Event code 316 (BTN_MODE)  |            PS           |       GUIDE      |
| Event code 317 (BTN_THUMBL) |            L3           |     LEFTSTICK    |
| Event code 318 (BTN_THUMBR) |            R3           |    RIGHTSTICK    |
|:---------------------------:|:-----------------------:|:----------------:|
|    Event type 3 (EV_ABS)    |                         |                  |
|     Event code 0 (ABS_X)    |   Left Analog Stick X   |       LEFTX      |
|     Event code 1 (ABS_Y)    |   Left Analog Stick Y   |       LEFTY      |
|     Event code 2 (ABS_Z)    |            L2           |    LEFTTRIGGER   |
|    Event code 3 (ABS_RX)    |   Right Analog Stick X  |      RIGHTX      |
|    Event code 4 (ABS_RY)    |   Right Analog Stick Y  |      RIGHTY      |
|    Event code 5 (ABS_RZ)    |            R2           |   RIGHTTRIGGER   |
|  Event code 16 (ABS_HAT0X)  |        DPAD L & R       | DPLEFT & DPRIGHT |
|  Event code 17 (ABS_HAT0Y)  |      DPAD UP & DOWN     |   DPUP & DPDOWN  |
|:---------------------------:|:-----------------------:|:----------------:|
|    Event type 21 (EV_FF)    |                         |                  |
|  Event code 80 (FF_RUMBLE)  |                         |                  |
| Event code 81 (FF_PERIODIC) |                         |                  |
|  Event code 88 (FF_SQUARE)  |                         |                  |
| Event code 89 (FF_TRIANGLE) |                         |                  |
|   Event code 90 (FF_SINE)   |                         |                  |
|   Event code 96 (FF_GAIN)   |                         |                  |
|:---------------------------:|:-----------------------:|:----------------:|

**Comment by InfoTeddy** [comment]
Did you mean to close this...? I see not much indication why this was closed.

**Comment by TheBagarius** [comment]
Not particularly, I was messing about on my fork but kept pushing commits onto here so while I was trying to "unlink" them I accidentally deleted my fork.

I was going to submit a new pull request with more of my notes attached but then life just got in the way of things.

**Pull request closed without merging**
