### PR TITLE
VisualC: Update project to V142 for can compile.

### PR DESCRIPTION
**Pull request by Zangetsu38**
# About:
I have just thinks update this file for can allow compile on Visual Studio 2019 without edit file/without broken git project, for more cleaner stuff, also without request using cmake for create visual project.

### CODE REVIEW

**Comment by sezero** [comment]
This will prevent people who want to use older toolsets, am I wrong?

**Comment by Zangetsu38** [comment]
> This will prevent people who want to use older toolsets, am I wrong?

no understund, but for me, i have just set it for can compile without using cmake, with project file already exist, that all ^^

**Comment by sezero** [comment]
The files you touch have nothing to do with cmake. Also, the VS project files
are for vs2010, but te VS you have will automatically upgrade them to a new
version when you run.

I don't see the need for this patch.

**Comment by Zangetsu38** [comment]
> 
> 
> The files you touch have nothing to do with cmake. Also, the VS project files
> are for vs2010, but te VS you have will automatically upgrade them to a new
> version when you run.
> 
> I don't see the need for this patch.

i see very need, just update on real project version, for no compiler ask on why i what version i want update and draft file project, is just logical..., here is ,dirty works, i set it in cleaner.
And i have no said relate cmake..., i have explain with this no request using cmake for create project because is already exist, totaly diferent.

**Comment by sezero** [comment]
Maintainers @slouken and/or @icculus will decide as they see fit

**Comment by Zangetsu38** [comment]
> 
> 
> Maintainers @slouken and/or @icculus will decide as they see fit

Oki

**Comment by slouken** [comment]
We intentionally leave the projects set to the oldest supported compiler.
People with newer compilers can do a one-time project upgrade, but if the project is already upgraded people with older compilers can't use it at all.
Your change is typical for people using the library, but it's not something we'd want to ship to everyone.

Thanks!

**Comment by Zangetsu38** [comment]
is totaly no sense, update project on your compiler broken git... also this gitignore is outdate... all is wrong here, my PR fix this with get proper works and no draft project

**Comment by slouken** [comment]
The gitignore is updated now, thanks!

**Comment by Zangetsu38** [comment]
> 
> 
> The gitignore is updated now, thanks!

oki thx, i need search other ways for my fix hmm for can works for all version without request edit file

**Comment by slouken** [comment]
@ccawley2011 found a way to do this, and this has been merged in https://github.com/libsdl-org/SDL/commit/b0daa9f1db90ac568383a9a1741a9e2629fd1004

**Comment by Zangetsu38** [comment]
oh, good :D i have thinks one things simalary but more hard, good works @ccawley2011

**Pull request closed without merging**
