### PR TITLE
GPU: 32-bit component texture formats

### LINKED ISSUE #10968: GPU: Add R32_INT / R32_UINT formats
These are nice to have because they support atomic operations.

### PR DESCRIPTION
**Pull request by thatcosmonaut**
Resolves #10968 

We have some FIXMEs for documentation but I wanted to get this in before lock.

### CODE REVIEW

**Review by flibitijibibo — APPROVED** [review]

**Comment by sezero** [comment]
d3d11.h in my toolchain (mingw-w64 v8.0.3 headers & crt) does not have `D3D11_FORMAT_SUPPORT2` enum, therefore it doesn't know `D3D11_FORMAT_SUPPORT2_UAV_TYPED_LOAD`. Since it is not a macro, I don't know a way of detecting its presence, but it means it can be made into a macro too, like below: Is that OK to apply?

```diff
diff --git a/src/gpu/d3d11/SDL_gpu_d3d11.c b/src/gpu/d3d11/SDL_gpu_d3d11.c
index 8776214..90402ed 100644
--- a/src/gpu/d3d11/SDL_gpu_d3d11.c
+++ b/src/gpu/d3d11/SDL_gpu_d3d11.c
@@ -5836,6 +5836,7 @@ static bool D3D11_SupportsTextureFormat(
         // TYPED_UNORDERED_ACCESS_VIEW implies support for typed UAV stores
         return false;
     }
+    #define D3D11_FORMAT_SUPPORT2_UAV_TYPED_LOAD 0x40 /* for old toolchains */
     if ((usage & (SDL_GPU_TEXTUREUSAGE_COMPUTE_STORAGE_SIMULTANEOUS_READ_WRITE) && !(formatSupport2.OutFormatSupport2 & D3D11_FORMAT_SUPPORT2_UAV_TYPED_LOAD))) {
         return false;
     }
```

**Comment by flibitijibibo** [comment]
That should be fine, yeah - basically the same idea as our defines for SDL_d3d12.h.

**Comment by thatcosmonaut** [comment]
Yeah, looks fine. We'll probably revise this support check anyway once we get to implementing legacy mode.

**Comment by sezero** [comment]
OK, applied. Thanks.

**Pull request merged**
