### PR TITLE
Install tests, and run a subset non-interactively

### PR DESCRIPTION
**Pull request by smcv**
In the Debian package for SDL, for a while I've been installing the manual test executables from `test/`, so that they can be used to smoke-test the library without having to compile them separately. However, they're a little annoying to run because they require the current working directory to be the directory in which they are installed, so I've added code to load from the `SDL_GetBasePath()` if possible. This branch also adds a Makefile target to install the tests, and optionally runs the subset that are non-interactive during the build (I've tried to wire this up to the Github Workflows, let's see whether it works).

There's no universal convention for how/where to install or discover manual and automated tests, but GNOME [has a convention](https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests) that seems as good as any: installing tests into `${libexecdir}/installed-tests/${project}`, and discovering automated tests via `.desktop`-style files in `${datadir}/installed-tests/${project}`. Some non-GNOME projects like libdbus already borrow GNOME's convention instead of inventing their own wheel, and I've done the same here.

~~`test/` doesn't currently compile successfully with CMake (it requires `libSDL-static.a`, which my OS-wide installation doesn't provide) so I've only done this for Autotools for now.~~ [edited: I got this mostly working.]

---

* cmake: Add some missing test-cases
    
    These were built by Autotools but not by CMake.

* test: Make testevdev succeed if the feature is disabled
    
    "Not applicable" is more like success than it is like failure.

* test: Run selected noninteractive tests at build-time
    
    In Autotools, these are run by `make -C ${builddir}/test check`.
    In CMake, they're run by `make -C ${builddir} test` or
    `ninja -C ${builddir} test` or `ctest --test-dir ${builddir}`.

* test: Add a mode to skip tests that involve arbitrary delays
    
    This can be used as a quick acceptance test for CI workflows.

* workflows: Run build-time tests

* workflows: Parallelize Linux Autotools and CMake builds

* test: Add some common code to load test resources
    
    As well as reducing duplication, this lets the tests load their resources
    from the SDL_GetBasePath() on platforms that support it, which is useful
    if the tests are compiled along with the rest of SDL and installed below
    /usr as manual tests, similar to GNOME's installed-tests convention.
    
    Thanks to Ozkan Sezer for the OS/2 build glue.
    
    Co-authored-by: @sezero 

* test: Add a `make install` target for the tests
    
    This makes it more convenient to compile them alongside SDL, install
    them in an optional package and use them as smoke-tests or diagnostic
    tools. The default installation directory is taken from GNOME's
    installed-tests, which seems as good a convention as any other:
    https://wiki.gnome.org/Initiatives/GnomeGoals/InstalledTests

* test: Install GNOME-style installed-tests metadata
    
    This allows these tests to be discovered and run by
    gnome-desktop-test-runner.

* workflows: Install and run GNOME-style installed-tests
    
    This is currently only done for the Linux Autotools build. The CMake
    build does not add a significant amount of extra test coverage, and
    Github Workflows run in an environment where `cmake` and `sudo cmake`
    point to different executables, which makes it awkward to install into
    /usr/local from CMake.

### CODE REVIEW

**Comment by smcv** [comment]
> Need the following to fix building tests for os/2

Thanks, added. I've also tried to fix the MSVC build, but I don't have Windows, so that's going to take some trial and error.

**Comment by smcv** [comment]
I've dropped the last commit to avoid conflict with #5526.

**Comment by sezero** [comment]
> I've dropped the last commit to avoid conflict with #5526.

Thanks.

**Comment by smcv** [comment]
@slouken, any opinion on this?

I'd like to get both CMake and Autotools builds happening in CI before #5602, even if the rest of this can't go in, so that we can check that the library versioning for the CMake build and the Autotools build match up correctly.

**Comment by smcv** [comment]
Marking as draft: I want to rebase this onto a branch that exercises the Autotools build *at all*, and fix the CMake side now that I have a working CMake build.

**Comment by slouken** [comment]
Sure, I'll merge this once you think it's ready.

**Comment by smcv** [comment]
> Sure, I'll merge this once you think it's ready.

I'm still getting this working, but for now perhaps you could look at #5606?

**Comment by slouken** [comment]
> I don't know whether you'll want to run the installed-tests from the Github workflows or not: some of them are relatively slow, so doing that makes the Linux test run go slightly slower than any of the Windows ones (10 minutes total).

I'd like to keep the workflow fast. Can we schedule them to run once a day or once a week or so?

**Comment by smcv** [comment]
> I'd like to keep the workflow fast. Can we schedule them to run once a day or once a week or so?

Not trivially, but I think yes. I'd have to add a separate workflow .yml file that is only run for scheduled jobs, not for PRs.

Ideally I'd like to keep the fast tests like `testevdev` running as part of the pre-acceptance checks for PRs, and only skip the slower ones like `testhread` (either that, or tell them to run faster/less thoroughly). Would that be OK?

Another option would be to do what Flatpak does: kick out slower CI steps into a separate workflow job (for Flatpak that's the `valgrind` test run, which takes literally hours to finish), and be willing to merge PRs even though that slow job hasn't finished.

**Comment by slouken** [comment]
> I'd like to keep the fast tests like `testevdev` running as part of the pre-acceptance checks for PRs, and only skip the slower ones like `testhread` (either that, or tell them to run faster/less thoroughly). Would that be OK?

Yep, that would be fine.

**Comment by smcv** [comment]
Several tests now look at `$SDL_TESTS_QUICK`, and don't do time-consuming stuff with threads or arbitrary delays if that's set. This brings the Linux/CMake and Linux/Autotools builds down to 1 minute and 2 minutes, respectively, which seems sufficiently close to instant gratification. (I'm also now running them in parallel.)

**Pull request merged**
