### PR TITLE
[SDL2] backport SDL_BLENDMODE_MUL change

### PR DESCRIPTION
**Pull request by 1bsyl**
manually back-port:  https://github.com/libsdl-org/SDL/pull/7475/

### CODE REVIEW

**Comment by 1bsyl** [comment]
I wonder if there isn't a bug in current blendmode MUL. 
if src has no Alpha, and dest has Alpha. I think it sets destA to 0xff.

https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_blit_auto.c#L2115  ?

**Comment by 1bsyl** [comment]
dstA is already set before https://github.com/libsdl-org/SDL/blob/main/src/video/SDL_blit_auto.c#L2087

**Comment by slouken** [comment]
Yeah, that seems like a bug.

**Comment by 1bsyl** [comment]
merging also because of this alpha bug

**Pull request merged**
