### PR TITLE
Fix VULKAN_UpdateViewport judgment.

### PR DESCRIPTION
**Pull request by huahua369**

### CODE REVIEW

**Comment by sezero** [comment]
This looks correct to me. @slouken?

**Comment by huahua369** [comment]
VULKAN_UpdateViewport function returns true.
`if( !VULKAN_UpdateViewport(renderer))`
updateConstants cannot be updated

**Comment by huahua369** [comment]
Please test the code. When I render multiple viewport, the latter ones are not updated. @sezero 
```SDL_Rect rect0 = { 10,10,200,200 };
SDL_Rect rect1 = { 300,300,300,300 };
SDL_SetRenderViewport(renderer, &rect0);
SDL_RenderGeometry(...);
SDL_SetRenderViewport(renderer, &rect1);
SDL_RenderGeometry(...);
```

`if (VULKAN_UpdateViewport(renderer))` is ok
image

`if (!VULKAN_UpdateViewport(renderer))` is error
image

**Comment by sezero** [comment]
You don't have to try convincing me, I'm already OK with your patch :)
I just wanted a review from a maintainer.

I wonder though, and I might be 500% off-base here but, can this have
any effect on #10318??

**Comment by slouken** [comment]
Yup, this is correct, thanks!

**Pull request merged**
