### PR TITLE
Losing keyboard focus doesn't automatically mean you lose mouse capture

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/5616

### CODE REVIEW

**Comment by slouken** [comment]
@Kontrabant, does this look right to you?

The test program in https://github.com/libsdl-org/SDL/issues/5616 doesn't work on Wayland, but it didn't before this change either...?

**Comment by Kontrabant** [comment]
The changes look ok.

The example code as-is won't work with Wayland, as it simply doesn't allow programmatic toplevel window positioning. You would need to set a hotspot on the new window to allow it to be moved.

**Comment by slouken** [comment]
> The example code as-is won't work with Wayland, as it simply doesn't allow programmatic toplevel window positioning. You would need to set a hotspot on the new window to allow it to be moved.

So on Wayland, it would be two steps, one to create the window, and then click again to drag it around? How do you normally implement tear-off UI in Wayland?

**Comment by slouken** [comment]
Chromium works, is that an XWayland trick?

**Comment by Kontrabant** [comment]
I believe that browsers handle things like tab tear-off by simply checking if the cursor is somewhere other than the tab bar when dragging a tab and opening a new window when the button is released. The problem in this case isn't tearing-off a window, it's putting the new window where you want it, and dragging a torn-off window back into another.

There is a protocol for dragging a window with a data offer, which Qt and Chrome implement for handling docking panels and turning a separate window back into a tab, but the application would have to be explicitly aware of this and handle window creation, destruction, and rendering in a way to make it appear seamless. It's also not implemented in any desktop other than KDE at this point, so it's of limited use right now.

There is a protocol being worked on for positioning windows relative to others in a zone for multi-window interfaces, which seems like it will be a better fit for SDL once it is finalized.

**Pull request merged**
