### PR TITLE
android: Added SDL_AndroidRequestPermissionAsync.

### PR DESCRIPTION
**Pull request by icculus**
The existing API is blocking, and may block indefinitely (until the user responds to a system dialog).

This runs the permission request asynchronously, and fires a callback when the response is available. The lower-level Android API is already async here, so this just improves SDL's interface to that API.

### CODE REVIEW

**Comment by icculus** [comment]
Once the build check completes, the other question here is: do we want to dump the blocking version of this from the API?

**Comment by slouken** [comment]
Sure... UI shouldn't be blocked while requesting permissions.

**Comment by madebr** [comment]
Can you also remove `SDL_AndroidRequestPermission` from `src/core/SDL_core_unsupported.c` and add a dummy `SDL_AndroidRequestPermissionAsync` implementation there?

**Comment by icculus** [comment]
> Can you also remove SDL_AndroidRequestPermission from src/core/SDL_core_unsupported.c and add a dummy SDL_AndroidRequestPermissionAsync implementation there?

Already did the new dummy version in one of the force-pushes, I'll remove the blocking function now.

**Comment by icculus** [comment]
Ok, this is async-only now, but the internal uses of the API still block. I'm going to fix up the audio ones after this merges, and the camera one is already fixed locally in my branch. I intend to leave the hidapi/android/hid.cpp one alone, but if @slouken wants to make that piece async, go for it, but right now we're no different than we were on that piece.

I've got an sdl2-compat patch ready once this merges, too.

**Comment by slouken** [comment]
The one in hid.cpp does need to stay synchronous.

**Pull request merged**
