### PR TITLE
Updated more functions to use SDL_GetStringRule 

### PR DESCRIPTION
**Pull request by slouken**
Fixes https://github.com/libsdl-org/SDL/issues/10300

- [x] SDL_GetAudioPlaybackDevices()
- [x] SDL_GetAudioRecordingDevices()
- [x] SDL_GetCameraSupportedFormats()
- [x] SDL_GetCameras()
- [x] SDL_GetDisplays()
- [x] SDL_GetFullscreenDisplayModes()
- [x] SDL_GetGamepads()
- [x] SDL_GetHaptics()
- [x] SDL_GetJoysticks()
- [x] SDL_GetKeyboards()
- [x] SDL_GetMice()
- [x] SDL_GetPreferredLocales()
- [x] SDL_GetSensors()
- [x] SDL_GetTouchDevices()
- [x] SDL_GetWindowICCProfile()
- [x] SDL_GetWindows()

### CODE REVIEW

**Comment by slouken** [comment]
Right now I'm just doing the simple thing, but we can go back and make this smarter about when we allocate and free the returned data.

**Comment by slouken** [comment]
@icculus, I made it possible to free specific pointers with SDL_FreeEventMemory(), which some applications will want to do for more fine grained memory management.

**Comment by slouken** [comment]
@sezero, I will have an sdl2-compat update ready soon.

**Review by icculus — APPROVED** [review]
This is good. I think what prompted my "are we being too clever?" comment before was the actual presence of a "rule" ...because this is exactly the sort of thing that made, say, Objective-C memory management a nightmare. You had to know _the rules_ which were special and magical and tucked away in a different chapter of the manual and had 20 exceptions.

No formal rule, just a single line of text in these functions that says "this is temporary memory that will be free'd later, but you can claim it now with ClaimMemory"? Honestly, it makes me feel like we aren't accidentally driving over a cliff now.

Clever, in a good way!  :)

**Comment by icculus** [comment]
Once this merges, in addition to the sdl2-compat stuff, though, someone should delete SDL3/SDL_GetStringRule.md from the wiki.

**Comment by slouken** [comment]
> Once this merges, in addition to the sdl2-compat stuff, though, someone should delete SDL3/SDL_GetStringRule.md from the wiki.

Sure, I'll do that.

**Pull request merged**
