### PR TITLE
Fixed memory leak at shutdown (thanks @1bsyl!)

### PR DESCRIPTION
**Pull request by slouken**
Clean up the textures first, as destroying the current render target will queue viewport and clip rectangle commands

### CODE REVIEW

**Comment by 1bsyl** [comment]
@slouken 
Not sure this is ok, because SDL_DestroyTexture flush the commands.

When we call DestroyRenderer, we want first to drop all the commands

**Comment by slouken** [comment]
We're not going to present, so I think it's fine to flush them instead of dropping them. In fact, I'll add a flush call so it's explicit that  that is the behavior.

**Comment by 1bsyl** [comment]
no, i still don't think that's a good idea...
flushing, means the back-ends will take all the commands, process them, change the state. make the context current etc.
maybe it's back-end dependant also.
Whereas, the application maybe just want to exit as fast as possible (eg android/ios while  in background)

I think it better to drop/discard all the current commands.

**Comment by slouken** [comment]
Okay, let's do that as a separate change then.

**Pull request merged**
